### ISSUE TITLE
Turning Image Preview off.

### ISSUE THREAD

**Issue by aparman** [deanoemcke/thegreatsuspender#100]
"Secondly, if you are really serious about reducing your memory foot-print, I would recommed turning the image preview option OFF. This can make quite a large impact on the amount of memory chrome uses."

Could you please tell me which "Image preview option" you are talking about?  I don't see this either in TGP options or Chrome's options.

**Comment by abcdefghijklmnopqrstuvwxyzabc** [comment]
Can I suggest that you update that page with the wording from your reply? I had to search google to get to this page to find the answer, and I suspect many others have made this journey as well!
Thank you for the bestest extension for Chrome ever. I'm gonna write you a nice review at the Chrome Web Store https://chrome.google.com/webstore/detail/the-great-suspender/klbibkeccnjlkjkiokjodocebajanakg?utm_source=chrome-app-launcher-search  right now, and so should everyone reading this :)

**Comment by patrickhealy** [comment]
I promise to write a nice one too - once that's updated in the Chrome
store. :-)

**Comment by Jitan** [comment]
Also had to google my way to this page..
