### ISSUE TITLE
Great Suspender crashed and lost all suspended tabs. Most recent import missing items after the third window.

### ISSUE THREAD

**Issue by Kovaelin** [deanoemcke/thegreatsuspender#1005]
* Extension version: 7.1.0
 * Browser name & version: Chrome 76.0.3809.100
 * Operating system & version: Windows 10 1803

Extension has been a life saver for the past year, but the most recent update on August 24 caused the loss of hundreds of tabs.

**Comment by liamjohnston** [comment]
Not sure if this is helpful or not, but... If the import FILE itself looks fine but Great Suspender isn't importing it correctly, try importing it via Session Buddy extension. The TGS importer has a bug.

**Comment by yzwind** [comment]
same here...
crash this afternoon and loss every suspended tab...

**Comment by Kovaelin** [comment]
It seems there's a bug with creating sessions. Some time between September 2018 and May 2019, the extensions fails to make complete exports.
