### ISSUE TITLE
Great Suspender Update

### ISSUE THREAD

**Issue by mbtir** [deanoemcke/thegreatsuspender#1007]
I have seen that The Great Suspender has updated and it tells me that a back up was automatically made, however there appear to be no saved sessions to import. Could you tel me how I re-open the windows that have closed when the update took place, please? Thank you.

**Comment by RobertAb1** [comment]
https://github.com/deanoemcke/thegreatsuspender/issues/988
https://github.com/deanoemcke/thegreatsuspender/issues/987
