### ISSUE TITLE
Message to update the extension

### ISSUE THREAD

**Issue by nukem2k5** [deanoemcke/thegreatsuspender#1009]
I launched Chrome yesterday and was greeted by a TGS tab telling me to update the extension, with a button to do so.  (EDIT: I was multitasking mindlessly clicked the button).  I thought extension updates happened automatically in the background.  Is this legit?  Just want to make sure I'm not executing something malicious.

**Comment by kalpaj12** [comment]
Hi @nukem2k5 
If you don't want to risk it.

1. Navigate to `chrome://extensions/`
2. Enable `developer mode`
3. Click `Update`

Now, cross-check current installed version to the latest available, from the chrome web-store.
P.s. The latest (currently) is v7.1.0

**Comment by liamjohnston** [comment]
That message is legit, though the update will eventually happen regardless of whether you take action.
