### ISSUE TITLE
[Feature Request] Chrome tab search and switch.

### ISSUE THREAD

**Issue by kalpaj12** [deanoemcke/thegreatsuspender#1010]
* Extension version: 7.1.0
 * Browser name & version: Chrome v76.0.3809.132 (Official Build) (64-bit)
 * Operating system & version: Ubuntu 19.04 5.0.0-25-generic

Allow suspended Chrome tabs to be searched and switched to, if found.

Something similar to this.

![Screenshot 2019-08-27 19-53-33](https://user-images.githubusercontent.com/41864755/63779774-bda0e080-c904-11e9-8844-dba52f65aea6.jpg)

:)

**Comment by Pascal666** [comment]
I use Quick Tabs for this functionality.  IMHO this feature is a bit out of scope for The Great Suspender.

https://chrome.google.com/webstore/detail/quick-tabs/jnjfeinjfmenlddahdjdmgpbokiacbbb

**Comment by kalpaj12** [comment]
Thanks @Pascal666,  for the extension. It does the work. 
Closing issue.
