### ISSUE TITLE
IndexedDB Log Question (Is this one corrupted????) 

### ISSUE THREAD

**Issue by jonibahu** [deanoemcke/thegreatsuspender#1011]
Hey

I lost my saved sessions and tried recovering them the last couple of days.
Still no success but i learned alot about where they are saved and how the extension works.

As far as i can tell, all the information gets saved into the .txt file that has a number as name (number changes) 
If u remove that, saved session are gone, if u put it back in they appear again.

I tried to recover that file but im not sure if the recovered version is corrupted or if something else is not working.

Could you maybe take a look at my "broken" txt files and see if u can tell whats wrong with them? 
https://gofile.io/?c=fJEu6S
https://gofile.io/?c=vD6yip (different recovery point, but both look weird) 

thank you very much.

**Comment by RobertAb1** [comment]
https://github.com/deanoemcke/thegreatsuspender/issues/988
https://github.com/deanoemcke/thegreatsuspender/issues/987
