### ISSUE TITLE
All tabs spontaneously unsuspending when Chrome gets focus

### ISSUE THREAD

**Issue by fredless** [deanoemcke/thegreatsuspender#1012]
Since the update to v7.1.0, I've seen the following behavior occur multiple times now:
when I'm away from the computer for some time (say overnight) when I return and switch to the Chrome window, ALL suspended tabs immediately start unsuspending.  I keep between 50-100 open and most are generally suspended, and this results in several minutes of waiting while the computer is essentially unusable as various Chrome windows and tabs continuously steal focus.  This has happened 4-5 times now over the last few days.

_EDIT_: _so a bunch of the unsuspended tabs from the last time this happened just suspended again when I hit the automatic time limit (1 hour in my case).  But the issue with tabs grabbing focus seem to be happening both when tabs suspend and unsuspend, it didn't use to do this.  While tabs were suspending again I had about 30 seconds of time in which I had to just sit and watch.  Probably going to disable this extension as this is getting very disruptive to my work day at this point._

I'm currently on Chrome 76.0.3809.100 and Windows 10 v1903 (18362.10005).

**Comment by RobertAb1** [comment]
https://github.com/deanoemcke/thegreatsuspender/issues/1015
