### ISSUE TITLE
Losing tabs (they are being closed)

### ISSUE THREAD

**Issue by danielsharvey** [deanoemcke/thegreatsuspender#1013]
Please complete the following information when submitting a feature request or bug report.
 * Extension version: v7.1.0
 * Browser name & version: Chrome Version 76.0.3809.100 (Official Build) (64-bit)
 * Operating system & version: MacOS Mojave 10.14.6 (18G87)

Update troubles (lots of reports by others about that).

However, I am now waking up to suspended tabs having been closed. No warning, no errors, just lots and lots of previously suspended tabs closed.

Let me know if you need any more information.

**Comment by RobertAb1** [comment]
https://github.com/deanoemcke/thegreatsuspender/issues/988
https://github.com/deanoemcke/thegreatsuspender/issues/987

**Comment by danielsharvey** [comment]
OK, my issues seem covered by others:

- This issue [Suspended tabs closed after automatic upgrade](https://github.com/deanoemcke/thegreatsuspender/issues/988)
- Compounded by Chrome bug referenced [here](https://github.com/deanoemcke/thegreatsuspender/issues/988#issuecomment-525062685) and [here](https://github.com/deanoemcke/thegreatsuspender/issues/988#issuecomment-524573198)

I have Session Buddy and seem to be able to restore an "window-at-a-time" without hitting the Chrome bug.
