### ISSUE TITLE
The great suspender crashed,updated automatically,and lost over 1400 tabs

### ISSUE THREAD

**Issue by diablo950** [deanoemcke/thegreatsuspender#1014]
The great suspender crashed,updated automatically,and lost over 1400 tabs. After the automatically upgrade,my session is gone and all my recent and saved sessions from the past too. I recovered the IndexedDB\chrome-extension_klbibkeccnjlkjkiokjodocebajanakg_0.indexeddb.leveldb folder with R-Studio data recovery but the new The great suspender version doesn't recognize the old files. I lost one month of my work(I was doing some important research). Looking through chrome's history is not an option since some tabs were old and some were new,some were discarded long time ago. Everything is gone.

**Comment by RobertAb1** [comment]
https://github.com/deanoemcke/thegreatsuspender/issues/988
https://github.com/deanoemcke/thegreatsuspender/issues/987
