### ISSUE TITLE
Bring back the "Don't suspend for now" option to right-click menu

### ISSUE THREAD

**Issue by sadokx** [deanoemcke/thegreatsuspender#1016]
* Extension version: v7.1.0
 * Browser name & version: Chrome Version 76.0.3809.100
 * Operating system & version: Mojave 10.14.5 

In this new version, you removed the context menu option to "Don't suspend for now" and other **incredibly useful** options that used **_natural language_** to convey their meaning.

Now we get these "Pause/Unpause", "Suspend/Unsuspend" options that I have no idea what they mean and that, to be honest, feel like lazy last-minute copywriting on the developer's part.

**Comment by dhjw** [comment]
Yeah I never know if suspending is paused or unpaused. I hate that menu option.
