### ISSUE TITLE
Convenient keyboard shortcut for unsuspend

### ISSUE THREAD

**Issue by devkev** [deanoemcke/thegreatsuspender#1019]
* Extension version: 7.1.0
 * Browser name & version: Google Chrome 76.0.3809.100
 * Operating system & version: Ubuntu 18.04.3

I try to minimise mouse usage.  It would be very convenient if I could just press Enter or Space to unsuspend a suspended tab.  Ctrl+Shift+S is a bit convoluted.  I used to be able to press Tab then Enter to unsuspend by focusing and selecting the URL on the suspension page.  But after the latest update this only works sometimes.  More commonly I need to press Tab 3 times before pressing Enter.

**Comment by liamjohnston** [comment]
The standard window refresh shortcut works (not sure what that is on Ubuntu but like the equivalent of F5 on windows or command-R on mac)
