### ISSUE TITLE
Feature Request: suspend tabs exceeding memory utilization

### ISSUE THREAD

**Issue by hrez** [deanoemcke/thegreatsuspender#1038]
Feature Request: 
add a condition to suspend only tabs exceeding some memory utilization threshold.
This would be in addition to other conditions.

Alternatively, don't suspend tabs below <X> Mb memory utilized.

**Comment by deanoemcke** [comment]
Duplicate of: https://github.com/greatsuspender/thegreatsuspender/issues/223
