### ISSUE TITLE
Dark mode doesn't work

### ISSUE THREAD

**Issue by omfganimal** [deanoemcke/thegreatsuspender#1054]
Please complete the following information when submitting a feature request or bug report.
 * Extension version: I just downloaded this so 7.1.0
 * Browser name & version: Google Chrome Version 78.0.3904.87 (Official Build) (64-bit)
 * Operating system & version: Windows 10 64 bit

I just downloaded this and I don't see a save button so I'm guessing it's supposed to auto update instantly when selected. Also assuming this via testing with other settings.

So when I select Dark theme it just stays white. My eyes are big ouch right now.
![dark](https://user-images.githubusercontent.com/55666565/68321440-666c7880-00ca-11ea-82f9-63cd64099714.png)

**Comment by liamjohnston** [comment]
At this stage, only the suspended tab itself has a dark theme. There's a feature request kicking about somewhere to make the settings pages etc dark mode-compatible too.
