### ISSUE TITLE
Has this been abandoned?

### ISSUE THREAD

**Issue by squidbe** [deanoemcke/thegreatsuspender#1074]
Anyone know if deanoemcke has abandoned this extension? With the exception of one "thank you" in November, s/he has had no interaction with this repo since April (neither commits nor responses to issues). @deanoemcke , are you still maintaining this extension?

**Comment by liamjohnston** [comment]
It has not been abandoned.

**Comment by squidbe** [comment]
Thanks, can you please elaborate? Do you know why the maintainer isn't responding to issues?

**Comment by liamjohnston** [comment]
Between having a full time job and a family etc, the maintainer doesn't have a lot of free time. He is working on the extension when time permits.

**Comment by squidbe** [comment]
I certainly understand the commitment of a full-time job and family since that's the boat I'm in. It's just somewhat disappointing that I paid the author for this extension and reported a bug in May where the payment nag screen won't go away (and I tried suggestions in the issues list), but the author hasn't even acknowledged the issue.
