### ISSUE TITLE
Don't Save Suspended Tabs in Browser History

### ISSUE THREAD

**Issue by johnyradio** [deanoemcke/thegreatsuspender#108]
My history fills up with "The Great Suspender" and then i cannot see what sites i visited. I use "History site blocker" extension to keep suspended tabs out of history. Maybe SuspensionLabs can find how to do this from https://chrome.google.com/webstore/detail/history-site-blocker/bkgnheiibhnjklgimaldgngjcfblachh

![suspender](https://cloud.githubusercontent.com/assets/6564280/3541799/c50b318e-084f-11e4-8468-728a8253c925.jpg)

**Comment by Corrodias** [comment]
I believe this issue can be closed. I have not seen any suspended tab urls in my history.

**Comment by greatsuspender** [comment]
@johnyradio you are correct that currently suspended tabs do not show their proper name in chromes history. this has been fixed in a newer version and will be released to the chrome webstore shortly.
see issue #164 for more details.
