### ISSUE TITLE
Suspended tabs loaded on chrome start

### ISSUE THREAD

**Issue by bit-man** [deanoemcke/thegreatsuspender#109]
When chrome starts all suspended tabs are loaded even that were previously suspended. After load they're suspended but during the process memory and CPU consumptions rises.

**Comment by jpluimers** [comment]
I see this too: when Chrome restarts (no matter how: auto-update, reboot system, voluntary Quit Google Chrome), all tabs that were suspended get loaded.

I'm running Chrome 45 on Mac OS X with latest Great Suspender, but this has happened for many Chrome and Great Suspender versions.

**Comment by deanoemcke** [comment]
Can I get some more info on this? Do the tabs initially open suspended and then reload? Or just load like normal tabs from the very start?
What version of chrome are you using? And what version of the extension?
And most importantly, what do you have in chrome settings under the 'on startup' section: 
![image](https://cloud.githubusercontent.com/assets/1051763/10116097/19888c06-63f4-11e5-87a6-9b68e882bbb6.png)

**Comment by jpluimers** [comment]
I've 'continue where you left off' set. I'll get back on the loading as soon as Chrome restarts.

**Comment by jpluimers** [comment]
By now the version is indeed old (:

I cannot reproduce this in the most recent version any more.
