### ISSUE TITLE
Header of suspended tab offset to the right edge of tab.

### ISSUE THREAD

**Issue by davmillar** [deanoemcke/thegreatsuspender#1139]
Extension: v7.1.0
Browser: Chrome 83.0.4103.61 {"arch":"x86-64","os":"linux"}
OS: Fedora Linux 31

After updating Chrome to v83, the suspended tab header is offset to the right edge of the tab. It's still center aligned but the bounding box is incorrectly positioned. Affects both light and dark mode and doesn't seem to correspond to a specific screen size. See attached screenshots.

![image](https://user-images.githubusercontent.com/576958/82917337-ea882f80-9f38-11ea-8087-9d9e5e46dcee.png)
![image](https://user-images.githubusercontent.com/576958/82917396-fd026900-9f38-11ea-887c-b2dfce7e8e7c.png)

**Comment by liamjohnston** [comment]
Fixed by https://github.com/deanoemcke/thegreatsuspender/pull/1136
