### ISSUE TITLE
Error after installing development version

### ISSUE THREAD

**Issue by krlmlr** [deanoemcke/thegreatsuspender#119]
Followed instructions [on wiki](https://github.com/deanoemcke/thegreatsuspender/wiki/Installing-beta-version) (but installed from a clone of the repository, not an unpacked `.zip`). Seen the following error, not sure if it matters:

![screenshot from 2014-08-25 09 34 18](https://cloud.githubusercontent.com/assets/1741643/4027211/ab5bea40-2c2a-11e4-84d2-31769bf2cf25.png)

![screenshot from 2014-08-25 09 33 18](https://cloud.githubusercontent.com/assets/1741643/4027212/aeca77d2-2c2a-11e4-9875-b13cbe92f3cb.png)

Error does not seem to reappear after reloading extension.

**Comment by vanta** [comment]
Similar here...

![image](https://cloud.githubusercontent.com/assets/2153370/5608047/87bf132a-9474-11e4-8919-34723121f294.png)

**Comment by deanoemcke** [comment]
sorry guys. this issue should now be resolved in the latest gitHub version.
