### ISSUE TITLE
how to return changed favicon for suspended tab?

### ISSUE THREAD

**Issue by zldrq** [deanoemcke/thegreatsuspender#120]
i installed canary and old dev version of greatsuspender stopped working
i downloaded new master branch and favicon is not changed anymore
i uncommented lines where function  generateFaviconUri is called, now favicon changes for 1-2 seconds, then changes back to original again

how to make it permanent?
without changed favicon greatsuspender loses like 50% of it's sense for me. or may be even more.

**Comment by Corrodias** [comment]
I haven't noticed any favicon problems in recent builds. Is this still happening for someone?
