### ISSUE TITLE
Customisable information on suspended tab page

### ISSUE THREAD

**Issue by fedWikiBackup** [deanoemcke/thegreatsuspender#1253]
Please complete the following information when submitting a feature request or bug report.
 * Extension version:
latest from chrome store
 * Browser name & version:
Chroms latest, Ubuntu
 * Operating system & version:
Ubuntu 18.04 inside VirtualBox

And please also do a search for your request/bug before create a new one thanks!

Hello. Thank you so much for this. I cannot communicatre too strongly how TGS is a part of my workflow. I use my machine in a pretty unauthodox manner, I work as part of many projects all over the world in various capacities. I have about 60 browser profile directories, and at any one time I often have more than a thousand tabs open on my machine. I use tabs as a todo list. Combined with i3wm, I am able to switch contexts at an amazing rate.

Sometimes I have many tabs (long standing, perhaps for weeks or months) that are all from the same site, and the suspended tab for all of them is indisinguishable. I make do by learning the order that they are in inside a window. It would be really quite useful to be able to put a user comment onto the suspended tab page.

in order to be useful the way that I am thinking this would require:
  * that the user comment be editable and visible on the suspended tab page for a page.
  * that when that tab used, and then re-suspended, the existing user comment was persisted

that it :)

Im happy to contribute some time to coding this if you are intrested in that. intiially I would like an idea of if this is possible, and if it is mega hard. I need to learn a bunch about chrome extensions for the next phase of my primary project, so this would be a useful use of my time to work on.

Hope you are well.. I have donated in the past. TGS is literally a core part of my life :) thanks very much

**Comment by fedWikiBackup** [comment]
Being able to change the tab title as part of this functionality could also beuseful, but its not necessary

**Comment by christopherreay** [comment]
Sorry, I closed this issue, because I submitted it as the wrong me!
