### ISSUE TITLE
Tabs suspending much quicker than setting.

### ISSUE THREAD

**Issue by Omegaclawe** [deanoemcke/thegreatsuspender#126]
I currently have the length of inactivity set to 6 hours before suspending due to inactivity. For newly opened tabs, this works as intended, however, as soon as a tab has been suspended, any time I remove focus from the tab, it will be suspended after approximately 1 minute. This means that I had to whitelist Youtube to prevent playing videos from being stopped, for instance, and sites I don't whitelist I have to constantly click and reload. Rather annoying when I'm trying to use multiple articles for reference.

Note: I have 32GB of RAM, so I don't exactly need aggressive memory management. I just need something to stop facebook and Tom's Hardware from using 4GB a tab after sitting there most of the day.

**Comment by ghodss** [comment]
I'm also experiencing the same issue.

**Comment by ghodss** [comment]
I can confirm that using the latest version from Github solves this problem. To do so:

1. If you have The Great Suspender already installed, do these steps first:
 1. Click The Great Suspender button in the top right and click Reload all tabs.
 1. Right click the button and click Remove from Chrome.
 1. Restart Chrome.
1. Checkout The Great Suspender git repo to a local directory. (Install git then run `git clone https://github.com/deanoemcke/thegreatsuspender.git`.)
1. Go to chrome://extensions, click Load unpacked extension..., and navigate to the directory you just created with git. Click Select.
1. The Great Suspender extension should now be installed and functioning.

There are lots of new features that aren't in the current store - it would be great to get the Chrome webstore package officially updated.
