### ISSUE TITLE
[Feature suggestion] Don't suspend this tab (current session)

### ISSUE THREAD

**Issue by samomar** [deanoemcke/thegreatsuspender#1267]
A great feature would be to prevent suspension of a certain tab for this session, the URL is never remembered and will still be suspended when browser is restarted or another tab is opened.

This is much needed for when you need resource heavy tabs to be suspended, but preserve 1 instance of them, temporarily.

We can already pause suspending all tabs, but the drawback is that either we lose functionality over all tabs because of just one tab or forgetting we paused the extension for a significant amount of time that could span over multiple days.

**Comment by ossilator** [comment]
afaict, this is the 2nd entry in both the extension button ("not now") and the right-click menus.

**Comment by samomar** [comment]
> afaict, this is the 2nd entry in both the extension button ("not now") and the right-click menus.

Thanks, I didn't realize that was not global pause.
