### ISSUE TITLE
Microsoft Edge malicious code.

### ISSUE THREAD

**Issue by bartoszek** [deanoemcke/thegreatsuspender#1269]
This extensions was blocked by Microsoft for containing malicious code, was there any reason for it, will this extension get back to Microsoft Edge store?

![image](https://user-images.githubusercontent.com/1213348/99874376-c48dd000-2be7-11eb-9fc5-3c81cca7e5d8.png)

_sorry for Polish lang screenshot, have no easy way to switch Edge to English without changing system language._

**Comment by ossilator** [comment]
see #1263

**Comment by bartoszek** [comment]
@ossilator sorry for duplicate, closing.
