### ISSUE TITLE
Tabs in Chrome 'Tab Groups' Sleep When Pinned

### ISSUE THREAD

**Issue by pixelpicnic** [deanoemcke/thegreatsuspender#1271]
Please complete the following information when submitting a feature request or bug report.
 * Extension version: 7.1.8
 * Browser name & version: Chrome Version 87.0.4280.66 (Official Build) (64-bit)
 * Operating system & version: Win 10

I understand this project is undergoing some changes at the moment, but I just noticed a strange behaviour with the new chrome tab group feature.
- Group a number of tabs, and pin them
- Set extension to not sleep pinned tabs
- Tabs will sleep

As this is a newer feature in chrome, I'm not sure how it's registering that a tab is 'pinned' while in a group, but this is unexpected.

Aside from that, this extension is awesome. Keep up the great work!
Thanks!

**Comment by pixelpicnic** [comment]
It appears this was due to user error - once grouped, pinning tabs appears to remove them from the group.

**Comment by wylie39** [comment]
these are good observations, but TGS is currently unmaintained here, and the store version is likely even malicious (see #1263).

**Comment by ossilator** [comment]
oh c'mon, pasting my message verbatim is a bit lame, don't you think? ;)

fwiw, there's about half a dozen other issues related to the (non-)interaction of TGS with groups. i haven't tried to make sense of them.
