### ISSUE TITLE
Trojan/spyware activity.

### ISSUE THREAD

**Issue by megastallman** [deanoemcke/thegreatsuspender#1274]
When I enable "The Great Suspender" extension, it connects to multiple different IP-addresses over HTTPS, doing something. One of them - is google-analytics.
Please add an option to remove it. I don't need trojans running on my system.

 * Extension version: v7.1.6
 * Browser name & version: Ungoogled Chromium Version 84.0.4147.135 
 * Operating system & version: Kubuntu 20.04

**Comment by ossilator** [comment]
such an option is actually in v7.1.8. but note #1263.

**Comment by megastallman** [comment]
Thanks @ossilator . Now I've moved to AutoTabDiscard. Looks like working. Or at least - doesn't connect to external hosts.
