### ISSUE TITLE
deleted

### ISSUE THREAD

**Issue by saurabhnemade** [deanoemcke/thegreatsuspender#1314]
Edit: I thought people will take it as joke but didn't pan out right.

But really, they should not have added malware to this.

**Comment by TomasHurtz** [comment]
There is nothing funny in these such incidents, many people lose.  Are you somehow involved in this malicious software?

Unacceptable and irresponsible comment. [Reported user to Github and I encourage others to do the same.](https://support.github.com/contact/report-abuse?category=report-abuse&report=saurabhnemade&report_id=17445338&report_type=user)

**Comment by saurabhnemade** [comment]
> There is nothing funny in these such incidents, many people lose. Are you somehow involved in this malicious software?
> 
> Unacceptable and irresponsible comment. [Reported user to Github and I encourage others to do the same.](https://support.github.com/contact/report-abuse?category=report-abuse&report=saurabhnemade&report_id=17445338&report_type=user)

Nahh. I am just a security researcher.
