### ISSUE TITLE
Cannot able to restore suspended tabs

### ISSUE THREAD

**Issue by uunnxx** [deanoemcke/thegreatsuspender#1315]
Please complete the following information when submitting a feature request or bug report.
 * Extension version: 7.1.6
 * Browser name & version: Chrome
 * Operating system & version: Linux

And please also do a search for your request/bug before create a new one thanks!

All my tabs were suspended and saved to bookmarks (do not ask why) and there are more than 500 pages, I'm not able to `unsuspend` them just because version 7.1.6 I've installed and latest version which was deleted by google has different `ID`

How can I get easily restore them without modifying every `uri` for new `id`

**Comment by andrewprofile** [comment]
#1313

**Comment by uunnxx** [comment]
Is there any solution ?
If I change manually `extension id`  which's `klbibkeccnjlkjkiokjodocebajanakg` with new installed it's working as expected.

**Comment by Nubbie** [comment]
Worked for me by:
* Turning off internet
* Activate the extension "The Great Expander" in Chrome again and go to -> Settings -> Session management -> Open and load
* Remove the extension "The Great Expander" 
* Turn on internet

**Comment by andrewprofile** [comment]
I have described point by point what needs to be done to restore operation. Take a look #1313

**Comment by welovfree** [comment]
That's why OneTab was very useful for me.

**Comment by uunnxx** [comment]
> #1313

I'm not able to get `sessions`.
No sessions at all.
All I have is automatically removed "The great suspender" and bunch of saved pages...

I see two ways: it's extracting `uri` part or changing `id`

**Comment by andrewprofile** [comment]
You need to export the sessions in 7.1.6, change the id manually(in editor notepad++/vscode or other by replace all) in all urls and re-import

**Comment by uunnxx** [comment]
previous one: with `id: klbibkeccnjlkjkiokjodocebajanakg` 
chrome-extension://klbibkeccnjlkjkiokjodocebajanakg/suspended.html#ttl=A%20beginners'%20introduction%20to%20Ruby%20classes%20and%20objects%20-%20Remi%20Mercier&pos=1590&uri=https://remimercier.com/beginners-introduction-to-ruby-classes-objects/

version 7.1.6: with `id: onlnmifhhekeccenhakoeigcnelmnbdl`
chrome-extension://onlnmifhhekeccenhakoeigcnelmnbdl/suspended.html#ttl=A%20beginners'%20introduction%20to%20Ruby%20classes%20and%20objects%20-%20Remi%20Mercier&pos=1590&uri=https://remimercier.com/beginners-introduction-to-ruby-classes-objects/

Is there any ways to easily change `id` ? 
I'm asking why `id` is changed if I reinstalled it ? 

https://developer.chrome.com/docs/apps/app_identity/#copy_key

> Copy key in the installed manifest.json to your source manifest, so that your application ID will stay constant during development.

Where should I put `ID` to get it as `constant` ?

**Comment by andrewprofile** [comment]
Unfortunately, I do not know how to change the id in chrome, I described how to solve your problem in my post, take a look there and follow all these steps only instead of dcfbmakmhgdbikhkhnoodjjdkcamgkcj put your onlnmifhhekeccenhakoeigcnelmnbdl. The chrome id differs because the add-on is being installed from a different source

**Comment by uunnxx** [comment]
Thank you @andrewprofile !

Export bookmarks -> change id by new one -> import back
