### ISSUE TITLE
Has the greatsuspender always been a pro account?

### ISSUE THREAD

**Issue by wylie39** [deanoemcke/thegreatsuspender#1334]
I just noticed that the greatsuspender account that owns this repo is paying for a pro membership. Has this always been the case? it seems odd that he would pay for it if he never uses it.

**Comment by Rekulous** [comment]
Don't use this version of the Great Suspender because it has been sold to a new owner that is Malicious, so bad where Chrome took it down from the webstore, only use this one directly from GitHub => https://github.com/aciidic/thegreatsuspender-notrack

**Comment by Technetium1** [comment]
It is also perfectly safe to use https://github.com/gioxx/MarvellousSuspender

**Comment by aleqx** [comment]
> It is also perfectly safe to use https://github.com/gioxx/MarvellousSuspender

Until it isn't. I'm surprised at the huge number of people recommending this new extensions from web store. The same thing can happen again, you all realize that, don't you? You have no control over what the extension will do in the next update, which may be more chinese/russian/etc dudes/dudettes snooping on your form data and urls.

If you care about your privacy and security then please stop using extensions from web store that have critical permissions, and consider putting up with the inconvenience of loading an unpacked version from source that you fetch from an open source project on github whose source you can inspect and which you manually update so you don't worry about the next update.

> Don't use this version of the Great Suspender because it has been sold to a new owner that is Malicious, so bad where Chrome took it down from the webstore, only use this one directly from GitHub => https://github.com/aciidic/thegreatsuspender-notrack

This ^. ... yet 3 people downvoted it, sigh ...

**Comment by equinox** [comment]
@aleqx Just out of the blue advertising other forks because you can isn't adding any positive value to any discussion. It would be less of an issue if the commentators weren't aware of what's happening, but, alas: OP was around before Google removed the extension, so they're obviously aware of the situation and there was nothing in OP's original message to suggest they were going to install TGS again.

**Comment by equinox** [comment]
@wylie39 The earliest wayback archive of their account ([link](https://web.archive.org/web/20210104004750/https://github.com/greatsuspender)), shows they were a PRO account at near the start of the year. At least it rules out them becoming a PRO account after the extension store removal's influx of activity.

**Comment by aleqx** [comment]
> @aleqx Just out of the blue advertising other forks because you can isn't adding any positive value to any discussion. It would be less of an issue if the commentators weren't aware of what's happening, but, alas: OP was around before Google removed the extension, so they're obviously aware of the situation and there was nothing in OP's original message to suggest they were going to install TGS again.

If you tried to miss the point you would have likely not been as successful at it than that

**Comment by equinox** [comment]
I'm not the least bit interested in what you said other than whining about people downvoting that comment. I was one of them, so I explained why I did.

**Comment by aleqx** [comment]
> I'm not the least bit interested in what you said

Clearly, that's why you keep replying

>  whining about people downvoting that comment.

More and more successful
