### ISSUE TITLE
console.log in file contentscript.js

### ISSUE THREAD

**Issue by ghost** [deanoemcke/thegreatsuspender#1365]
Please complete the following information when submitting a feature request or bug report.
 * Extension version 7.2.3
 * Browser name - chrome & version - 112.0.5615.49 (Official Build) (64-bit)
 * Operating system - win 10 pro 64
Prevents debugging sites through the console. Because extra logs pop up.
Problem in contentscript.js file.

**Comment by ossilator** [comment]
note that the version you specified is not in this git repository, which has been dead for a long time. see #1295.

**Comment by ghost** [comment]
I didn't even pay attention to the version of the extension. Thank you very much!!!
