### ISSUE TITLE
[BUG] On Chrome launch, using up a lot of CPU (100% on one core) and crashes after a while (Ubuntu)

### ISSUE THREAD

**Issue by matgardon** [deanoemcke/thegreatsuspender#14]
Hi, first of all great extension which I terribly needed. here is my problem :

I'm using Chrome with ubuntu (11.04), and whenever I re-open chrome (after a restart of my computer for example), something in Chrome (I suppose the extension because nothing else has changed and it didn't do that before) takes up a whole core undefinitely ; after a while, Chrome is blocked (greyed out and unaccessible), which is I suppose a behavior of the OS preventing a misconducting program from executing.

The weird thing is, if I go to all the tabs (ctrl+tab until I have put the focus once in all open tabs), while chrome is using  up all the ressources, then the CPU usage goes down and Chrome does not crash, returning to normal usage.

Weirder thing is, this chrome has a lot of tabs (+ 50), but I use another chrome linked to another account (chrome sessions), and this one has less open tabs, and it does not reproduce the same behavior.

I'm willing to investigate further if you need any help, using any tools necessary, to get some interesting data that might help corner the bug.

Any idea :) ?

**Comment by deanoemcke** [comment]
Closing as it is an old issue and extension has been significantly changed since then.
