### ISSUE TITLE
Doesn't work with Chromebooks / Chromeboxes

### ISSUE THREAD

**Issue by frontalot** [deanoemcke/thegreatsuspender#142]
Your extension doesn't work with Chromebooks and Chromeboxes. Any plans to add support for these devices?

Thanks!

**Comment by deanoemcke** [comment]
Could you please elaborate on exactly how it does not work? Do you mean that chrome on these devices does not support extensions?

**Comment by Zymoloid** [comment]
Hi deanoemcke,
When you attempt to load unpacked extension you get the error message 
"Could not load background script 'js/db.js'."

**Comment by patrickhealy** [comment]
It would if it were in the play store since you wouldn't have to unpack
it.....

**Comment by deanoemcke** [comment]
@frontalot @Zymoloid i have released a new version of the extension into the chrome webstore. i don't have a chromebook to test on. could one of you check to see if the webstore version runs on a chromebook? cheers!

**Comment by frontalot** [comment]
Yes, new version works perfectly. Thanks!!!
