### ISSUE TITLE
Settings don't save

### ISSUE THREAD

**Issue by rickydeez** [deanoemcke/thegreatsuspender#143]
Any reason why my settings aren't saving?

I set the Length of inactivity and Whitelist, but it resets to default every time I reopen the settings page.

I see a JS error on the settings page:

Uncaught TypeError: Cannot read property 'preview' of null

**Comment by jackterror** [comment]
Same issue here.

**Comment by deanoemcke** [comment]
Hi,
Hopefully this should be fixed in the latest version (v5.38).
Can you confirm?

**Comment by jackterror** [comment]
Fixed!
You are a code god!!!
