### ISSUE TITLE
Past Tabs Re-Open

### ISSUE THREAD

**Issue by jackterror** [deanoemcke/thegreatsuspender#144]
If my history isn't cleared, past suspended tabs are opening when I start Chrome. 
Restarted computer didn't fix; the only fix I could find was clear the history.

**Comment by deanoemcke** [comment]
@jackterror 
are you using the latest gitHub version of the extension? there is now a new recovery screen that should appear if the extension detects that some tabs have crashed or been closed due to extension crash.

**Comment by jackterror** [comment]
Yeah... It's working great now!!! Thanks for checking in.
