### ISSUE TITLE
Suspended tabs end up with 'Aw, Snap!' crash

### ISSUE THREAD

**Issue by echristopherson** [deanoemcke/thegreatsuspender#146]
Starting 1/24/2015 or so, in the Chrome store version of the plugin, all my suspended tabs seem to eventually crash, leaving the Chrome page that says:

    Aw, Snap!

    Something went wrong while displaying this webpage. To continue, reload or go to another page.
    If you're seeing this frequently, try these suggestions.

Reloading such a tab does properly restore the suspended tab page; and then clicking on it reloads the actual page. I am currently seeing the problem with Chrome Version 40.0.2214.91 (64-bit) on OS X 10.9; but I was also seeing it before I updated to this version (also on 1/24/2015).

**Comment by echristopherson** [comment]
It just occurred to me to turn off the graphical preview saving (which was on before). So we'll see how it goes now.

Any reason this hasn't been updated in the Chrome store for so long?

**Comment by deanoemcke** [comment]
Any luck since turning off graphical preview?
I'd say there's a high chance that is what is causing the tabs to crash.
I have just committed some new functionality that should detect crashed tabs in future and prompt to reload them.

New version coming to chrome store very soon :D

**Comment by echristopherson** [comment]
On Tue, Feb 10, 2015, deanoemcke wrote:
> Any luck since turning off graphical preview?
> I'd say there's a high chance that is what is causing the tabs to crash.
> I have just committed some new functionality that should detect
> crashed tabs in future and prompt to reload them.

So far, so good.

> New version coming to chrome store very soon :D

Great!

-- 
        Eric Christopherson
