### ISSUE TITLE
Clean New Install of Lastest Master (28/1/2015) Doesn't Work

### ISSUE THREAD

**Issue by tjharman** [deanoemcke/thegreatsuspender#147]
I can't save any settings.
I'm using it on another PC where I've slowly upgraded and followed progress, this seems to be working fine.  It's like it's not able to create a database or something like that.

Terrible bug report I know, let me know what other information I can provide.

Tim

**Comment by deanoemcke** [comment]
umm.. are you sure you're posting in the correct gitHub project??

**Comment by tjharman** [comment]
Yes, I am.
I have The Great Suspender installed on Two Machines, my work laptop and my home laptop.
My work Laptop is Windows 7, Home is Windows 8.  Both are Chrome, have the same addons etc (using sync)

I have to manually add The Great Suspender though, as it's loading as a developer plugin.

At home, I have the icon for TGS in my toolbar, clicking on options brings up the TGS options. I can fill out the whitelist sites, but clicking on the "Save Settings" button does nothing.  It doesn't close the options like it does on my work PC.

So I'm able to run it, but I can't get it to save any settings, or even do anything.  If I try to get it to suspend a tab by clicking on the icon and selecting "Suspect this tab" - the menu closes buy nothing happens.

The addon's there, but it's not active.

The only thing I can think of is that I used the github repo for the last couple fo weeks, and I've been updating it from github (downloading the master.zip file) every few days.  But I only decided to install it at home yesterday.  Downloaded the master.zip and now I'm in this situation.

What can I do to provide you with better debug info?

Thanks!

**Comment by tjharman** [comment]
Edit: I realise I had a pretty dumb typo in my subject... Sorry about that.

**Comment by deanoemcke** [comment]
Hey. Really sorry about this. You're totally right - I did a stupid thing in my last commit.
This should be fixed now.
Sorry for doubting!

**Comment by tjharman** [comment]
Thank you, the latest version fixes this now.
I'm sorry for such a shite initial bug report.

**Comment by tjharman** [comment]
This issue appears again with commit 1c5c67fc26d2bf6a8a21dd53bafeed2466b12759 (Note, I haven't tested the previous few commits to see when it started again)

Thanks

**Comment by deanoemcke** [comment]
Thanks for letting me know once again :) 
I never really test on brand new environments.
Should be fixed again now.
