### ISSUE TITLE
Update the extension in Chrome Web Store

### ISSUE THREAD

**Issue by niutech** [deanoemcke/thegreatsuspender#148]
The Great Suspender in [Chrome Web Store](https://chrome.google.com/webstore/detail/the-great-suspender/klbibkeccnjlkjkiokjodocebajanakg) is in version 4.74. Please update it to the latest version.

**Comment by tjharman** [comment]
**Please look before** adding another issue [when one exists already](https://github.com/deanoemcke/thegreatsuspender/issues/140).

**Comment by niutech** [comment]
Sorry for duplicating issue #140. Closing.
