### ISSUE TITLE
Some previously suspended tabs are fully loading when restoring after a Chrome crash

### ISSUE THREAD

**Issue by niutech** [deanoemcke/thegreatsuspender#149]
After Chrome crashes with a 100+ suspended tabs in multiple windows, when I restart it, Chrome restores all windows and tabs, but unfortunately many of previously suspended tabs are getting fully loaded, so I have to wait a long time until they all load, then I have to click Suspend All Tabs in each window. Instead, on Chrome restore, all tabs should remain suspended. Anybody experienced that?

**Comment by deanoemcke** [comment]
@niutech 
Are you using the chrome webstore version of the extension or a developer one from this github project? The latest version on gitHub should behave as you are expecting. If it doesn't, I can look into it.

**Comment by niutech** [comment]
I am using the Web Store version.

**Comment by deanoemcke** [comment]
OK. I'll close this issue then as I'm fairly sure it's been resolved. New version will be in the webstore shortly.
