### ISSUE TITLE
Setting to only suspend when running on battery?

### ISSUE THREAD

**Issue by raarts** [deanoemcke/thegreatsuspender#150]
Hi,

thank you for a great extension. I am kinda hoping you can create a setting for only suspending when running on battery. This is for my Macbook Air.

Thanks,
Ron

**Comment by deanoemcke** [comment]
@raarts 
This request has been raised before (#103). Unfortunately there is no easy way to detect the power source of the computer. Perhaps in future I'll make an easy way for you to enable/disable the extension so that you can manually do this when changing power source.

**Comment by raarts** [comment]
Can't you use this? http://www.w3.org/TR/battery-status/

**Comment by deanoemcke** [comment]
This has now been implemented in the latest gitHub version.
Chrome webstore release following shortly.

**Comment by raarts** [comment]
Thank you very much!!

Ron
