### ISSUE TITLE
Enough already

### ISSUE THREAD

**Issue by patrickhealy** [deanoemcke/thegreatsuspender#151]
Launch this extension will you? How long are you going to sit on this thing? The developer's version sucks in a few ways - like not getting synced with chrome. Push the goddamn code already!

**Comment by tjharman** [comment]
Dear Dev, 

Just because of this twat, please delay putting the update in the app store for a few months. 

Cheers, 
Tim

**Comment by patrickhealy** [comment]
Don't play Tim!
