### ISSUE TITLE
Only suspend when running on power: does not work for me

### ISSUE THREAD

**Issue by raarts** [deanoemcke/thegreatsuspender#152]
I run Macbook Air on Yosemite. Chrome latest version.
What I did was run the following code in my browser, to see if the charging indicator was reliable.

```  <script>
    window.onload = function () {
      var previous;
      var count = 0;
      function updateBatteryStatus(battery) {
        document.querySelector('#charging').textContent = battery.charging ? 'charging' : 'not charging';
        if (battery.charging != previous) {
          count += 1;
        }
        previous = battery.charging;
        document.querySelector('#chargechanges').textContent = count;
        document.querySelector('#level').textContent = battery.level;
        document.querySelector('#dischargingTime').textContent = battery.dischargingTime / 60;
      }

      navigator.getBattery().then(function(battery) {
        // Update the battery status initially when the promise resolves ...
        updateBatteryStatus(battery);

        // .. and for any subsequent updates.
        battery.onchargingchange = function () {
          updateBatteryStatus(battery);
        };

        battery.onlevelchange = function () {
          updateBatteryStatus(battery);
        };

        battery.ondischargingtimechange = function () {
          updateBatteryStatus(battery);
        };
      });
    };
  </script>
```

And it did, the counter stayed at 1, so the battery status was stable. I could see it change when I pulled the power, but for this test I didn't.
I set the timeout to 5mins, and after 5 mins the tabs still suspended. I do have the 'Only auto-suspend if running on battery' box checked.

By the way, if I donate will the popup still ask for a donation?

Best,
Ron

**Comment by deanoemcke** [comment]
oops! i think i got it round the wrong way. ie. it will only suspend if laptop IS charging.
i have just committed a fix to swap this around. either try the opposite (test with your laptop plugged in to see if it still suspends) or do an update and try again.
also, if you donate you will no longer get the donation popups. but no pressure :)

**Comment by raarts** [comment]
Hi,

installed the fix. Much better ;-)
