### ISSUE TITLE
Long delay when opening new tabs

### ISSUE THREAD

**Issue by ghodss** [deanoemcke/thegreatsuspender#153]
At https://github.com/deanoemcke/thegreatsuspender/commit/0500902cc2dfcef8511eb771065598c79925e1ac, when I open a new tab and go to a URL (or cmd+click on a link), there is a 1-2s pause with a white screen where nothing is happening before the page starts loading. I notice that thegreatsuspender icon in the top right is gray for those 1-2s, then as soon as it turns brown, the page loads. It seems like the extension is preventing the page from loading.

**Comment by ghodss** [comment]
Also during this loading period the entire browser freezes up, i.e. if I open a tab in the background, my current tab is unresponsive until those 1-2s are up.

**Comment by deanoemcke** [comment]
Can you definitely attribute it to this extension? If you disable the extension does the problem go away?

**Comment by ghodss** [comment]
Yes. I just tried uninstalling the extension and the behavior disappeared
without even a restart. I've now restarted and reinstalled the extension
and the behavior is not appearing, but I will post if it starts up again.

On Fri, Feb 20, 2015 at 12:19 PM, deanoemcke <notifications@github.com>
wrote:

> Can you definitely attribute it to this extension? If you disable the
> extension does the problem go away?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/deanoemcke/thegreatsuspender/issues/153#issuecomment-75311965>
> .
>



-- 
Sam
