### ISSUE TITLE
Recovery page appears on chrome launch

### ISSUE THREAD

**Issue by deanoemcke** [deanoemcke/thegreatsuspender#155]
The recovery page should only appear if the extension crashes. But it appears to be coming up on a chrome restart as well. Initially raised as part of issue #140.
@Corrodias: Just to clarify what is happening. You have a chrome session with some tabs open but none of them are suspended. And then you close chrome. At a later date you restart chrome and as well as the new tab page coming up, you also get the recovery page appearing?
If you could let me know the following:
- The version of the extension (go to settings->support)
- Your operating system
- On the recovery page, what tabs (if any) appear under the 'Tabs to restore' heading.
- Your 'on startup' setting in chrome->settings (i think you've already told me it's 'open the new tab page')
- In chrome->settings->show advanced settings, under system, is the 'continue running background apps when google chrome is closed' option checked or unchecked?

That should help me make a start on diagnosing the issue.

**Comment by Corrodias** [comment]
Testing results:
If I have no suspended tabs and exit Chrome, when I launch Chrome, the recovery page appears. It lists all of the tabs that I had open upon exit and no others.
If I have a suspended tab and exit Chrome, when I launch Chrome, the recovery page does NOT appear.

The extension is the master branch, commit bb137f5..., "Style tweaks".
OS: Windows 7, 64-bit. Chrome is also the 64-bit version.
On startup: open the new tab page
Continue running background apps: unchecked

**Comment by juristr** [comment]
Not sure this helps, but I have a similar problem of having the recovery page appear, but not only when I launch Chrome, but from now and then **when leaving a page** by either closing it, or by navigating to another one through some links.

**Comment by Corrodias** [comment]
That is a familiar problem with the 5.46 beta on the front page, but as far as i can tell, it has been fixed, in the repo.

**Comment by juristr** [comment]
Ya, sorry. Just cloned the repo after submitting the issue. I'll verify if it happens again and eventually let you guys know.

**Comment by deanoemcke** [comment]
I have just committed some changes to the recovery logic of the extension (master branch).
If you have a moment, it would be great if you could test it out :)

**Comment by Corrodias** [comment]
I was very busy today. Sorry! But tomorrow I should get to trying it.

**Comment by Corrodias** [comment]
It appears to work in the cases of "no suspended tabs" and "mixed suspended and normal tabs". The recovery page continues to open in the case of "all tabs are suspended".

**Comment by Corrodias** [comment]
As of 82c5616, or perhaps earlier, this issue appears to have been solved entirely.

**Comment by deanoemcke** [comment]
Yes. I specifically addressed this in my last update.
