### ISSUE TITLE
Exclude pages where developer tools are open

### ISSUE THREAD

**Issue by joepie91** [deanoemcke/thegreatsuspender#160]
It would be useful to have a way to exempt tabs from suspension while the Chrome Developer Tools are open - that way, the extension doesn't get in the way during development. Right now, the reload to unsuspend a page means you lose eg. your element selection and the data in the Network tab.

**Comment by olso** [comment]
+1 or anything at localhost

**Comment by joepie91** [comment]
My suggestion definitely extends beyond `localhost`, though. I do a fair amount of scraping work, and it's rather annoying to have my pages suspended while I'm trying to pick apart a few different pages.

**Comment by Corrodias** [comment]
That's not a bad idea. In the meantime, as a workaround, I suggest you either disable automatic suspending or, in the addon's menu, choose "don't suspend for now" before you begin working on a page.

**Comment by zldrq** [comment]
let me get this straight: you -- as a part of small group of developers who are so lazy, they can't explicitly use "don't suspend for now", or disable suspending temporarily -- are trying to make someone to override this behavior for you?
the fact this functionality is very specific and needed by 'strong minority' making it worse.
here! i have an idea: fork and implement. oh, and don't forget a setting in options to switch it on/off, because actually it will be poor behavior for me in particular and, i assume, for many others

don't take personal, plz. it's the rationalism demon speaking ^^

**Comment by Corrodias** [comment]
Your post would be easier not to take personally if you didn't write it with personal attacks.

Yes, people request features from developers. Sometimes those features don't get made. This thread in no way forces the developer to comply with the request.

**Comment by olso** [comment]
@Corrodias :+1: 

@zldrq :-1:

**Comment by joepie91** [comment]
@zldrq That kind of hostility is completely unwarranted. That's not rationalism - it's attacking people for no good reason.

**Comment by deanoemcke** [comment]
I feel that the option to 'temporarily pause suspension' is a good workaround for this. It's these kind of use-cases that the option was written to handle. 
Also, without looking into it too much, I'm pretty sure I can't detect whether the developer tools is open.
Whitelisting is another option - The whitelist works purely by string comparison of the url. So you can add any string to your whitelist that uniquely identifies the site you are developing. 
Adding localhost to your whitelist should also work quite well.

**Comment by joepie91** [comment]
[This](http://stackoverflow.com/a/25155634/1332715) seems like a potentially viable option to detect developer tools being opened.

Unfortunately, the alternative options you suggested don't quite cut it:

* __Temporarily pause suspension:__ I very frequently switch between developing and not-developing (specifically when working on scraping stuff), and it's very cumbersome to have to constantly enable/disable suspension, while also being very prone to being forgotten - plus, as I understand it, the pausing is global and affects *all* tabs, not just those being developed on.
* __Whitelisting:__ Works for developing your own site, but not for scraping. You're necessarily working on other people's domains, often many of them.

**Comment by deanoemcke** [comment]
@joepie91 actually, the pausing is just for the active tab. it looks like the link you posted will detect when dev tools is open in its own window, but doesn't help to detect if dev tools is embedded in an actual tab - which is what I assume you're after?

**Comment by joepie91** [comment]
Yes. Do Chrome extensions not get the ability to inject code/behaviour into loaded documents? Perhaps I'm misunderstanding something about how extensions work.

**Comment by deanoemcke** [comment]
@joepie91 They do. But I'm not sure how this helps? To implement this functionality, you would need to have some js that you could run inside the console of a tab that returned whether devtools was open for that tab. Does that make sense? There may well be some obvious code for this, I just am not aware of it.

**Comment by joepie91** [comment]
As I understand it, the code I linked can be injected into a page to detect whether developer tools are open or not. The extension could then use that injected code to automatically pause suspension for that tab when developer tools are opened.
