### ISSUE TITLE
Not suspending at all

### ISSUE THREAD

**Issue by coder65535** [deanoemcke/thegreatsuspender#161]
I have just been updated to the latest version of this extension. For reference, my previous version was before the style change, probably less than a week old. I am now unable to suspend any tabs at all, whether by waiting for them to expire or by clicking on the extension and choosing "suspend this tab". I am using Chrome Version 41.0.2272.101 m (64-bit). Could you please either fix this issue, or tell me what I need to do to fix it?

**Comment by deanoemcke** [comment]
it seems a small number of people have been affected by this bug. i'm currently working on a fix. will keep you posted.

**Comment by coder65535** [comment]
For me, an uninstall and reinstall worked.

Well, to be more specific, an uninstall, followed by panicking because Chrome closes an extension's tabs on uninstall (I lost 80+ tabs), followed by a reinstall, followed by more panicking because my tabs weren't in the session manager, followed by me restoring Chrome's session from a backup, followed by another reinstall because that destroyed my extension list worked.

So, basically, a reinstall.

**Comment by deanoemcke** [comment]
@coder65535 it was be great if you could try something for me. Try going to the main extensions page and restart the extension. Does this fix the problem? If not, can you try turning on the developer mode in extensions, then open the background page for this extension, restart the extension, and report any errors you see in the background page console? Let me know if you need help with any of this stuff. Cheers.

**Comment by coder65535** [comment]
It is already working. The reinstall chain fixed it. Do you want me to do this anyway?

**Comment by deanoemcke** [comment]
@coder65535 i'm really sorry. i should have told you to unsuspend all first! just assumed that because it wasn't working you wouldn't have had any suspended tabs.
i suspect that simply restarting the extension would have worked as opposed to uninstalling and reinstalling. nevermind, glad it's all working now.

**Comment by deanoemcke** [comment]
@coder65535 no, don't worry about all the testing stuff anymore. now that you've got a working version there won't be any interesting test cases to debug. another user has provided me with some errors that i can work with. thanks for all your help.
