### ISSUE TITLE
Does not work at all with WhiteHat Aviator

### ISSUE THREAD

**Issue by Prito** [deanoemcke/thegreatsuspender#162]
Been using with Aviator for several months now.  With this new upgrade, not only can I not suspend tabs, but I can't even save changes on the options page.

**Comment by deanoemcke** [comment]
@Prito can you tell me which version you have been upgraded to? there has been a few recorded instances of not being able to save changes to the options page. i am pretty sure this has been resolved in the most recent release (v6.14).
if you go to settings->support or chrome://extensions you should be able to see your version number.
if you find you're not on the latest version, then unsuspend all tabs, and then uninstall and reinstall the extension from the webstore. this should solve your problem.
let me know how you get on.

**Comment by deanoemcke** [comment]
@Prito This should be fixed in the latest chrome webstore version (v6.16).
The update is not automatic so you'll need to do an uninstall / reinstall to get the latest version. Make sure you unsuspend all tabs before doing this.
