### ISSUE TITLE
Update deleted all suspended tabs

### ISSUE THREAD

**Issue by Cschuldt** [deanoemcke/thegreatsuspender#163]
Xubuntu 14.04
Chromium Version 39.0.2171.65 Ubuntu 14.04 (64-bit)
Great Suspender 6.14

Hey, after the new version automatically installed today (noticed through random "great suspender" tab that said "everything is awesome now like always") all my suspended tabs got deleted.
Trying to restore the last "recent session" through the settings opened 20 empty windows causing my chromium to crash (greetings from my laptop...). After several more and different tries I gave up and started restoring by hand via history (from 5 windows 50 survived tabs back to 19 windows 150 tabs taking over 1 hour - which aren't even all).

Please check your (major) releases/update processes more carefully - I do not wish to go through that again....

**Comment by code88899091** [comment]
"Does this extension makes you emotional?" YES INDEED!!!!!11111
Nothing is worse than asking such question after this AWESOME AWFUL DREADFUL HORRIBLE UPDATE!

**Comment by Corrodias** [comment]
Do you happen to know what version it upgraded from?

**Comment by Cschuldt** [comment]
Sadly I don't, but it should have been the latest version published to the extension store.

**Comment by code88899091** [comment]
From 4.74

**Comment by zldrq** [comment]
but what i suggest, is to back up suspended tabs list at least in some human-readable format, or at html file automatically and store it somewhere in chrome user data folder

if it is impossible, store this list in database of extension, so if this awful event occurs again on update (i expect extension ID just changed or smth?), user would be able to find old database file and show it to extension so extension will retrieve lost tabs.

or if it is possible, backup (ask to backup) this tab list before every update.

also, as i understand extension knows its ID (and new version would know old version's) and read the backup from database automatically, or at leas give user a clue where to find the database file

it's all from the top of my not-knowing-anything-about-wrighting-extensions head as i thinking of this (horrible as i consider) "crash". there must be better solutions, i suppose. but it must be solved with top priority. everyone hates when things like that happen and it doesnt serve extension's positive reputation or rating for sure

(as of me, when i'd found out that extension was updated on chrome webstore, i disabled my local copy of github extension and lost all suspended tabs
i enabled it again and loaded all tabs, unsuspended them and suspended with version from chrome webstore. so i was lucky)

**Comment by Corrodias** [comment]
If I had to guess, the restoration-on-update process only works if the version you're updating -from- records what tabs are open and the version you're updating -to- reads that record. If the older versions such as 4.74 don't record the tabs, then there is no possible change in a new version that will make it able to restore the tabs from that version.

But I haven't looked at the code.

**Comment by eoosting** [comment]
this plagued me as well.

However, after update, I was able to restore my session by going to extension's settings/options, then to Session Management, and then selecting a session to restore.

not ideal, but perfectly acceptable workaround.

**Comment by deanoemcke** [comment]
This closed thread may contain some useful information for people looking for solutions as to how to recover lost tabs: https://github.com/deanoemcke/thegreatsuspender/issues/512
