### ISSUE TITLE
Suspended tabs in the sync list are called "Suspended Tab"

### ISSUE THREAD

**Issue by Corrodias** [deanoemcke/thegreatsuspender#164]
When you look at the history page to see what tabs are open on other devices, anything that's suspended is called "suspended tab" with the TGS favicon. It would be preferable to coerce Chrome to display the altered title and favicon that TGS sets on the tab locally. I have no idea whether this is possible.

**Comment by greatsuspender** [comment]
Actually I discovered this yesterday, and have already implemented exactly what you suggested.
Look out for version 6.15 which will contain this functionality.
As an added bonus, it means that suspended tabs now sync nicely across devices!

**Comment by Corrodias** [comment]
Well, sweet. Thanks for being on top of this.

**Comment by deanoemcke** [comment]
It turns out that the chrome sync issue has not been resolved. I'll try to take another look at this. Note though, that this issue relates to history of other devices only, the history of the local computer does show the proper favicon, title and urls.

**Comment by deanoemcke** [comment]
To continue following this issue refer to https://github.com/deanoemcke/thegreatsuspender/issues/225
