### ISSUE TITLE
No suspention for javascript-disabled tabs

### ISSUE THREAD

**Issue by Profforgr** [deanoemcke/thegreatsuspender#169]
Hi.

I regulary disable javascript while visiting websites. But with new version of plugin, it does not work on javascript-disabled tabs.

It looks like i can still suspend them by manually click "Suspend other tabs", but it does not happen automatically.

Can this be fixed?

**Comment by deanoemcke** [comment]
In the new version of the extension, I changed how tab suspension works (it is now performed by the tab itself via a setTimeout in a content script. 
This explains why it will no longer work on javascript disabled tabs. There has been another issue raised from this #176 in which I explain my reasons for the change.
I may look at changing this in the future but it will need some more discussion. How badly is it affecting you? I would guess that not many people disable javascript?

**Comment by Profforgr** [comment]
> I may look at changing this in the future but it will need some more discussion. How badly is it affecting you? I would guess that not many people disable javascript?

I see you are rather busy. That's not critical. I will close that.
