### ISSUE TITLE
suspended tab display options [request]

### ISSUE THREAD

**Issue by zldrq** [deanoemcke/thegreatsuspender#171]
now suspended tab is just dimmed
when there were no updates, i used version from github (load unpacked extension)
i've made some changes so suspended tabs were seen better:

![susp](https://cloud.githubusercontent.com/assets/3038215/6902924/9bb56558-d71f-11e4-8068-bfa40356f3f4.PNG)

unfortunately i'm not javascript programmer (happily, actually. c# rules) and i only was able to change the style, but not to add an option to extension to switch style back and forth to submit it into repository

so it wold be great if someone could manage it

**Comment by deanoemcke** [comment]
Can you please be more specific with exactly what you are requesting? Are you saying you'd like to add an option to prevent suspended tabs from dimming their favicons?

**Comment by zldrq** [comment]
no, i'm saying that just dimming the favicon is not obvious enough and those must be more distinct =)

**Comment by deanoemcke** [comment]
I have toyed with this idea in the past and even implemented it before. But in the end I felt that it distracts from the favicon itself which is so key to identifying what a tab is.
I may look at implementing an optional styling as you suggested some time in a future release though. Especially if this feature requests gets some support.
