### ISSUE TITLE
The extension does not recognize that the laptop is on battery

### ISSUE THREAD

**Issue by nicocarbone** [deanoemcke/thegreatsuspender#174]
Unplugging the laptop from the power source does not trigger the automatic suspend of tabs. The extension popup still says ""Connected to power source".

I am using Chrome x64 on Ubuntu 14.04.

**Comment by deanoemcke** [comment]
The only way to detect whether the computer is connected to a power source is with navigator.getBattery(). This feature is only available in chrome v38 and higher. Does this account for your issue?

**Comment by thomaswsu** [comment]
I have this issue with the latest version of Brave Browser on my Mac. When I used Chrome it works.
