### ISSUE TITLE
Feature request: suspend down to a certain number of active tabs

### ISSUE THREAD

**Issue by aug-riedinger** [deanoemcke/thegreatsuspender#175]
I like the idea of #170 , though it might be very tricky to handle.

I have a more lightweight version to suggest: having an optional parameter of the number of tabs that should be kept active (Eg. 20). When the user's opening the 21st one, the eldest goes sleepy (and it could be combined with the duration rule: 21st and older than 1 hour).

It shall achieve more or less the same results as #170 but the extension doesn't have to calculate what "low memory" means (which is hard), as the user knows that after 20 tabs, its laptop starts becoming slow.

This would definitly prevent me from having to reload quite a lot of tabs!

**Comment by deanoemcke** [comment]
This has been suggested before in #136 and #19.
I am leaving #136 open as the active thread for further discussion (and will hence close this issue).
For the record, I think this is a great idea. As mentioned in the other thread though, I'm just worried that it will make the extension overly complicated. Happy to hear input from others on the topic though.
