### ISSUE TITLE
Unsuspend when refreshing tab

### ISSUE THREAD

**Issue by liamjohnston** [deanoemcke/thegreatsuspender#177]
Sup Dean. 

Whenever I select a suspended tab and want to unsuspend it, my instinct is to refresh the page (using the keyboard). But all this does is refresh the suspended page (effectively doing nothing). I then have to grab my mouse and click the page instead.

My workaround has been to set my keyboard shortcut for unsuspending a tab to be the same as refreshing a page (command + R on OS X)....  this works fine, but I'd really expect this to be the default behaviour when refreshing a suspended tab. 

EDIT: scratch that; this workaround doesn't work as it stops the shortcut for refreshing a non-suspended tab from working 

Unless there's a good reason you might want to refresh a suspended tab?? Is this so that when opening a window with suspended tabs all suspended tabs don't unsuspend or something?? Or just an oversight?

L

**Comment by deanoemcke** [comment]
I whole-heartedly agree that refresh should unsuspend the tab.
But you are correct in your assumption that I have not implemented this as it would mean that reloading a window with suspended tabs would cause all suspended tabs to reload.
AFAIK there's no way to tell the difference between a page reload, and an initial page load.
I think it's important to keep the functionality that allows pages to remain suspended when opening a window - at the cost, it seems, of not being able to use refresh to unsuspend a tab.

**Comment by Zegnat** [comment]
Long shot, but, what about triggering on `unload`? IIRC browsers will fire an `unload` event before a refresh, but shouldn’t on initial page load (for obvious reasons).

**Comment by deanoemcke** [comment]
@Zegnat great idea! tried unsuccessfully to call some window.location code on unload, but then managed to get it to work with an extension message requesting a reload.
will try to get this out in a release soon. thanks for your help.

**Comment by Zegnat** [comment]
No problem, I expect to get full credit for the words “triggering on `unload`” 😉 Nice work on this extension!

**Comment by deanoemcke** [comment]
This has been released (v6.x).

**Comment by TalOrbach** [comment]
Is there any way to make this work when reloading several tabs?
