### ISSUE TITLE
Feature request: Hide Suspender button

### ISSUE THREAD

**Issue by Darkhand81** [deanoemcke/thegreatsuspender#178]
Would greatly appreciate an option to hide the Suspender button in the bar (as cute as he is), to prevent clutter.  Thanks in advance!

**Comment by goldbattle** [comment]
Right click on the icon, and click `Hide Button`.

**Comment by Darkhand81** [comment]
Apologies for missing that somehow!

**Comment by KarthikNayak** [comment]
Close the issue?
