### ISSUE TITLE
For suspended tabs, switch the function of the top box with the function of the box below

### ISSUE THREAD

**Issue by zwaa-vengeance** [deanoemcke/thegreatsuspender#180]
For suspended tabs, switch the function of the small box on top(Title and "Add [site] to whitelist") with the function of the big box below("Tab suspended - Click to reload"). The most clicked box must be closest to the tab selector to minimize mouse movements.

**Comment by deanoemcke** [comment]
@zwaa-vengeance this is very similar in nature to your other feature request to be able to double click the favicon to unsuspend. i'm noting that here to keep them linked.
are you aware that there is a keyboard shortcut for unsuspending a tab? this might be an alternative for you. also, there is a preference you can check to automatically unsuspend tabs when you view them, meaning you don't need to click anything to reload the tab.

**Comment by zwaa-vengeance** [comment]
Sorry for late answer. The double click thingy suggestion is quite different in use, and similar only in the sense that it's addressing suspend/unsuspend. I have answered that issue in there.
As for this issue, having to move the mouse way down is a drag, though from your point of view I'm guessing that you prefer having the whitelist tip on top, so perhaps I'll just have to live with that.
It's all about saving time, as is the other issue, and using a keyboard shortcut would mean having to let go of the mouse, strike the keyboard shortcut, and lastly return to the mouse. That would actually take a lot more time than swiping the mouse down to the "Tab suspended - Click to reload" box.

**Comment by zwaa-vengeance** [comment]
The automatic unsuspend feature doesn't play well with the way I switch tabs. Personally, I generally avoid using it because I keep trigging it unintentionally when switching from one tab to another. But again, perhaps I'll just have to live with the current design.

**Comment by deanoemcke** [comment]
There is now a reload link in the top bar.
And you can also reload the tab by refreshing the page (using keyboard shortcut).
Hopefully this addresses your issues

**Comment by zwaa-vengeance** [comment]
I wish to emphasize that keyboard shortcuts is never a replacement for
mouse controls. Providing efficient mouse controls should be a priority
because keyboard shortcuts has distinct disadvantages:
- The more apps, extensions and whatnot that you use keyboard shortcuts in,
the more shortcuts you will inevitably confuse and forget. Using the wrong
shortcut can lead to devastating results, and therefore the *only* safe way
to operate is to use the mouse over keyboard shortcuts.
- There is a finite number of keyboard shortcuts that the operating system
provides, and many extensions that provide shortcuts doesn't allow for
changing them or turn them off, setting the table for unpredictable
conflicts even with shortcuts outside of Chrome, ie system wide shortcuts
that may be blocked. I have encountered this more than once and in a couple
of instances even chose to refrain from keeping the extension because of it.
- Over time, the average user will install and uninstall countless apps,
extensions etc, and even more keyboard shortcuts will accompany them.
Keeping track of all shortcuts for even one single app can be too
exhausting, and in the end the keyboard shortcuts that you remember and use
are the ones that you save the most time using, and that saved time is a
combination of how often you use them and how much faster any given
shortcut is compared to the mouse operation equivalent.
- For any developer to expect the users to memorize and use the keyboard
shortcuts and therefore not provide mouse alternatives is to deprive the
users their free choice of which shortcuts that they're going to try and
remember, if any at all (yes, such users exist and in abundance).

**Comment by kankaristo** [comment]
Just to play devil's advocate (in favor of keyboard shortcuts):
1. Mouse isn't "the only safe way", you can always accidentally click the wrong thing, too (I accidentally click "Whitelist" all the time, when I meant to click "Don't suspend for now")
2. As far as I know, Chrome extensions can't define keyboard shortcuts without the user being able to redefine them through `chrome://extensions/shortcuts` (an average user won't know this though)
    - You can also use this to override even Chrome's own keyboard shortcuts (I've overridden Ctrl+S, because I never save a webpage as an HTML file, and I like using Ctrl+S as "save" for more useful things)
3. Can't really argue with this (for average users at least), although some programs allow you to redefine keyboard shortcuts, so you can redefine these programs to use the same shortcuts for similar things (less memorization for each program's own shortcuts)
    - Ctrl+Shift+Z versus Ctrl+Y for "redo" is a pet peeve of mine
4. This is absolutely true, and it would be nice if The Great Suspender would show the keyboard shortcuts in its menu items (but I'm not sure if Chrome's extension API allows retrieving the user's keyboard shortcuts?)

**Comment by deanoemcke** [comment]
@zwaa-vengeance 
sorry to bring up keyboard shortcuts again. i only mentioned it because the **default chrome refresh keyboard shortcut** will now unsuspend tabs. so you don't need to memorise any new shortcut. 

also, i do understand that if you're a mouse-centric user, having to use the keyboard is always going to be sub-optimal. but as kankaristo pointed out, using a mouse comes with accuracy issues. i would have thought that the most important thing for a mouse user would be a very large space to click on. i can't imagine having to aim at a small bar at the top of a tab is easier than clicking anywhere further down?

@kankaristo 
the new version shows the keyboard shortcut for suspending/unsuspending on the suspended tab page. so for users that are not aware it exists, this should help.
