### ISSUE TITLE
The settings "Only auto-suspend if .." are out of whack

### ISSUE THREAD

**Issue by zwaa-vengeance** [deanoemcke/thegreatsuspender#181]
1. If you check "Only auto-suspend if running on battery", also "Only auto-suspend if connected to the internet" gets checked, regardless if it's not checked to begin with.

2. The setting "Only auto-suspend if connected to the internet" does not save unless also "Only auto-suspend if running on battery" is checked.

**Comment by teresaejunior** [comment]
I have the same problem on the latest Chrome stable (42.0.2311.90).

**Comment by sprt** [comment]
Same here

**Comment by deanoemcke** [comment]
Thanks for the fix @matheod

**Comment by teresaejunior** [comment]
Seems to be working fine, thank you!
