### ISSUE TITLE
Idea: store tab state on disk

### ISSUE THREAD

**Issue by sprt** [deanoemcke/thegreatsuspender#183]
Have you ever considered this possibility?

**Comment by deanoemcke** [comment]
@sprt What exactly do you mean by tab state? In a way, this is exactly how the extension currently works. It records the current tab title, favicon and (optionally) an image preview, and saves this information to disk. This is how, if you restore a chrome window with suspended tabs, all those tabs are able to reload their favicons and titles without needing an internet connection.

**Comment by sprt** [comment]
I mean storing the DOM itself so that you don't have to reload the page. Not sure it's even feasible though.

**Comment by deanoemcke** [comment]
huh. that could be interesting. no idea if it's feasible or not. might have a look into it.

**Comment by deanoemcke** [comment]
thinking a bit more about this, it would probably be a whole other extension in itself. one that has already been implemented by many other people it seems: http://superuser.com/questions/470813/make-chrome-webpages-available-offline
i will probably not go down this route, though i can see how it would be awesome.

**Comment by deanoemcke** [comment]
I have had another think about this and may look at implementing some kind of offline mode at some point. 
Here is a similar related issue: #220

**Comment by deanoemcke** [comment]
Duplicate of: https://github.com/deanoemcke/thegreatsuspender/issues/265
