### ISSUE TITLE
Bookmarked suspended tabs won't open..

### ISSUE THREAD

**Issue by thostby** [deanoemcke/thegreatsuspender#185]
So, as title explains; bookmarked suspended tabs won't unsuspend and goes back to my previous page. 
Ex. when I open chrome with google as homepage and select to open a bookmarked tab/page (that was suspended when bookmarked), it opens the tab/page suspended. Then further when I click to unsuspend the page I get directed back to my previous page (this time google).

The only thing that's possible (to open the suspended pages) is to erase/cut out some of the symbols that the great suspender has added to the original url?

**Comment by deanoemcke** [comment]
@thostby Can you please let me know the version of the extension you are using? Tests on the latest version seem to handle this usecase OK. ie:
- bookmark a suspend page
- open a new window and then load bookmark
- click on the suspended page to unsuspend it
- bookmarked page loads ok.

**Comment by thostby** [comment]
Hi, 
Suspender version is 4.74
Chrome version is 42.0.2311.135 m

**Comment by deanoemcke** [comment]
ok. you are on a very old version of the extension. i have not automatically upgraded users, as the upgrade process causes you to lose any tabs that were suspended at time of upgrade.
if you want the latest version, you can uninstall your current version and then reinstall from the webstore. IMPORTANT NOTE: make sure you unsuspend all tabs before doing the uninstall. you will also lose any saved sessions you may have made.
