### ISSUE TITLE
Settings don't carry over into incognito

### ISSUE THREAD

**Issue by theworstninja** [deanoemcke/thegreatsuspender#189]
When I turn on the extension for incognito mode, the welcome screen opens up in a new tab (the screen that pops up when you first get the extension) and none of the settings I had are there.  Can you make it so the extension keeps the settings it had from regular chrome mode in incognito mode as well?

**Comment by deanoemcke** [comment]
The welcome bug has been fixed in the development version of this extension. As for the settings, it does appear that I could get this working if I switch to using chrome.storage instead of local.storage. I may make this change in future.

**Comment by theworstninja** [comment]
When you say the 'development version' of the extension, do you mean the one currently on the google webapp store, or are you talking about something else?

**Comment by deanoemcke** [comment]
I mean this version on gitHub. You need to follow different instructions to install it from source.
The fix is not yet available in the chrome webstore but will be soon. For reference, v6.16 and higher will contain the welcome message fix.

**Comment by Busimus** [comment]
Inability to properly use The Great Suspender in incognito is the only problem I have with the extension. Would love to see a fix.

**Comment by deanoemcke** [comment]
The latest version (not yet in the webstore) supports synching of settings. This will enable you to sync between normal and incognito mode as well.

@Busimus Could you please elaborate on the current issues you are having with the extension in incognito mode? Is it just that you would like the settings to sync?

**Comment by Busimus** [comment]
@deanoemcke Yes. I just built the 6.31 version and it solved all my problems. Thanks!
