### ISSUE TITLE
Tab not suspending properly

### ISSUE THREAD

**Issue by theworstninja** [deanoemcke/thegreatsuspender#190]
Whenever another chrome window is opened (but still part of the same session, i.e. long onto one website in one window and still be logged in on the site in the next), if I'm only using one window and not the other (actively scrolling and clicking in the window selected), the non-used window wont go into a suspended state.

**Comment by deanoemcke** [comment]
The active tab in each window (the one showing when you switch to that window) will never suspend. So if that window only has one tab open, that tab will stay unsuspended. You can force it to suspend however with the option from the popup or by using the suspend tab hotkey.
Does this account for your issue?

**Comment by theworstninja** [comment]
That was addressing what my issue was concerning.  It's unfortunate to hear that it can't be automatically suspended when it's the only tab open in the window, as I'll often browse with multiple windows using multiple tabs, and I would like to have the active tabs in other windows be suspended after the automatic suspension time limit has been hit.

**Comment by deanoemcke** [comment]
I consider that a worthy feature request. I have raised it as such in issue #191.
I will close this issue as it is somewhat ambiguously named.
