### ISSUE TITLE
Dark theme for suspended pages

### ISSUE THREAD

**Issue by deanoemcke** [deanoemcke/thegreatsuspender#193]
From an email request:

As many others do, I have extensions for my most frequented websites that make them 'dark'. This is to reduce strain on the eyes, mostly. However, when the Great Suspender kicks in, the page gets replaced by a very bright, blue color. It's a bit like having to look into a camera flash.

On behalf of night users, I'd like to suggest making an option for what the suspended tabs look like. A simple dark theme would suffice for me, although more customizations are always welcome for advanced users of any program.

**Comment by Ardens** [comment]
Original requester here,

I attempted to implement it for myself as per your suggestion. However, upon the first edit of 'suspended.html', Chrome immediately shut down the extension, saying that it was corrupted and directed me to a fresh install.

.centerBoxContainer {
	background-color: #2D2D2D;
}

**Comment by deanoemcke** [comment]
Right. Chrome must not allow you to tamper with extensions installed from the webstore.
An alternative is to download the source from this repository and install it directly. There are instructions on how to do this on the readme of the main project page.
You will then be able to modify your css at your leisure :)

**Comment by Ardens** [comment]
Thanks for all the help, I now have a wonderful dark color on my Suspender.

For those who would like some more detail on how (aka if you are inexperienced like I am):
Navigate to the css\suspended.css file within the Suspender files, and insert

background-color: #2D2D2D;

to a bunch of the sections, most notably .centerBoxContainer . Any text editor suffices for editing it.
If you want a darker color than that, look up a Hex color picker and replace as desired.

**Comment by cwilliams5** [comment]
Aaaand there goes my suspended tabs, gone forever... For anyone else, you can't modify the suspended.css as mentioned above on a running chrome webstore install of great suspender. Chrome will kill the extension as tampered with and make your resinstall, even after undoing my changes.

I also desperately need a dark version, but wouldn't installing from source to customize cause me to miss out on auto updates?

It would be nice to have a way to modify the theme while staying on the webstore version for auto-updates. Doesn't even need a whole dark theme, just a box to paste in custom css would be great.

Also, thanks for the most important chrome extension in existence.

**Comment by deanoemcke** [comment]
@Ardens @cwilliams5 hey guys. could you share exactly what changes you made in your custom night mode? I'm looking at implementing this and want to get an idea of what is working for you..

**Comment by Ardens** [comment]
thegreatsuspender-6.15-beta.2\css\suspended.css is where I made my edits. Fairly certain I reverted the other file I messed with, though even if I didn't, my edits there didn't seem to make a difference.

I ran my file and yours through diff checker, and my changes are as follows:

body{} removed. Not sure why I did this, probably just because I was trying things until it worked.
a{} removed. 	.btnDonate {} removed. 	.btn {} removed. Again, unsure why I did this. Probably an accident?


The line 
background-color: #2D2D2D; 
was added to the following sections:
	#gsTopBar
	#gsTopBarTitle
	#gsWhitelistLink
	.centerBoxContainer
	.centerBox
	#suspendedMsg h1, #suspendedMsg h2
Although most of this was just me pasting it into whatever section and refreshing the page in Chrome. Hope it helps.

**Comment by deanoemcke** [comment]
This feature is now live on the chrome webstore in version 6.21.

To update you will need to uninstall and then reinstall the extension. 
IMPORTANT: Before uninstalling, make sure you unsuspend all currently suspended tabs. Also, this will delete your whitelist and any saved sessions you have created, so you will need to export these before you update.

**Comment by Pysis868** [comment]
Can't believe I missed this setting since it's right by the suspend thumbnail option, and I have 7.1.0.  Now I just need it to change the settings page as that is still bright as heck..
