### ISSUE TITLE
Add wildcards to whitelist

### ISSUE THREAD

**Issue by deanoemcke** [deanoemcke/thegreatsuspender#197]
From an email request:

I recently started using The Great Suspender, it's definitely living up to its name. The one feature that I would really like to see is for the whitelist to use wildcards instead of... whatever it does now. I don't understand words enough to state the difference. But, it would be really great to whitelist a parent domain without also whitelisting the subdomains.

For example, a big use I have for it is on my million reddit tabs that I open as I browse the front page and will get to later, but I'd prefer not to suspend my "reddit.com" page and have to refresh it. So, if the sub pages were whitelisted with *reddit.com* instead it wouldn't be a problem.

**Comment by deanoemcke** [comment]
A workaround to this would be to take advantage of the 'dont suspend for now' option.
If you click this on your main reddit.com page, it will stop it from suspending automatically. All your other reddit pages will continue to suspend as normal.
The whitelist currently works as a simple string match - so adding reddit.com will whitelist ALL reddit subdomains as you have found.
I can see a use for adding in more complex whitelisting functionality, but am not sure it's worth the extra complexity as long as there are good workarounds.
Happy to hear other use-cases for this though..

**Comment by DanAtkinson** [comment]
It seems a little bizarre that simple wildcards haven't made it into the extension.

As a minimum level of support, I would expect the following to pass a whitelist check:

* **\*.example.com** - Where the \* is a subdomain.
 * www.example.com
 * foo.example.com
* **example.*** - where the \* is a TLD.
 * example.com
 * example.co.uk
* **example.com/section/*** - Where the \* is a part of the site that is not 
 * example.com/section/foo
 * example.com/section/bar

**Comment by deanoemcke** [comment]
Related to suggestion at the end of issue #106

**Comment by vogler** [comment]
+1
Maybe instead of the [indexOf](https://github.com/deanoemcke/thegreatsuspender/blob/4fece858bf349856d9824ee835a10fb928326697/src/js/background.js#L39), do something like @DanAtkinson described (e.g. [like this](http://stackoverflow.com/questions/3117218/matching-url-with-wildcards)) if there are `*` in it, and full RegExp if it contains anything from  `.*, +, [, ]` and successfully parses as one.

**Comment by DanAtkinson** [comment]
As seen by the above, I finally snapped and decided to look at resolving this issue. It's a single line fix, replacing out `url.indexOf(word) >= 0` for `RegExp(word).test(url)` which returns a boolean.

**Comment by deanoemcke** [comment]
OK. I have now implemented this in the latest gitHub version. Would be great if someone could test it out. To prevent existing whitelisted entries from being evaluated as regular expressions, I require all regex entries to be enclosed in forward slashes. ie: /^https:.*google\.com/
Anything without a leading and trailing slash will be evaluated as a substring.

**Comment by deanoemcke** [comment]
This feature is now live on the chrome webstore (v6.21).

To update you will need to uninstall and then reinstall the extension. 
IMPORTANT: Before uninstalling, make sure you unsuspend all currently suspended tabs. Also, this will delete your whitelist and any saved sessions you have created, so you will need to export these before you update.

**Comment by justingoldberg** [comment]
This feature needs documented examples.

**Comment by DanAtkinson** [comment]
@justingoldberg Hover over the question mark icon.

**Comment by justingoldberg** [comment]
Dan, thanks, I was clicking it and nothing happened!
