### ISSUE TITLE
Add setting to prevent suspension of rightmost tab

### ISSUE THREAD

**Issue by NeilMartin** [deanoemcke/thegreatsuspender#198]
I would love to have a checkbox setting that would never suspend the rightmost tab.

"Never suspend rightmost tab"

This is because the rightmost tab is very often the most important tab to me _right now_. Usually the last tab opened, and if not I drag it to the right anyway. Not important enough to add to the whitelist, just the most important thing _right now_. e.g. shopping at some online store or referring to a thread or some documentation or writing this post. You could even go more 1337 and have a setting like...

"Never suspend rightmost [0..n] tabs"

Where [0..n] is a textbox for entering an integer.

This would allow the user to easily and quickly nominate a tab to not be suspended without going into the settings.

Thanks for a great extension!

**Comment by deanoemcke** [comment]
I think this might be behaviour that is pretty specific to your work flow only. There are a couple of precendents that go counter to this idea:
- Pinned tabs automatically pin to the *left* indicating that the leftmost tabs are the most important
- Right clicking on a tab title has an option 'close all tabs to the right' indicating that tabs to the right tend to be less important.
