### ISSUE TITLE
By default, don't suspend tabs that show notifications

### ISSUE THREAD

**Issue by dbkaplun** [deanoemcke/thegreatsuspender#200]

**Comment by deanoemcke** [comment]
I'm not sure if it is possible to detect whether a tab shows notifications. Will need to do some more research on this.
As an alternative, I have implemented an option in the popup call 'dont suspend for now' which will prevent the current tab from suspending automatically in the background. This can be used to prevent tabs that show notifications from suspending.
Another alternative is to whitelist the url of the site if you'd like it to always remain unsuspended.
