### ISSUE TITLE
suspend other tabs issue

### ISSUE THREAD

**Issue by dbcdcw** [deanoemcke/thegreatsuspender#203]
when i click the button 'suspend other tabs' . it will suspend all tabs with the one i don't want suspend

**Comment by deanoemcke** [comment]
can you please be a bit more specific about the issue you are having? are you saying that the active tab is also being suspended when you click this button?

**Comment by MrMormon** [comment]
This is happening to me quite often as well.

**Comment by deanoemcke** [comment]
Closing as duplicate of #273
