### ISSUE TITLE
Fix 6.16 package uploaded to the Chrome Web Store

### ISSUE THREAD

**Issue by mjgiarlo** [deanoemcke/thegreatsuspender#204]
When I try to install this extension via:

https://chrome.google.com/webstore/detail/the-great-suspender/klbibkeccnjlkjkiokjodocebajanakg

I cannot due to the following error: `Package is invalid. Details: 'Could not unzip extension'.`

**Comment by deanoemcke** [comment]
@mjgiarlo can you please give me information on your chrome version and also your operating system? thanks.

**Comment by mjgiarlo** [comment]
@deanoemcke Certainly. I am running Chrome 43.0.2357.65 beta (64-bit) on Ubuntu 14.10.

**Comment by mjgiarlo** [comment]
Nevermind!  I had an issue with an overly full /tmp directory.  Sry.
