### ISSUE TITLE
Retina favicons

### ISSUE THREAD

**Issue by deanoemcke** [deanoemcke/thegreatsuspender#205]
From a webstore request:

Please suspend the favicons in the tabs with Retina quality. Currently they are very blocky on most Macs.

**Comment by hpurmann** [comment]
I just noticed the same after switching to a Retina display.

It seems that `chrome://favicon/` itself gives non-retina, blurry favicons. So this may not be that easy to solve.

**Comment by liamjohnston** [comment]
Sorted it out. It's in a new pull request, I'm working with @deanoemcke to get this into the next version.

Here's some before and afters to whet your appetite.

Codepen before:
<img width="161" alt="codepen before" src="https://user-images.githubusercontent.com/1134713/27408351-4701863e-5730-11e7-8349-5d596756a9b7.png">
Codepen after:
<img width="135" alt="codepen after" src="https://user-images.githubusercontent.com/1134713/27408350-47003130-5730-11e7-84d3-77df9f4bd8d7.png">

Apple before:
<img width="139" alt="apple before" src="https://user-images.githubusercontent.com/1134713/27408369-597de1a4-5730-11e7-816f-20fd741196bb.png">
Apple after:
<img width="128" alt="apple after" src="https://user-images.githubusercontent.com/1134713/27408370-598421e0-5730-11e7-91d4-6f6fcc0203ac.png">

It will still look crappy where the site does not have a retina favicon loaded, e.g. this site is the same before and after:
<img width="150" alt="ird" src="https://user-images.githubusercontent.com/1134713/27408402-7bc30e2e-5730-11e7-8e6d-e286dd02455c.png">

And the suspended tab, of course. Before:
<img width="235" alt="suspended before" src="https://user-images.githubusercontent.com/1134713/27408380-627a80c8-5730-11e7-92fb-b50d8c892724.png">
...and after:
<img width="241" alt="suspended after" src="https://user-images.githubusercontent.com/1134713/27408379-62786982-5730-11e7-8c52-17e20a6d34c6.png">

And finally the session management screen before:
<img width="261" alt="sessions before" src="https://user-images.githubusercontent.com/1134713/27408408-88634392-5730-11e7-9ad0-964c0dff7cc5.png">
and after:
<img width="260" alt="sessions after" src="https://user-images.githubusercontent.com/1134713/27408409-88635bde-5730-11e7-8c3e-b543d006fa57.png">

**Comment by hpurmann** [comment]
Nice, looks good 👍
