### ISSUE TITLE
Network Failed

### ISSUE THREAD

**Issue by jogden12** [deanoemcke/thegreatsuspender#207]
Cannot download, though my internet connection is strong.

**Comment by deanoemcke** [comment]
Do you get any kind of error displayed? Are you trying to download from the chrome webstore? What url are you using?

**Comment by jogden12** [comment]
from chrome web store...
https://chrome.google.com/webstore/search/the%20great%20suspender?hl=en-US

Could not take a screen shot... Message pops up after some delay.

An Error has occurred
Network Failed
Learn more (with hyperlink to page that gives directions for removing software that may be blocking download, but I ran the Software Removal tool; it didnt find anything.

Buttons for Reload and Close

**Comment by deanoemcke** [comment]
OK. Can you let me know your operating system and version of chrome. I'll do a test at my end to see if I can replicate it.

**Comment by jogden12** [comment]
Windows 8.1
Chrome Version 40.0.2214.93 dev-m

**Comment by deanoemcke** [comment]
Hi. I'm sorry but I've tested on Windows 8.1 chrome version 40 and seem to have no problem accessing the extension and installing it. There must be something else going on with your computer that's preventing the extension from installing. Unable to help you much more than that sorry.
