### ISSUE TITLE
Feature Request: Hotkey for "Don't suspend for now"

### ISSUE THREAD

**Issue by Voronoff** [deanoemcke/thegreatsuspender#208]
I'd love to be able to set a hotkey for this function. Navigating the right click menu can be annoying. Half the time I'm using it to say "don't make me rebuffer this video" which makes it so you have to make sure to right-click on the non-video portion of the page.

**Comment by deanoemcke** [comment]
An alternative to right-click is to click on the extension icon. There is the same set of options in the popup menu.
May add a hotkey for this in a future release.

**Comment by Voronoff** [comment]
I'm aware of that button and still want the hotkey. I'm glad to hear you are considering it.

I also want to say that this plugin is amazing, and that the lack of this hotkey is my only pain point.

**Comment by isMyUsername** [comment]
+1 for this

**Comment by deanoemcke** [comment]
Implemented in upcoming release
