### ISSUE TITLE
[question] infrastructure improvemetns

### ISSUE THREAD

**Issue by ZuBB** [deanoemcke/thegreatsuspender#209]
I admin that forever active tabs is a real problem. But I did find a good plugin for that till now. 

However when I looked at size of your addon (309KB) I was surprized a bit.

I made a quick investigation and found that 2/3 of addon size is used by thumbs.db

```
vv@e5520 /tmp $ unzip -v the-great-suspender-fixed-0.zip | grep -i thumbs
  118784  Defl:N   102112  14% 2015-05-20 22:52 05009656  img/Thumbs.db
    9216  Defl:N     6221  33% 2015-02-25 06:58 d6deee6e  js/Thumbs.db
  114176  Defl:N   104725   8% 2015-01-26 04:13 39ac9af4  Thumbs.db
vv@e5520 /tmp $ 
```

After that I clicked on 'website' link and was surprised by fact that addon is open and hosts on gh.

As far as I can see you make a new version of crx manually. what do you think if I make a grunt-based build system for that?

**Comment by deanoemcke** [comment]
yikes! really? I had no idea. thumbs.db must be hidden so i've never noticed it.
thanks heaps for the heads up. you're right, it's a pretty manual process at the moment. i'll take a look at grunt because it's a bit ridiculous the way i'm currently doing it :D

**Comment by ZuBB** [comment]
just would like ot let you know that I made a first sketch how things can look and behave

https://github.com/ZuBB/thegreatsuspender/tree/grunt

**Comment by deanoemcke** [comment]
Thanks a lot for that. I got part way through installing grunt and reading
the documentation then ran out of time. Still meaning to take a good look
at this and then I do I'll check out your implementation.
Cheers for helping me out with this :)

Dean

**Comment by deanoemcke** [comment]
@ZuBB thanks for all your help ZuBB. i have set up grunt based loosely on your implementation. to keep things simple i have removed the use of 'load-grunt-config' and not moved all the html files into a separate directory (this would have involved unnecessary/unwanted code refactoring. And of cource, added Thumbs.db to the ignore list :)

**Comment by ZuBB** [comment]
> to keep things simple i have removed the use of 'load-grunt-config
