### ISSUE TITLE
Suspending disables Vimium plugin and restoring doesn't restore Vimium

### ISSUE THREAD

**Issue by deiga** [deanoemcke/thegreatsuspender#21]

**Comment by dumblob** [comment]
This seems to be no more valid. Restoring works for me with already several versions of Vimium and the latest release of The Great Suspender.

@deiga feel free to test it and close this issue.

**Comment by deiga** [comment]
You are correct, it does look like something fixed this. :)

**Comment by devanshuDesai** [comment]
I know this is a very old issue that was supposedly resolved but I'm facing this exact issue in 2020. Maybe a newer version re-introduced this bug.
