### ISSUE TITLE
Feature Request: Page scroll preservation

### ISSUE THREAD

**Issue by luizpericolo** [deanoemcke/thegreatsuspender#210]
Hello, Dean.

I recently started using this extension and I'm loving it so far. I'm telling all my "I use Firefox instead of Chrome because it doesn't load all my opened tabs at once" friends about it and they are all impressed by it!
One thing that bugs me though is that the page scroll is not preserved when a page is unsuspended. I think that this would be an awesome feature, since I have a hard time continuing from where I left off when reading a long post, for instance, when the page is unsuspended. 

I was also surprised that this was not already listed here as a feature request.

Cheers! Keep up the good work!

**Comment by deanoemcke** [comment]
Remembering page scroll location has been implemented. I'm surprised it isn't working for you. However there is one known bug with it (#296) which I will be fixing in the next release.

**Comment by luizpericolo** [comment]
Yup, @deanoemcke. That fixed it.
Sorry for taking so long to answer.

Cheers!
