### ISSUE TITLE
The extension does something for whitelisted sites

### ISSUE THREAD

**Issue by Zachu** [deanoemcke/thegreatsuspender#215]
First of all sorry for vague title...

**When this happens:** Not always when refreshing, but quite often
**What happens:** This extension does something for a website even though it is whitelisted. That something is detected by the website and is concidered as suspicious.
**What should happen:** Whitelisted websites should be left untouched
**Chrome version:** 42.0.2311.152
**Extension version:** v6.14
**Reproducible:** Yes, atleast with https://www.op.fi/

**A longer story:**
So lets cut to the chase. I'm using my online bank website, and as you would know the bank sites are a bit suspicious about things as they should. So that's why I've whitelisted my banks domain, and The Great Suspender shows accordingly the text that "Site whitelisted".

After a refresh or two, the bank website stops working saying that the service usage is prevented and it lists one possible resolution as to stop using browser extensions. And we all know that we're not going to do that, right ;)

The error message that is given from the bank isn't very technical, but it gives one hint. It hints that giving certain special characters (# being listed there) could produce the error. I'm just guessing this might be the case here, and my intuition says that it's the part that scrolls the suspended pages back where it was before, but my guess might be false too.

The bank website can be accessed again by deleting all cookies, but will be unaccessible after a couple of refreshes. Oh, and you don't have to be logged in to this happen.

Here's the translated error I'm getting

```
The service is blocked

Check the following and try again.

• Did you use special characters such as (#)?
• Clear your browser cookies. Note that when you clear your browser history, also other saved information can be removed.
• Does your browser have extensions? Our service does not support extensions. Additional information on browser extensions and how they are can be found from the providers website.
• Try to log in using a different browser.

Error code: <numerical code that changes every time>
```

Hope I didn't forget anything... =)

**Comment by deanoemcke** [comment]
@Zachu thanks for the detailed info. i was not aware that some websites behaved in this way. whitelisting a url will prevent the tab from automatically suspending, however the tab will still contain an extension content script. i would be interested to know why it doesn't happen consistently every time the page loads. I tried out your linked page but can't see anything unusual happening. I guess I need to be logged in?
As a workaround, you could load your banking tab in an incognito window (assuming you don't have the extension enabled for incognito).

**Comment by Zachu** [comment]
Oh it's totally fine for me since as you said, there are multiple of ways to go around it. I just thought to inform about that if there would be something that could be done for it  =)

I agree that it's absolutely weird that it doesn't happen on every single refresh. I'm not logged in and it keeps happening to me both on my work and on my home computers but as a matter of fact it took me dozens of refresh now to produce that behaviour, and earlier it only took like one or two refreshes. One way to make it happen every time is to manually suspend the tab. After returning to the page, it always seems to give the same error.

I also tested the thing with another computer and without any other extensions than The Great Suspender and I couldn't get it to show the error with just refreshing the sites but I could get it by suspending and resuming. Maybe the problem might be somehow related to some other extension together with this one.

If there's nothing to do for this then it's fine. Then I keep using the bank in incognito or with another browser :)
