### ISSUE TITLE
Settings Page Issue

### ISSUE THREAD

**Issue by junoncannon** [deanoemcke/thegreatsuspender#222]
When I right click on the GreatSuspender icon, then click "Options" it focuses on the left-most suspended tab in the current window and forces that tab to go to the extension settings page.  This would be okay, if hitting "Save Settings" didn't then close the tab.  So basically it's closing tabs at random if you need to change the extension options.

What I have to do now as a workaround is this:

1) Open new tab
2) Go to a site, since new tab can't be suspended, so type in URL: google.com
3) Click on Great Suspender
4) Click Suspend Tab
5) Click on Great Suspender again
6) Click Options

... I think we have an issue.

Hitting "Options" should just open a new tab with GreatSuspender Settings.

Found another workaround while typing this:

1) Launch new window
2) Click on Great Suspender
3) Click Options

At least that's more usable than the previous workaround.  This needs to be fixed.

Okay I just migrated from the old version, turns out that Left Click -> Settings works fine.

This issue is only for Right Click -> Options.

**Comment by deanoemcke** [comment]
I can't for the life of me work out why The Great Suspender does this with rightclick->options. I agree that it is bad form and should be fixed. I'll do some more investigation.

**Comment by deanoemcke** [comment]
Fixed by @mrinc
