### ISSUE TITLE
External resources need to be downloaded before the popup can open

### ISSUE THREAD

**Issue by RossBrunton** [deanoemcke/thegreatsuspender#224]
I have a bad internet connection, and when I'm downloading a Youtube video or something, I can't download anything else. So when I start up my browser after having closed it, I usually want to suspend any Youtube videos to help other pages load. The problem is, that the popup downloads its fonts and stuff before it opens (yeah, I don't know why it does this...), so it either never opens or takes a while to open while the network isn't functioning properly and the files aren't in the cache. This should easily be fixed by having the stuff it needs to be downloaded be bundled with the extension.

**Comment by kirb** [comment]
Chrome extensions are meant to bundle all assets that they use; the fact that this extension downloads fonts from Google should be considered a hack (which might not have been as obvious due to the `http://*/*` and `https://*/*` permissions). https://developer.chrome.com/apps/contentSecurityPolicy

**Comment by deanoemcke** [comment]
@RossBrunton @kirb thanks for the heads up guys. it is indeed something i should be fixing up. i'll try to get this sorted in the next release.

**Comment by Diablo-D3** [comment]
@RossBrunton As for HTML5 videos auto-starting, you may want to consider trying out https://chrome.google.com/webstore/detail/stop-youtube-html5-autopl/ajkibmginjljbmmpgnipfbcbmkcodaap?hl=en

I use it to prevent 9000 tabs all playing sound at the same time when Chrome restores itself after a crash.

**Comment by deanoemcke** [comment]
This was fixed by @liamjohnston in an older version: https://github.com/deanoemcke/thegreatsuspender/commit/b32abd75ca8b1211e034cfa9ed0d780796b069e0

thx liam :+1:

**Comment by liamjohnston** [comment]
😎
