### ISSUE TITLE
keep track of web store user issues/reviews

### ISSUE THREAD

**Issue by kzahel** [deanoemcke/thegreatsuspender#226]
Letting you know I have a hosted service that might be of use to you. You can get an email every time there's a support issue or review
https://www.chromebeat.com/ext/the-great-suspender/klbibkeccnjlkjkiokjodocebajanakg

**Comment by deanoemcke** [comment]
yikes! really?! that's fantastic. chrome's support service is totally unusable. whats the deal with pricing for the service?

**Comment by kzahel** [comment]
It's possible to pay me for the service. If you go to the plans page it's possible to check out with stripe. Currently no business logic enforces the constraints or anything like that, so it's on an honor system :-)

**Comment by deanoemcke** [comment]
OK. Thanks. 

Just a heads up. I just tried sending an email to support at chromebeat and got the following error:
This is the mail system at host c9mailgw10.amadis.com. I'm sorry to have to inform you that your message could not be delivered to one or more recipients. 

I had a couple of suggestions I wanted to put forward to you. What is the best channel for doing this?

**Comment by kzahel** [comment]
Sorry about the trouble -- I seem to be having problems with the MX records ... try kgraehl@gmail.com
