### ISSUE TITLE
Crash or something causes TGS to become unusable

### ISSUE THREAD

**Issue by deiga** [deanoemcke/thegreatsuspender#23]
I was just browsing away and suddenly my tabs don't have the refresh header anymore, apparently TGS doesn't respond to clicks anymore and all my suspended tabs are lost.

I don't know what caused this, but I can't risk using the extension if this happens..

**Comment by deanoemcke** [comment]
I'm treating this as a duplicate of #30.
For all bug reports of this extension causing chrome to crash please add to this other isssue.
Closing.
