### ISSUE TITLE
only un-suspend when connected to the internet

### ISSUE THREAD

**Issue by wulabs** [deanoemcke/thegreatsuspender#230]
Only un-suspend when connected to the internet?  This is useful because now I have it taking screenshots after 1hr, but when I am mobile without internet and want to read the screenshot pages it tries to reload (there is checkbox for manual un-suspend, but this is very annoying if connected to internet), and since it is not connected to internet, the page dies.

**Comment by deanoemcke** [comment]
A good suggestion. I will add this to prevent automatic unsuspension if not internet connection present.
Note that chromes ability to detect whether you are online is a little flakey so this may not always function as well as you would hope.

**Comment by JosephMcArthur** [comment]
I'd +1 this. Personally, a little "pause all suspending" button would be good.

**Comment by deanoemcke** [comment]
This has been implemented.
