### ISSUE TITLE
Keep the tunes flowing

### ISSUE THREAD

**Issue by steinvanbroekhoven** [deanoemcke/thegreatsuspender#232]
First let me start with thanking you for this awesome plugin.
I have a feature request:
In suspend setting add a way to not suspend a tab that has audio playing.
Suspending open but not active youtube stuff is great mem saving, but what I'm listelinig to should stay active.
Just thought this would be the most elegant method.

**Comment by deanoemcke** [comment]
Thanks for the feedback. This is a pretty hotly demanded feature - one that is not so simply to implement.
See here: https://github.com/deanoemcke/thegreatsuspender/issues/28

Closed as duplicate.
