### ISSUE TITLE
Use less memory on screen capture?

### ISSUE THREAD

**Issue by kzahel** [deanoemcke/thegreatsuspender#233]
I have been using the suspend tabs feature for the past few days and it's great. But it is a little annoying not seeing the page when I come back, so I can see the motivation for the screen capture feature.
You mention with a large warning that it uses a lot of RAM... I assume because you are keeping the image in the tab and thus loaded in RAM.
I wonder if it might be possible to store the image in the FileSystem API and clear the image when the tab is not active, loading it back from disk once the tab comes into view (might have a slight latency, but should be OK)
This might not be easily doable if you are supporting firefox (are you?)

**Comment by deanoemcke** [comment]
@kzahel interesting idea. it makes sense. i'm not supporting firefox so no problems there. i guess it just needs some decent profiling to test it out in practise.

**Comment by tleish** [comment]
FileSystem API is not available to chrome extensions, only chrome apps.

**Comment by kzahel** [comment]
That's not true... even web pages have access to DOM filesystem api

**Comment by tleish** [comment]
Perhaps I'm confusing the Chrome Filesystem API vs the HTML5 Filesystem API.

see: http://stackoverflow.com/questions/19802032/how-can-a-chrome-extension-save-many-files-to-a-user-specified-directory

**Comment by kzahel** [comment]
Sounds likely. The apis are identical only the chrome one gives a
filesystem object that can be an actual directory or file on the computer

**Comment by deanoemcke** [comment]
Storing images on the filesystem will not help reduce memory usage, as the image still needs to be loaded into the suspended page.
The image data is currently stored in an indexedDb store. This is fine and there is no need to switch to the filesystem for storage.

I don't think the additional memory usage is actually that high. I have removed the warning.
