### ISSUE TITLE
Change title of suspended tab to indicate that it's suspended

### ISSUE THREAD

**Issue by DanAtkinson** [deanoemcke/thegreatsuspender#240]
This is probably a minor, optional feature, but I'd like the title of the webpage to change to indicate that it's been suspended.

For example, on the [issues page](https://github.com/deanoemcke/thegreatsuspender/issues):
- Active page title: `Issues · deanoemcke/thegreatsuspender`
- Inactive page title: `Issues · deanoemcke/thegreatsuspender (suspended)`

**Comment by Diablo-D3** [comment]
It does fade the favicon when it suspends, but I'd actually like an option to not do the fade at all.

**Comment by a13ph** [comment]
[Tab Hibernation](https://chrome.google.com/webstore/detail/tab-hibernation/pbdpajcdgknpendpmecafmopknefafha) adds moon symbol/emoji in front of original tab name

**Comment by deanoemcke** [comment]
Any consensus on what the preferred option is here?
What are the use cases for needing to see this changed title? 
In my experience, once you get more than a certain number of tabs open, you don't see the title at all. Wouldn't this make any changes to the title a moot point, and also mean that fading the favicon is essential to being able to tell a tab has been suspended?

**Comment by shajiquan** [comment]
I agree. But the format of the title should be `(suspended) - Issues · deanoemcke/thegreatsuspender`, put the `suspended` on the front.
