### ISSUE TITLE
Sites on whitelist not being protected

### ISSUE THREAD

**Issue by Gunner76th** [deanoemcke/thegreatsuspender#241]
Application is not respecting/recognizing wildcards when checking the page that is listed in the whitelist section. 

I recently setup some white listed pages, specifically domain level whitelists. The entry was *.minecraft.gamepedia.com/* which should block anything that includes minecraft.gamepedia.com/ anywhere in the URL string. This however was not the case, as several pages, http://minecraft.gamepedia.com/Minecraft_Wiki
http://minecraft.gamepedia.com/Crafting
http://minecraft.gamepedia.com/Smelting
all were suspended. I also have an entry in for *.cursecdn.com/*, and the page 
http://hydra-media.cursecdn.com/minecraft.gamepedia.com/1/12/MinecraftPotionsClean.png
was also suspended even though cursecdn.com is 1) in the whitelist string 2) is the domain level of the URL posted.

By not recognizing wildcards such as * , it is seriously limiting the flexibility and capability of the application.

**Comment by Diablo-D3** [comment]
@Gunner76th I think the syntax you're looking for is just "minecraft.gamepedia.com", thats what TGS writes itself when you right click on the toolbar icon and do "never suspend this site".

**Comment by Gunner76th** [comment]
This would be true, if I wanted to "whitelist" the entire domain. What I am asking for/suggesting is that the use of wildcards be added (similar to just about every other application that has a whitelist/blacklist has) to allow more refined control. Tab blocking is nice, but being restricted to either whitelisting the entire domain, or nothing at all is a bit undesirable.

**Comment by deanoemcke** [comment]
This has been requested before in issue #197.
I'm hoping to implement wildcard support for whitelist soon.
Closing as duplicate.
