### ISSUE TITLE
Notification of Updates

### ISSUE THREAD

**Issue by tjharman** [deanoemcke/thegreatsuspender#242]
Hi,

I understand why you don't have new builds pushed automatically from the Chrome Web Store - makes perfect sense.

However, would it be possible in a future version have it so it can "self check" and say "Hey, a new version is available from the Chrome Store".  Then I can do my usual trick of saving all my whitelists, uninstalling then re-installing.

Or maybe that uninstall/reinstall process could be automated? Probably not, given how tied down that stuff is.

Anyway, it's just an idea, I will keep checking now and then for new updates!  I just updated from .16 to .19!

Thanks again, great extn.

**Comment by deanoemcke** [comment]
Your best bet is to follow me on twitter (@greatsuspender).
I will tweet when (and only when)  a new release is available.
Alternatively, I could set up a gitHub issue and post to it when a new release is out. Then you could just follow that issue..

**Comment by tjharman** [comment]
Thanks, I'm already following you on Twitter.
Didn't realise you were a fellow Kiwi, nice one.

**Comment by deanoemcke** [comment]
It has actually been suggested to me that a Tweet is probably not the best format for release updates (although I will still report this on my twitter).
I actually have another option of popping up a new tab on users screens which I could use to notify of updates. The difference here is that twitter is opt-in for the user, whereas a tab opening is going to be forced upon everybody.
I'm actually exploring options for how I can preserve whitelist and session information over uninstall and reinstall. I might be able to store something on the filesystem? Not sure yet but it would be good to make the process a bit nicer for users.

Re: Kiwis. I'm actually in Montreal at the moment. Moved over here a few months ago. Run into 2 other kiwis in just the last 3 days which is pretty rare for Montreal :)

**Comment by deanoemcke** [comment]
The extension will now (as of v7.0.104) notify you when a new release is available. Unfortunately this will only happen _after_ upgrading to v7.0.104. And also, if your chrome should restart chrome, the update will be forced upon you automatically.
More info here: https://github.com/deanoemcke/thegreatsuspender/issues/609
