### ISSUE TITLE
Other extensions failing to load properly after unsuspending

### ISSUE THREAD

**Issue by DakuTree** [deanoemcke/thegreatsuspender#244]
Loaded chrome today to notice various extensions (tampermonkey, linkclump etc.) no longer properly load on tabs that have just been unsuspended.
This issue appears to persist until the url is manually changed in the address bar. Changing the URL by clicking on links on the page doesn't fix the issue.

I'm guessing the bug is caused by something in the new [chrome dev update](http://googlechromereleases.blogspot.co.uk/2015/06/dev-channel-update_23.html) (v45.0.2438.3 dev-m).

**Comment by thoroc** [comment]
+1

**Comment by deanoemcke** [comment]
It could well be a new dev issue - it happens on mine too. However, I don't think the problem is related to this extension. It seems to be whenever a tab is redirected to ANY local extension url, subsequent sites in that tab will have broken extension behaviour. It seems like a pretty major bug to me?

**Comment by DakuTree** [comment]
Yeah, the problem does seem to occur on any chrome-extension:// tabs.
From what I can tell, it seems to limit the tab to only use the extension that was used in the local extension url (Meaning an Adblock chrome-extension:// url would make the tab load Adblock, but no other extensions).

I opened a bug report a few days ago with the issue @ https://code.google.com/p/chromium/issues/detail?id=505248.
Hopefully this will be resolved soon, since it kinda makes unsuspending tabs a pain :|

**Comment by deanoemcke** [comment]
Thanks for the link. Hopefully they'll resolve it soon.

**Comment by caeldom** [comment]
Also experiencing this issue. If it's browser-wide issue then I guess can only wait on Chrome devs to fix it :(
I just reverted from dev build to stable 45.0.2438.3 64bit, and the issue persists.

**Comment by DakuTree** [comment]
This issue seems to be resolved as of the current chrome dev build (45.0.2454.6 - 
[fix commit](https://chromium.googlesource.com/chromium/src/+/f01734ae15fc5c2a39181b25999683d336109dbf)).
Unsuspending tabs no longer breaks extension loading. :smiley:
