### ISSUE TITLE
Right Click

### ISSUE THREAD

**Issue by jpagarcia** [deanoemcke/thegreatsuspender#245]
Please add "Unsuspend Current Tab" feature on Right Click mouse. Currently only has "Unsuspend ALL Tabs"

**Comment by liamjohnston** [comment]
Did you know you can left click almost anywhere in the suspended page to unsuspend?

**Comment by jpagarcia** [comment]
Oh yeah. I totally forgot. sorry for my ignorant request :) though there
are times I need to zoom out of the screen to be able to left click to
unsuspend.

On Thu, Jul 2, 2015 at 3:22 PM, Liam <notifications@github.com> wrote:

> Did you know you can left click almost anywhere in the suspended page to
> unsuspend?
>
>
>
> > On 2/07/2015, at 5:31 pm, jpagarcia <notifications@github.com> wrote:
> >
> > Please add "Unsuspend Current Tab" feature on Right Click mouse.
> Currently only has "Unsuspend ALL Tabs"
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/deanoemcke/thegreatsuspender/issues/245#issuecomment-117940634>
> .
>



-- 
- Juan Paolo A. Garcia
