### ISSUE TITLE
Feature request - reload all tabs

### ISSUE THREAD

**Issue by KamilZm** [deanoemcke/thegreatsuspender#250]
Please can you add into menu and keyboard shortcut function to reload all tabs (suspended + not suspended)?

**Comment by deanoemcke** [comment]
In the latest version (v6.19) there is actually already a keyboard shortcut for doing this (no menu item though sorry). 
Go to Settings -> Keyboard Shortcuts and then set the 'Unsuspend all tabs in all windows' hotkey.
