### ISSUE TITLE
msi for group policy active directory distribution

### ISSUE THREAD

**Issue by raulhp** [deanoemcke/thegreatsuspender#253]
Please, I need a msi installation file for windows of the great suspender in order to distribute it via GPO in our enterprise active directory. Is there anyway to get it??
Thank you very much in advance.
And, is there a way to configure our own Whitelist file?

**Comment by deanoemcke** [comment]
Unfortunately I don't know much about that stuff sorry and don't have the time right now to investigate. Perhaps somebody else can contribute some information?
The extension can be built as a .crx file which can then be manually installed offline as an extension in chrome. Unfortunately there is currently no way of pre-configuring a whitelist. Although there may be in future as part of this issue: #242

**Comment by deanoemcke** [comment]
Duplicate of issue: https://github.com/deanoemcke/thegreatsuspender/issues/456

**Comment by allwizard** [comment]
Hi, I develop and implement custom tab suspenders, ping me hei.gb@outlook.com
