### ISSUE TITLE
Feature Request - Whitelist by File Type

### ISSUE THREAD

**Issue by jordan9001** [deanoemcke/thegreatsuspender#257]
It would be useful if one was able to whitelist a certain filetype, .pdf for example, and never have a tab viewing a pdf suspend.

**Comment by deanoemcke** [comment]
The whitelist is somewhat flexible in that you can enter substrings of a url. For example, if you enter .pdf in your whitelist, this should have the desired affect of preventing pdf tabs from suspending.

**Comment by DanAtkinson** [comment]
This _should_ be resolved by the changes made in #197.

Assuming the pull request is successful, you could simply do `.*\.pdf` which would filter out urls containing `.pdf`.

**Comment by deanoemcke** [comment]
Actually, as mentioned in my first response, the old whitelist can already handle this simply by adding .pdf to it. As far as regular expressions go, this has the same effect as ```.*\.pdf.*```
The new regular expression support will enable to you ensure that the .pdf part is at the end of the url. adding the following to the whitelist in v6.21 will do this: ```/.*\.pdf$/```
