### ISSUE TITLE
Sync settings across computers using Chrome Sync

### ISSUE THREAD

**Issue by rb-109** [deanoemcke/thegreatsuspender#262]
I really like the extension and it has saved me so much time waiting for my PC to load every tab at startup (not to mention less crashes/freezes).  I did donate too, as I think it deserves it.

My request:  I use several PCs to log into the same account.  It would be great if you could use the native Chrome sync to sync settings, so that I don't have to recreate the white list and adjust settings from scratch every time I use a different computer or even for migrating to a new computer.  That is the only inconvenience I find with the extension.

**Comment by galambalazs** [comment]
+1 

and saved sessions should be synced as well

**Comment by mrinc** [comment]
+1

**Comment by webash** [comment]
+1

**Comment by maxxyme** [comment]
+1000 for this feature!!!
Everytime I re-log on a new computer, the extension gets re-installed, but the settings are gone (esp. the Whitelist!!!!) :-(

**Comment by emouawad** [comment]
+1

**Comment by yxliang01** [comment]
Hope this is going to be published soon. As it's really helpful!
Thanks! :)

**Comment by dragon788** [comment]
I like the implementation that keeps my data safe, but I would also love to get a "use synced settings" button that I can click to override the local whitelist (since on many of my machines it will probably think that it was an upgrade due to how often I switch).

**Comment by yxliang01** [comment]
@deanoemcke just curious, it has been two years already. Why this hasn't been published?

**Comment by deanoemcke** [comment]
@dragon788 What do you mean by "it will probably think that it was an upgrade due to how often I switch"? If you really want to replace your current whitelist with the synced one, you could always uninstall and then reinstall the extension on that machine. A new installation will always have the 'Sync settings' option set to true and will sync when first installed.

@yxliang01 two years since when? the last release was June 2017. the new release is coming really soon i promise! or did you mean it just *seems* like two years? :D

**Comment by vapier** [comment]
two years since this feature request was opened

**Comment by deanoemcke** [comment]
ah ok. well it's only been 3 months since the feature has been built. i feel that is a more relevant timeframe to be talking about in regards to impatience.

**Comment by revolter** [comment]
@deanoemcke, If only you didn't forget to mention that uninstalling the extension also **automatically closes** suspended tabs... I lost 50 tabs because of this.

**Comment by revolter** [comment]
I don't understand why couldn't the sync option appear for old users too... I recently moved and thought that this extension doesn't support syncing at all, only to find out that the option is hidden for old users.

**Comment by revolter** [comment]
Actually, I still can't find the sync option

**Comment by vapier** [comment]
that's because this PR is still open

**Comment by deanoemcke** [comment]
yes sorry :(
it's tagged as waiting-on-release
