### ISSUE TITLE
Restore only focused and pinned tabs on startup

### ISSUE THREAD

**Issue by aitchnyu** [deanoemcke/thegreatsuspender#263]
As with Firefox default behavior, all tabs except pinned and focused tab should be suspended on startup. I currently use Footab along with GTS for this purpose. Please include it's functionality into GTS, since they dont tango well with each other.

**Comment by sldx** [comment]
yes pls

**Comment by deanoemcke** [comment]
Duplicate of issue: https://github.com/deanoemcke/thegreatsuspender/issues/49
