### ISSUE TITLE
All Users on PC

### ISSUE THREAD

**Issue by jrutkowsi** [deanoemcke/thegreatsuspender#270]
Does Suspender get installed for each user? Chrome has the annoying habit of installing only for the existing user.  We too see great benefit in Terminal servers where Chrome eats up a lot of the resources.

**Comment by smrqdt** [comment]
http://lmgtfy.com/?q=chromium+extension+all+users&l=1

That's not an issue with the extension.

**Comment by deanoemcke** [comment]
Chrome extensions get installed on a per-user basis. I have no ability to circumvent this rule.
