### ISSUE TITLE
'Suspend other tabs' option suspends all tabs

### ISSUE THREAD

**Issue by Degree23** [deanoemcke/thegreatsuspender#273]
Including the tab that you are currently on. Is it supposed to do that or no?

**Comment by deanoemcke** [comment]
This is a bug in the current version. Will try to release a fix soon.

**Comment by pinecone99** [comment]
I'm having the same issue where 'Suspend other tabs' suspends all tabs, including the one you're on. In addition, it sets the URL on all of them to that of the last opened tab. I love this extension, hope you can fix it soon.

**Comment by deanoemcke** [comment]
This issue should now be fixed on the latest version in the chrome webstore (v6.21).
To update you will need to uninstall and then reinstall the extension. 
IMPORTANT: Before uninstalling, make sure you unsuspend all currently suspended tabs. Also, this will delete your whitelist and any saved sessions you have created, so you will need to export these before you update.

**Comment by weiweihuanghuang** [comment]
I want it to suspend all tabs though...

**Comment by Degree23** [comment]
Oh ok, I'm just saying what if people want to suspend all of the other tabs except for one? I'm not saying to replace the suspend all tabs option but to make a new one


Sent from my T-Mobile 4G LTE Device

<div>-------- Original message --------</div><div>From: Wei H <notifications@github.com> </div><div>Date:10/24/2015  4:55 AM  (GMT-05:00) </div><div>To: deanoemcke/thegreatsuspender <thegreatsuspender@noreply.github.com> </div><div>Cc: Degree23 <ps3noobkiller@aol.com> </div><div>Subject: Re: [thegreatsuspender] 'Suspend other tabs' option suspends all tabs
  (#273) </div><div>
</div>I want it to suspend all tabs though...

**Comment by weiweihuanghuang** [comment]
I suppose you could have a setting that toggles it as 'suspend all tabs' vs 'suspend other tabs'? otherwise i just fixed it myself!

**Comment by Degree23** [comment]
I suppose? Your call man, I was just suggesting.


Sent from my T-Mobile 4G LTE Device

<div>-------- Original message --------</div><div>From: Wei H <notifications@github.com> </div><div>Date:10/24/2015  1:48 PM  (GMT-05:00) </div><div>To: deanoemcke/thegreatsuspender <thegreatsuspender@noreply.github.com> </div><div>Cc: Degree23 <ps3noobkiller@aol.com> </div><div>Subject: Re: [thegreatsuspender] 'Suspend other tabs' option suspends all tabs
  (#273) </div><div>
</div>I suppose you could have a setting that toggles it as 'suspend all tabs' vs 'suspend other tabs'? otherwise i just fixed it myself!
