### ISSUE TITLE
Clicking on one suspended tab causes all other suspended tabs to re-load

### ISSUE THREAD

**Issue by GrogHills** [deanoemcke/thegreatsuspender#275]
I have a bunch of suspended tabs.
When I click on one suspended tab it automatically re-loads.
Unfortunately, so do all of my other suspended tabs.

Chrome Mac 45.0.2454.37 (beta)
This occurs on two separate Mac computers. 

I've also gone and disabled all other plugins to see if that is causing the problem, but that didn't work. 

Note: If I turn off "Automatically unsuspend when tab gains focus" and manually enable a suspended tab, this problem does not occur. It only occurs when automatically unsuspending a tab. 

Any suggestions? Thanks.

**Comment by alexescalona** [comment]
Same here. Noticed it after the last update to chrome. Maybe it was happening before already.

The work around listed by the OP works for me as well.

Chrome Version 45.0.2454.85 (64-bit), Mac OS X 10.10.5 (14F27)

**Comment by ntang** [comment]
Whoops, opened #288 as a dupe.

**Comment by deanoemcke** [comment]
This issue should now be fixed on the latest version in the chrome webstore (v6.21).
To update you will need to uninstall and then reinstall the extension. 
IMPORTANT: Before uninstalling, make sure you unsuspend all currently suspended tabs. Also, this will delete your whitelist and any saved sessions you have created, so you will need to export these before you update.
