### ISSUE TITLE
Option to prevent suspension of tabs that are potentially producing sound

### ISSUE THREAD

**Issue by AndrewJDR** [deanoemcke/thegreatsuspender#28]
Sometimes, its nice to run soundcloud, rdio, youtube, etc in the background to play some music or other multimedia for an extended period. Ideally, there'd be some option to prevent auto suspension of a tab like this that is responsible for producing sound.

Such a feature could perhaps utilize the same technique that this extension is using to detect potentially sound producing tabs, or could perhaps even work in concert with this extension:
http://www.mutetab.com/

**Comment by deanoemcke** [comment]
The latest webstore version now has the ability to 'temporarily pause suspension' for a site. If you have a tab open that is playing music and you do not want it to suspend, you can use this option to prevent it from suspending in the background.
I will not be doing any work in future to try and automatically detect tabs that are producing audio.

**Comment by deanoemcke** [comment]
Just to reiterate as this is one of the more commonly requested features. Chrome does not provide developer access to its ability to detect which tab is playing music. Therefore I am unable to include an option to prevent these tabs from suspending.
As an alternative, I have implemented an option in the popup call 'dont suspend for now' which will prevent the current tab from suspending automatically in the background. This can be used to prevent tabs that are playing audio from suspending.
Another alternative is to whitelist the url of the site if you'd like it to always remain unsuspended.

**Comment by secrettriangle** [comment]
Would you consider reopening this ticket if Chrome were to provide the ability to easily detect which tabs were playing audio? Maybe if you got a pull request?

**Comment by deanoemcke** [comment]
Definitely. I would love to have a dedicated option 'dont suspend tabs that are playing audio'.

**Comment by kirb** [comment]
The content script could look for `audio`/`video` tags and check `!element.paused`. There could also be a catch-all setting for Flash/Silverlight as a hack (could still attempt to call `!element.paused` since the site might be using something like [MediaElement.js](https://github.com/johndyer/mediaelement)). If anyone's insane enough to use Java for playback, it appears there's a Java API to detect that too. I don't think it's worth supporting the [JS audio API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API) because this is typically used for notification sounds/game sound effects.

It's not a perfect way to do it but considering many major sites are using `<audio>`/`<video>` now it might be an acceptable compromise.

Worth also looking at the MuteTab extension's [FAQ](http://www.mutetab.com/mutetabfaq.html).

**Comment by deanoemcke** [comment]
@kirb i have checked out mutetab, and it left me with the impression that there's just too much hackery involved in getting this feature working. i could definitely do as you suggested and catch a large percentage of the use-cases, but i'm worried that it would appear to be a buggy feature as it would not work consistently.
You're welcome to have a crack at it, and if it seems to work fairly reliably then i'd consider including it.

**Comment by dbkaplun** [comment]
I think it would be acceptable if there was a "Do not suspend tabs that have audio or video" checkbox that simply checked if the page had any `<audio>` or `<video>` tags.

**Comment by maxxyme** [comment]
I use theses websites to play music: SoundCloud, Mixcloud and YouTube.

**Comment by DanAtkinson** [comment]
Requires a development of the tabs extensions to allow this. For more information, see [here](https://code.google.com/p/chromium/issues/detail?id=438903) for the Chromium issue.

**Comment by edmundo096** [comment]
I would like to see this soon. Its a great extension that deserves this.
Maybe add an "experimental-noted checkbox" which only checks for HTML5 `<audio><video>` tags, using what @kirb suggested (on his comment on Jun 5).

**Comment by deanoemcke** [comment]
If i was to implement this (highly considering it), what websites specifically should I be targetting? It seems that the audio/video !paused should be fairly easy. but with some quick tests this won't work for soundcloud or spotify. Any broad strokes I can make to detect flash audio/video? What about soundcloud? And are there other popular sites that I should be testing for?

**Comment by maxxyme** [comment]
In addition to the 3 aforementioned websites, I would add:
Beatport.com (you can listen for free music there; the shop has moved to pro.beatport.com)
Hearthis.at
Hypem.com
Official.fm

**Comment by DanAtkinson** [comment]
The audible tab functionality has now been baked into Chrome. Specifically, you should be able to query tab.audible to return a boolean value of whether the tab has produced sound in the last couple of seconds.

More info on the API: https://developer.chrome.com/extensions/tabs

**Comment by deanoemcke** [comment]
Finally! This has now been implemented :dancers:

**Comment by infusion** [comment]
When is it planned to push out this feature?

**Comment by ForsakenHarmony** [comment]
Well now?

**Comment by deanoemcke** [comment]
Available in the chrome webstore in v6.30
