### ISSUE TITLE
automatically suspend soundcloud playing tab

### ISSUE THREAD

**Issue by mAmged** [deanoemcke/thegreatsuspender#283]
the extension is suspending soundcloud tab while the tab is playing an audio track.

**Comment by bberenberg** [comment]
I encountered the same thing. I think that the extension should have an option to not disable tabs with active media content in them. Basically, any tab with a speaker icon in the tab.

**Comment by transfuturist** [comment]
Third. I came here hoping to find out whether it would suspend tabs with active content. I'm a little disappointed to find this.

**Comment by deanoemcke** [comment]
This is a highly requested feature which is not easy to implement. Please see existing issue #28.
Note: As a work around, you can click the 'dont suspend for now' option in the popup menu to prevent the tab from being suspend in the background.
