### ISSUE TITLE
Chrome 45 Update Causing Multi-Tab Issues and Possible Fix

### ISSUE THREAD

**Issue by E9C81F815E536B97AB4086B7A60D79D5178B435** [deanoemcke/thegreatsuspender#287]
There are numerous issues with multiple tabs being affected by individual actions.

This is possibly a result of [this](https://codereview.chromium.org/1225413002) fix of [this](https://code.google.com/p/chromium/issues/detail?id=507461) bug.

Possible fix: `try {chrome.tabs.sendMessage(tabId, message, {frameId: 0})} // throws on Chrome prior to 41
catch(e) {chrome.tabs.sendMessage(tabId, message)}`.

Credit to [wOxxOm's stackoverflow response](http://stackoverflow.com/a/32443797) for identifying the possible problem and fix.

**Comment by richardmtl** [comment]
This might fix #278 and #280, I hope!
