### ISSUE TITLE
All tabs opened from Facebook get suspended as the last opened one.

### ISSUE THREAD

**Issue by napravnik** [deanoemcke/thegreatsuspender#290]
E.g. when I open 5 different articles by clicking on Facebook posts, at the moment of suspesion they all become the last opened article, and the Facebook tab also becomes the last opened article. Thus, I lose 4 first opened articles and I have to find them again on the Facebook timeline. When I manually suspend any of the tabs opened through Facebook, no matter whether last, first or any other, all opened tabs including Facebook become the tab manually suspended.

**Comment by koalasloverain** [comment]
Same problem with the facebook tab -- the other article tabs usually don't change, but sometimes they do. Facebook tab is pinned and marked as never suspend, but it does suspend into the last link I clicked on Facebook.

**Comment by deanoemcke** [comment]
This issue should now be fixed on the latest version in the chrome webstore (v6.21).
To update you will need to uninstall and then reinstall the extension. 
IMPORTANT: Before uninstalling, make sure you unsuspend all currently suspended tabs. Also, this will delete your whitelist and any saved sessions you have created, so you will need to export these before you update.

Feedback on any issues with this new version would be greatly appreciated.
