### ISSUE TITLE
On Chrome 45 unsuspending a tab unsuspends all tabs

### ISSUE THREAD

**Issue by claunia** [deanoemcke/thegreatsuspender#291]
On Chrome 45 when unsuspending a tab all suspended tabs unsuspend automatically

**Comment by deanoemcke** [comment]
I am unable to replicate this. Anyone else? Could you give me a better description of what you are doing and also your operating system?

**Comment by claunia** [comment]
Mac OS X 10.10.0
Google Chrome	45.0.2454.85 (Official Build) (64-bit)
Revision	4321fbd965a0cfb327829005e6054c07669f81d5-refs/branch-heads/2454@{#439}
OS	Mac OS X 
Blink	537.36 (@201276)
JavaScript	V8 4.5.103.29
Flash	18.0.0.232

I have about 30 suspended tabs, and the currently viewing unsuspended tab.
Clicking on a suspended tab, or just closing the current one, temporarily reactivates all the tabs, and, in less time than the timer (but more than a second), resuspends all of them again.

I have tried closing and reopening Chrome, same happens.

**Comment by deanoemcke** [comment]
OK. Thank you for you help. I've managed to recreate your issue. I'm working on a fix now. Sorry for the trouble.

**Comment by claunia** [comment]
Sure! Tell me if you need testing

**Comment by smrqdt** [comment]
Same problem with Chromium 45.0.2454.85 (64-bit) on Arch Linux.

I found a temporary fix: untick “Automatically unsuspended when tab gains focus” in the extension options

Thank you for maintainig this great extension!

**Comment by deanoemcke** [comment]
This issue should now be fixed on the latest version in the chrome webstore (v6.21).
To update you will need to uninstall and then reinstall the extension. 
IMPORTANT: Before uninstalling, make sure you unsuspend all currently suspended tabs. Also, this will delete your whitelist and any saved sessions you have created, so you will need to export these before you update.

Feedback on any issues with this new version would be greatly appreciated.

**Comment by smrqdt** [comment]
The new version looks great, thank you!

The problem seems to be fixed.

**Comment by claunia** [comment]
Confirmed solved, thanks!
