### ISSUE TITLE
Dropdown menu actions work only in last window

### ISSUE THREAD

**Issue by Alex-Sokolov** [deanoemcke/thegreatsuspender#293]
Often I used 2 browser windows (Google Chrome).
When The Great Suspender suspend tabs — all ok, tabs suspended in both windows.
But when I use some of menu actions, like "Unsuspend all tabs" or "Suspend other tabs" — it's work only for tabs in last browser window and nothing happens in another

Using
Google Chrome 46.0.2490.22 beta-m
The Great Suspender 6.19

**Comment by deanoemcke** [comment]
This is by design. The menu options in the drop down are only meant to apply to that window.
If you go into the settings page and edit your hotkeys, you will find there are some hotkeys for suspending/unsuspending all tabs in all windows - but these options are not available in the dropdown.

**Comment by Alex-Sokolov** [comment]
OK. But in that case it not wotk too.
If I have two browser window with suspended tabs. And click unsuspend all in *second* window - tabs unsuspended at *first* window and not any in second
