### ISSUE TITLE
Suspend all tabs assigns same url to many consecutive tabs

### ISSUE THREAD

**Issue by bgr** [deanoemcke/thegreatsuspender#295]
I had a couple of active tabs (let's call it group 1), followed by a number of already suspended tabs (group 2), followed by many active tabs (group 3). Upon pressing "Suspend all tabs" tabs in groups 1 and 3 got assigned the url of the last tab in group. Sites opened in those tabs were from various domains. Tabs in group 2 that were already suspended were not affected.

This problem in combination with #294 makes it critical since I have no way to restore original urls.

**Comment by wsh** [comment]
I'm also encountering this issue. Alas.

**Comment by wsh** [comment]
@bgr on second thought, have you tried the latest from master rather than the Chrome store? I think @deanoemcke may have already fixed it. https://github.com/deanoemcke/thegreatsuspender/issues/290

**Comment by bgr** [comment]
@wsh It was the latest one from the Chrome store (6.19 I believe)

**Comment by wsh** [comment]
@bgr hence my suggestion that you should download and install the latest master, which is version 6.21 and includes the fix for #290.

**Comment by Amarok63** [comment]
@wsh I've this version installed, but the problem remains, not only when using "suspend all tabs" but as well when they´re suspended automatically. Moreover, when the last tab suspends, if it was generated from another tab (ctrl+link), the original *currently active* tab suspends in front of you with the same assigned url too!

**Comment by deanoemcke** [comment]
This issue should now be fixed on the latest version in the chrome webstore (v6.21).
To update you will need to uninstall and then reinstall the extension. 
IMPORTANT: Before uninstalling, make sure you unsuspend all currently suspended tabs. Also, this will delete your whitelist and any saved sessions you have created, so you will need to export these before you update
