### ISSUE TITLE
TGS Scrolls on newly opened tabs

### ISSUE THREAD

**Issue by yath** [deanoemcke/thegreatsuspender#296]
When opening a website that has previously been suspended in another tab, that other’s tab scroll position gets restored. That’s especially annoying since I often keep (forget) front pages open and re-open them in a new tab later again and suddenly the fresh tab scrolls down.

Steps to reproduce:
1. Open some URL
2. Scroll down on this page
3. Suspend this tab
4. Open a new tab
5. Open the same URL as in Step 1
6. Watch the page scroll to the location you scrolled to in Step 2

I believe this is due to gsScrollPos being synced between the different “instances” of that page.

**Comment by rnand** [comment]
@yath well, this explains the strange scroll behavior I've been experiencing :smile:

**Comment by deanoemcke** [comment]
This has been fixed (gitHub only - not pushed to chrome webstore yet).
With the following caveat: scroll position will now no longer be remembered after a chrome restart or session restore.

**Comment by yath** [comment]
Verified, thanks a lot!

**Comment by decadent** [comment]
Hi. I realize it's your free time and everything, but... will there be a new release?

Anyway, thanks for the great extension!

**Comment by korzynski** [comment]
Hi! Will this fix be added to the chrome store release?

**Comment by deanoemcke** [comment]
This feature is now available in the chrome webstore on v6.30.

**Comment by nachokb** [comment]
@deanoemcke hi! I'm still having this issue (on Twitter, happened twice in a few weeks). Extension version is 6.30. I just delete all gs* cookies and it's ok.

Thanks for such an useful extension!

![image](https://user-images.githubusercontent.com/17967/32529008-c09d5850-c414-11e7-8ffa-89c5646b03ed.png)

**Comment by deanoemcke** [comment]
OK. The upcoming version has reimplemented the way the scrolling functionality works. It should resolve this issue.
