### ISSUE TITLE
Corrupting the URL on suspension!

### ISSUE THREAD

**Issue by luckybuilding** [deanoemcke/thegreatsuspender#300]
Unfortunately, it changes the URL of a website that you have opened multiple tabs of it. For example, you open sss.com/aa and sss.com/bb and sss.com/cc in multiple tabs. But, you come back and see all suspended tabs are sss.com/aa
It happens a lot and you can't bring back all the tabs you had before suspension.

Please, solve this problem that is very serious.

Thanks

**Comment by deanoemcke** [comment]
This issue should now be fixed on the latest version in the chrome webstore (v6.21).
To update you will need to uninstall and then reinstall the extension. 
IMPORTANT: Before uninstalling, make sure you unsuspend all currently suspended tabs. Also, this will delete your whitelist and any saved sessions you have created, so you will need to export these before you update.

Feedback on any issues with this new version would be greatly appreciated.
