### ISSUE TITLE
Add "suspend every tab" in addition to current "suspend all tabs"

### ISSUE THREAD

**Issue by jpluimers** [deanoemcke/thegreatsuspender#301]
The "suspend all tabs" suspends only the tabs in the current Chrome Window (at least: that's on Mac OS X with Chrome 45).

I would love a "suspend every tab" that suspends all the tabs in all Chrome windows.

Various reasons use cases come to mind:

- ease of use
- as a precursor of fixing https://github.com/deanoemcke/thegreatsuspender/issues/109
- when you know you have to hit the road and need to spare battery life

**Comment by deanoemcke** [comment]
In the latest version (v6.21) there is actually already a keyboard shortcut for doing this (no menu item though sorry). 
Go to Settings -> Keyboard Shortcuts and then set the 'Suspend all tabs in all windows' hotkey.
It will suspend all tabs in all windows.

**Comment by jpluimers** [comment]
There is no "Keyboard Shortcuts" under the Settings of Great Suspender:

![No Keyboard Shortcuts](https://www.dropbox.com/s/qob2uc5ak4e2ory/Screenshot%202015-10-06%2019.30.41.png?raw=1)

But Chrome indicates indicates I do have the latest version installed:

![Chrome indicates latest version](https://www.dropbox.com/s/39k3pujegberjjx/Screenshot%202015-10-06%2019.32.37.png?raw=1)
