### ISSUE TITLE
Can not suspend Chrome WebStore

### ISSUE THREAD

**Issue by gotnix** [deanoemcke/thegreatsuspender#302]
The Great Suspender can't suspend Chrome WebStore, it says "Tab cannot be suspended." such as: https://chrome.google.com/webstore/category/apps

**Comment by deanoemcke** [comment]
This is deliberate. For some reason trying to suspend the chrome webstore page in older versions of chrome crashes the extension so it has been disabled.
Perhaps once the majority of users are on newer versions of chrome I will re-enable this.

**Comment by tiagoefreitas** [comment]
This also happens when trying to suspend tabs with pdfs which is annoying because they waste ram...

**Comment by deanoemcke** [comment]
See this link: https://groups.google.com/forum/#!topic/chromium-extensions/NalGwl-pK88
Extensions are forbidden from running on the chrome webstore page.
