### ISSUE TITLE
Feature idea: Take a snapshot of the tab for reference in the suspended tab

### ISSUE THREAD

**Issue by mfbx9da4** [deanoemcke/thegreatsuspender#305]
I find it hard to identify what the tab was using just the title, a snapshot would help a great detail to identify the tab. Perhaps, at least the favicon?

**Comment by entdark** [comment]
Make the suspended tabs or favicons blink maybe?

**Comment by rnand** [comment]
@entdark That would be horribly distracting, I think. 
@mfbx9da4 Turn on the 'screenshot' feature in settings.

**Comment by mfbx9da4** [comment]
@rnand Thank you, sorry for clogging up your issues!
