### ISSUE TITLE
Duplicate URLs

### ISSUE THREAD

**Issue by vaisov** [deanoemcke/thegreatsuspender#306]
Recently I started to observe strange behavior of the plug-in. Two tabs with different URLs have the same URL when frozen. However if I click "back" in both tabs I get to two different URLs. But if I click anywhere to unfreeze I end up on same website in both tabs.

**Comment by rafaelnunes** [comment]
Same issue here

OSX Mountain Lion
Chrome Version 45.0.2454.85 (64-bit)

**Comment by deanoemcke** [comment]
This issue should now be fixed on the latest version in the chrome webstore (v6.21).
To update you will need to uninstall and then reinstall the extension. 
IMPORTANT: Before uninstalling, make sure you unsuspend all currently suspended tabs. Also, this will delete your whitelist and any saved sessions you have created, so you will need to export these before you update.
