### ISSUE TITLE
Facebook won't suspend

### ISSUE THREAD

**Issue by northwinds** [deanoemcke/thegreatsuspender#308]
Hi there
I find this a really useful addin for when I have too many tabs and am researching something. However when I take a break from work to check Facebook I often open several tabs from there for looking at in detail later but I am unable to suspend them when getting back to important stuff?
Is there some service in facebook I need to disable that is keeping them live?
Many thanks!

**Comment by tnorthcutt** [comment]
FYI, this suspends Facebook tabs just fine for me. You might try checking the [devtools console](https://developer.chrome.com/devtools/docs/console) to see if there are any javascript errors being triggered when you try to suspend a tab.
