### ISSUE TITLE
pinned tabs

### ISSUE THREAD

**Issue by jhgreene** [deanoemcke/thegreatsuspender#31]
after suspending multiple tabs and quitting chrome upon restart those tabs that were pinned (some of which were suspended and some not) do not reappear in their previous state as expected.  they do however appear listed on a recovery page from which they can be easily be ctrl clicked and relaunched.  problem is manageable 

love the extension as chrome eats my 4gb of memory

do you have a firefox version?

awesome job thank you

**Comment by deanoemcke** [comment]
I have tested this in the latest version and pinned tabs appear to restore as expected. Closing optimistically :D 
Please let me know if you still have this issue on the latest version (from the GitHub project, not the chrome webstore).
