### ISSUE TITLE
Feature request: Suspend only if more than x tabs

### ISSUE THREAD

**Issue by lipsumar** [deanoemcke/thegreatsuspender#310]
I only get troubles when i have many tabs open, not 2 or 3. So it would be nice to be able to specify the minimum amount amount of tabs after which it starts suspending them.

That would make it less frustrating sometimes, when a tab gets suspended but there was actually no real problem with it.

**Comment by deanoemcke** [comment]
See this issue for in depth discussion of this feature request: #136
