### ISSUE TITLE
Whitelist/Pin tabs

### ISSUE THREAD

**Issue by Vcaras** [deanoemcke/thegreatsuspender#314]
Just as easy to Pin tabs and setting - "Do not suspend pinned tabs".  Working perfectly for me.

**Comment by Yolgie** [comment]
What is your question/Issue?
This feature exists:
![image](https://cloud.githubusercontent.com/assets/200311/10759198/47b8cfc0-7cb6-11e5-8576-111434182555.png)

**Comment by Vcaras** [comment]
I was just trying to reply to a comment that others had left.  They were having trouble whitelisting tabs so I was suggesting that if you pin a tab, it won’t suspend.  I’m not having any challenges and it is a godsend to me!  It’s amazing, so thank you so much.
