### ISSUE TITLE
HTML injection in Webpage title

### ISSUE THREAD

**Issue by dungsaga** [deanoemcke/thegreatsuspender#316]
In "Session management", webpage title is not escaped and is subjected to HTML injection.
Example: Visit http://meowni.ca/posts/a-story-about-input/ and then open Settings page of The Great Suspender, you can see an input box in title of that webpage

**Comment by tnorthcutt** [comment]
Can you include a screenshot? I'm not seeing the same behavior with:

Chrome 46.0.2490.80 (64-bit)
The Great Suspender 6.21

**Comment by dungsaga** [comment]
I use Chrome 46.0.2490.80 (32-bit) and The Great Suspender v6.21.
Here is the screenshot: http://imgur.com/tz4bZS0
The webpage with this strange title is  http://meowni.ca/posts/a-story-about-input/

**Comment by deanoemcke** [comment]
This feature is now available in the chrome webstore on v6.30.
