### ISSUE TITLE
Disable GPU use

### ISSUE THREAD

**Issue by BrandiATMuhkuh** [deanoemcke/thegreatsuspender#318]
It seems like "the great suspender" uses a lot of GPU Memory. For every suspended Tab the GPU usage goes up. Is their a GPU heavy task running. E.g A Video tag?

The screenshot shows around 60 tabs with all Chrome Tabs suspended. 
- the great suspender: 112Mb
- GPU-Process: 710Mb. 
  ![gpu usage](https://cloud.githubusercontent.com/assets/440625/10785721/cddd4a70-7d5d-11e5-99a2-a09fddc279ba.png)

In this screenshot I killed "the great suspender" extension. 
- the great suspender: 112Mb
- GPU-Process: 710Mb. 
  ![killedgreatsuspender](https://cloud.githubusercontent.com/assets/440625/10785858/a0f81cf0-7d5e-11e5-92d1-bb0eaf9fb933.png)

**Comment by deanoemcke** [comment]
Thats odd. I get almost zero GPU usage with a lot of tabs suspended. 
Do you have the image capture option turned on in settings? And what version of the extension are you using?
