### ISSUE TITLE
Whitelist specific page URL instead of whole domain

### ISSUE THREAD

**Issue by britishcoder** [deanoemcke/thegreatsuspender#321]
I'd like to be able to quickly whitelist a specific URL without whitelisting the whole domain. Ideally from the extension's icon. In other words, whitelist the specific URL, not the whole domain.

**Comment by deanoemcke** [comment]
In the upcoming release, the suspended tab page now has the ability to whitelist the specific page.
I have not add this to the extension icon popup menu. 
I'll update the issue title to reflect this.

**Comment by deanoemcke** [comment]
Actually, it has now been moved into the popup menu of a suspended tab.
