### ISSUE TITLE
After unsuspending, back button goes to "page suspended" page...

### ISSUE THREAD

**Issue by kuoirad** [deanoemcke/thegreatsuspender#323]
I believe this is a new behavior, I don't think this happened before.  When I go back to a suspended tab and it unsuspends, if I hit the back arrow, I get the "page suspended" page again.  If I hit the back arrow again, I get the page I was previously on, as desired.

I thought previous 4.x versions skipped the "page suspended" and went back to the previous page in history.  I could be misremembering.

TGS 6.21 from Chrome Store
Chrome 46.0.2490.80 (64-bit) on OS X (10.11.1)

**Comment by deanoemcke** [comment]
I was about to write a comment about how this is too hard to fix. Then I had a new idea and fixed it instead ;)

**Comment by kuoirad** [comment]
Awesome!  I would have accepted a too-difficult-to-fix reason, since it's just a minor annoyance, but never mind. :)

**Comment by kuoirad** [comment]
Do you know when we might get the release that fixes this?

**Comment by deanoemcke** [comment]
This feature is now available in the chrome webstore on v6.30.
