### ISSUE TITLE
Unsuspent button dosn't work

### ISSUE THREAD

**Issue by zonch** [deanoemcke/thegreatsuspender#324]
After auto-suspending tabs, if i press unsuspend all - nothing happens.I need to unsuspend all tabs manually by pressing on each.

**Comment by deanoemcke** [comment]
@zonch Can you tell me the version of the extension you are on?
And also, how are you trying to unsuspend all. Via the popup menu, the right-click menu, or via hotkey?

**Comment by zonch** [comment]
Version The Great Suspender v6.16
How i press it ![image](https://cloud.githubusercontent.com/assets/1043736/11143684/113948d0-8a08-11e5-8c50-aee92fdef97f.png)
But it appears not every time, i think mostly it after long period of not-active time.
Usially every evening i left some tabs open, my PC doesn't go to sleeping mode, but in the morning i usially can't unsuspend it.
