### ISSUE TITLE
Suspend other tabs / unsuspend all not working with multiple Chrome windows

### ISSUE THREAD

**Issue by ptnik** [deanoemcke/thegreatsuspender#325]
When using multiple windows, the "Suspend other tabs" and "unsuspend all" affect always just one window, even if the command is issued in another chrome window (having no effect in the window we intended it work).

**Comment by deanoemcke** [comment]
Could you please let me know the version of the extension you are using? The implementation of this feature was changed in a recent update so it would be useful to know if you have the new or old implementation.

**Comment by ptnik** [comment]
6.21

**Comment by iaoweb** [comment]
+1 also having this issue

**Comment by ryanstockau** [comment]
+1 having this issue too. This used to work fine until maybe a month ago (though I don't know for sure what date). If I click Suspend This Tab or Suspend All Tabs, they only suspend tabs in another window, which always seems to be the same window. I'm using V4.74, from the Google Chrome Store.

**Comment by ykavalenka** [comment]
I have more then 5 open window at work. When i suspend at selected window - others windows not suspend. But at this window anybody tabs are not suspend too. Mb this is bug or not?

**Comment by nikolay** [comment]
This is a very important bug to fix - it diminishes the value of the extension as you have to manually suspend tons of tabs.

**Comment by lrq3000** [comment]
I had the exact same bug before with the version from the Chrome App Store, but since I use the latest snapshot from this github, it works perfectly well.

**Comment by deanoemcke** [comment]
Could somebody please confirm if this is still happening in the latest release (v6.30) ?

**Comment by deanoemcke** [comment]
Even though I cannot reproduce, I will assume that this issue will be made redundant by the upcoming release v7.x
