### ISSUE TITLE
Session management: duplicating windows

### ISSUE THREAD

**Issue by bam80** [deanoemcke/thegreatsuspender#327]
Pressing "resuspend" or "reload" in Session management doubles amount of windows/tabs by duplicating them

**Comment by deanoemcke** [comment]
I'm unable to duplicate this. What version of the chrome extension are you using?
Do you mean that when you click 'resuspend' a single new window opens but every tab is created in that window twice?

**Comment by bam80** [comment]
I'm using Version: 6.21.
No, all already opened windows and tabs begin open again, duplicating existing ones. Another press again adds new bunch of windows/tabs, which was opened originally

**Comment by bgiesing** [comment]
This is also happening with the Tabli extension. I think it might be a Chrome bug

**Comment by bam80** [comment]
@bgiesing have you been able to replicate it with this extension?

**Comment by bgiesing** [comment]
@bam80 Yep
