### ISSUE TITLE
No setting / unable to stop repeated bitcoin / paypal donation popup.

### ISSUE THREAD

**Issue by bs27975** [deanoemcke/thegreatsuspender#332]
Please add a "Don't show me this again." checkbox to the bitcoint / paypal donation popup.

**Comment by deanoemcke** [comment]
If you simply click the donation popup it will stop appearing. You do not actually need to donate.
I will not be adding this requested feature as I feel it's a fairly unobtrusive popup.
In future releases (already in this github version) you will be able to disable the popup from within the support page as well.
