### ISSUE TITLE
Can't Turn off the "Ruh roh!" Page

### ISSUE THREAD

**Issue by antofthy** [deanoemcke/thegreatsuspender#334]
I am really really starting to hate this page.
Whenever I login I want my browser to simply start. Instead I I get the page

Ruh roh!
Looks like you're recovering from an extension crash.
Your suspended tabs may have crashed or disappeared.

Yes I know it means my browser was not closed properly.  I don't care. I don't want this page or need it!  I just want things to start as normal.  But no settings are provided to tell "The Great Suspender" to just get out of the way and let the browser start as normal.  If I want previous tabs from the previous session then I can get them from the Session Management.

Please add a setting to disable this page with at least the choice of: Ignore Previous Session

**Comment by deanoemcke** [comment]
Just a few things to note here. First, what do you have set in your chrome startup options? Is it set to 'continue where you left off?' If so, trying changing this if you are not actually wanting the previous tabs to reopen.
Also, you should not actually see the ruhroh page on chrome startup. This sounds like a bug. Are you doing a normal shutdown of chrome? Or are you killing the process somehow? If you are killing the process and then trying to 'continue where you left off' on restart, then actually I would argue that you want the option to restore all your suspended tabs, and that this page is justified.
Would like to hear your feedback on this.

**Comment by antofthy** [comment]
I've given up on it.  No it does not get shutdown properly (it gets killed
using a x windows 'xclosedown' command, and no I don't have continue where
I left of set.  Normal chrome does not bring back the previous page, though
a long time firefox did have a simular 'restore seession page', but they
removed that a long time ago.   Chrome (and firefox) both have a 'restore
previous session' setting which I do use on the rare occasion, but genally
don't use.

I just don't want or need to see the "Ruh Roh!" page, period!  It is just a
pain.
