### ISSUE TITLE
Ability to resume youtube video at same time as before suspension

### ISSUE THREAD

**Issue by guedalia** [deanoemcke/thegreatsuspender#342]

**Comment by rscafi** [comment]
It works like this for me, but not everytime. I don't know if Youtube or TGS is responsible for this.

**Comment by mazenbesher** [comment]
I am working on this feature in this [fork](https://github.com/mazenbesher/thegreatsuspender).

**Comment by Varatnar** [comment]
Are there any news regarding this feature ?

**Comment by deanoemcke** [comment]
This has been implemented thanks to @shanedrgn
It's still in pull request phase: https://github.com/deanoemcke/thegreatsuspender/pull/682#issuecomment-386880663

Will hopefully merge soon.

**Comment by deanoemcke** [comment]
This has been implemented. Here's is the commit (80513c8)
