### ISSUE TITLE
TGS scrolls down on page load

### ISSUE THREAD

**Issue by Terraism** [deanoemcke/thegreatsuspender#345]
Looks like there's been some slightly similar issues going the other direction, but I'm finding that when using TGS and I open a site in a new tab, it immediately jumps to the bottom of the page upon being finished loading. Does't seem like an extension conflict issue, because I'm seeing it when I disable everything other than TGS, and not when TGS is disabled and others are running.

Using 6.2.1 on Chrome.  I don't believe it's the same issue as reopening a suspended site and remembering its position, unless for some reason it's only using the base domain (frequent example is reddit posts).

**Comment by nerdazoid** [comment]
Also experiencing this issue. I had a hard time believing it was this extension but after experimenting with all my other extensions I definitely narrowed it down to this particular one. I've been noticing it's not all pages and it's been happening to me randomly over the last few weeks but wasn't annoying enough for me to track it down until now.

**Comment by korzynski** [comment]
Sounds like the same issue as #296
