### ISSUE TITLE
Feature request: Open link in new Suspended Tab

### ISSUE THREAD

**Issue by pashaformearth** [deanoemcke/thegreatsuspender#346]
![321](https://cloud.githubusercontent.com/assets/16447678/12008313/0d8c00fc-ac44-11e5-9222-b5389c9eddda.PNG)

**Comment by pashaformearth** [comment]
I'm sorry, didn't saw #228, #255 and #264 requests!

**Comment by jessegilbride** [comment]
I think this would be a great feature.  I'd like to see it also available as a keyboard shortcut.
