### ISSUE TITLE
Suspension destroys forward history

### ISSUE THREAD

**Issue by alexfink** [deanoemcke/thegreatsuspender#35]
I let a tab get suspended in which the last thing I did was navigate back a couple times, and was disappointed to see that I couldn't go forward again; the suspension had smashed the forward stack, replacing it with the suspension notice page.  

(OS X 10.5.8, Chrome 21.0.1180.90, in case it matters.)

**Comment by deanoemcke** [comment]
Agreed that this is annoying. However, I haven't been able to work out a way of resolving this. Will leave the issue open and will possibly take another stab at it in the future.

**Comment by SamHasler** [comment]
Before suspending could you navigate forward recording urls and then go back to the current url and then on unsuspend open those urls and navigate back to current? 

(It might not work if there had been post-redirect-get in the forward-history, not sure.)

**Comment by SamHasler** [comment]
Alternatively, if you can tell that there is forward-history, could you add a "Do no suspend if there is tab history" setting?

**Comment by deanoemcke** [comment]
This seems to work now ¯\_(ツ)_/¯
