### ISSUE TITLE
Auto reload on focus

### ISSUE THREAD

**Issue by rahilwazir** [deanoemcke/thegreatsuspender#354]
Is there any option to auto reload the tab when its focused after it get suspended.

**Comment by tmetten** [comment]
Hi Rahil,

There certainly is: you can find it under the extension's settings > Automatically unsuspend when tab gains focus




Kind regards,

Thomas Metten
Karel Gesslerstraat 22, 3680 Maaseik | M: +32 498 85 14 38 | Twitter: @tmetten

**Comment by rahilwazir** [comment]
@tmetten Great thanks!!
