### ISSUE TITLE
Pages are loaded upon chrome quit

### ISSUE THREAD

**Issue by adcurtin** [deanoemcke/thegreatsuspender#357]
whenever I quit chrome, all of my suspended tabs seem to unsuspend themselves, prevents chrome from quitting.

I have 100ish tabs open, and 80-90 of them are suspended. When those all suspend while quitting, chrome pretty much stops responding and I have to force quit it. This makes chrome's built in session manager a crapshoot. sometimes it can restore, other times it can't.

I have disabled "Automatically unsuspend when tab gains focus" and I still have this problem.

**Comment by deanoemcke** [comment]
Are you still having this issue on the latest version?

**Comment by adcurtin** [comment]
Nope, I've done a couple restarts of chrome and have not had this issue.
