### ISSUE TITLE
wrong tab suspended

### ISSUE THREAD

**Issue by sethblumberg** [deanoemcke/thegreatsuspender#362]
When I ask The Great Suspender to "Suspend this Tab", it instead suspends a different tab (in a different window).  It seems that it continues to try to suspend this same already-suspended wrong tab, no matter which tab I ask it to suspend.  It is usually a tab I was reading recently, but I don't know how to predict exactly which one it will choose.

This is similar to [issue 206](https://github.com/deanoemcke/thegreatsuspender/issues/206), except in that issue, the user clicked to activate a new window while TGS was working.  In my case I stay with one tab active, and it still gets it wrong.

I'm using Chrome 47.0.2526.111 on Mac OSX 10.9.5.

**Comment by mightybs** [comment]
I've been experiencing this problem for a little while as well.  As stated it seems unpredictable as to which tab will get suspended, but I too see a different tab in a different window get suspended.

Version 48.0.2564.103 (64-bit) on Mac OS X El Capitan (10.11.3)
