### ISSUE TITLE
Suspended tabs show empty title

### ISSUE THREAD

**Issue by Cthalin** [deanoemcke/thegreatsuspender#366]
After the newest Chrome update I guess, most of my suspended tabs show an empty title bar like this:
![title](https://cloud.githubusercontent.com/assets/12426628/12984386/ba1b5854-d0ed-11e5-8df8-1098def15a2c.jpg)
There is simply nothing in the title, not white text or so.
After reloading the tab and suspending it again, the title appears normally. But the empty title comes back every now and then. ôo

**Comment by chronometric** [comment]
Indeed, I came to report this issue. Let's say I have an average of 30 tabs going while leaving the program open most of the day, all but the last handful suspended. I'd say between 1/2 and 2/3 lost their titles in this way, and it will behave differently between sites of the same domain, so I have no guesses.

You can mouseover where the title should be and still see the underline, do CTRL+A and it will select where the text should be. Favicon is still there too. It also causes the "*Add X to Whitelist*" to disappear in the same way.

If I inspect the elements for a normal and textless tab, here are the results:

## Normal Tab
```
<div id="gsTopBar">
	<div id="gsTitleWrap">
		<img id="gsTopBarImg" src="chrome://favicon/http://www.sims.me/"> <a id="gsTopBarTitle" href="http://www.sims.me/">SIMSme</a>
	</div>
	<a id="gsWhitelistLink" data-text="www.sims.me">Add www.sims.me to whitelist</a>
</div>
```

## Missing Text:
```
<div id="gsTopBar">
	<div id="gsTitleWrap">
		<img id="gsTopBarImg" src="chrome://favicon/https://github.com/notifications">
		<a id="gsTopBarTitle" href="https://github.com/notifications">Notifications</a>
	</div>
	<a id="gsWhitelistLink" data-text="github.com">Add github.com to whitelist</a>
</div>
```

Not sure if that indicates anything at that display level of HTML. Anyway, not really crippling, but would be nice to be able to ID tabs before thawing them out ^^
