### ISSUE TITLE
Leaving tab suspends tab immediately

### ISSUE THREAD

**Issue by seadoggie01** [deanoemcke/thegreatsuspender#368]
I hope this wasn't mentioned already, but here's what happens:

I look at a web page for a while. (Probably at least 5 minutes, as that is my "Automatically suspend tabs after:" setting is set to) I leave the tab for a split second, return to the first tab, and it is suspended.

**Comment by BobMasterBob** [comment]
For the past week, for the first time, whenever I leave a tab and go back in about 10 minutes, it has been suspended.
My settings are never to automatically suspend tabs I have visited and gone away from. This is the first time this has happened. 
It makes the great suspender a lot less useful.
Can you fix this bug?

**Comment by joeytwiddle** [comment]
I may be wrong but I think I experience the same thing like this:

- I have a suspended tab
- I unsuspend it. (In my case, I switch to the tab, and it auto-unsuspends after 1 seconds.)
- **If I don't interact with it**, and I change tab, it will immediately suspend.
- If I do interact with it (clicking, scrolling), then I change tab, it will not suspend.

I hope that might help developers reproduce it.

For users my advice is, if this is happening, use the tab a little bit, and that might prevent it from suspending!

It seems recent versions of Chrome have introduced some issues with this extension, which was working perfectly before. That is a real shame!

**Comment by BobMasterBob** [comment]
I deleted The Great Suspender from my Chrome, and installed it again from the Chrome Store. Indeed there was a new version. Still, whenever I work on a tab for a while, but then go away, it will suspend, although my setting is to NEVER suspend.
