### ISSUE TITLE
Re-opening Chrome often results in previously suspended tabs reloading

### ISSUE THREAD

**Issue by zachariahkral** [deanoemcke/thegreatsuspender#37]
When I completely close Chrome with most tabs suspended, and reopen Chrome (say after a reboot), without fail, many (but not all) of the tabs that were suspended when Chrome was exited, are not suspended when chrome is reloaded, resulting in Chrome talking a ridiculously long time to open fully.

Chrome version: 26.0.1410.64 m
Windows 7 64 bit

**Comment by deanoemcke** [comment]
In the latest version of the extension, any tabs that were suspended when chrome is restarted will be resuspended automatically.
If you are interested in the feature where ALL tabs are suspended on restart regardless of whether they were suspended or not beforehand, please refer to this issue: https://github.com/deanoemcke/thegreatsuspender/issues/49
