### ISSUE TITLE
saving settings closes tab, even if it's the last one opened

### ISSUE THREAD

**Issue by IlianP** [deanoemcke/thegreatsuspender#370]
[change request]
If the settings are the last tab that is still open in the browser, then clicking "save" should not close it (and thus the whole browser) but leave a "new tab" open (according to the user's browser settings).

**Comment by IlianP** [comment]
Also, the setting should open in a new tab. Right now, going into settings (at least from the right click menu) switches the current tab over to settings. Thus, if the user clicks on "save", the tab should not be closed but bring the user back to the (suspended?) tab.

**Comment by deanoemcke** [comment]
This has been effectively fixed by removing the save/cancel buttons on the options page: https://github.com/deanoemcke/thegreatsuspender/issues/381
