### ISSUE TITLE
whitelist cross session

### ISSUE THREAD

**Issue by sescobb27** [deanoemcke/thegreatsuspender#372]
hi, i'm using this plugin on both my job and house laptop but it doesn't synchronize the whitelist even though i'm using the same chrome session.

what i can do, or that feature isn't implemented yet? thanks

**Comment by deanoemcke** [comment]
Duplicate of https://github.com/deanoemcke/thegreatsuspender/issues/262
This has been implemented and will be available in the upcoming release :)
