### ISSUE TITLE
unloaded tab still has lots of Javascript memory usage

### ISSUE THREAD

**Issue by techcode96** [deanoemcke/thegreatsuspender#376]
Had some high memory usage so I investigated with chromes build in task manager, and it turns out that unloaded tabs still have lots of javascript memory assigned.
Some real numbers: Chrome has combined 2 (unloaded) tabs into one process and together they have 214.736 K (32.772 K live). This seems way to much for unloaded tabs.
Does the extension correctly unload the javascript files (or is this not even possible), is it Chrome itself that is unnecessarily caching these files. Or has the extension a memory leak?
version 6.21

**Comment by techcode96** [comment]
an update:
The javascript must be from the extension itself because I have the same problem again on a local webpage of my own. The content of the webpage is only 2 links, no images, no css, no javascript just 2 small hyperlinks, jet the unloaded tab uses 240 MB memory

**Comment by lrq3000** [comment]
Did you try the latest extension snapshot (by downloading this repo and using Chrome Developer mode for extensions)?

**Comment by deanoemcke** [comment]
Merging this issue into: https://github.com/deanoemcke/thegreatsuspender/issues/613
