### ISSUE TITLE
[Huge annoyance] all reddit pages scrolling down to bottom

### ISSUE THREAD

**Issue by individuell** [deanoemcke/thegreatsuspender#377]
When the suspender chrome extension is enabled, it scrolls down to the bottom of the site on all of the reddit pages I haven't visited yet (e.g. a comments section or a random subreddit https://www.reddit.com/r/random/) - when it's disabled everything is fine.

Using Chrome on Windows 10 by the way. Whitlisting "reddit.com" didn't help. Had to disable the extension for now :-(

**Comment by TimBeyer** [comment]
Same problem here. Not only happens on Reddit, but it's most common there.

**Comment by TimBeyer** [comment]
Looks like it's related to https://github.com/deanoemcke/thegreatsuspender/blob/daa6119fe9ffde3c853f486d82edfc7d1e68a487/src/js/contentscript.js#L77-L81

This has been fixed already, but it seems like the updates have never been published so 6.21 still shows the bugs. So basically we'd just have to do a manual build and install it, and this would be fixed.

Would be great to just publish those changes as a new release though.

**Comment by lrq3000** [comment]
No need to manual build a Chrome extension. Just download the archive, extract it somewhere on your computer, enable Developers extensions in Chrome and then you can just "Load non packaged extension" by pointing to the extracted folder (you need to point to the `src` subfolder). Works perfectly well, but you need to keep the folder, you cannot delete it or this will delete the extension in Chrome as well.

**Comment by TimBeyer** [comment]
That won't work here @lrq3000 because the latest release is from September 16, and the fix was merged on September 26. There currently is no release that contains this fix so you'd have to build it yourself.

**Comment by Alex131089** [comment]
@deanoemcke : do you plan to upload to the store a version with this fix included ?
This is becoming a deal-breaker for me, and I don't like the way the Tab Suspender handle things (& I would like to avoid to use "unofficial"/dev version too).

**Comment by decadent** [comment]
possibly related to #296

**Comment by rickydeez** [comment]
Can we get this pushed for release?

**Comment by deanoemcke** [comment]
I will endeavour to get this bug fix into the webstore soon. Please see this thread for the latest information on my extension updating policy: https://github.com/deanoemcke/thegreatsuspender/issues/322

**Comment by deanoemcke** [comment]
This is in the latest chrome webstore release (v6.30).
