### ISSUE TITLE
Junkware Removal Tool false positive ?

### ISSUE THREAD

**Issue by exadeci** [deanoemcke/thegreatsuspender#379]
I did a scan with https://www.malwarebytes.org/junkwareremovaltool/ and it deletes AppData\Local\Google\Chrome\User Data\Default\Extensions\klbibkeccnjlkjkiokjodocebajanakg (Folder) 

It doesn't affect the extension but I found it weird.

**Comment by and7eh** [comment]
+1

Today I've been Hijacked, and when I executed JRT I've found this:

> ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> Junkware Removal Tool (JRT) by Malwarebytes
> Version: 8.0.6 (04.25.2016)
> Operating System: Windows 10 Home x64 
> Ran by and7eh (Administrator) on 16/05/2016 at 20:43:35,80
> ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 
> 
> 
> 
> File System: 3 
> 
> Successfully deleted: C:\Users\and7eh\AppData\Local\Google\Chrome\User Data\Default\Extensions\klbibkeccnjlkjkiokjodocebajanakg (Folder) 
> Successfully deleted: C:\Users\and7eh\AppData\Local\Google\Chrome\User Data\Default\Local Storage\chrome-extension_klbibkeccnjlkjkiokjodocebajanakg_0.localstorage-journal (File) 
> Successfully deleted: C:\Users\and7eh\AppData\Local\Google\Chrome\User Data\Default\Local Storage\chrome-extension_klbibkeccnjlkjkiokjodocebajanakg_0.localstorage (File) 
> 
> 
> 
> Registry: 0 
> 
> 
> 
> 
> 
> ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> Scan was completed on 16/05/2016 at 20:47:26,15
> End of JRT log
> ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Also, after restart Windows, the extension has been semi-deleted from Chrome.

**Comment by deanoemcke** [comment]
A slightly related issue regarding extension corruption: https://github.com/deanoemcke/thegreatsuspender/issues/551

I will do some more investigation into the effects of tools such as HijackThis on the extension.

**Comment by deanoemcke** [comment]
I can confirm that JRT removes the extension folder. I think you'll find it **does** affect it. It corrupts the extension on that computer and effectively loses all your data (and tabs).

Running HijackThis did not bring up anything however.

For JRT,  it should be noted that it also removed two other extensions: Alexa Traffic Rank and Evernote Web. Both of which are very reputable. 

It seems JRT is no longer supported. And I don't really know what to say other than, it shouldn't be removing it. I have no idea why it does. But we're probably not ever going to find out.

**Comment by deanoemcke** [comment]
I am going to close this issue, as I'm not inclined to provide support for third party applications that falsely detect this extension as malicious.
If anyone can point to a specific reason why this extension specifically would be targeted then I'll be happy to revisit it.
