### ISSUE TITLE
Donate button to persist

### ISSUE THREAD

**Issue by rstolper** [deanoemcke/thegreatsuspender#380]
After clicking the Donate button, the buttons disappear and are replaced by an ASCII cat.
I think the cat is  great, but I would suggest to also keep the Donate buttons visible in case someone wants to donate again. Or as it was in my case, I closed the PayPal tab before completing the donation, and now I don't have a way to get to it again.

**Comment by jblz** [comment]
+1 I came to report the same. My transaction didn't go through and I noticed the cute kitty when I went to find the link again :)

Cheers!

**Comment by deanoemcke** [comment]
The latest version has this ability. Under the 'support' section in the extension options, there is a link with 'Want to donate again?' which will allow you to donate again :)
