### ISSUE TITLE
Changes made in settings tab should be modeless

### ISSUE THREAD

**Issue by voxadam** [deanoemcke/thegreatsuspender#381]
I'd love to see the settings tab for The Great Suspender's settings tab to be made [modeless](http://www.usabilityfirst.com/glossary/modeless/); changes applied immediately on state change.

The problem is that TGS' settings interface consists of multiple sub-tabs. This creates an issue where when a person needs to change a setting that's part of the _General settings_ then switches to the _Session management_ the changes they made in _General settings_ results in any change made in _General settings_ to be lost. Of course the user can click _Save settings_ but that has the effect of closing the settings tab which forces the user to open the settings tab again to continue what they had previously been doing.

Another option would be for TGS to pop dialog asking if they'd like to save their changes when the user selects a different sub-tab (e.g. _Keyboard shortcuts_). Personally, I nearly always prefer modeless interfaces, especially in the case of configuration interfaces, as it reduces unnecessary dialogs, and buttons. If you are worried users inadvertently making changes and not knowing how to revert them you could replace the _Cancel_ button with something _Revert Changes_ or _Discard_.

I'd like to tell you how much I love this extension and extend my appreciation to you for developing it. Without TGS I'd have undoubadly thrown my Chromebook with it's measly 4 gigs out the window of a moving vehicle a long time ago which probably wouldn't have turned out well for me or my fellow commuters. Thanks!

**Comment by deanoemcke** [comment]
This has been implemented. Just a purely modeless view now.
