### ISSUE TITLE
Export settings to users on a multiuser server running chrome.

### ISSUE THREAD

**Issue by xztnc** [deanoemcke/thegreatsuspender#382]
Hi i wish to know where the plugin saves its settings and if it's possible to export the settings to other users? I can't find where it is saving the settings right now. Basically we run a hosted environment where there can be up to 300 users running google chrome, a problem we have is excessive memory usage and want to use this plugin to restrict it. What we got working is pushing the plugin via GPO but now are stuck at how to manage the different settings for the plugin as well. We don't want to login as thousands of users and set the settings manually.

Is this something that can be built is as some sort of import export or is there a place where i an grab the settings file or so and push it into each users appdata folder?

**Comment by deanoemcke** [comment]
The settings are saved to local storage. If you are running all the accounts under a single user, then the upcoming release (v7.x) supports syncing of settings: https://github.com/deanoemcke/thegreatsuspender/issues/262
This means all your instances should be able to automatically pull down the same set of settings. Does that solve your problem?

**Comment by IvovanTulden** [comment]
The current beta version shows the 'sync settings between different systems', can this also be used to sync between different users on the same machine? (Remote Desktop server)

**Comment by deanoemcke** [comment]
@IvovanTulden It depends what you mean by different users. The syncing is between the same chrome profile (ie. logging into chrome as a specific user).
If you mean different users on the same machine as in, different operating system logins, then you could have the settings all sync, so long as each of the different logins used the same chrome profile. This would have other side-effects however, like a shared tab history, saved passwords etc.

**Comment by deanoemcke** [comment]
Upon closer inspection, it seems that what you're after is probably what is described in this issue: 
https://github.com/deanoemcke/thegreatsuspender/issues/456

**Comment by allwizard** [comment]
Hi, I develop and implement custom tab suspenders, ping me hei.gb@outlook.com
