### ISSUE TITLE
"Suspend other tabs" and auto-suspend not working

### ISSUE THREAD

**Issue by Lepanto7** [deanoemcke/thegreatsuspender#383]
First, thanks for this great add-on. Up until now, it's made my browsing experience a lot smoother.

Recently (maybe when I installed the latest Chrome version), "Suspend other tabs" and auto-suspend have stopped working for most tabs. They only work for seemingly random tabs, with no obvious rhyme or reason between them (no form inputs or anything). Every other tab remains open indefinitely, and must be manually suspended.

Any idea what might be causing this? Any further info you require?

Thanks!

**Comment by deanoemcke** [comment]
Sorry about the slow reply on this. Could you please let me know if you are still encountering this issue on the latest release (v6.30)?

It seems others have reported a similar issue: https://github.com/deanoemcke/thegreatsuspender/issues/449
