### ISSUE TITLE
Suspended tabs not fully functional after browser restart

### ISSUE THREAD

**Issue by npt** [deanoemcke/thegreatsuspender#385]
When I restart the browser, every suspended tab changes its title from the former page title to "Suspended Tab", the favicon/title/"Add $DOMAIN to whitelist" bar at the top of the page is blank, and clicking on the page does nothing. Reloading the tab restores it to the normal suspended-tab page and clicking on it then works.

**Comment by sldx** [comment]
I have a similar issue but the url is the correct one I think:  chrome-extension://klbibkeccnjlkjkiokjodocebajanakg/suspended.html#uri=https://....

And there is the message, but clicking on it doesn't work. and reload doesn't work either. It's pretty disturbing.

Help?

**Comment by deanoemcke** [comment]
Possible duplicate of: https://github.com/deanoemcke/thegreatsuspender/issues/173
@npt @sldx Could either of you confirm if this is still happening in the latest version? (v6.30).
Thanks.

**Comment by sldx** [comment]
Nope, seems fixed now, thank you!
