### ISSUE TITLE
Center Click Mouse Wheel Activates Suspend Yellow Bar

### ISSUE THREAD

**Issue by emagin** [deanoemcke/thegreatsuspender#39]
I have a Logitech M505 Mouse, configured to scroll the page on click of mouse wheel
It's set to = center click in my settings.

Sometimes when I click mouse wheel to scroll down a page (activates little circle with 4 arrows to smoothly move around page), the yellow GS bar comes up and my content disappears. I have to click mouse wheel again to get rid of it.
It's not clear to me why this is happening, as it only happens once every 5-6 mouse wheel clicks. But it's annoying.
Wondering if this is on my end or ?

Thx

**Comment by deanoemcke** [comment]
Did you ever get to the bottom of this? Sorry, haven't been able to recreate it from my end.
