### ISSUE TITLE
Whitelisting a URL pattern In Addition To Domains/IP Addresses?

### ISSUE THREAD

**Issue by justingoldberg** [deanoemcke/thegreatsuspender#390]
Any chance of having an option to whitelist certain url patterns? I log into a lot of different customer zyxel firewalls that all have the same url pattern, eg: '_/ext-js/web-pages/index/index.html#_'

Thank you so much for this great and memory-saving extension, by the way.

**Comment by deanoemcke** [comment]
The latest version of the extension has support for regex. See this issue: https://github.com/deanoemcke/thegreatsuspender/issues/197

**Comment by justingoldberg** [comment]
Does it work on IP addresses/subnets? Eg whitelist 172.16.*.* ?

**Comment by 1o55** [comment]
> Does it work on IP addresses/subnets? Eg whitelist 172.16._._ ?

Yes. See my response to #1067.
