### ISSUE TITLE
Privacy and security

### ISSUE THREAD

**Issue by ihteshamraza** [deanoemcke/thegreatsuspender#393]
this extension is great and i'd love to use it for my whole life, but is it safe? the permissions it ask? reading and writing all the content of tabs. it compromises security and passwords and all that. your thoughts? Thanks

**Comment by RedCraig** [comment]
It also asks for the ability to read and write access to browsing history and (as @ihteshamraza mentioned) content/data on pages.
Could you please clarify what these permissions are used for?

Thanks much.

**Comment by weitzhandler** [comment]
I won't install this extension unless I understand why on earth this extension requires reading and writing access to all contents. Why isn't tabs enough??

**Comment by ihteshamraza** [comment]
@RedCraig @weitzhandler still hasn't figured out why it needs all those permissions but trust me this is really useful addon to chrome. I've been using it since 1 year now and it works great. I think you should trust the developers.

**Comment by weitzhandler** [comment]
I'm not giving my credit card info before I have a convincing explanation for why it needs this level of permission. Why can't it rely just on history and tab info?

**Comment by deanoemcke** [comment]
Please see this issue for more information on the permissions required by the extension: https://github.com/deanoemcke/thegreatsuspender/issues/213
