### ISSUE TITLE
When reloading saved session, the first tab (that also was a fixed tab) previously saved, doesn't open. 

### ISSUE THREAD

**Issue by iGallina** [deanoemcke/thegreatsuspender#397]
Instead it shows a blank tab at the end of the fixed tabs and before the not fixed tabs, every other saved tabs, shows perfectly, is just the first of every saved session.

I am on windows 7 + Chrome, but have this issue on Mac OS X Yosemite at home.

Thanks,
Ian

**Comment by deanoemcke** [comment]
This has been fixed with this commit: https://github.com/deanoemcke/thegreatsuspender/commit/bb867c863243dbd73af33b70df08d181b00d6c82

Will be released soon
