### ISSUE TITLE
gitlab pages get restored as json

### ISSUE THREAD

**Issue by glensc** [deanoemcke/thegreatsuspender#400]
i've noticed this happening more than once, so it must be reproducible.

open this url (for example, but any gitlab issue will do):
https://gitlab.com/gitlab-org/gitlab-ce/issues/42
let it be suspended, and then wake up. at some point a json is restored:

``` javascript
{
id: 14957,
title: "background_jobs update for sidekiq command line",
assignee_id: null,
author_id: 17232,
project_id: 13083,
created_at: "2014-01-29T19:51:21.000Z",
updated_at: "2015-03-01T13:29:04.913Z",
position: 0,
branch_name: null,
description: "The sidekiq command line options are wrong for the background_jobs script: diff --git a/script/background_jobs b/script/background_jobs index 623e26a..7be71f4 100755 --- a/script/background_jobs +++ b/script/background_jobs @@ -32,7 +32,7 @@ function start_no_deamonize function start_sidekiq { - bundle exec sidekiq -q post_receive,mailer,system_hook,project_web_hook,gitlab_shell,common,default -e $RAILS_ENV -P $sidekiq_pidfile $@ >> $sidekiq_logfile 2>&1 + bundle exec sidekiq -q post_receive -q mailer -q system_hook -q project_web_hook -q gitlab_shell -q common -q default -e $RAILS_ENV -P $sidekiq_pidfile $@ >> $sidekiq_logfile 2>&1 } case "$1" in",
milestone_id: null,
state: "closed",
iid: 42,
updated_by_id: null,
weight: null,
confidential: false,
moved_to_id: null,
deleted_at: null,
due_date: null,
labels: [ ]
}
```

if i reload the url, it will show normal html page.

i'm guessing that perhaps same url is used for html and json responses, but with different http headers in request. and that maybe confuses thegreatsuspender.

**Comment by aslafy-z** [comment]
I'm encountering the same issue using Vivaldi without this addon, i'm wondering if it's not directly coming from Gitlab

**Comment by deanoemcke** [comment]
The gitlab link seems to work ok on the latest release (v6.30)

**Comment by glensc** [comment]
the problem was hard to reproduce anyway, because it did not always happen. however i haven't noticed the original reported bug either quite recently.
