### ISSUE TITLE
suspending tab should not remove its contents

### ISSUE THREAD

**Issue by warrenharris** [deanoemcke/thegreatsuspender#401]
When a tab gets suspended, its contents are replaced by a large "Tab suspended, click to reload" message. So if you are somewhere without internet access you can no longer see the page contents. In most cases I just want to read the page contents, and this is unfortunate since now I have to get back online to reload the page. 

I think that a better UI would be to leave the page contents in place with just a banner at the top saying "Tab suspended, click to reload". Then I could still read the page, even if it is inactive.

**Comment by rappo** [comment]
@warrenharris I think that would defeat the purpose of the extension, no? It suspends tabs to free up resources, but if the content remains it's still using resources.

**Comment by liamjohnston** [comment]
If you need to *see* the contents of the screen, try the "Screen capturing" option in the settings page. This probably will use more memory though (but less than not suspending).

Also the "Only auto-suspend if connected to the internet" option may be of use to you.
