### ISSUE TITLE
disabling thegreatsuspender should not delete tabs

### ISSUE THREAD

**Issue by warrenharris** [deanoemcke/thegreatsuspender#402]
I had many windows with many tabs opened. The Great Suspender suspended most of the tabs. Then I decided to disable the extension. This caused all my tabs to be closed and removed from the browser, thus losing everything I had open! 

A better behavior would be to instead reload all the suspended pages and leave the tabs open.

**Comment by deanoemcke** [comment]
Unfortunately there is nothing I can do about this. Chromes extension api gives me no chance to act on an 'extension disabled' event.
Re-enabling the extension should recover all tabs seamlessly though. Although uninstalling the extension will not :(

See this thread for more indepth info: https://github.com/deanoemcke/thegreatsuspender/issues/526
