### ISSUE TITLE
Ability to suspend all tabs in a domain

### ISSUE THREAD

**Issue by truth1ness** [deanoemcke/thegreatsuspender#404]
I'd like to be able to suspend all the tabs from one domain. I usually run into problems when I have multiple tabs open from one resource intensive site like Facebook and it'd be great to be able to suspend all of those at once without having to go tab by tab or suspending all and unsuspending the ones I don't want suspended.

**Comment by deanoemcke** [comment]
Duplicate: https://github.com/deanoemcke/thegreatsuspender/issues/673
