### ISSUE TITLE
Un-suspended tabs don't display page content until tabbing away and back

### ISSUE THREAD

**Issue by oddhack2** [deanoemcke/thegreatsuspender#41]
Running 4.74 on Chromium 26 / Debian 7, clicking on the 'Tab suspended: click to reload' header often appears to do nothing immediately. However, if I move to another tab and then back to the just-restored tab, it appears properly un-suspended and the page contents restored. So the work is getting done, but the page doesn't immediately get displayed for some reason. Is this a known behavior, or perhaps an interaction with other extensions?

I'm enjoying The Great Suspender enormously, BTW - thanks!

**Comment by deanoemcke** [comment]
Hi. Just wondering if you are still encountering this behaviour?
Have you tried to the GitHub version of the extension? It will be updated on the webstore very shortly.

**Comment by oddhack2** [comment]
On Tue, Jan 13, 2015 at 04:10:00AM -0800, deanoemcke wrote:
> Hi. Just wondering if you are still encountering this behaviour?
> Have you tried to the GitHub version of the extension? It will be updated on the webstore very shortly.

    I haven't seen this behavior for a while. I'm currently running 4.74
with Chromium 39 on Debian 8. Perhaps some browser changes since the
original bug report have fixed it. Apologies for not updating the issue.

**Comment by deanoemcke** [comment]
All good. Thanks for getting back to me.
