### ISSUE TITLE
Suspends regardless of set interval

### ISSUE THREAD

**Issue by 1kenthomas** [deanoemcke/thegreatsuspender#415]
No matter what delay is set to,  often suspends tabs very quickly-- highly disruptive.

**Comment by 1kenthomas** [comment]
The attention to what would seem a critical issue affecting functionality is noted.  I've solved the issue by using other software.

**Comment by deanoemcke** [comment]
Sorry about that. I have had no other users reporting this issue so I assumed it had been resolved with a subsequent release.
Perhaps try the latest version?
