### ISSUE TITLE
Feature request: Suspend least recently used tabs (above some threashold)

### ISSUE THREAD

**Issue by Stvad** [deanoemcke/thegreatsuspender#417]
The gist of the proposal - to suspend tabs automatically not after some time has passed since you visited them, but when they fall behind some allowed threshold of opened tabs.

So, for example, you have the threshold of 15 tabs specified. This means that if you have 15 tabs opened when you open next one - the tab that you've opened least recently will be suspended and so on for more new tabs.

See "LRU cache" to help visualize the concept.

The threshold could be specified by the user in a number of tabs or deduced automatically  based on resource usage.

**Comment by deanoemcke** [comment]
This has been discussed at length in another issue: https://github.com/deanoemcke/thegreatsuspender/issues/136
