### ISSUE TITLE
Closes all suspended tabs on uninstalling

### ISSUE THREAD

**Issue by brajmohans** [deanoemcke/thegreatsuspender#418]
I just uninstalled this plugin but to my surprise it dragged away all suspended tabs with it. 
I couldn't see any valid reason for this behaviour. Its just inconvenient

**Comment by ronin13** [comment]
This is because the extension is not using event pages.

Hence,
```
    //wishful thinking here that a synchronus iteration through tab views will enable them
    //to unsuspend before the application closes
    chrome.runtime.onSuspend.addListener(function () {
        chrome.extension.getViews({type: 'tab'}).forEach(function (view) {
            view.location.reload();
        });
    });
```

in background.js never gets triggered.

It needs the background pages to be converted into event pages as described here:  https://developer.chrome.com/extensions/event_pages

**Comment by dandv** [comment]
This is a super critical bug :-/

I'm going to uninstall right now, before it suspends anything.

**Comment by deanoemcke** [comment]
Please refer to this guide on why this happens and how to recover lost tabs: #526
