### ISSUE TITLE
Title of Youtube is shown incomplete.

### ISSUE THREAD

**Issue by sanketbk** [deanoemcke/thegreatsuspender#42]
Thanks for creating the useful extension. The page titles of youtube pages doesnt seem to be captured accurately.It just displays "Youtube".This affects when i bookmark the tabs and makes difficult to recognize which video i was watching when i revisit my bookmarks. Thanks

**Comment by deanoemcke** [comment]
Hi. Just wondering if you are still encountering this behaviour?
Have you tried to the GitHub version of the extension? It will be updated on the webstore very shortly.
