### ISSUE TITLE
Chrome: "This extension may have been corrupted"

### ISSUE THREAD

**Issue by jmahhh** [deanoemcke/thegreatsuspender#422]
According to my Extensions. The product's been disabled in the Chrome store as well. What's going on?

**Comment by mylemans** [comment]
@jmahhh Not for me

https://chrome.google.com/webstore/detail/the-great-suspender/klbibkeccnjlkjkiokjodocebajanakg?utm_source=chrome-app-launcher-info-dialog

**Comment by deanoemcke** [comment]
Possible duplicate of: https://github.com/deanoemcke/thegreatsuspender/issues/551
