### ISSUE TITLE
option to disc to favorit

### ISSUE THREAD

**Issue by wleds** [deanoemcke/thegreatsuspender#427]
I speak of an option that after a certain adjustable time to transfer the tabs, RAM in the SSD / HDD, another option for transferring tabs, RAM / SSD / HDD favorites. which allows to easily record tab when you do a lot of research for example. I add this link to a basic idea of the interface. [https://docs.google.com/drawings/d/1bHP772G5ls9Grc-T0tTMsNq837fdYpE2oWTnwWI7akQ/edit?usp=sharing](url)

**Comment by deanoemcke** [comment]
You're probably best to look elsewhere if you want to be able to save tabs for offline use.
I think [pocket](https://getpocket.com/) does a good job of this
