### ISSUE TITLE
Auto unsuspend For No Reason

### ISSUE THREAD

**Issue by CheweyZ** [deanoemcke/thegreatsuspender#429]
when you click on to suspend a tab manually 1/5 tabs sometimes  times it will just keep immediately unsuspending and will continue to do so

**Comment by deanoemcke** [comment]
This sounds like a previous bug that was fixed in v6.30: https://github.com/deanoemcke/thegreatsuspender/issues/274

**Comment by CheweyZ** [comment]
This has been quiet for a while but I can still occasionally happen the pages it happens on the most are Gmail and also when you manually suspend it will do it

this is what I've found to be the most reliable way (doesn't always do it)

**Comment by liamjohnston** [comment]
I wonder if what is actually happening is that the tab has been 'discarded' (Chrome's native equivalent of tab suspension, which it will do when system memory is low). Visiting a discarded tab will automatically reload it, which you may be mistaking for a suspended tab unsuspending. 

I'm unsure if suspended tabs can be discarded currently, but if so then this is a possible explanation. 

Just a theory though 😬
