### ISSUE TITLE
Not all tabs are reopened in certain situations.

### ISSUE THREAD

**Issue by gezabohus** [deanoemcke/thegreatsuspender#430]
Using Chrome Version 52.0.2743.116 (64-bit) on OS X 10.11.5. Several tabs in several windows. Some of them don't reopen if Chrome crashes or needs to be forced to quit.

**Comment by deanoemcke** [comment]
The tab recovery system has been significantly rewritten in the upcoming release (v7.x).
Hopefully this will resolve any issues as above.

**Comment by gezabohus** [comment]
Thank you.

On October 23, 2017 8:06:01 PM GMT+02:00, Dean Oemcke <notifications@github.com> wrote:
>The tab recovery system has been significantly rewritten in the
>upcoming release (v7.x).
>Hopefully this will resolve any issues as above.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/deanoemcke/thegreatsuspender/issues/430#issuecomment-338746503

-- 
Sent from my brain.
