### ISSUE TITLE
whitelisted  sites are getting suspended

### ISSUE THREAD

**Issue by mhmoran** [deanoemcke/thegreatsuspender#432]
brighttalk youtube tunein event.on24 infosecurity-magazine 
is the whitelist.   brighttalk, tunein, event.on24 and infosecurity-magazine routinely get suspended at the 15 minute mark.

Additionally,  it isn't consistent. For example,  listening on tunein.com, tab have been open an hour before getting suspended.  Restart the tab, it suspends again 90 seconds after focus switches.  This happens for about 20 minutes and all the sudden I'm back to being whitelisted, running through multiple songs when the tab doesn't have focus.

chrome 52.0.2743.116 (64-bit)  with the great suspender  4.74

**Comment by deanoemcke** [comment]
Please open a new issue if this is still happening on the latest version.
