### ISSUE TITLE
Not working on linux / chrome 53.0.2785.80 beta (64-bit)

### ISSUE THREAD

**Issue by theblackhole** [deanoemcke/thegreatsuspender#434]
Hello,

The extension is not working on Linux Mint 18 with 53.0.2785.80 beta (64-bit) : it just doesn't want to suspend tabs !

**Comment by gnzlbg** [comment]
Can reproduce with the same chrome version and with the latest chrome dev version (Version 55.0.2868.3 dev (64-bit)).

The extension doesn't suspend any tabs anymore.

**Comment by mikevel** [comment]
With Chrome M54 (on Linux) it stopped working and Chrome asks to kill The Great Suspender tabs.
Does anyone care anymore?

**Comment by dandv** [comment]
The extension works for me in 54.0.2840.59 (64-bit) on Ubuntu 16.04.1

**Comment by deanoemcke** [comment]
Is this still happening on the most recent version (v6.30)?

**Comment by theblackhole** [comment]
Nope. I haven't used Linux in a while so I just updated chrome and my extensions to see if it has been fixed: everything works fine now, thank you. :smiley: I will close this issue. 

Chrome version : 62.0.3202.62 beta (64 bits)
Extension version : 6.30
