### ISSUE TITLE
Saved Sessions issue

### ISSUE THREAD

**Issue by TusharTT** [deanoemcke/thegreatsuspender#438]
Recently I updated this extension and though the update was successful but all my **Saved sessions and Recent sessions** were gone. How can I get them back ?? Any particular location where I can look for them on my system ??

**Comment by deanoemcke** [comment]
I fear that I'm too late on this one. Sorry :(
Just cleaning up old issues.

I now have a guide to recovering lost tabs and sessions: https://github.com/deanoemcke/thegreatsuspender/issues/526

Please open a new issue if you want further assistance.
