### ISSUE TITLE
All Pages in Chromes Cross Computer History Show as Suspended Tab

### ISSUE THREAD

**Issue by CultD** [deanoemcke/thegreatsuspender#440]
It's very inconvenient when trying to use google Chromes Cross Computer History and Great Suspender. 
The Great Suspender should make the page name, Suspended Tab (suspended pages name). or (suspended pages name) Suspended tab, or (suspended pages name).

**Comment by deanoemcke** [comment]
Duplicate of: https://github.com/deanoemcke/thegreatsuspender/issues/46
