### ISSUE TITLE
Suspended tabs still consume large amounts of memory

### ISSUE THREAD

**Issue by mskogly** [deanoemcke/thegreatsuspender#441]
Is this a bug or feature? Even when suspended the tabs seem to be consuming large amounts of RAM, see screenshot. I also suspend tabs with unsaved forms. 

![suspender](https://cloud.githubusercontent.com/assets/81774/19145960/b3989e90-8bb1-11e6-8241-fa0324305c0a.png)

**Comment by jddcef** [comment]
Was this straight after installing the extension? Has the browser been restarted?

**Comment by mskogly** [comment]
I've used suspender for several months? But never checked the memory consumption. CPU usage is zero

**Comment by deanoemcke** [comment]
Merging this issue into: https://github.com/deanoemcke/thegreatsuspender/issues/613
