### ISSUE TITLE
Ability to remember timestamp on youtube pages

### ISSUE THREAD

**Issue by DeadSix27** [deanoemcke/thegreatsuspender#444]
So I've had 2 ideas, maybe you already had them yourself and I will look into actually adding them myself (unlikely)
Auto suspending YouTube pages and saving the current timestamp in the suspend-url like:
chrome-extension://_/suspended.html#uri=https://www.youtube.com/watch?v=_&t=[TIME]

This way it would auto-resume where it left off, which would be insanely handy.

The other thing I haven't figured out, whitelisting exact-urls for example:
I whitelisted:
/^https:\/\/example.com\/$/

which I hoped would keep https://example.com loaded BUT NOT https://example.com/fooBar
etc, but maybe I just did the regex wrong, I'm a bit rusty in regex.

**Comment by jonasroessum** [comment]
You can test regex'es with something like [RegExr](http://regexr.com/).
Would be nice with a button to close all suspended tabs.
![image](https://cloud.githubusercontent.com/assets/1959615/19447058/159764e4-949c-11e6-8d06-8c6681f38fbc.png)

**Comment by jonasroessum** [comment]
I looked in the code and it seems that it supports regex, you just forgot to wrap your expression with slashes.

```javascript
testForMatch: function (whitelistItem, word) {

    if (whitelistItem.length < 1) {
        return false;

    //test for regex ( must be of the form /foobar/ )
    } else if (whitelistItem.length > 2 &&
            whitelistItem.indexOf('/') === 0 &&
            whitelistItem.indexOf('/', whitelistItem.length - 1) !== -1) {

        whitelistItem = whitelistItem.substring(1, whitelistItem.length - 1);
        try {
            new RegExp(whitelistItem);
        } catch(e) {
            return false;
        }
        return new RegExp(whitelistItem).test(word);

    // test as substring
    } else {
        return word.indexOf(whitelistItem) >= 0;
    }
},
```

**Comment by deanoemcke** [comment]
See here for the youtube feature request: #342
