### ISSUE TITLE
You're Not Releasing the Chrome.exe process

### ISSUE THREAD

**Issue by scottedwards2000** [deanoemcke/thegreatsuspender#45]
I've been testing this extension extensively, and it's clear that many times, you are not releasing the chrome.exe process tied to the tab.  I realize that you can't do that, as long as another non-suspended tab is tied to that process, but I'm seeing this happen in cases where I've suspended ALL tabs tied to the process.  For instance, when i open the Chrome task manager right now, I see 17 processes, but when I look in Task Manager, I see close to 30.  This app doesn't help if it doesn't release those processes.

**Comment by deanoemcke** [comment]
Hi. Just wondering if you are still encountering this behaviour?
Have you tried to the GitHub version of the extension? It will be updated on the webstore very shortly.
