### ISSUE TITLE
Opera version?

### ISSUE THREAD

**Issue by RJVB** [deanoemcke/thegreatsuspender#452]
Opera is basically Chromium with a different coat; it will run most if not all extensions for Google Chrome (and doesn't -yet- have the increasing set of restrictions Google puts on extensions).

This extension works almost perfectly with the current Opera version, but:

- I cannot yet say if it auto-suspends as it should but it seems it might not do so reliably for background tabs
- unsuspend does not work when clicking in the window when the browser restored its open tabs after a restart. Unsuspend does work from the menu and also by clicking in the window after suspension during the same session.
- possibly related: suspended tabs do not show an URL. This may be an Opera thing, but it seems like it could be risky. I've noticed the same thing can happen in Chrome and unsuspend becomes difficult/impossible when it happens. Maybe the extension could use a special placeholder URL and register as its handler so that the browser doesn't try to be clever with the URL?

**Comment by deanoemcke** [comment]
Please submit any bugs under opera to this issue thread: https://github.com/deanoemcke/thegreatsuspender/issues/124
