### ISSUE TITLE
How to install the greatsuspender using group policy? 

### ISSUE THREAD

**Issue by zahidoanis** [deanoemcke/thegreatsuspender#456]
I tried to install Chrome Extension using group policy but its not working

I configure the ExtensionInstallForce List key by adding string value contain id_extension;http:location of the crx file and its still not working.(I enable the crx mime type in iis and i can access it with browser) 
I also tried to point the http to xml file that contain reference to the crx file and its not working .

Has anyone managed to install chrome extension using group  or master_preferences ?

**Comment by deanoemcke** [comment]
Sorry, I know very little about group policy.
Any community advice would be appreciated here.

**Comment by deanoemcke** [comment]
@zahidoanis did you ever resolve your issue?
another user @stanps seems to have successfully installed via group policy.
also, if anyone knows how to communicate with an extension via group policy so that it can preconfigure settings your knowledge would be much appreciated.

**Comment by deanoemcke** [comment]
Duplicate issue: https://github.com/deanoemcke/thegreatsuspender/issues/253

**Comment by deanoemcke** [comment]
@nagato-fm seems to have got this extension working with GPO. 
see this issue: https://github.com/deanoemcke/thegreatsuspender/issues/97

**Comment by deanoemcke** [comment]
I did come across this guide: http://dennisspan.com/deploying-google-chrome-extensions-using-group-policy/
Does that help?

**Comment by deanoemcke** [comment]
duplicate of: https://github.com/deanoemcke/thegreatsuspender/issues/97

**Comment by bontinckd** [comment]
Message for the developer that made this great extension (deanoemcke ):
The Chromium.org site has some clear info about how to use policies on windows: ie, https://www.chromium.org/administrators/configuring-policy-for-extensions.
Chrome definitly knows on what OS he is running, so it would be really handy to dig a bit in all the info mentioned on that site about using Extension to adapt your TAB-suspender. So people can deploy your extension via GPO's, if it is not configurable via the GPO editor, that's not a problem, just use the correct Windows registry-key's mentioned on that Site. This way we are able to apply the settings via an import of a registry-file. Many thanks
