### ISSUE TITLE
Preserve Tab title

### ISSUE THREAD

**Issue by bkeadle** [deanoemcke/thegreatsuspender#461]
when I look at Chrome history across my devices, I see a long list of "Suspended Tab", which doesn't help me identify the tab(s) I may be looking for from my computers:

Might there be a way to keep the tab title instead of changing it to "Suspended Tab", maybe as a configurable option?  To identify the tab as being suspended, perhaps give it some other visual cue instead of completely replacing the title?

![image](https://cloud.githubusercontent.com/assets/24754039/21467546/592af144-c9b7-11e6-9a78-3ce2280e5d8c.png)

**Comment by Bachomp** [comment]
Duplicate. See #443
