### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by ShalokShalom** [deanoemcke/thegreatsuspender#465]
Hi there :) 

When comes a new release?

**Comment by Barleyman** [comment]
Updating the store version once a year would seem reasonable..

**Comment by liamjohnston** [comment]
Not really an option :(

The way it's been rewritten means that updating would close all suspended
tabs. With 1.3M active users that's too much hurt to be causing.

This is not the official word on the matter (it's not my extension) but I
wouldn't hold your breath for a new web store version ever happening. But
possibly as a separate extension (TGS2) someday...

**Comment by ShalokShalom** [comment]
+1 for TGS2

**Comment by deanoemcke** [comment]
Here is my current policy on upgrading the extension: https://github.com/deanoemcke/thegreatsuspender/issues/322
