### ISSUE TITLE
Feature Request: "Suspend all tabs in active window" keyboard shortcut to suspend current tab AND other tabs

### ISSUE THREAD

**Issue by valerieosmith** [deanoemcke/thegreatsuspender#467]
If I want to suspend every tab in a window, including the one currently visible, I have to perform the keypresses for both "Suspend active tab" and "Suspend all tabs in active window"

**Comment by Zoooook** [comment]
+1

**Comment by deanoemcke** [comment]
Im not sure there is much demand for this feature. Most people, when wanting to suspend all tabs in the current window, would *not* want the current tab to suspend.

**Comment by valerieosmith** [comment]
@deanoemcke The use case for me, at least, is that Chrome kills my MacBook's battery. When I'm on battery, I tend to suspend every single tab in several windows. This extension is a godsend for tab hoarders like I am who organize windows by topic, and it stands to reason that if there's a keyboard shortcut to suspend the current tab AND other tabs, one might wish to suspend them all at once too. It'd just be nice to have.

**Comment by Omar-Elrefaei** [comment]
I Think I would use that

**Comment by deanoemcke** [comment]
The upcoming version has a new option (both as a keyboard shortcut, and a right-click menu option) called 'Force suspend all tabs in all windows'.
This will attempt to suspend every tab in every window in a single operation. This includes currently focussed tabs, and will also override any whitelist, form input, pinned tab etc statuses.

The existing 'Suspend other tabs' functionality has also been tweaked. It will now respect any whitelist, form input, pinned tab etc. statuses.

I hope this will satisfy your requirements. For the use case where you want whitelisting etc to be respected and _still_ close the currently focussed tab, you will need to use the 'Suspend other tabs' button on each open window, and then manually suspend the currently focussed tab afterwards.

**Comment by valerieosmith** [comment]
@deanoemcke Wow, that's more than I was thinking. I was just talking about suspending every tab in the currently selected window (including the currently focused tab). But this is great! I'll definitely be using this whenever I'm on battery throughout the day. Thanks!
