### ISSUE TITLE
Doesn't suspend and unsuspend properly on some specific pages

### ISSUE THREAD

**Issue by pointyointment** [deanoemcke/thegreatsuspender#469]
This page:
https://surplus.gov.ab.ca/CnCList.aspx
Also, the individual sale list pages, such as:
https://surplus.gov.ab.ca/CashnCarryDetail.aspx?SaleCode=CCCALOUT20170001
(When that expires, you can click on one of the links in the "Cash & Carry ID" column on the first page to get to an equivalent one.)

When these tabs get suspended, the tab title is lost (i.e. it changes to "Suspended Tab") and the top bar of the suspension page is empty. Clicking where it says "Tab suspended / Click to reload" doesn't reload it, and neither does using the browser reload button/key. I have to manually edit the URL to get the page to load again. (Thanks for making that editing easy, by the way!)

I think it used to work properly, but I don't remember for sure.

I have figured out that it's not caused by the domain, because [this part of the site](https://surplus.gov.ab.ca/OA/ItemsSearch.aspx) suspends and resumes just fine.

The Great Suspender 6.21
Chrome 55
Windows 7

**Comment by bengan** [comment]
I don't see this. It works as it should.

The Great Suspender 6.21
Chrome Version 56.0.2924.87 (64-bit)
Linux openSUSE Tumbleweed

**Comment by pointyointment** [comment]
I'm now on Chrome 56 and it's working again.
