### ISSUE TITLE
Add the option to not suspend if the tab is playing sound

### ISSUE THREAD

**Issue by abendebury** [deanoemcke/thegreatsuspender#470]
For example, youtube music, spotify, bandcamp, etc. - I'd want them to be suspended when they aren't playing sound, but not if I'm listening to them.

**Comment by liamjohnston** [comment]
Are you on the latest version? Go to the extension's settings and see the 3rd checkbox: "Do not suspend tabs that are playing audio"

**Comment by abendebury** [comment]
I'm on 6.21 (the most recent tagged version) and I'm not seeing it. Is there a more recent version?

![2017-02-15_17 14 02](https://cloud.githubusercontent.com/assets/146027/23002928/40510860-f3a2-11e6-8002-586143e29afa.png)

**Comment by liamjohnston** [comment]
I'm on 6.3, and my checkbox options are:

![screen shot 2017-02-16 at 2 59 21 pm](https://cloud.githubusercontent.com/assets/1134713/23003934/9b71a37e-f458-11e6-8e41-f320be066840.png)

**Comment by abendebury** [comment]
I see. The chrome web store also only has 6.21:

https://chrome.google.com/webstore/detail/the-great-suspender/klbibkeccnjlkjkiokjodocebajanakg?hl=en

But seeing as this feature is already implemented I'm going to close this issue. Hopefully 6.3 gets pushed out soon. Thanks!

**Comment by deanoemcke** [comment]
Duplicate of: https://github.com/deanoemcke/thegreatsuspender/issues/28
