### ISSUE TITLE
Unsuspending Tabs with Google Drive Docs/Sheets/etc. Changes Google Account With Which "File" Was Opened

### ISSUE THREAD

**Issue by hmhecht** [deanoemcke/thegreatsuspender#472]
Hi,

First off, let me say that I love this extension and it has saved my PC from getting bogged down since I always have far too many tabs open. Thank you!

I have been consistently experiencing and issue that I'd appreciate if you could look into addressing in a future release.

I have multiple Google Accounts - personal, plus a few work-related ones. I keep a bunch of my work-related Google Drive documents (docs, sheets, etc.) open, which get suspended to save resources. Note that on almost all of my Google Drive documents, my personal account also has "backup" access -- but when I edit them I **must** do so via the proper work Google account.

The problem: When I unsuspend a tab which has a Google Drive document which was opened with my work account, it opens it with my personal account instead. This is causing a number of issues (I can explain those if you'd like) and I'd really like it to open back up with my work account, and not "switch" to my personal account. 

Steps to reproduce are:
1. Sign in to personal Google Account. (i.e. user@gmail.com)
2. Via Google's "Add Account" feature, also sign in to a work-owned Google Account. (i.e. user@company.com)
3. From the work-related Google Drive Account, and open a Google Drive Doc or Sheet that also happens to be "Shared" with the personal Google Account. Notice in the upper right corner it says "user@company.com")
4. Suspend that tab.
5. Unsuspend that tab. Notice now that it says "user@gmail.com" instead and you're now editing the Doc or Sheet with your personal account.

Is there any way to ensure the same account is used to re-open the tab? 

Note that I did notice the URLs are exactly the same, so this may be unavoidable. I'm not sure how Google keeps track of which account was used. In other Google-related tabs such as Gmail there is a part of the URL which indicates which account it is -- i.e. /mail/u/0/ versus /mail/u/1/ and /mail/u/2/ -- but this does not seem to be present in open Google Drive Docs or Sheets. 

Thank you in advance!

**Comment by fwextensions** [comment]
I see this happen a lot as well, though I'm not sure if there is a workaround.

**Comment by deanoemcke** [comment]
Yes. It does not seem like an extension issue. Suspending and unsuspending is pretty much the same as closing the tab then reopening it.
