### ISSUE TITLE
A Few Suggestions

### ISSUE THREAD

**Issue by natkey** [deanoemcke/thegreatsuspender#476]
Is this extension still in development? It's good for what it does but I have some suggestions. 1) Could you kindly include a quick way to close all suspended tabs? I know 'The Great Discarder' exists but I prefer to have the option to close the tabs myself. 2) Also, it would be nice if the extension didn't suspend tabs where you had typed some text (in a box, for example) but hadn't submitted it yet. I know there is an option to prevent this but it doesn't seem to work in all cases. 3) Another option I think would be nice to have is an option for some sort of subtle indication that a tab will be suspended soon. This could help you quickly decide whether you need to save a tab or not. 4) An option to not suspend tab if audio is playing. This is implemented in "The Great Discarder"

**Comment by liamjohnston** [comment]
The latest version on GitHub has the audio flag you're after. Don't hold
your breath for this version getting to the web store.

**Comment by natkey** [comment]
Nice to know. Sad it's not likely to be on the web store though. Chrome unfortunately gives that warning each time you start up for extensions that aren't from the web store.

**Comment by deanoemcke** [comment]
1) There have been two pull requests to try to implement this. I am still reluctant to add it as a feature. A discussion on this can be found here: https://github.com/deanoemcke/thegreatsuspender/pull/499
2) If you're having issues with the 'do not suspend tabs receiving form input' feature, can you please open it as a separate issue and give specific examples of how to reproduce.
3) There is an open github issue for something like this: https://github.com/deanoemcke/thegreatsuspender/issues/544 however I would need more details on the use case you are trying to handle, and a possible solution to the problem.
4) The audio option is live in the latest webstore release (v6.30 :)
