### ISSUE TITLE
Extension causing Google Drive to fail upload for long uploads

### ISSUE THREAD

**Issue by maddiericola** [deanoemcke/thegreatsuspender#477]
Extension causing Google Drive to fail upload for long uploads in chrome

**Comment by piotrowski** [comment]
Does the tab where the upload is running get suspended and by this the upload fails? Then your solution would be to whitelist the domain of this tab to never suspend.

**Comment by deanoemcke** [comment]
Alternatively, if you do not wish to permanently whitelist the site, you can select "Dont suspend for now"

**Comment by maddiericola** [comment]
I have whitelisted. It does not suspend but upload fails.

**Comment by deanoemcke** [comment]
If the tab is not suspending, i'm not sure how it can be interfering with your upload. Why do you think it is the extension that is causing you problems?
