### ISSUE TITLE
Icon color should change when a tab starts receiving input, playing audio etc

### ISSUE THREAD

**Issue by natkey** [deanoemcke/thegreatsuspender#479]
The great suspender button is supposed to turn grey when a tab is no longer going to be suspended. When this happens automatically (in the case of a tab playing audio or when you type some text in a form on the tab), I find that the icon color doesn't change to grey until after I switch to a different tab and then back to the previous tab. It would be nice to see the change immediately I start typing for example.

**Comment by deanoemcke** [comment]
This has been address in the upcoming release (v6.31).
Here is the commit: https://github.com/deanoemcke/thegreatsuspender/commit/6abe254acac346db50485a851c9fea10fff8b7e6
