### ISSUE TITLE
Feature: more options in "Automatically suspend tabs after"

### ISSUE THREAD

**Issue by mikinw** [deanoemcke/thegreatsuspender#482]
I would be glad to have "5 days" or "7 days " options when selecting the time interval for suspending tabs. Often when I leave my computer for the weekend, even with the 3 days selected, some of my tabs (that I wouldn't want to be suspended) gets suspended.
Eg. I open up some tutorials, articles in the morning and during Friday. And next time on Monday afternoon when I get back to those tutorials all of them are suspended.
(of course it's not a big deal, but I think the this feature doesn't need a lot of coding either)

**Comment by deanoemcke** [comment]
The upcoming release will have a 1 and 2 week option :)
Just be slightly wary of this outstanding issue: https://github.com/deanoemcke/thegreatsuspender/issues/176 which is due to the computer going to sleep or hibernating.
