### ISSUE TITLE
Many Chrome Tabs Open on Restart

### ISSUE THREAD

**Issue by threew01** [deanoemcke/thegreatsuspender#483]
First: close all (unsuspended) tabs and shut down Google Chrome. Then, on reopen  many, many tabs open. Not just the ones closed prior to browser shut down but also tabs that were closed previously in the same session. This happens even if Great Suspender sessions are all cleared before shutting down Chrome. 

In Chrome Settings, On Start Up, "continue up where you left off" is selected.

**Comment by deanoemcke** [comment]
This behaviour has nothing to do with this extension. The Great Suspender does not try to control which tabs get opened on browser start. That is purely chrome behaviour (unless you have another extension installed that might do this).
