### ISSUE TITLE
Disable developer mode extensions warning

### ISSUE THREAD

**Issue by Larusek** [deanoemcke/thegreatsuspender#484]
Hi,
I've recently upgraded to version 6.30 by loading unpacked source from here in my Chrome Canary install.
Everything works ok but I always get that warning on Chrome startup:

![screenshot](http://image.prntscr.com/image/b733f57d989945a3b8088509312dce23.png)

Is it possible to disable this warning? I tried adding extension ID to google group policy whitelist but it still displays the warning.

Thanks in advance.

**Comment by dirdigeng** [comment]
For me, once I had installed the version from here, I could untick the Developer mode box on the Extensions page. The "Load Unpacked Extension" and "Pack Extension" buttons disappeared but Great Suspender was still on the list of extensions and still works OK

**Comment by deanoemcke** [comment]
Also, this is a security feature implemented by chrome to ensure malicious extensions are not installed without the users knowledge so I am not able to control when it appears.
The chrome webstore does have v6.30 now though so you may be able to switch to that.
Please follow the correct procedure for doing so though: https://github.com/deanoemcke/thegreatsuspender/issues/526

**Comment by Larusek** [comment]
Thanks, but somehow the mentioned Windows Policy Whitelisting rule for Chrome started to work. So I could get rid off that annoyance.
