### ISSUE TITLE
Problem When Uninstalling

### ISSUE THREAD

**Issue by vmnrao** [deanoemcke/thegreatsuspender#486]
When the great suspender is uninstalled and I have many suspended tabs open in multiple windows, it should unsuspend all tabs before uninstalling, but it doesn't do this. Instead, it leaves  each suspended tabs with unusable links after uninstall. 

On a related note, a feature should be added to unsuspend all tabs. The current unsuspend button doesn't seem to work for tabs in the current window, much less all tabs in all windows.

**Comment by piotrowski** [comment]
> Instead, it leaves each suspended tabs with unusable links after uninstall.

Can't you just click the page title that links to the page that is suspended?

**Comment by deanoemcke** [comment]
There is a feature request for this: https://github.com/deanoemcke/thegreatsuspender/issues/40
For a guide on recovering lost tabs please refer to: https://github.com/deanoemcke/thegreatsuspender/issues/526#what-is-the-safe-way-to-update-the-extension
