### ISSUE TITLE
Copyright issue

### ISSUE THREAD

**Issue by MWFIAE** [deanoemcke/thegreatsuspender#487]
It looks like theres a clone for this great extension around. 

https://chrome.google.com/webstore/detail/tab-memory-saver/pehgadfgejpbgkgkofomjkbgfbnhdfll

Maybe you want to consider to fill out following form:
https://support.google.com/legal/troubleshooter/1114905#ts=1115658%2C1115673

**Comment by deanoemcke** [comment]
Thanks. I am aware. Someone else has also reported this: https://github.com/deanoemcke/thegreatsuspender/issues/500

Given this extension is open source, I'm not sure I have any rights to complain? I'm more concerned with the outrageous user numbers the extension purports to have. It doesn't seem to correlate with the number of reviews it has on the webstore :/
