### ISSUE TITLE
Feature Request: display state in right-click menu of extension icon

### ISSUE THREAD

**Issue by cori** [deanoemcke/thegreatsuspender#488]
For example, if the current tab is whitelisted, or set to "not suspend for now" place a check mark or some indicator in the popup menu that's displayed when you right-click the extension icon.

**Comment by piotrowski** [comment]
Same behaviour as in left-clicking the extension icon?

**Comment by cori** [comment]
ha. yeah.

Thanks!

**Comment by piotrowski** [comment]
To be fair: I didn't know there was actual functionality in right-clicking the extension icon.
