### ISSUE TITLE
Accept bitcoin for donations

### ISSUE THREAD

**Issue by john-light** [deanoemcke/thegreatsuspender#489]
This is a really cool app! I would like to chip in to support its development. Do you have a bitcoin address or link that can be used to send you bitcoin donations? If not, and you'd be interested in getting help setting this up, I can help you with this.

**Comment by liamjohnston** [comment]
Head to he settings area, there's a donate option :)

**Comment by john-light** [comment]
Brilliant! Thanks :+1:
