### ISSUE TITLE
Donation option disappears after using one of the options

### ISSUE THREAD

**Issue by john-light** [deanoemcke/thegreatsuspender#490]
After pressing the "Donate using Coinbase" button and going through the flow, the donation buttons in the Settings menu have been replaced with this message:  

Thanks a lot for your donation. You've made thank you cat happy.

  |\      _,,,--,,_
  /,`.-'`'   ._  \-;;,_
 |,4-  ) )_   .;.(  `'-'
'---''(_/._)-'(_\_)
            

Does this message ever go away? What if I want to donate again? Just wondering :)

**Comment by liamjohnston** [comment]
Yeah, it's a petty lo fi solution. You can head to the settings section to
donate again :)

**Comment by john-light** [comment]
I did go back to the settings section to donate again, and that cat was there instead of the donate buttons.

**Comment by liamjohnston** [comment]
You don't see this "want to donate again?"

![screen shot 2017-04-05 at 5 01 04 pm](https://cloud.githubusercontent.com/assets/1134713/24690546/904226c4-1a21-11e7-8b22-1ab3b42bdb7a.png)

What version are you on?

**Comment by john-light** [comment]
I do not! Using The Great Suspender v6.21.

**Comment by liamjohnston** [comment]
6.3 has it :) And some other good stuff that 6.21 might not have (can't remember, audio whitelisting maybe?)

Maybe back up your tabs before updating.

**Comment by john-light** [comment]
The latest version in the Chrome store is 6.21, how do I install 6.3?
![screen shot 2017-04-18 at 11 38 49 am](https://cloud.githubusercontent.com/assets/9424721/25147249/bf922e74-242b-11e7-919d-77c685e9fd67.png)

**Comment by Pascal666** [comment]
6.30 is now available from the Chrome Web Store and the feature you requested appears to be working perfectly.
