### ISSUE TITLE
Unsuspending and going to previous page, returns back to suspended page.

### ISSUE THREAD

**Issue by vitalilng** [deanoemcke/thegreatsuspender#491]
1. make some google search.
2. click on any link from the results and then suspend it.
3. unsuspend the tab.
4. click to back button on browser(Google Chrome).

**Result:** If I unsuspended the tab, then I chose to go page back, then the previously opened page should be shown(google search results in this case), instead of the suspended tab on which I was.

**Comment by deanoemcke** [comment]
I cannot reproduce this. Is it still happening on v6.30?

**Comment by vitalilng** [comment]
Yes, is not reproducing on v6.30.
