### ISSUE TITLE
Feature: Never suspend this tab

### ISSUE THREAD

**Issue by xtre3m** [deanoemcke/thegreatsuspender#493]
I believe this option was implemented and then was removed. I would like to see the option to "Never suspend this page/tab". I frequently work with some tabs during a day that I don't want to be suspended automatically until I mark them again as "suspendable". 

I am using a 2 hour option for automatically suspending and I would like to see an option for "Never suspend this tab", same as "Never suspend this site".

Thank you very much!

**Comment by felipe1982** [comment]
you can choose that any *pinned* tabs are never suspended.

**Comment by xtre3m** [comment]
Thank you felipe1982 for your suggestion! The thing is a pinned tab si compacted and you can't see it's title so it's a hassle to work with a lot of pin tabs. The neat solution would be the simple one, the suggestion I've presented above. Thanks!

**Comment by deanoemcke** [comment]
There is a "dont suspend for now" option that will prevent the tab from being suspended until it is closed or chrome is restarted. That is exactly what you are after no?
Perhaps it's a UI wording issue..
