### ISSUE TITLE
tabs suspend but the memory is still used

### ISSUE THREAD

**Issue by 7404411** [deanoemcke/thegreatsuspender#494]
Hi,

I recently installed the GS in hopes to free up the RAM that's been consumed a lot by Chrome. 

The tabs do turn to the suspended mode, I have to click on them to reload - everything seems to be working fine.

However, I don't see any positive effect on RAM. E.g. 3-4 active tabs in the browser, while 10-15 "Chrome Helper" rows in the Activity Monitor that eat up my 16Gb.

Can you please explain to me whether your tool is supposed to free up the memory or is there another benefit of having the tabs suspended/reloaded?

Thanks!

**Comment by piotrowski** [comment]
Check the Chrome task manager. There you can see that the suspended tabs don't use the memory any more internally in Chrome. This is not necessarily directly linked to the memory usage in your OS unfortunately.

**Comment by deanoemcke** [comment]
I have had mixed success in directly trying to validate memory savings. However, anecdotally the extension definitely does work. I realize that's not much comfort. 

I have attempted in the past to track the memory savings directly, but it is difficult to directly track the memory change from one process disappearing (the suspended tab - if it was the last tab with in that domain) and another increasing in memory slighly (the extension process).
Also, I don't know what other things are going on in the chrome internals.

Finally, there is the CPU factor. Suspended tabs have all their javascript removed (well actually replaced with some very small script from the suspended tab). So there should be a gain in processing as well.

**Comment by deanoemcke** [comment]
Merging this issue into: https://github.com/deanoemcke/thegreatsuspender/issues/613
