### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by davidrthorn** [deanoemcke/thegreatsuspender#498]
When tabs are set to reload on refocus, they instantly reload when manually suspended. It would be great if reload delayed for 5 seconds so I could click onto a different tab before this one reloaded

**Comment by piotrowski** [comment]
Not a bad request, but of course would make the "Automatically unsuspend when tab gains focus" label for this functionality quite wrong. 

If at all this would have to be added as a new check box in the options "Unsuspend when tab gains focus and stays focused for x seconds". Which also makes clear that this would be misunderstood by many users and sounds a bit like an edge case.

Maybe disable the existing option and use Ctrl+Shift+U keyboard shortcut when you focus the tab?

**Comment by deanoemcke** [comment]
I cannot replicate this. Manually suspending a tab (in v6.30) does not cause it to automatically reload after being suspended.
Also, the functionality to have a delay is already implemented. If you ctrl+tab through suspended tabs fast enough, they do not automatically reload.
