### ISSUE TITLE
Full-page screenshot support

### ISSUE THREAD

**Issue by dariomannu** [deanoemcke/thegreatsuspender#501]
It would be great if we could optionally have full-page screenshots that extend below the fold.

**Comment by ShalokShalom** [comment]
This comes up in the next version 6.30

According to the developer is that one already available on Github, so I guess a build from source give you, what you want. :)

**Comment by Pascal666** [comment]
6.30 is now available from the Chrome Web Store and the feature you requested appears to be working perfectly.

**Comment by ShalokShalom** [comment]
thanks :+1:

**Comment by dariomannu** [comment]
Works greatly. Amazing job. Thanks, folks!
