### ISSUE TITLE
When forms are suspended, they are incorrectly returned without previous contents

### ISSUE THREAD

**Issue by BobAalsma** [deanoemcke/thegreatsuspender#502]
When re-activating suspended tabs, all previous contents have been removed. 
This makes the software less than useful for suspending any form :(

**Comment by MaxPleaner** [comment]
There is an option to not suspend if there is an unsaved form input, but it doesn't seem to work. @deanoemcke would appreciate your input

**Comment by deanoemcke** [comment]
Unsuspending a tab is basically just reloading it. As with any tab, if you reload it, you tend to lose any form input (unless the website supports quick saving). 
The extension is not designed to save form input, and it would raise security concerns if it did try to do so.
There is the option: "Do not suspend tabs that contain unsaved form inputs". This is designed to detect when you have started entering information into a form, and prevent the page from suspending automatically if it detects form input.
@BobAalsma What is the url of the tab that is causing you problems? Do you have the above option enabled? And is the tab suspending automatically?

**Comment by BobAalsma** [comment]
(1) The URL is a localhost Django application, sorry;
(2) "Do not suspend tabs that contain unsaved form inputs" is checked;
(3) I'm using the Django admin interface for this application. The Django admin site will add Javascript to those pages: "

Each DateTimeField gets free JavaScript shortcuts. Dates get a “Today” shortcut and calendar popup, and times get a “Now” shortcut and a convenient popup that lists commonly entered times.

" (see [doc](https://docs.djangoproject.com/en/1.11/intro/tutorial02/#explore-the-free-admin-functionality)). These Javascript shortcuts are usually not displayed after un-suspending.

**Comment by deanoemcke** [comment]
Well an easy workaround is to whitelist that page. That will prevent it from auto suspending. The form input detection is not perfect, but without an actual webpage to test on, it's hard to know what might be going on.

**Comment by MaxPleaner** [comment]
Thanks for being responsive dean, I wasn't able to reproduce the issue I
had with form text being ignored. But I do have one question. I have a
whitelist rule for  **.bandcamp.com <http://bandcamp.com>* *but it doesn't
catch sites like *blankbanshee.bandcamp.com
<http://blankbanshee.bandcamp.com>* and I have to whitelist them
individually; how can I get around this?

**Comment by deanoemcke** [comment]
If you want to use special characters like the * wildcard in the whitelist, you need to use the alternative regular expression syntax which looks something like this:
/^https:.*google\.com/

for your example:
/.*blankbanshee\.bandcamp\.com/ 
should work.

**Comment by MaxPleaner** [comment]
Thanks I guess I didn't read the guide well enough, didn't notice the regex
stuff

**Comment by deanoemcke** [comment]
Haha. I think it's probably more that the 'guide' is not made obvious enough :)
