### ISSUE TITLE
Chrome crashed 

### ISSUE THREAD

**Issue by klfstl** [deanoemcke/thegreatsuspender#504]
My Chrome crashed this am and when it came back none of the tabs were visible. Chrome also wouldn't navigate to specific pages like domains.google. 

I was able to narrow the problem to the Great Suspender by process of elimination , and when i disabled the extension the tabs returned but i was still unable to navigate to domains.google. 

During this and even now i can navigate to google by using safari.

**Comment by klfstl** [comment]
Im sorry i didn't screen shot when this was going on... as busy as i am i kinda freaked out a bit and only looked for a solution.

**Comment by deanoemcke** [comment]
Any update on this? From what you've given me I can't really help you. 
Can you provide steps to reliably reproduce the issue?
