### ISSUE TITLE
6.30

### ISSUE THREAD

**Issue by ShalokShalom** [deanoemcke/thegreatsuspender#506]
I read on several issues now, that they are solved or partly solved in 6.30. Where is that one? :)

**Comment by Pascal666** [comment]
6.30 is now available from the Chrome Web Store.

**Comment by ShalokShalom** [comment]
thanks :)

**Comment by ShalokShalom** [comment]
by the way: it seems my Opera updated it, while i installed it in the first place via the Chrome Web Store

How that? I think there is no auto update function?
