### ISSUE TITLE
Feature Request: Instant visual feedback on "Unsuspend tab"

### ISSUE THREAD

**Issue by janpio** [deanoemcke/thegreatsuspender#507]
When working with many suspended tabs and e.g. going through lots of them to unsuspend them it would be beneficial if you would get instant visual feedback that your Ctrl+Shift+U was registered and the page is reloading (which always takes a few hundred miliseconds to acutally show). 

A switch of the "Click to Reload" text to "Loading page..." or an animated spinner would be nice and would greatly improve the usage experience.

**Comment by deanoemcke** [comment]
Implemented in commit: https://github.com/deanoemcke/thegreatsuspender/commit/e3168d2d2dadb4f7e8cc89dfea57cce28e95cc2c

**Comment by liamjohnston** [comment]
Really nice 👍
