### ISSUE TITLE
Some tabs become black and clicking does nothing

### ISSUE THREAD

**Issue by mailinglists35** [deanoemcke/thegreatsuspender#51]
http://clip2net.com/s/5PrkFR
I can't click anywhere, I must manually copy URL from address bar and remove encoded characters such as : / spaces etc
chrome dev 31 windows xp
installed extensions

dblock Plus 1.5.5
The free adblock tool for Chrome: Blocks annoying video ads on YouTube, Facebook ads, banners and much more. Permissions Visit website
ID: cfhdojbkjhnklbpkdaibdccddilifddb
Inspect views: background page

Allow in incognito
 Options

Enabled
 
Awesome Screenshot: Capture & Annotate 3.4.5
Capture the whole page or any portion, annotate it with rectangles, circles, arrows, lines and text, blur sensitive info, one-click upload to share. Support PNG and shortcuts. Permissions Visit website
ID: alelhddbbhepgpmgidjdcjakblofbmce

Enable
 
Clearly 9.3374.689.453
Clearly makes blog posts, articles and webpages clean and easy to read. Save them to Evernote to read anywhere. Permissions Visit website
ID: iooicodkiihhpojmmeghjclgihfjdjhj
Inspect views: background.html

Allow in incognito
   Allow access to file URLs Options

Enabled
 
Easy Youtube Video Downloader 4.1
Easiest method to download YouTube videos in FLV, MP3, 3GP, MP4, 720p and 1080p FULL-HD video qualities. Permissions
ID: fmknocfkgffdgekmfonabppnhdgmghem

Allow in incognito
 
Enabled
Not from Chrome Web Store.
 
Facebook Select All 1.0
Select all facebook friends. Permissions Visit website
ID: clbcjpjecmkjagmnhgfojblhjhnalbda

Enable
 
FlashControl 3.3.15
Flash content filter for Chrome. Permissions Visit website
ID: mfidmkgnfgnkihnjeklbekckimkipmoe
Inspect views: background page

Allow in incognito
 Options

Enabled
 
Google Docs 0.5
Create and edit documents Permissions Visit website
ID: aohghmighlieiainnegkcijnfilokake

Enable
 
Image Properties Context Menu 0.7.6
A simple context menu extension to show the properties of an image. Permissions Visit website
ID: khagclindddokccfbmfmckaflngbmpon

Enable
 
Lazarus: Form Recovery 3.2
Autosaves everything you type so you can easily recover from form-killing timeouts, crashes and network errors. Permissions
ID: loljledaigphbcpfhfmgopdkppkifgno
Inspect views: background.html

Allow in incognito
 Options

Enabled
Not from Chrome Web Store.
 
MediaPlus 2.1.2
Take control of videos, games, images & other media content on webpages. Move, resize, turn lights off, or make them full screen. Permissions Visit website
ID: emaamodndfmmmcjepfigalbjjjemadom

Enable
 
ScriptSafe 1.0.6.16
Regain control of the web and surf more securely. Permissions Visit website
ID: oiigbmnaadbkfbmpbfijlflahbdbdgdf
Inspect views: html/background.html

Allow in incognito
 Options

Enabled
 
Social Fixer for Facebook 7.801
Social Fixer for Facebook fixes annoyances, adds features, and enhances existing functionality to make FB more fun and efficient Permissions Visit website
ID: ifmhoabcaeehkljcfclfiieohkohdgbb

Enable
 
The Great Suspender 4.74
Permissions Visit website
ID: klbibkeccnjlkjkiokjodocebajanakg
Inspect views: background page

Allow in incognito
 Options

Enabled
 
User-Agent Switcher for Chrome 1.0.26
Spoofs & Mimics User-Agent strings. Permissions Visit website
ID: djflhoibgkdhkhhcedjiklpkjnoahfmg

Enable

**Comment by deanoemcke** [comment]
Possibly related issue: https://github.com/deanoemcke/thegreatsuspender/issues/34
Can anyone confirm that this is still happening? And are we happy to assume it is not related to the extension?
Closing optimistically :D 
Please let me know if you are still having issues with this.
