### ISSUE TITLE
start where left off with >600 suspended tabs, RAM usage over 16Gb

### ISSUE THREAD

**Issue by sheershoff** [deanoemcke/thegreatsuspender#511]
Hello, I've got >666 tabs in my chrome-stable on my Kubuntu machine. It has maximum RAM allowed by the motherboard (16Gb).

I've got lots of extensions installed alongside the magnificent Great Suspender v6.21 (screen capture disabled). Sometimes upon loading the Chrome ("start where I left off option" is on) the RAM usage seers above maximum and I have a swap-freeze situation, which also prevents from "suspend all" global keyboard shortcut to show memory effect before it goes to swap. Sometimes it goes OK and the total Chrome usage is no more than 4Gb which is acceptable.

Also, I see that the network usage is rising when it loads the suspended tabs. Seems like it tries to fetch the headers and/or icons. If it's the case, is there an option to not fetch titles/favicons?

What should I do? (close some tabs, for sure, but...) Is there any setting or improvement possibility? Maybe it's other extensions that come in effect with the ram usage. Still, the Great Suspender is the first suspect to me, sorry if it's not that.

Should I try the great discarder instead?

**Comment by sheershoff** [comment]
Seems like the memory hogs, in this case, were the plugins that tried to help organize tabs: easy tabs and tabs outliner. I don't use them, so I uninstalled them and tried to restart chrome. It all went like a bliss.

Thank you for the great suspender.

**Comment by deanoemcke** [comment]
Thanks for the update @sheershoff . Let me know if you encounter problems in the future.

**Comment by sheershoff** [comment]
Yesterday I've encountered the situation again. Seems like it just wanted to load all the tabs to memory despite the fact that they're all remembered as suspended. Since the situation is random and occurs seldom, is there a CLI option I can add so I can have some logs for you in case the situation comes up again?

**Comment by deanoemcke** [comment]
Merging this issue into: https://github.com/deanoemcke/thegreatsuspender/issues/613
