### ISSUE TITLE
Why author needed modify user data sites ??? What is it - the desire to gain access to confidential information? It also expands the opportunities for abuse !!! Explain !!!

### ISSUE THREAD

**Issue by romario300** [deanoemcke/thegreatsuspender#513]
as the author explains finally: what he needs to "change all user data on all websites" ??? This is simply not acceptable !!! Because it gives the author access to passwords and personal data !!! Why so abuse the trust of users ??? And most importantly - this writer does not speak a word !!! WHY?!?

**Comment by troyshu** [comment]
The developer got hacked, and is working with Google to regain control. See https://github.com/deanoemcke/thegreatsuspender/issues/512

**Comment by Infinitay** [comment]
Should I be worried? The extension just updated for me, and all my tabs got closed. I saw it got disabled and even ignored the security warning message and re-enabled the extension and reopened and loaded my tabs. :x

**Comment by Corrodias** [comment]
Yes, disable the extension. Use a session manager like Session Buddy to save your tab list before doing so if you are concerned about losing the list.

**Comment by nikolay** [comment]
@Infinitay I think this happened because Google disabled the extension.

**Comment by nikolay** [comment]
@Corrodias Any idea what the hacked extension does?

**Comment by Corrodias** [comment]
Read the linked issue for the current discussion. The only obvious change is the version number, but of course it can't be trusted.

**Comment by sashasimkin** [comment]
Same here. Just found out that many of my tabs suddenly got closed, then noticed that suspend shortcut isn't working.
thx for the pointer @troyshu

**Comment by sammarcus** [comment]
![image](https://user-images.githubusercontent.com/8689264/26853786-6c57541e-4ae1-11e7-8250-b89a52076196.png)

**Comment by MahmoudAmeen** [comment]
Does that means that any of our saved data (usernames, passwords etc) may have been hacked ?

**Comment by romario300** [comment]
**Well, expansion of 6.22 was broken and criminals and therefore require an extension - "to read and modify all your data on the websites you visit."
  Now finally the author (looks like) is corrected (for which he thanks), and released a normal and safe expansion of 6.3, right?
  Then why this extension (version 6.3) again calls me in Chrome extensions page - "read and modify all your data on the websites you visit" ??? It must be so? Can someone explain ???**

**Comment by Corrodias** [comment]
Sure, I can answer that by quoting the readme file:If you were asked recently to accept new permissions, this is purely because you were upgrading from an older version of the extension to a newer one (v6.22). The extension has required these permissions to operate for quite some time now and is not related at all to the extension being compromised.

**Comment by Corrodias** [comment]
And as a long time user of 6.21, I can guarantee that that old version did require the same permissions.

**Comment by deanoemcke** [comment]
And please see this thread for an explanation of why the extension requests these permissions: https://github.com/deanoemcke/thegreatsuspender/issues/213

**Comment by romario300** [comment]
Thank you for the clarification, deanoemcke!
 I am absolutely not a great expert in programming. I am a regular user classic, always afraid of hackers and thieves passwords)) ... because your explanation I was a little relieved.
  That means I can trust this expansion and to allow him to "read and change all my data on the sites."
 This is good news! Now I'll include it and will continue to use, because your extension really very, very useful and very convenient and simplifies my life, because I like to open 500 tabs and work with them whole months. So thank you very much for your work! ;)

**Comment by romario300** [comment]
Dear **deanoemcke**, sorry that once again I write here, but I just came up an interesting idea and I would like you as a developer to ask - is it possible to do some special option (user selectable) when choosing which extension will not ask such terrible permissions (READ and CHANGE ALL data)? Let maybe some extra features will not be available in this case (for example screen shot, etc.). I think then to all these questions, fears and suspicions of many users would simply fall away by themselves!
  This is possible in principle to do ???

**Comment by deanoemcke** [comment]
I have considered this, and as a result I created another extension called The Great Discarder. It is significantly better than The Great Suspender in terms of memory use and required permissions, but lacks the features that these permissions allows.
It's probably exactly what you're after. Check it out:
Chrome webstore: https://chrome.google.com/webstore/detail/the-great-discarder/jlipbpadkjcklpeiajndiijbeieicbdh?hl=en
GitHub: https://github.com/deanoemcke/thegreatdiscarder
