### ISSUE TITLE
"This extension contains a serious security vulnerability."

### ISSUE THREAD

**Issue by DearFreja** [deanoemcke/thegreatsuspender#514]
Chrome disabled it and the reason given is "This extension contains a serious security vulnerability."

I ..don't know why this is happening but some insight would be appreciated. Is this safe to use? 
![suspender](https://user-images.githubusercontent.com/29239712/26853588-016ef046-4ae9-11e7-8e59-96f9ac5e08fe.png)

**Comment by sammarcus** [comment]
This is addressed in #512 and #513. Specifically this [comment](https://github.com/deanoemcke/thegreatsuspender/issues/512#issuecomment-306356434)

**Comment by dfberger** [comment]
It also looks like google pulled the extension from the store.  

Until an updated extension is available one idea would be:

enable the extension
restore all the tabs it had suspended
un-suspend them all
disable the extension
