### ISSUE TITLE
Don't close tabs when extension is removed

### ISSUE THREAD

**Issue by Anusien** [deanoemcke/thegreatsuspender#515]
It would be really nice if this wouldn't close your tabs when the extension is removed.

**Comment by EvanBG42** [comment]
As much as I like this, the suspended pages appear to just be extension pages with a URL added on. I doubt it's possible because the suspended pages *are* the extension.

**Comment by TCAllen07** [comment]
This request is all the more necessary given the vulnerability/hack that occurred in the last couple days, though kudos to @deanoemcke and other contributors for being aware of and working on the issue in a timely manner. 

I strongly encourage investing effort in this task/Issue -- the sudden removal of the extension has resulted in a large amount of lost history by my team and substantial lost productivity. I'm not intending to criticize or blame -- this Chrome extension has been _really_ great -- just lending all the support I can urge to addressing this shortcoming to prevent future problems.

**Comment by faphdev** [comment]
Hmm, can someone please enlighten me with some background? What vulnerability/hack occurred, and what does it mean that the extension was removed?
I lost a lot of history, thinking it was my computer.... Is there a way to reload all tabs at once? thanks!

**Comment by Anusien** [comment]
You can re-enable the extension and restore the session in settings.

**Comment by Tallinu** [comment]
I'd thought what just happened to me was an issue with the update that popped up when I started up Chrome a few minutes ago, but it sounds like something else may have been involved. It would be nice to know exactly what happened, but it was _even nicer_ to learn that the dozens of suspended tabs I'd had open when I last shut down Chrome could be reopened -- I didnt' even realize this thing had that capability. Thank you very much (and to Anusien for mentioning that feature)!

**Comment by alidan** [comment]
As far as I am aware, when session buddy crashes, or at least when it crashed for me a few times, it didn't kill tabs, it just stopped working correctly and all I had to do was delete the suspended stuff to get the tab back.

there should be a way to deal with tabs in a better way.

Thankfully both of these things happened while I was away so I was not actively doing shit, so a backup from thread outliner allowed me to get back to square one, but its annoying it came to that at all.

**Comment by deanoemcke** [comment]
Please refer to this guide on why this happens and how to recover lost tabs: #526
