### ISSUE TITLE
turned javascript off and shut down ... lost tabs

### ISSUE THREAD

**Issue by JimJJewett** [deanoemcke/thegreatsuspender#517]
I have sometimes been turning javascript off to regain responsiveness.
Recently, I shut down and rebooted while javascript was still off.  Upon restore, the suspended tabs were no longer available, even in history.  (Based on the timing, there may have been some interference from the Google shutoff/upgrade, but I did not take any manual steps to turn it on/.off/upgrade, and it claims to now have 6.30 active.)

**Comment by deanoemcke** [comment]
Javascript is most definitely required for the extension to function at all. Suspended tabs will simply not display without it. I do not recommend turning off javascript if you intend to also use this extension.
However, reenabling javascript should cause everything to return to normal.
