### ISSUE TITLE
"Suspend All Tabs" missing from right-click menu in 6.3

### ISSUE THREAD

**Issue by JesterZero** [deanoemcke/thegreatsuspender#518]
I'm pretty sure it was there in 6.21 and 6.22, but I wouldn't swear to it.

Steps to reproduce:

1) Right-click on The Great Suspender icon in chrome toolbar
2) "Suspend All Tabs" option is missing

**Comment by deanoemcke** [comment]
It has been renamed to 'suspend other tabs'. It functions the same, except that it won't suspend the currently active tab (not sure if it ever did actually),
