### ISSUE TITLE
Suspended tab doesn't automatically unsuspend after closing another tab

### ISSUE THREAD

**Issue by sunspeck** [deanoemcke/thegreatsuspender#519]
The latest update to this great extension seems to have introduced a bug / removed a desirable behavior.

I have it set to "Automatically unsuspend tab when it is viewed."

Previously, this would unsuspend tabs when they are clicked on, and also unsuspend a newly focussed tab when the previous tab is closed (via keyboard shortcut or [X] button).

The new update will no longer automatically unsuspend the next tab when a tab is closed.  To unsuspend the next tab I must manually switch away from it and then switch back.

I found the original way this was handled to be much more intuitive, useful, and effective.

Thanks!

**Comment by poulhansen** [comment]
It's the same here although sometimes it works.
It happened after my screen showed an "update" to the program.

**Comment by deanoemcke** [comment]
I have updated the issue title to be more specific as it looks like clicking on a suspended tab does automatically unsuspend it. It is only failing when a tab is closed and a suspended tab is shown in its place.

**Comment by deanoemcke** [comment]
lol. i just came across this other issue which tidying up: https://github.com/deanoemcke/thegreatsuspender/issues/114

it requests that suspended tabs that gain focus after anther tab is closed should *not* automatically unsuspend. i agreed with the user at the time, hence the change in functionality.
it's not a bug, it's a feature!

i guess the long-term solution is to have this as a configurable option.

**Comment by sunspeck** [comment]
Hi, I only realized after I posted this what you were already dealing with regarding the security issue, yikes.

After living with this new behavior for a few days, and turning on the screen capture function to cope with it, I can sorta see how it would be desirable at times.  But a configurable option allowing auto-unsuspend after tab close would definitely be enjoyed by those of us who open a stack of tabs to read the morning news.

Anyway, many thanks for this fine plugin which has saved my Macbook from a most certain heat death.

**Comment by acidlung** [comment]
I agree with sunspeck that the previous behavior (automatically unsuspending focused tabs rather than forcing a click) was more intuitive.  Since I usually have 20 tabs open and am doing research, when I revert to a suspended tab, I almost always want to view it.  Admittedly, that is MY personal workflow and my style is probably in the minority.  That said, I'm the type of user that realizes huge benefits from your excellent extension and doesn't mind diving into the settings screen to really dial things in.  Others obviously have a different use case.  
I enthusiastically agree that making this behavior into a setting would be hugely helpful for me and make all parties happy.  Also it should likely default to the current behavior since users seem to prefer it, judging by the fact that only a few have filed an issue since you changed it.

**Comment by smilejack1** [comment]
My work habits are like acidlung's, and would greatly prefer either a reversion to the previous behavior or to have such behavior as an option.  As much as I appreciate this extension, it is much less helpful to me than it was.

**Comment by deanoemcke** [comment]
After some deliberation, I have decided to revert this functionality back to how it used to be. Any suspended tab that gains focus will now automatically reload, regardless of whether the focus was gained via the closing of another tab.
The main reason for this decision was consistency. It appeared to be too much like a bug the way it currently operated. And I'm not sure the number of people in favour or against this feature is significant either way.

**Comment by poulhansen** [comment]
THANK YOU for your time.

Poul Hansen

May you enjoy Peace and Happiness!
Give time, the most precious gift.
Make the world better, stop Anger and Greed

**Comment by draarong** [comment]
@deanoemcke I'm really glad you decided that a tab gaining focus after another tab is closed should be automatically unsuspended...But it doesn't seem to work for me! Has something changed w/more recent versions of MacOS or Chrome?

**Comment by mcmasjc3** [comment]
I never have seen it work.  I figured Dean changed his mind.


Jim McMaster
mailto:jim.mcmaster@gmail.com

**Comment by smilejack1** [comment]
Has never worked for me, either.

**Comment by draarong** [comment]
Hey @deanoemcke , did you know that this function isn't working, at least on MacOS?

**Comment by mcmasjc3** [comment]
Or on Windows 10.


Jim McMaster
mailto:jim.mcmaster@gmail.com

**Comment by deanoemcke** [comment]
@draarong @mcmasjc3 @smilejack1 
really? it seems to work for me?
just to confirm:
- you have 'Automatically unsuspend tab when it is viewed' checked. 
- you visit a suspended tab by clicking on it.
- it automatically unsuspends.
- you close that tab and chrome brings another suspended tab in focus.
- this tab **does not** automatically unsuspend?

this is working fine for me on v7.0.90. ie: it **does** automatically unsuspend the tab in the last step.

can each of you please go through the above steps and confirm that this does not work? and also record the version of the extension you are using?

thanks!

**Comment by mcmasjc3** [comment]
It does indeed work.  Thank you.  I checked the Settings several times to
see if there was an option that enabled this behavior.  The last time I
checked it was not there.


Jim McMaster
mailto:jim.mcmaster@gmail.com

**Comment by mcmasjc3** [comment]
I take it back. It works on my Linux machine at work, but not on my Windows
10 laptop. The case might be a bit different, though. I have several tabs
open and am working through them, closing them as I go. Eventually, some of
the tabs suspend while I am reading the article in the focused tab. When I
close that one, the newly-focused tab does not unsuspend.


Jim McMaster
mailto:jim.mcmaster@gmail.com

**Comment by t0m05** [comment]
> it requests that suspended tabs that gain focus after anther tab is closed should not automatically unsuspend. i agreed with the user at the time, hence the change in functionality.
it's not a bug, it's a feature!
> i guess the long-term solution is to have this as a configurable option.

> After some deliberation, I have decided to revert this functionality back to how it used to be. Any suspended tab that gains focus will now automatically reload, regardless of whether the focus was gained via the closing of another tab.
> The main reason for this decision was consistency. It appeared to be too much like a bug the way it currently operated. And I'm not sure the number of people in favour or against this feature is significant either way.

I recently got the update and think TGS is generally one of the greatest extensions I use.
However, when it comes to this issue, I have to say I prefer the previous functionality. I don't see why closing one tab should unsuspend the next (unrelated) tab to get focus.
I accept that others have voiced a different opinion based on their workflow, so I would be all for it being a configurable option.

**Comment by t0m05** [comment]
> @t0m05 i have created a new issue requesting the ability to make this a configurable behaviour: #747

Thanks! 👍

**Comment by mcmasjc3** [comment]
This still doesn't work for me on the latest version of Chrome on Windows.
It works fine on Linux and Mac.


Jim McMaster
mailto:jim.mcmaster@gmail.com

**Comment by deanoemcke** [comment]
@mcmasjc3 Can you please check a few things for me?
1. Tell me the version of TGS you are using
2. Ensure 'Automatically unsuspend tab when it is viewed' is checked
3. Open a new chrome window and navigate to a website and then suspend that tab while looking at it
4. Create a new tab in that same window (so you have just 2 tabs in that window) and then close it again immediately.
5. Confirm that the suspended tab unsuspends automatically (or not :/ )

Thanks :)

**Comment by mcmasjc3** [comment]
The version I had on my Windows machine is v6.30, which is much lower than
the one I have on my Mac at work.  I removed and re-added the extension and
now I have v7.0.109.  That was the problem.  I don't know why TGS wasn't
updating automatically.

Thank you, and sorry for the trouble.

Jim McMaster
mailto:jim.mcmaster@gmail.com
