### ISSUE TITLE
No longer unsuspends when viewed

### ISSUE THREAD

**Issue by adefaria** [deanoemcke/thegreatsuspender#523]
The "Automatically unsuspend tab when it is viewed" suddenly no longer works.

Version: 6.30

**Comment by poulhansen** [comment]
It's the same here although sometimes it works.
It happened after my screen showed an "update" to the program.

**Comment by deanoemcke** [comment]
Duplicate of: https://github.com/deanoemcke/thegreatsuspender/issues/519
