### ISSUE TITLE
Cannot remove right-click context menu

### ISSUE THREAD

**Issue by deanoemcke** [deanoemcke/thegreatsuspender#527]
(from external source)

as of version v6.30, I cannot remove The Great Suspender from my right-click context menu.  There is a permanent "Open link in suspended tab" item there.

The "Add The Great Suspender to right-click context menu" checkbox is unchecked, and has always been.  I also tried cycling it, and uninstalling / reinstalling the extension.  No matter what I try, "Open link in suspended tab" is always in the right-click context menu.

Any ideas?  My system:

Chrome Version 59.0.3071.86 (Official Build) (64-bit)
Model: MacBook Pro (15-inch, Retina, Mid-2012)
CPU: Intel Core i7-3720QM (8 Threads, 4 Cores) @ 2.60 GHz
Memory: 16.00 GB
Graphics: Intel HD Graphics 4000, NVIDIA GeForce GT 650M
Screen Resolution: 1440 x 900 (HiDPI Mode)
OS: OS X El Capitan (Version 10.11.6, Build 15G1421)

**Comment by deanoemcke** [comment]
Unfortunately it seems that my implementation of "Open link in suspended tab" does not obey the "Add The Great Suspender to right-click context menu" checkbox.
Also, I'm finding weird behaviour on right click of links. Sometimes it gives me an entire menu of choices, and other times just the single "Open link in suspended tab" option.

**Comment by jhuckaby** [comment]
Thanks Dean!  FYI, it was me!  I am the external source! ;)

**Comment by DAOWAce** [comment]
I noticed this after upgrading to 6.30 too.

Bit annoying.  I only have select things in that menu, and this is not something I want there.

**Comment by adrianis86** [comment]
Hi there. Will this fix be promoted to stable sometimes soon?

**Comment by adrianis86** [comment]
Hi there. Will this fix be promoted to stable sometime soon?

**Comment by rxbasu** [comment]
Adding to this... I noticed after a recent upgrade to the extension that I had TWO "The Great Suspender" context options appear on right click to get the context menu. I assume that one of them was from the previous version. In an effort to clean things up, I've removed the extension (I'll put it back!), but... There's still a Great Suspender item in the context menu. **And it works**, which is confusing since the extension is theoretically removed. Thoughts?

**Comment by deanoemcke** [comment]
@rxbasu Is it possible you've just hidden one installation from the menu bar?
if you go to chrome://extensions can you see a version of TGS there?

**Comment by rxbasu** [comment]
Thanks for the quick response, @deanoemcke. No, TGS has disappeared from my list of installed extensions. That's why it seems so funky that it still shows in the context menu, and is functional.

**Comment by rxbasu** [comment]
@liamjohnston yep, that's what I'm looking at. Interestingly, I've realized/rememberd that I can get to the settings for TGS by clicking on the link in the lower right corner of any suspended tab. So, basically, the extension seems to be installed in a kind of "stealth" mode.

@deanoemcke I forgot to specify that this is on a Mac running High Sierra. I'm using Chrome version 71.0.3578.98 (Official Build) (64-bit). And TGS itself is v7.0.131.

**Comment by deanoemcke** [comment]
@rxbasu that's super weird. sorry but i'm not sure i'll be able to help you much with this. it seems like some kind of chrome bug. 

you can try deleting the extension files manually from your filesystem.
if you open up the settings page for the extension, it should show you the extension id in the url. if you do a search for this id on your filesystem you should be able to find out where the extension files are being stored on your computer.

**Comment by rxbasu** [comment]
FWIW, manually removing the extension files seems to have, oddly, made the extension appear in chrome://extensions/, but at the top of the list rather than alphabetically where it belongs. Whatever. It's working and I'm happy. Thanks!
