### ISSUE TITLE
Hacked version causing url redirects?

### ISSUE THREAD

**Issue by smayer97** [deanoemcke/thegreatsuspender#528]
I have had a strange problem during this hacked period. During the same days that this has occurred, I started to get my Yahoo mail redirected to survey sites. Thought my browser was compromised. As soon as the extension was updated, the problem seems to have gone away.

Strange this is that only that affected the tab that had Yahoo Mail. Checked my other browsers (a couple of version of Firefox) and did not run into this issue; only in Chrome. 

Thinking this was a problem I my side I restored my Mac OS twice and still had the problem.

Anyone else run into this? Because of the timing of the start and stop of this I am wondering if the extension had been hacked to inject redirecting code?

**Comment by smayer97** [comment]
Maybe I spoke too soon...problem is still occurring... :frowning_face:

**Comment by deanoemcke** [comment]
I personally checked the code of the 'hacked' version and there was no alteration to the behaviour of the extension in any way. It really sounds like you've got some malware on your computer from somewhere..

**Comment by smayer97** [comment]
thanks for the feedback...I'll keep investigating...
