### ISSUE TITLE
General Bugs/Feature Requests/Feedback

### ISSUE THREAD

**Issue by matthewkol186** [deanoemcke/thegreatsuspender#53]
- I hate the whole blurry icon thing. Seriously, it really bugs me.
- Text that is too long often spills off the yellow slab
- Can you differentiate the three pieces of information by color? Like, the top rectangle is the title of the website, the middle rectangle is URL, and bottom is click to reload, etc.
- I know the whole "website capture" thing is still in beta, but please please please work on this! If you do this well enough, you might be able to entirely eradicate the blurry icon!

Overall, amazing job. Keep up the great work!

**Comment by deanoemcke** [comment]
The latest gitHub version has made significant changes to the visual UI. I hope it's more to your liking! It will be released to the webstore shortly.
