### ISSUE TITLE
In certain situations, tabs no longer automatically unsuspend on focus

### ISSUE THREAD

**Issue by acidlung** [deanoemcke/thegreatsuspender#532]
I'm running Chrome 58.0.3029.110 (64-bit) and Great Suspender 6.30.  I have been running GS now for a couple of years.  I have always enabled the option "Automatically unsuspend tab when it is viewed".  About 3 weeks ago, the behavior changed in a minor way.  Typically, I have 20 tabs open (numbered 1 to 20, left to right).  Let's say that I return to my computer and all tabs are suspended.  

If I click on the heading of tab 3, it will unsuspend, as expected.  However, let's say I instead open another tab right way, that's tab 21.  Then I close tab 21, now exposing tab 20 WITHOUT actually clicking on it, just giving it focus.  Tab 20 will not unsuspend unless I click somewhere in the BODY in that tab.  Previously, it would immediately unsuspend upon focus.

Obviously, this is not the end of the world, but it sure was a slick user experience the way it worked before.  I tried to be clear, but if you need a video of the behavior, I can supply it upon request.  Thank you for creating and maintaining such an incredible browser enhancement.  I have a low-powered ultrabook and this critical extension makes every day of my life better!

**Comment by liamjohnston** [comment]
Duplicate of #519 

It now seems that some people like it the way it worked before, while in the past others had requested it work the way it works now. 

The current behaviour is the intended behaviour. Personally I feel the current behaviour is better (leaving suspended tabs suspended if they aren't *explicitly* focused). If you felt strongly you could add a feature request to make this behaviour configurable I guess?

**Comment by acidlung** [comment]
Sorry for the duplicate issue report.  Thank you for letting me know it was intended behavior.  I'll move further discussion to #519.
