### ISSUE TITLE
Capture entire page does not

### ISSUE THREAD

**Issue by Pascal666** [deanoemcke/thegreatsuspender#533]
For longer pages, the Capture entire page option does not actually capture the entire page.  The bottom is missing.  Some examples:
http://www.illinoiscourts.gov/SupremeCourt/Rules/Art_III/ArtIII.htm
https://www.bloomberg.com/features/2017-the-ether-thief/

**Comment by deanoemcke** [comment]
Similar to this issue: https://github.com/deanoemcke/thegreatsuspender/issues/554
For performance (memory) reasons, I have a limit to the length that an screen capture image can be.

**Comment by deanoemcke** [comment]
Actually, this limit has a practical side too. An image greater than a certain size cannot be converted to a dataUrl which is what i use to store the captured screenshot on disc.
