### ISSUE TITLE
On a QHD/4K Display, mouse should correctly track popup

### ISSUE THREAD

**Issue by hugodahl** [deanoemcke/thegreatsuspender#534]
In Windows (10, Anniversary Edition/ v1607 at least), when using Chrome on a QHD/4K display, which isn't set as the primary, the mouse does not correctly track items in the popup. It is off by a factor of 2, which is the scaling factor I set for this display (200%).

This makes clicking some of the links extremely difficult in some cases, and impossible in others, since the popup, rightfully, does nor and/or can not track the mouse location, since it's "off the document". The only way, for now, to be able to use the popup is to move the browser window (or just the tab) to an unscaled display.

I intend to look into this issue when time permits, but wanted to have it noted here in case others experience the same behaviour. I will also attach visuals/screen shots comparing the behaviour differences between the standard and high DPI monitor.

**Comment by hugodahl** [comment]
Screenshots displaying the different behavior between standard and 4K display

## 4K Display ##

### These should both be activating the `:hover` state of the "Suspend" menu item ###
![Popup open, pointer on the "Suspend" line (should trigger `:hover` state)](https://user-images.githubusercontent.com/757374/27150323-677d390a-510c-11e7-883e-96b12b48a356.png)

![Popup open, pointer immediately over the "Suspend" text (should trigger `:hover` state)](https://user-images.githubusercontent.com/757374/27150325-69c7cfa4-510c-11e7-9b6b-a3283c1a0bab.png)


### This actually activates the `:hover` state, however, the pointer is over the "Never Suspend" menu item ###

![Popup open, pointer over "Never Suspend", but "Suspend" menu item's `:hover` state is active](https://user-images.githubusercontent.com/757374/27150326-6c9c0466-510c-11e7-9be8-f05ea3b1bc32.png)

## Standard Display ##
This displays the behaviour that is expected on any display - the `:hover` state is activated for the line over which the pointer is placed.

![Popup open, pointer over "Suspend", with "Suspend" link hover active](https://user-images.githubusercontent.com/757374/27150328-6eda046c-510c-11e7-843e-3b24c61391ea.png)

**Comment by liamjohnston** [comment]
It looks like this may not be specific to TGS. Lots of other people with the same issue with your setup and chrome extensions generally:
https://productforums.google.com/forum/#!topic/chrome/tyzywUJfkQI

Seems like a Chrome issue.

There are some _workarounds_ in that thread.

**Comment by liamjohnston** [comment]
Also tracked in Chromium here: https://bugs.chromium.org/p/chromium/issues/detail?id=715552
