### ISSUE TITLE
suspended tabs don't update titles and favicons when they change

### ISSUE THREAD

**Issue by adcurtin** [deanoemcke/thegreatsuspender#539]
If a facebook tab gets suspended when there are notifications, the suspended version will forever have the notifications in the title. If the tab is unsuspended, the title updated, and then resuspended, it will still display the original notification count.

More subtly, I think the same is true for the favicon. Reddit Enhancement Suite badges the favicon with an unread message count. I think this was behaving in the same way as the title, though it's been a while so I may be misremembering.

Also note this was before all the recent updates, on version 6.15 I think.

**Comment by deanoemcke** [comment]
@adcurtin Can you confirm this is still happening on the latest version? (v6.30).
I am unable to recreate it at my end. If i change the number of unreads in my gmail inbox and resuspend, the favicon and title both update to the new contents.

**Comment by adcurtin** [comment]
I tested both gmail, with a dynamic tab title, and reddit with reddit enhancement suite (maybe an old version of RES), with a dynamic favicon, and neither still had this problem.
