### ISSUE TITLE
Some tabs automatically unsuspend

### ISSUE THREAD

**Issue by BlueRayONE** [deanoemcke/thegreatsuspender#540]
In the settings I have deactivated the option "Automatically unsuspend tab when it is viewed". Nevertheless suddenly some tabs get unsuspended when I open them. Yes, this happens only with **some** tabs, not everyone! Can't find a pattern, there is also no correlation with my whitelist.

Can I provide any further information like logs?

**Comment by deanoemcke** [comment]
Sorry for the delayed response on this. Are you still having the issue? Are you on the latest version (v6.30)? And finally, does it happen after a chrome restart?
Oh, and is there any chance you have two versions of the extension installed?
Once I have this information, I might be able to do some more debugging.
