### ISSUE TITLE
New feature: option to view URL in the suspended page

### ISSUE THREAD

**Issue by Omar-Elrefaei** [deanoemcke/thegreatsuspender#546]
It is really hard to differentiate between tabs with the same favicon (same site)
And my RAM can't actually afford enabling the screenshot option (also, it is kind of crappy)

**Comment by Omar-Elrefaei** [comment]
It is really hard to differentiate between tabs with the same favicon (same site)
And my RAM can't actually afford enabling the screenshot option (also, it is kind of crappy)

**Comment by deanoemcke** [comment]
This is a duplicate of: https://github.com/deanoemcke/thegreatsuspender/issues/309
Please add your input there to help keep the feature request consolidated.
