### ISSUE TITLE
chrome memory usage still high

### ISSUE THREAD

**Issue by allanlaal** [deanoemcke/thegreatsuspender#549]
chrome task manager reports memory usage of 13GB, of which 170MB is used by The Great Suspender

However when I add all the tabs and extensions together they sum up to ~7GB.

Is it possible that some information is still kept in RAM by Chrome after TGS suspends a tab?

**Comment by deanoemcke** [comment]
It is possible. Tbh i'm not that familiar with the internals of chrome's memory management. And perhaps the there is also some peculiarities in how the task manager reports on memory usage too. I vaguely recall an article from Google that mentioned accurate memory reporting is very hard to achieve.

The method used to suspend tabs by this extension is simply the most effective method I could find (that is, to redirect the tab to an internal extension url). If you are able to find a better method, or to provide some repeatable process for a tab not being released from memory, then I can try to improve from there.

**Comment by allanlaal** [comment]
yeah, Chrome sucks :(

I find that I need to kill and restore all tabs periodically, since it will grow to eat up all of my 32GB of ram within mere days and will always report using i.e. 13GB in Chrome task manager, when its really using ≥27GB

**Comment by deanoemcke** [comment]
Merging this issue into: https://github.com/deanoemcke/thegreatsuspender/issues/613
