### ISSUE TITLE
Extension gets disabled with message "This extension has been corrupted"

### ISSUE THREAD

**Issue by jaug1337** [deanoemcke/thegreatsuspender#551]
As the headline reads, the issue I have encountered, only on my main workstation, is a random corruption. 

The first time, I lost 40 tabs, but going through my history I managed to recover a few. 

The second time, I lost 6 tabs, however, the exact same problem occurred. I was met with the extension disabled, and with a red message reading (when in the extensions tab) "This extension has been corrupted." 

Any help would be greatly appreciated.

**Comment by jaug1337** [comment]
Quick update, it seemed to have crashed, not corrupted, on my Chromebook too, luckily I was able to recover it all. The WS is a Windows machine. I am getting slightly confused here. 

This has never happened before, and I am in no position to lose my tabs on my Chromebook.

**Comment by jaug1337** [comment]
And here we go again, the third time it has corrupted itself. Great.

**Comment by deanoemcke** [comment]
I have never come across an error like this before. Is the exact error message you're getting actually "This extension may have been corrupted" ?
Some googling does not reveal much. I assume you have tried uninstalling and then reinstalling the extension (make sure you unsuspend all tabs before doing this) ?
Is it possible your copy of the extension is somehow being modified locally?

**Comment by MrHappymoose** [comment]
Just want to say I've had the exact same issue with the same results and error messages. If I'm researching something I'll often have a lot of tabs open at once so this is a real issue for me as I've always been able to rely on TGS. It didn't even save the tabs in the session management.

**Comment by jaug1337** [comment]
@deanoemcke yes that is the exact message. 

I have tried uninstalling and reinstalling with no success, I have not seen any indication of my Chrome extensions being modified locally. 

I did, however, try to reinstall Chrome, so let's see if that helps - I just export tabs at random times, just to be sure. 

Thanks for the help.

**Comment by deanoemcke** [comment]
There is another issue reporting extension corruption: https://github.com/deanoemcke/thegreatsuspender/issues/559
This person has suggested that it was their anti-virus that was corrupting the extension. I guess it is incorrectly identifying the extension as being malicious and then altering the extension files.

@jaug1337 Do you have any anti-virus installed? Could this possibly be the cause for you?

**Comment by jaug1337** [comment]
It seems there was an issue with Chrome. 

I did a clean reinstallation which fixed it.

**Comment by Pascal666** [comment]
This Chrome bug has affected a number of plugins.  Clicking repair in chrome://extensions/ will delete all of the extension's data (saved sessions, settings, etc.).  Unfortunately, that is the only option given there.

Work-around is to visit the extension in the Chrome store.  There will be a note at the top of the screen saying "This item has been disabled in Chrome. Enable this item".  Click on Enable and the extension will work again with no data loss.

It would be nice if TGS synchronized data via the chrome.storage API or similar, so the loss of local data was not irrevocable.

**Comment by YourContentEditor** [comment]
Hi, I'm afraid this issue isn't gone. Having the same problem repeatedly. Will add screenshots on next instance. LMK what details you need.
