### ISSUE TITLE
After the error 400 on youtube with 40 cookie, we get the infinite loading with 70 cookie on store.playstation.com

### ISSUE THREAD

**Issue by H0R1Z0N** [deanoemcke/thegreatsuspender#552]
Seriously, how much time until this motherfucking bug of a cheap hack to put position in cookie get fucking fix. Not only youtube require me to clear his cookie 2-3 times a day, now i also have to do it with sony's psn store since i have ocd problem on spending on digital license. It has been 2 fucking month, if it's not fixed soon, i will publish an older version on chrome store since i don't give a crap about copyright and license. 2 month for an easy fix or simply a version downgrade should be fucking easy. You are going to lose all the user base if this don't get fixed soon.

**Comment by deanoemcke** [comment]
A fixed has been committed. A webstore update should follow soon. Still not sure if it will be an automatic update of if it will require a reinstall to upgrade.
https://github.com/deanoemcke/thegreatsuspender/issues/552
