### ISSUE TITLE
'Suspend other tabs' overrides 'do not suspend' settings

### ISSUE THREAD

**Issue by crafty-geek** [deanoemcke/thegreatsuspender#553]
Currently "suspend other tabs" suspends all other tabs, regardless of whether they qualify as "never suspend this site" as well.  This is a useful feature sometimes, especially because "suspend other tabs" seems to be window-specific - sometimes I might want to literally have only 1 tab open.

However, when I'm in my "media" window and a video autoplays somewhere other than where I'm watching, I use "suspend other tabs" to kill the rogue video, BUT this makes me lose the now-playing state of my music streaming service (that doesn't do scrobbling to a text document or keep a playback history).

Could we get a way to run the auto-suspension on command, so that "never suspend" sites are respected?  Ideally not as a replacement for the current behavior, but as a supplement?  Maybe that becomes "suspend level 0," and "never suspend this tab" ignoring becomes "suspend level 1"?  Would it be too feature-creepy to consider giving sites "persistence levels" or something so you can have more than 2 levels?

**Comment by crafty-geek** [comment]
ALSO just tested on chrome webstore version (figuring out how to update to the github build is a tomorrow task...) - suspend other tabs seems to stomp on the "don't suspend audio tabs" setting if I have it enabled (as a workaround to see if I can limit autoplay-hunting by suspending tabs that haven't started to autoplay but might; also helps keep good audio active).  Unless the way it respects "don't suspend audio tabs" is with a "do you want to navigate away from this site" message allowing you to stop the suspension...

**Comment by deanoemcke** [comment]
This is closely related to issue: https://github.com/deanoemcke/thegreatsuspender/issues/329

I have decided to treat this as a bug. As it seems more intuitive to me that the 'suspend other tabs' button should respect the users automatic suspend settings. In a few particular cases, not doing so has a significant negative impact, such as:
1) Suspending a tab that is receiving form input. This could result in loss of user input content.
2) Suspending a tab that is playing audio. This could result in music/audio stopping.
Other use cases are less severe.

**Comment by deanoemcke** [comment]
This has been implemented in commit: https://github.com/deanoemcke/thegreatsuspender/commit/78b7fa5005db87fff2d4189d27717490fdd0fce6

The 'suspend other tabs' button will now respect whitelist, temporary whitelist, form input, pinned tabs, and audible preferences.
