### ISSUE TITLE
Crash on load, Chrome Dev

### ISSUE THREAD

**Issue by aeshildr** [deanoemcke/thegreatsuspender#556]
Hi there,

Great suspender 6.30 is crashing on load for Chrome Dev Version 61.0.3155.0 (Official Build) canary (64-bit)

I've tried updating chrome, removing and reinstalling, and clearing cache & app cache.

**Comment by deanoemcke** [comment]
@aeshildr are you still having this issue? I have tried on OSX with chrome dev (Version 61.0.3159.5 (Official Build) dev (64-bit)) and it seems ok?
This is with v6.30 of the extension.

Please let me know if I need to investigate this further.

**Comment by aeshildr** [comment]
Thanks - it eventually stopped. I think there was another update :)


----- Original message -----
