### ISSUE TITLE
Session Managemen all gone

### ISSUE THREAD

**Issue by kelfmv4** [deanoemcke/thegreatsuspender#558]
Current session:

Recent sessions:
Saved sessions:

all gone lost all 

update is VERY great!!
one and half year 
all my tab...

**Comment by deanoemcke** [comment]
I'm really sorry. Please see this issue for another person in the same situation: #468

**Comment by acetriper** [comment]
experiencing the same problem atm on chrome mac,
looking for a solution to restore my lost sessions

**Comment by deanoemcke** [comment]
If you are having issues with lost SAVED sessions, please refer to: https://github.com/deanoemcke/thegreatsuspender/issues/464
If you are having issues with no entries for CURRENT and RECENT sessions, please refer to: https://github.com/deanoemcke/thegreatsuspender/issues/659
