### ISSUE TITLE
Uninstall causes Chrome to crash

### ISSUE THREAD

**Issue by sixside** [deanoemcke/thegreatsuspender#56]
After several attempts to disable the extension, I instead tried to just uninstall. Clicking Uninstall also caused Chrome to crash. When it restarted the extension was no longer listed as installed -- so I guess it sort of worked.

**Comment by deanoemcke** [comment]
Related to issue #55 Chrome browser crash on disable.
Would be interested to know if this behaviour is still being experienced. Anyone run into a similar issue?
