### ISSUE TITLE
Disappearing Context Menu

### ISSUE THREAD

**Issue by nekosaurus** [deanoemcke/thegreatsuspender#564]
Started noticing this a couple months ago. Great Suspender isn't even listed in the context menu during normal browsing. It shows up in incognito and after a browser restart but it disappears forever after a few minutes or so until a new restart is applied. I use Chromium 59.0.3071.109 (Official Build) (64-bit) if it helps.

**Comment by deanoemcke** [comment]
There is some known issues with the context menu functionality in the current webstore version of the extension: https://github.com/deanoemcke/thegreatsuspender/issues/527
Although this is not exactly the same issue as you are reporting. There should be a new test build available later this week. Would you be interested in trying it out to see if it resolves the issue?

**Comment by nekosaurus** [comment]
I'd like that, thank you! I think it might have to do with opening incognito for the first time while great suspender is allowed in incognito. I guess it sort of "transfers" the context menu over to incognito mode?

**Comment by MattSuda** [comment]
The Great Suspender menu has been missing from my right click menu for a few months now. It only shows in incognito windows. Really annoying. Using Chrome 60.0.3112.101 (Official Build) (64-bit) right now.

**Comment by deanoemcke** [comment]
@nekosaurus thank you for explaining that info about the incognito window. that is indeed the problem! i have fixed this and it will be released in the upcoming version.
@MattSuda until then, you should be able to restore your context menu by unchecking (and saving) and then re-checking (and saving) the "Add The Great Suspender to right-click context menu" option.

**Comment by Jollfye** [comment]
The Great Suspender 6.30 is [missing](https://imgur.com/S2CcNu3) in right-click context menu when it's [enabled](https://imgur.com/vC9ROrG) in options, and TGS extension was always disabled in incognito mode, never tried to enable it there.. also option to "Open link in new suspended tab" [works](https://imgur.com/IP9ICQq) properly, (+feature request? to add usual context menu into URL right click, maybe right after "Open link...", cos sometimes I'm clicking on url with intention to suspend the current tab, not to open that url in a new one), soo it's just main TGS menu disappeared several dev chrome versions ago, re-checking (and saving) "Add The Great Suspender to right-click context menu" doesn't help, using now latest [chrome 63.0.3213.3 (Official Build) dev (64-bit)](https://imgur.com/kprIMwm).. if issue is fixed, is there any pre-release build I could use? so annoying, oh n I'm on windows 10.. well, anyway, thank u, love ur extension, @deanoemcke ^_^

**Comment by deanoemcke** [comment]
@Jollfye Thanks for the info. I've made a lot of changes to how the right-click context menu is built in the upcoming version (v7.x). I'm going to just hope that this resolves all the issues as I'm unable to replicate your issue in v6.30. 
There is a pre-release version you can use. See the "Install as an extension from source" section of the readme for installation instructions. Bear in mind this is an alpha release (currently) but it should be reasonably stable.
