### ISSUE TITLE
Tabs crashing

### ISSUE THREAD

**Issue by mikeshultz** [deanoemcke/thegreatsuspender#565]
Suspended tabs are crashing.  Chrome ends up asking for kill/wait.  Tabs show only a blue background.  This may happen when cycling through tabs quickly.  

Seen on Chromium 59.0.3071.109 and TGS version 6.3.  

I didn't find any stored logs in the extension directories, so let me know if there's more information I can provide.

**Comment by deanoemcke** [comment]
@mikeshultz Are you still having this issue? Can you send me a screenshot of a crashed tab? Is it all suspended tabs that crash or just one every now and then?

**Comment by mikeshultz** [comment]
Happened twice the day I posted this, but not since.  Don't think it can be blamed on resource usage or anything, since this was the only thing affected.  If/when it happens again, I'll get a screenshot and maybe see if there's anything in the console.  

And to be clear, it's not just one crashed tab.  When it happens, all suspended tabs crash.

**Comment by deanoemcke** [comment]
Ah ok. The tabs crash, but they do not disappear (ie. are not removed from chrome)?
Interesting, this means that the extension itself has not crashed. I have seen this happen occasionally, but always very sporadically.

**Comment by mikeshultz** [comment]
Correct, the tabs do not disappear.  Restarting chrome will bring everything back.

**Comment by mikeshultz** [comment]
For whatever it's worth, I haven't seen this since the summer.  Perhaps it was a bug with Chromium that has since been resolved?
