### ISSUE TITLE
Feature Request: Keyboard shortcuts: Suspend all *unpinned* tabs in active window

### ISSUE THREAD

**Issue by amcmillion** [deanoemcke/thegreatsuspender#567]
I often have multiple pinned tabs in a window that I want to leave open while I suspend other tabs to save system resources. My current flow has me suspending all other tabs, then unsuspending the pinned tabs one-at-a-time. Please add a keyboard shortcut (or a function in general) to suspend tabs on command filtering on the pinned/unpinned criterion.

**Comment by deanoemcke** [comment]
Please refer to this issue: https://github.com/deanoemcke/thegreatsuspender/issues/553
In the upcoming release, suspend other tabs will now respect the 'dont suspend pinned tabs' preference.
