### ISSUE TITLE
Set a limit for suspending  taps

### ISSUE THREAD

**Issue by ljhui** [deanoemcke/thegreatsuspender#570]
Nice extension, I love it! I want to suggest a new feature, when there are few tabs ,I don't like to auto suspend them. can you add a option setting which set a limited tap number or a limited RAM consumation
for the extension, only the number of taps or RAM consumation exceed the limited, it works and suspend the taps according to some rules, for example ,RAM consumation or the tap created time. once the number of  taps under the limit or RAM consumation has reduced  until below the limit, it stops suspending tabs.

**Comment by deanoemcke** [comment]
These ideas already exist as issues.
For allowing a limited number of tabs to remain unsuspended: https://github.com/deanoemcke/thegreatsuspender/issues/136
For suspending based on a memory limit: https://github.com/deanoemcke/thegreatsuspender/issues/223
