### ISSUE TITLE
Sometimes "suspend this tab" option stops working

### ISSUE THREAD

**Issue by SnIPeRSnIPeR** [deanoemcke/thegreatsuspender#574]
Hi. I have a problem with "The Great Suspender" extension. Sometimes "suspend this tab" option stops working for no reason. I am trying to tap on this button and nothing occurs. If I restart the browser, that option works fine, but after 30-60 minutes stops working again. This bug was appeared in one of the latest Google Chrome updates..

I am using Google Chrome v. 60.0.3112.113 x64 on Windows 10 LTSB.

P.S. A video proof: https://www.dropbox.com/s/8gu5f1zz6w3hzfb/The%20Great%20Suspender%20Bug.mov?dl=0

**Comment by SnIPeRSnIPeR** [comment]
I have a video proof: [https://www.dropbox.com/s/8gu5f1zz6w3hzfb/The%20Great%20Suspender%20Bug.mov?dl=0](url)

**Comment by SnIPeRSnIPeR** [comment]
Suspend timer is also doesn't work for all tabs...

**Comment by SnIPeRSnIPeR** [comment]
Chrome 61.0.3163.79. Bug is still here :(

**Comment by slashdotfx** [comment]
I'm having the same issue. Currently Chrome 61.0.3163.100.

**Comment by deanoemcke** [comment]
Even though I cannot reproduce, I will assume that this issue will be made redundant by the upcoming release v7.x

**Comment by SnIPeRSnIPeR** [comment]
"caused-by-old-version-of-extension?"

NO

I am using 7.0.109 right now

**Comment by deanoemcke** [comment]
@SnIPeRSnIPeR please see #735 for any issues with 'suspend now' on the latest version. This issue was raised from an older version of the extension, hence the 'caused-by-old-version-of-extension' label.
