### ISSUE TITLE
Unsuspending tab on focus responds very slow

### ISSUE THREAD

**Issue by wwwhttp** [deanoemcke/thegreatsuspender#576]
Viewed tabs need about 1-2 sec beeing viewed **before it starts** to unsuspend...

**Comment by wwwhttp** [comment]
If I close an active tab and the browser automaticly switching to the next (suspended) tab, **it doesn't start** to aut. unsuspended the tab, so you have to click on it.

**Comment by deanoemcke** [comment]
In regards to original comment, this is by design. There is a delay so that tabs don't automatically unsuspend when you are just 'tabbing though' tabs via ctrl+tab.

For second comment, see: https://github.com/deanoemcke/thegreatsuspender/issues/519
