### ISSUE TITLE
Options for suspended URL

### ISSUE THREAD

**Issue by GOESPROTOCALL** [deanoemcke/thegreatsuspender#577]
It was a 5 star add-on until it recently (couple months back?) updated to included the page title in the suspended tab's address bar url.

I used to grab urls with CAU  (https://chrome.google.com/webstore/detail/copy-all-urls/djdmadneanknadilpjiknlnanaolmbfk) and could easily mass extract the URLs (i.e. for sharing) by removing TGS's extension text with a search/replace. Now everything is garbled up!

I don't want to have to unsuspend the tabs just to copy the URLs, then suspend them again later. Please add an option to not have the Title info there.

**Comment by deanoemcke** [comment]
Try going into the Session management screen from the extension settings page. 
This will show you your current session, and you can export it to a text file. This text file is the unsuspended urls.

Is that what you're after? Saves you using this other extension altogether right?

**Comment by GOESPROTOCALL** [comment]
Nope. Nope. Nope.

Your suggestion involved multiple steps to just to get the list of active
urls in a window, whereas with the other extension I can just press a
hotkey. Your solution also unnecessarily generate .txt files which I will
have to clean up later on. I just need to get some urls to send to someone,
but you adding in the page title is just complicating thing unnecessarily (I
really don't see what purpose it serves).

Please reopen the issue and fix it.
