### ISSUE TITLE
"Click to reload" message should also mention keyboard shortcuts

### ISSUE THREAD

**Issue by terminalmage** [deanoemcke/thegreatsuspender#579]
When I came upon a suspended tab for the first time, I noticed a "click to reload" message. This was a little annoying as I prefer to navigate with the keyboard. Only later did I find in the options that you can suspend/unsuspend with keyboard shortcuts.

One simple tweak to make this more clear would be to make the "Click to reload" message say "Click (or press Ctrl+Shift+U) to reload".

**Comment by deanoemcke** [comment]
I have added this to the suspended tab page in the upcoming release (v7.x)
