### ISSUE TITLE
Please add "one day", "two days", and "three days" to "autosuspend after" options.

### ISSUE THREAD

**Issue by daniel-pittman** [deanoemcke/thegreatsuspender#58]
G'day.  The autosuspend feature is great, but I would prefer to use it mostly on things that have sat idle for at least 24 hours -- just to avoid coming back in the morning and finding everything suspended that I was doing last night.

**Comment by deanoemcke** [comment]
This has been implemented in the latest (gitHub) version of the extension. It will be released to the webstore shortly.
