### ISSUE TITLE
unable to unsuspend tabs! (tried emailing before, no success)

### ISSUE THREAD

**Issue by izzyslair** [deanoemcke/thegreatsuspender#580]
I emailed the dev about this over 2 weeks ago and still no reply!  Somehow, Chrome ran into an error, and when I opened it again, all of my extensions had been removed.  I figured everything would be fine because I use Session Buddy, but when I reloaded my session, it turned out that I couldn't "unsuspend" any of the tabs.  It's like The Great Suspender lost its memory of what I previously had, and, unlike all of my other extensions, it did not save my data when I reinstalled it.  Please help!!  It looks like I can manually edit the address in each tab's address bar, but...I had over 300 tabs, so that's impossible.  (Yeah, there's a reason I need both Session Buddy and TGS...)  Please help - I haven't been able to find a suitable answer online yet.  I really need those tabs, many of which are vital for my job!  :(

**Comment by deanoemcke** [comment]
@izzyslair Try restoring your session buddy session, and then choose the 'unsuspend all tabs' option from the popup menu. Hopefully that will unsuspend all the tabs.

if that fails, someone has made a bookmarklet to help in this situation: https://github.com/deanoemcke/thegreatsuspender/issues/216

let me know how you get on. and sorry for the inconvenience :(
