### ISSUE TITLE
IndexedDB taking up large amount of space

### ISSUE THREAD

**Issue by Walkman100** [deanoemcke/thegreatsuspender#585]
TGS v6.30, Vivaldi 1.11.917.43, Linux Mint KDE 17.3

My `~/.config/vivaldi/Default/IndexedDB/chrome-extension_klbibkeccnjlkjkiokjodocebajanakg_0.indexeddb.blob/1/` folder is 15.4 GiB. Surely with only 374 tabs open in two windows that amount of space shouldn't be needed? A quick overview in Midnight Commander:
![image](https://user-images.githubusercontent.com/5454764/29845037-ab1e9eb0-8d11-11e7-955e-5d06d4d3160e.png)

Is this something unavoidable? or is there something that can be done to reduce the size?

**Comment by deanoemcke** [comment]
@Walkman100 that is definitely not right. it should never really get much over 1MB. On extension startup, the db should get truncated to keep the maximum object items down.

Are you able to get a better analysis of the contents of the db?
In chrome, if you inspect the background page of the extension and then go to the 'application' tab, you can browse the contents of the indexdb database.

Alternatively, if you can get access to the console of the background page (once again, this is pretty easy in chrome), you can try the following command:
```
gsUtils.getDb().then((s) => {
  s.query(DB_KEY).all().execute().then((result) => console.log(result))
});
```
try it with the following substituted `DB_KEY` values:
```
'gsPreviews'
'gsSuspendedTabInfo'
'gsCurrentSessions'
'gsSavedSessions'
```

That will give you all the possible contents of the indexedDb database. 
As I mentioned, these tables should be automatically truncated on extension startup based on these max table entry values:
`gsPreviews`: 200
`gsSuspendedTabInfo`: 1000
`gsCurrentSessions`: 5
`gsSavedSessions`: no limit

It would be great to find out what is taking up so much space!

**Comment by velinath** [comment]
I also have a large (9GB in my case) TGS IndexedDB. Exploring the IndexedDB as you've described, I have ~1350 entries in gsSuspendedTabInfo, 6 in gsCurrentSessions, nothing in gsPreviews, and nothing in gsSavedSessions.

**Comment by Walkman100** [comment]
Hi, sorry about the late reply, I'd been staying away from a browser for a while. I looked at the IndexedDB folder and it's empty. the 1/00 1/01 e.t.c. folders are all there, but no files at all. My tabs in Vivaldi are completely intact, and even after loading a few suspended tabs it's still empty.

I suspect it was emptied after rebooting, which might have been because I update my system before rebooting and vivaldi probably updated. Either way, it's clear now and I have another 15 GB free on my system drive :D
Sorry for wasting your time.

**Comment by deanoemcke** [comment]
@velinath does a computer restart affect the size of your indexedDb files?
