### ISSUE TITLE
Bitcoin Donation

### ISSUE THREAD

**Issue by joehenriod** [deanoemcke/thegreatsuspender#588]
I love the plugin.  I went to donate.  I almost automatically did the "suggested" Bitcoin donation, which is approximately $87.00 USD now. 

It might be time to update that pre-filled value to a more reasonable amount, based on the current price of Bitcoin.  I was expecting something more in the $5 to $20 range.

**Comment by deanoemcke** [comment]
This has been fixed. But will not update until the next release.
https://github.com/deanoemcke/thegreatsuspender/commit/344b343263d23766420d00238cc724cfbab23e7b
