### ISSUE TITLE
Feature Request - a way of searching or at least listing titles and switching to suspended windows

### ISSUE THREAD

**Issue by togakangaroo** [deanoemcke/thegreatsuspender#590]
I regularly end up with 30+ suspended windows in which I know there's an article on what I need *somewhere* but I can't find the tab itself. A way of searching them for text would be nice. At the very least I should be able to see a list of all suspended tab titles from a menu and be able to switch to them.

Bonus feature request - make it work with `O` command on vimium?

**Comment by fwextensions** [comment]
@togakangaroo I've got an early version of a tab-switcher extension called [QuicKey](https://chrome.google.com/webstore/detail/quickey-%E2%80%93-the-quick-tab-s/ldlghkoiihaelfnggonhjnfiabmaficg) that lets you type just part of a tab title or URL and then switch to that tab. (It doesn't match on text in the page, which would require a lot of local storage and indexing.)  

It also supports The Great Suspender: suspended tabs have greyed out favicons and you can hit shift-enter to switch to a suspended tab and immediately unsuspend it.  The URL shown in the results list is also the unsuspended URL, not the long `chrome-extension://klb...` one in the location bar. 

Anyway, I'm still working on it (it's not even searchable in the store yet), but it sounded like you might find find it useful.  More info [here](https://fwextensions.github.io/QuicKey/) and code [here](https://github.com/fwextensions/QuicKey).

**Comment by togakangaroo** [comment]
Thanks, I'll check it out!
For the record, I don't think you'd need a lot of local storage - at least not if you're doing full-word match.

1) Take the top 1000 or top 100 unique, non-common words on the page. Lowercase them.
2) Stick them in a Bloom Filter 
3) Save the Bloom Filters (but thats almost no space at all)
4) Lowercase any search words and run them against the stored filters

Since false positives are no big deal here and speed and storage size are, it would seem like a Bloom Filter is perfect for the job.

**Comment by Pascal666** [comment]
This feature strikes me as out of scope for this plugin.  You would still need a way to find a particular tab even if it were not suspended.

I use Quick Tabs to get a list of all my tabs sorted by most recently used and it does text searches of titles and urls.  You will probably want to disable fuzzy search: https://chrome.google.com/webstore/detail/quick-tabs/jnjfeinjfmenlddahdjdmgpbokiacbbb?hl=en

**Comment by deanoemcke** [comment]
I agree with @Pascal666 . This functionality is best delivered by a separate extension as it does not apply just to suspended tabs but to all tabs suspended or not.
