### ISSUE TITLE
Not rememberd scroll location. It will be moved to the top of the site

### ISSUE THREAD

**Issue by blastend** [deanoemcke/thegreatsuspender#592]
i used ver6.30

**Comment by blastend** [comment]
I confirmed that it works normally with vivaldy browser.
I uninstalled chrome and reinstalled it and put only the great suspender, but did not remember the scroll position

**Comment by Pascal666** [comment]
I am seeing the same thing.  When a tab is unsuspended I always get returned to the top of the page.

**Comment by aclbros** [comment]
Same problem here. Version 6.30 and Chrome in Xubuntu 16.04.

**Comment by deanoemcke** [comment]
The implementation of storing scroll position has been overhauled in the upcoming version of the extension (v7.x).

**Comment by mimiheart** [comment]
I'm on chrome, using 7.0.50 and this issue is still happening.

**Comment by deanoemcke** [comment]
@mimiheart thanks for this report.
I have fixed the issue in the github version (v7.0.80).
It was caused by a chrome change in v61: https://bugs.chromium.org/p/chromium/issues/detail?id=766938
