### ISSUE TITLE
Keyboard toggle shortcut

### ISSUE THREAD

**Issue by davidfregoli** [deanoemcke/thegreatsuspender#594]
Would be nice to have a single shortcut to toggle the active tab between suspended and unsuspended.
You could add a new shortcut or just make that the default behaviour for the current suspend tab shortcut.

**Comment by Omar-Elrefaei** [comment]
Yeah, that would enhance productivity.

**Comment by deanoemcke** [comment]
This has been implemented in the upcoming release (v7.x).
I have repurposed the 'Suspend active tab' shortcut to also unsuspend a suspended tab.
The original 'Unsuspend active tab' shortcut still exists for backwards compatibility. Both will now unsuspend a tab.
