### ISSUE TITLE
Background page was null when Chrome reloaded some suspended pages, so titles just say "Suspended Tab"

### ISSUE THREAD

**Issue by fwextensions** [deanoemcke/thegreatsuspender#597]
After restarting Chrome, a bunch of suspended tabs now just have "Suspended Tab" as their title.  The page is empty other than the default text.  Clicking the page does nothing.  

There's an error in the console:

    Uncaught TypeError: Cannot read property 'gsUtils' of null at suspended.js:4

Maybe the background page wasn't ready when the tab was loaded?

**Comment by deanoemcke** [comment]
I have never been able to replicate this. And there is very little documentation on exactly when the background page can be relied on to exist.
I have added some safety checks into the suspended tab page in the upcoming release which will first perform a wait in the background page is initially unavailable, and then fallback on sensible defaults for the page if it never becomes available: https://github.com/deanoemcke/thegreatsuspender/commit/7154895e928a12317f66120852def6796b1b9c33

**Comment by deanoemcke** [comment]
Related to: https://github.com/deanoemcke/thegreatsuspender/issues/559
