### ISSUE TITLE
Suspend This Tab and Others

### ISSUE THREAD

**Issue by harryfear** [deanoemcke/thegreatsuspender#599]
I often want to suspend all tabs in a window, but to do this I have to:

(1) Suspend Other Tabs
(2) Suspend This Tab

Can we have an additional Suspend All Tabs option?

**Comment by deanoemcke** [comment]
Please refer to issue: https://github.com/deanoemcke/thegreatsuspender/issues/467
The upcoming version (v7.x) has a new option to 'force suspend all tabs in all windows'. This will be available as a right-click menu option, and as a keyboard shortcut.
