### ISSUE TITLE
White list doesn't work

### ISSUE THREAD

**Issue by cbuck1** [deanoemcke/thegreatsuspender#60]
I put URLs in the White List but the great suspender continues to suspend those tabs.  What gives?  I'm using Windows 7 Professional and Chrome.Version 30.0.1599.69 m

**Comment by deanoemcke** [comment]
The whitelist looks for any substring match within the url - so in effect, it is automatically adding wildcards to any whitelisted term.
Closing this issue as I believe it has been resolved in the more recent gitHub versions of the extension.

**Comment by adam-hu** [comment]
I just had this issue (Macbook Air), but I think it's because I was using comma delimiter and a line break rather than space - perhaps you can add a small note at the bottom saying that it is in fact space delimited with no line break?
