### ISSUE TITLE
graphic glitch on suspended tabs

### ISSUE THREAD

**Issue by eMPee584** [deanoemcke/thegreatsuspender#600]
![screenshot_2017-10-01_21-55-46](https://user-images.githubusercontent.com/1227833/31058411-5a335c42-a6f3-11e7-9cf8-86e0a2f868ac.png)
.. huh?
seems to have started (IIRC) since I migrated my debian to 64bit nvidia from 32bit nouveau. ...

**Comment by deanoemcke** [comment]
I'm tempted to say "that's awesome!" but do not want to undermine your issue :D 

But seriously, that is the most odd thing I've ever seen. Do you have screen capture turned on? Is it possible that an actual screenshot image (if you inspect the page)? Or is it just a graphical glitch displaying the suspended tab page?

If the latter, then I'd say it's a native chrome issue.

**Comment by eMPee584** [comment]
Mhh. The problem went away and hasn't occurred since.. well wha'eva 😆
