### ISSUE TITLE
After some time suspended page need a refresh to being able to "unfreeze"

### ISSUE THREAD

**Issue by dragGH102** [deanoemcke/thegreatsuspender#601]
(I posted this on Chrome store too - but I'm posting it again to get a notification if any answer ...)
As per the title.
It's like the tab was suspended twice (one refresh allow clicking on "reload", without that nothing happens)

NOTE: I'm using "continue from left off" in Chrome. and certain tabs are suspended at the time I close Chrome.

EXAMPLE of url for a blocked tab: 

> chrome-extension://<extension id>/suspended.html#ttl=effects%2Ftesting.md%20at%20master%20%C2%B7%20ngrx%2Feffects&uri=https://github.com/ngrx/effects/blob/master/docs/testing.md

Also SUGGESTION: why not reverting tabs suspended -> normal state when closing browser? (e.g. USEFUL when trying to access those tabs on Chrome Mobile's "recent tabs")

**Comment by deanoemcke** [comment]
This is strange. That url you posted does not seem to be valid. Are you sure that is how it was? It seems to be missing the extension id. I would expect something more like: 
```
chrome-extension://klbibkeccnjlkjkiokjodocebajanakg/suspended.html#ttl=effects%2Ftesting.md%20at%20master%20%C2%B7%20ngrx%2Feffects&uri=https://github.com/ngrx/effects/blob/master/docs/testing.md
```
Navigating to your url as you pasted it leads me to a page that says "Suspended.html is blocked".
And refreshing this page does not take me to another suspended page.

Are you able to give me a screenshot of both the first AND second stages of this problem?

**Comment by dragGH102** [comment]
So, I finally managed to get in the same issue again (how to reproduce: no idea ... but I guess it may have to do with the "continue from left off" of Chrome).

This could be the issue. In **console** (dev tools) **before refresh** I see: 

> A Uncaught TypeError: Cannot read property 'gsUtils' of null at suspended.js:4

whereas in other (correctly) suspended pages (or the "blocked" page **after refresh**), **no error**.

As you may ask, **no error** in **"inspect pop up"** dialog (the error mentioned above is shown in the actual page's console, not extension's console)

## Before refresh

![before_page_referesh](https://user-images.githubusercontent.com/5430550/32135144-6aeee242-bbfa-11e7-9e48-fabfdd599d40.png)

The URL in the "blocked" state is

> chrome-extension://klbibkeccnjlkjkiokjodocebajanakg/suspended.html#ttl=intellij%20idea%20-%20How%20can%20I%20setup%20webstorm%20to%20automatically%20add%20semi-colons%20to%20javascript%20functions%2C%20methods%2C%20etc%20-%20Stack%20Overflow&uri=https://stackoverflow.com/questions/11805103/how-can-i-setup-webstorm-to-automatically-add-semi-colons-to-javascript-function

What I noticed is that the header is missing in the "before refresh" image

## after refresh

![after_page_refresh](https://user-images.githubusercontent.com/5430550/32135162-bf0957e0-bbfa-11e7-8cd4-9552773024cf.png)

whereas in **non-blocked** state (the same url, after page refresh) - at first glance the same which would confirm the JS bug is the issue:

chrome-extension://klbibkeccnjlkjkiokjodocebajanakg/suspended.html#ttl=intellij%20idea%20-%20How%20can%20I%20setup%20webstorm%20to%20automatically%20add%20semi-colons%20to%20javascript%20functions%2C%20methods%2C%20etc%20-%20Stack%20Overflow&uri=https://stackoverflow.com/questions/11805103/how-can-i-setup-webstorm-to-automatically-add-semi-colons-to-javascript-function

I hope you're not gonna ask me to tell me to click on the JS error, because I've already refreshed and it's gone ;) (unless you know a way to "recover" Chromes console's history)

**Comment by dragGH102** [comment]
same issue just happened (on a different URL abd tab).

And Here is the source the error in console refers to:

> document.getElementById('gsTitle').innerHTML = chrome.extension.getBackgroundPage().gsUtils.getSuspendedTitle(window.location.href);

**Comment by deanoemcke** [comment]
@dragGH102 thanks a lot for the extra info.
it appears to be a duplicate of this issue: https://github.com/deanoemcke/thegreatsuspender/issues/597

if you wanted to do me a REALLY big favour, would you be interested in trialling the new alpha build of the extension? I have made some changes to try to address this issue, but i'm not 100% confident that it will have any effect.

Instructions on installing can be found here: https://github.com/deanoemcke/thegreatsuspender#install-as-an-extension-from-source

If you do want to try out the new version, I would recommend either leaving the existing version installed, but change the suspend time to 'never', or disabling the current version (but make sure you unsuspend all your tabs first!).

**Comment by dragGH102** [comment]
Sure @deanoemcke . just done. I've however noticed the new version was installed side-to-side with 6.30 (which I then removed).

Can I rest assured that if this extension is updated, the dev version will be updated with it or do I need to install from Chrome store to do so?
In the former case, feel free to close and I'll let you know if I spot the same error again!

**Comment by dragGH102** [comment]
@deanoemcke I decided to revert to the stable one 6.30 because installing the new one messed up with all the previously suspended tabs.

Now each of them show: mfcggejhdikbikdpdclgodpidmbhcjlk is blocked (ERR_BLOCKED_BY_CLIENT)

Then, when selecting from TGS' extension's pop-up "Restore all the suspended tabs", it seems to work. I didn't actually check immediately ... but when I went back to my computer I saw "FILE NOT FOUND" shown in the suspended tab and even in the extension pop up

**Comment by liamjohnston** [comment]
@dragGH102 
Webstore version: you WILL get updates automatically, if and when the dev wants this to happen.
Dev version (unpacked extension): you WON'T get any updates until you manually update your local copy of the code and hit 'reload' on the extensions screen.

**Comment by deanoemcke** [comment]
@dragGH102 sorry for the hassle. this is why i recommended that you leave the v6.30 version of the extension installed but set to 'never' for the suspend time. Or alternatively, I suggested that you should unsuspend all your tabs before removing the 6.30 version.
As liamjohnston said, if you want to receive automatic updates, you should stay with the webstore version. The development version was just for you to test if your issue still happens in the newer version.

Thanks for giving it a go! Hope I haven't caused you too much hassle.

**Comment by michaelkolber** [comment]
Not sure if anyone will see this but I can confirm that the issue is still happening for me, on both Windows and ChromeOS. There doesn't seem to be a pattern, and it happens infrequently enough that I forget about it.
