### ISSUE TITLE
Captured screen does not support high resolution displays

### ISSUE THREAD

**Issue by danielsedlacek** [deanoemcke/thegreatsuspender#602]
On high-resolution displays the saved image is 2x bigger than it should be.

**Comment by deanoemcke** [comment]
@griii2 :

The size of the screen capture is dependent on the window size of the browser and the resolution of the monitor the browser is displayed on when the screen capture is taken.
Is it possible that the screen captures were taken on a different monitor, or with a browser at a different size than the one currently displaying it?

Can you please verify this by suspending an unsuspended tab, and then checking if it exhibits the same issue? If so, can you please paste a screenshot of this happening into this issue thread?

Thanks.

**Comment by deanoemcke** [comment]
This is possibly the same issue as: https://github.com/deanoemcke/thegreatsuspender/issues/211

**Comment by deanoemcke** [comment]
There have been some changes made to the html2canvas library in how it captures the screen on retina screens: https://github.com/deanoemcke/thegreatsuspender/pull/562
These changes are in the upcoming release. Perhaps they will fix your issue?

Also, the new release will shrink screen captures that are larger than the current window down to fit. This should also resolve your problem.

**Comment by fcherman** [comment]
I believe the problem is a simple typographical error – a missing semicolon in the CSS. See my thread at https://github.com/deanoemcke/thegreatsuspender/issues/622
