### ISSUE TITLE
7.4 not in Chrome Store

### ISSUE THREAD

**Issue by simplepinoi177** [deanoemcke/thegreatsuspender#603]
It's been a while since I manually updated. So color me surprised that when I went to re-install the extension straight from the source, it had been updated and changed! But when I did the same re-install on another machine but through the Chrome Web Store, it did not install the updated version here on Github. It actually states the one on the store is still at 6.3.
Being able to install it from the Chrome Web Store vs. from the source through "Developer Mode" and loading unpacked extension would actually bypass my other issue...but I'll start a new issue for that...
To Be Continued...

**Comment by deanoemcke** [comment]
New version is coming really soon. Sorry about the delay!
