### ISSUE TITLE
Manually installing 7.4 causes "disable Developer Mode extensions"

### ISSUE THREAD

**Issue by simplepinoi177** [deanoemcke/thegreatsuspender#604]
This may be because version 7.4 can't be installed from the Chrome Web Store (https://github.com/deanoemcke/thegreatsuspender/issues/603). I only ever ran into this issue before when, just like this instance, I was installing manually from the source/extracted .zip file through developer mode. By disabling Developer Mode, however, causes to disable the 7.4 extension. I know that it's not too good/easy to somehow disable the error message, so I figure maybe installing it from the Chrome Web Store (updated version of course) may bypass this issue. That or resolve the issue causing Chrome to not liking the installation or running without Developer Mode enabled...

**Comment by deanoemcke** [comment]
This is not an issue per se. Just intended behaviour. The current gitHub version is in alpha (v7.0-alpha-50). It has not been thoroughly tested and therefore has not been pushed out live to everybody.
If you want this release in advance, you have no option but to install as you have done via developer mode. The message you are receiving from chrome is a choice made on their part (the chrome developers). I assume it is there as a security precaution. It is outside of my ability to change this, and anyone installing chrome extensions from source must experience this.

There will be an official webstore version of v7.x soon. This will automatically update any older webstore version you have installed (most likely v6.30).
