### ISSUE TITLE
Incognito mode often does not include extension in the right-click context menu

### ISSUE THREAD

**Issue by simplepinoi177** [deanoemcke/thegreatsuspender#605]
Often, as I load up chrome "incognito," I find that (although it is clearly checked in the settings [even in the incognito session]) the extension is not included in the right-click context menu -- even though my Adobe Acrobat extension is seen and contains selectable menus! 
My only resolution I can do is to close the incognito session, and open a new one. It's a coin-flip as to if the extension would be in the right-click context menu. And, at times, it would show itself there, but with only 2 options in the menu vs. the full 7+; i.e. suspend tab & settings. Most times I have to open & close 4 times before I "hit the spot."
But once I have an incognito session with the full menu in the right-click context menu, it will constantly stay there and be available even as I open new incognito tabs and windows. It only "may" go away if closing the whole incognito session (closing all incognito tabs in all windows).  
A thought as you may attempt to recreate the issue; there are times when it is there on the first try/load up of an incognito session, so relaunching chrome in "incognito mode" multiple times (5+) may be needed...

**Comment by deanoemcke** [comment]
This is a known issue with v6.30: https://github.com/deanoemcke/thegreatsuspender/issues/564
It will be fixed in the upcoming release (v7.x)
Sorry for the annoying bug!
