### ISSUE TITLE
Feature Request: Context Menu in Tab Row

### ISSUE THREAD

**Issue by simplepinoi177** [deanoemcke/thegreatsuspender#606]
I am aware that most likely the right-click context menu for the tab row might be exclusively for the Google Chrome web browser to control, but I was hoping to ask anyways just in case...

Sometimes I'm dealing with older tabs (located/sorted from left to right) and find that I wish to suspend the window/tabs. But in order to, I have to right click on an empty spot of the current webpage to suspend all tabs or go all the way to the right (where my extension shortcuts are) of the window. It would be nice sometimes to not need to do this...

**Comment by deanoemcke** [comment]
Yes unfortunately, this is not under my control.
The only other option available (other than right-click or the popup menu) is using the keyboard shortcuts. This is probably the most convenient way to suspend all tabs.
