### ISSUE TITLE
Improve automatic update process

### ISSUE THREAD

**Issue by deanoemcke** [deanoemcke/thegreatsuspender#609]
Due to my recent new knowledge of the wonderful 'onUpdateAvailable' chrome api event (thanks @uecasm) it should now be possible to rollout automatic updates in a non-catastrophic fashion.

The work for this is mostly done, but unfortunately it will take one more (catastrophic) update to get everybody onto a version that supports the onUpdateAvailable event. 

Once on this new release (v7.x), then a subsequent available update will trigger a popup informing users of the incoming update, and offering them an option to save a backup of their tabs before continuing.

It will also automatically save a copy of the current tab session in the Session History view to help users recover tabs should anything go wrong during the update that causes tabs to disappear permanently.

**Comment by deanoemcke** [comment]
The bulk of this work is in these commits:
- https://github.com/deanoemcke/thegreatsuspender/commit/2c749d9a31b280f2dc727ecebc5a5aeabc8695d3#diff-c4bc9070545f4f4a8528b8a30066ff3d
- https://github.com/deanoemcke/thegreatsuspender/commit/b8f0d0b68f69ffe2d31bd91da83e49713f3335b1

**Comment by Firecul** [comment]
Any update on when we will get the big chrome store update? I'm getting tired of all my tabs loading back in whenever I relaunch chrome because I'm using a developer mode extension, I can't go back to 'stock' as I'm a heavy youtube user so having to clear out the cookies costs a lot of time per day.
