### ISSUE TITLE
Text invisible in 7.0.50-alpha

### ISSUE THREAD

**Issue by DAOWAce** [deanoemcke/thegreatsuspender#611]
Finally updated to the dev build which fixed that gscrollpos issue: https://github.com/deanoemcke/thegreatsuspender/issues/537

Noticed the text rendered completely invisible: 

![tgs no text](https://user-images.githubusercontent.com/480587/31871032-5940b7c0-b77f-11e7-9ffa-ad9adf6eb4f7.png)

I could only find a version for 7.3.0 linked in the mentioned issue.  This version works just fine.

It's probably because I'm using an older Chrome version (51.0.2704.106), which I unfortunately am unable to update due to GDI being removed and DirectWrite being forced in v52+ and making all text cause me eye strain.  Chromium devs don't care and it's apparently impossible for any extension to be made to change this.

Is there a way for you to keep legacy browser support?

**Comment by liamjohnston** [comment]
Interesting. Do you get this issue on any other sites?

I'm using the 'system font stack' that's kinda hot right now:
`font-family: -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Oxygen-Sans,Ubuntu,Cantarell,"Helvetica Neue",sans-serif;`

I like it because you a get nice font without having to download any webfonts. It has a fallback of 'sans-serif' so I'd expect _something_ to show.

**Comment by DAOWAce** [comment]
I don't recall ever seeing invisible text on a website thus far, just this version of the addon.

Do you have an example website that uses the same font display that I could test with?

**Comment by liamjohnston** [comment]
Well, GitHub.com for one. Some info and examples here:
https://css-tricks.com/snippets/css/system-font-stack/

The fact that you're not seeing this issue on other sites makes me think it could be a caching issue. One of the new changes _is_ changing to this font stack from a locally served web font (Open Sans) so maybe your browser is still looking for that font? Weird that there'd be no visible fallback though in either case :/

Can you inspect the text and see what font it's trying to load? And look at the computed styles? And add an inline style via the inspector, e.g. `font-family: sans-serif;`, and see if that makes the text appear? Thanks!

**Comment by deanoemcke** [comment]
@DAOWAce Actually, this looks like an issue with the internationalization. I notice that there's the word 'other' rendering ok in that screenshot. That's because I forgot to internationalize that particular string :/
Are you still having the invisible text issue? I imagine it probably affects all the internal screens within the extension? (ie. suspended tab page, session history page etc) ?
If so, are you able to open the developer console and tell me if you can see any errors?

I have tried debugging with browser stack on a chrome v51 instance (via OSX sierra) and can't see the same issue.

**Comment by DAOWAce** [comment]
Sorry about not responding to this.

After dealing with trying to switch to the unpacked version to fix the gScrollPos issue and Chrome being god awful, nagging about how it was running an unpacked extension, then trying to pack it and actually get chrome to load it.. having to go through whitelisting in some group policy setting for it, almost losing my tabs because of the ID changing when packing.. ugh, ugh.

It just made me not want to change versions again.

I can look into it again with an updated version now I guess, just have to find the time for it..

**Comment by DAOWAce** [comment]
Okay, finally got around to this.. ironically as I was setting up a conversion to Cent to finally get off my old Chrome version into a Chrome based browser that actually cares about its users. (ie; still has GDI rendering so text isn't a blurry eye straining mess, plus numerous advanced options).

Yes, the invisible text is on every page the extension creates.  The drop down menu, the welcome screen, the options screen, the suspended tab screen.. _(though I'm not sure how to suspend a tab, the ctrl+shift+s hotkey isn't working, maybe I rebound the default and forgot)_

The console outputs this on the welcome page:

`welcome.js:7 Uncaught TypeError: Cannot read property 'documentReadyAndLocalisedAsPromsied' of undefined`

When I try to view the options, I get this:

`options.js:155 Uncaught TypeError: Cannot read property 'documentReadyAndLocalisedAsPromsied' of undefined(anonymous function) @ options.js:155(anonymous function) @ options.js:193`

Screenshot of some console stuff: 
![tgs console](https://user-images.githubusercontent.com/480587/33373052-3184a59a-d4ce-11e7-9633-d9fe199c9d51.png)

I don't reeeeally know what I'm doing here (despite being an IT person, I've never gotten into coding and it super intimidates me), but I'd assume that error confirms your suspicion of it being a localization or "I18N" problem.

Hopefully I can get my Cent switch done soon so you (and other web/app devs) don't have to worry about the rare person like me running an old Chrome version (which should forcefully auto-update normally..).

**Comment by deanoemcke** [comment]
hmmm.. ok. thanks for this. it's super helpful.
could you tell me the exact OS and version of chrome you're running?
and also, in that console window in the bottom-right of your screenshot, what happens if you type `chrome.extension.getBackgroundPage()` in there?

**Comment by DAOWAce** [comment]
OS:  Windows 10 x64 v1703 build 15063.726
Chrome:  51.0.2704.106  x64

Running that command gives me a list of things far too long to paste here.  I can right click and save the log, but it only appears to save what's actually displayed on screen; doesn't include everything in the collapsed menus.  It also saves it as a mass of text instead of being formatted as shown in the console.

Short example: <details><summary>Mass of text</summary>
<code>Uncaught TypeError: Cannot read property 'documentReadyAndLocalisedAsPromsied' of undefined
chrome.extension.getBackgroundPage()
Window {external: Object, chrome: Object, document: document, db: Object, gsStorage: Object…}
Infinity: InfinityAnalyserNode: AnalyserNode()arguments: nullcaller: nulllength: 0name: "AnalyserNode"prototype: AnalyserNode__proto__: AudioNode()<function scope>AnimationEvent: AnimationEvent()AppBannerPromptResult: AppBannerPromptResult()AppView: appview()ApplicationCache: ApplicationCache()ApplicationCacheErrorEvent: ApplicationCacheErrorEvent()Array: Array()ArrayBuffer: ArrayBuffer()Attr: Attr()Audio: HTMLAudioElement()AudioBuffer: AudioBuffer()AudioBufferSourceNode: AudioBufferSourceNode()AudioContext: AudioContext()AudioDestinationNode: AudioDestinationNode()AudioListener: AudioListener()arguments: nullcaller: nulllength: 0name: "AudioListener"prototype: AudioListener__proto__: ()<function scope>AudioNode: AudioNode()AudioParam: AudioParam()AudioProcessingEvent: AudioProcessingEvent()AutocompleteErrorEvent: AutocompleteErrorEvent()BarProp: BarProp()BatteryManager: BatteryManager()BeforeInstallPromptEvent: BeforeInstallPromptEvent()BeforeUnloadEvent: BeforeUnloadEvent()BiquadFilterNode: BiquadFilterNode()Blob: Blob()BlobEvent: BlobEvent()Boolean: Boolean()CDATASection: CDATASection()CSS: CSS()CSSFontFaceRule: CSSFontFaceRule()CSSGroupingRule: CSSGroupingRule()CSSImportRule: CSSImportRule()CSSKeyframeRule: CSSKeyframeRule()CSSKeyframesRule: CSSKeyframesRule()CSSMediaRule: CSSMediaRule()CSSNamespaceRule: CSSNamespaceRule()CSSPageRule: CSSPageRule()CSSRule: CSSRule()CSSRuleList: CSSRuleList()CSSStyleDeclaration: CSSStyleDeclaration()CSSStyleRule: CSSStyleRule()CSSStyleSheet: CSSStyleSheet()CSSSupportsRule: CSSSupportsRule()CSSViewportRule: CSSViewportRule()Cache: Cache()CacheStorage: CacheStorage()CanvasCaptureMediaStreamTrack: CanvasCaptureMediaStreamTrack()CanvasGradient: CanvasGradient()CanvasPattern: CanvasPattern()CanvasRenderingContext2D: CanvasRenderingContext2D()ChannelMergerNode: ChannelMergerNode()ChannelSplitterNode: ChannelSplitterNode()CharacterData: CharacterData()ClientRect: ClientRect()ClientRectList: ClientRectList()ClipboardEvent: ClipboardEvent()CloseEvent: CloseEvent()Comment: Comment()CompositionEvent: CompositionEvent()ConvolverNode: ConvolverNode()Credential: Credential()CredentialsContainer: CredentialsContainer()Crypto: Crypto()CryptoKey: CryptoKey()CustomEvent: CustomEvent()DOMError: DOMError()DOMException: DOMException()DOMImplementation: DOMImplementation()DOMParser: DOMParser()DOMStringList: DOMStringList()DOMStringMap: DOMStringMap()DOMTokenList: DOMTokenList()DataTransfer: DataTransfer()DataTransferItem: DataTransferItem()DataTransferItemList: DataTransferItemList()DataView: DataView()Date: Date()DelayNode: DelayNode()DeviceMotionEvent: DeviceMotionEvent()DeviceOrientationEvent: DeviceOrientationEvent()Document: Document()DocumentFragment: DocumentFragment()DocumentType: DocumentType()DragEvent: DragEvent()DynamicsCompressorNode: DynamicsCompressorNode()Element: Element()Error: Error()ErrorEvent: ErrorEvent()EvalError: EvalError()Event: Event()EventSource: EventSource()EventTarget: EventTarget()ExtensionOptions: extensionoptions()ExtensionView: extensionview()FederatedCredential: FederatedCredential()File: File()FileError: FileError()FileList: FileList()FileReader: FileReader()Float32Array: Float32Array()Float64Array: Float64Array()FocusEvent: FocusEvent()FontFace: FontFace()FormData: FormData()Function: Function()GainNode: GainNode()Gamepad: Gamepad()GamepadButton: GamepadButton()GamepadEvent: GamepadEvent()GoogleAnalyticsObject: "ga"HTMLAllCollection: HTMLAllCollection()HTMLAnchorElement: HTMLAnchorElement()HTMLAreaElement: HTMLAreaElement()HTMLAudioElement: HTMLAudioElement()HTMLBRElement: HTMLBRElement()HTMLBaseElement: HTMLBaseElement()HTMLBodyElement: HTMLBodyElement()HTMLButtonElement: HTMLButtonElement()HTMLCanvasElement: HTMLCanvasElement()HTMLCollection: HTMLCollection()HTMLContentElement: HTMLContentElement()HTMLDListElement: HTMLDListElement()HTMLDataListElement: HTMLDataListElement()HTMLDetailsElement: HTMLDetailsElement()HTMLDialogElement: HTMLDialogElement()HTMLDirectoryElement: HTMLDirectoryElement()HTMLDivElement: HTMLDivElement()HTMLDocument: HTMLDocument()HTMLElement: HTMLElement()HTMLEmbedElement: HTMLEmbedElement()HTMLFieldSetElement: HTMLFieldSetElement()HTMLFontElement: HTMLFontElement()HTMLFormControlsCollection: HTMLFormControlsCollection()HTMLFormElement: HTMLFormElement()HTMLFrameElement: HTMLFrameElement()HTMLFrameSetElement: HTMLFrameSetElement()HTMLHRElement: HTMLHRElement()HTMLHeadElement: HTMLHeadElement()HTMLHeadingElement: HTMLHeadingElement()HTMLHtmlElement: HTMLHtmlElement()HTMLIFrameElement: HTMLIFrameElement()HTMLImageElement: HTMLImageElement()HTMLInputElement: HTMLInputElement()HTMLKeygenElement: HTMLKeygenElement()HTMLLIElement: HTMLLIElement()HTMLLabelElement: HTMLLabelElement()HTMLLegendElement: HTMLLegendElement()HTMLLinkElement: HTMLLinkElement()HTMLMapElement: HTMLMapElement()HTMLMarqueeElement: HTMLMarqueeElement()HTMLMediaElement: HTMLMediaElement()HTMLMenuElement: HTMLMenuElement()HTMLMetaElement: HTMLMetaElement()HTMLMeterElement: HTMLMeterElement()HTMLModElement: HTMLModElement()HTMLOListElement: HTMLOListElement()HTMLObjectElement: HTMLObjectElement()HTMLOptGroupElement: HTMLOptGroupElement()HTMLOptionElement: HTMLOptionElement()HTMLOptionsCollection: HTMLOptionsCollection()HTMLOutputElement: HTMLOutputElement()HTMLParagraphElement: HTMLParagraphElement()HTMLParamElement: HTMLParamElement()HTMLPictureElement: HTMLPictureElement()HTMLPreElement: HTMLPreElement()HTMLProgressElement: HTMLProgressElement()HTMLQuoteElement: HTMLQuoteElement()HTMLScriptElement: HTMLScriptElement()HTMLSelectElement: HTMLSelectElement()HTMLShadowElement: HTMLShadowElement()HTMLSourceElement: HTMLSourceElement()HTMLSpanElement: HTMLSpanElement()HTMLStyleElement: HTMLStyleElement()HTMLTableCaptionElement: HTMLTableCaptionElement()HTMLTableCellElement: HTMLTableCellElement()HTMLTableColElement: HTMLTableColElement()HTMLTableElement: HTMLTableElement()HTMLTableRowElement: HTMLTableRowElement()HTMLTableSectionElement: HTMLTableSectionElement()HTMLTemplateElement: HTMLTemplateElement()HTMLTextAreaElement: HTMLTextAreaElement()HTMLTitleElement: HTMLTitleElement()HTMLTrackElement: HTMLTrackElement()HTMLUListElement: HTMLUListElement()HTMLUnknownElement: HTMLUnknownElement()HTMLVideoElement: HTMLVideoElement()HashChangeEvent: HashChangeEvent()Headers: Headers()History: History()IDBCursor: IDBCursor()IDBCursorWithValue: IDBCursorWithValue()IDBDatabase: IDBDatabase()IDBFactory: IDBFactory()IDBIndex: IDBIndex()IDBKeyRange: IDBKeyRange()IDBObjectStore: IDBObjectStore()IDBOpenDBRequest: IDBOpenDBRequest()IDBRequest: IDBRequest()IDBTransaction: IDBTransaction()IDBVersionChangeEvent: IDBVersionChangeEvent()IIRFilterNode: IIRFilterNode()IdleDeadline: IdleDeadline()Image: HTMLImageElement()ImageBitmap: ImageBitmap()ImageBitmapRenderingContext: ImageBitmapRenderingContext()ImageData: ImageData()InputDeviceCapabilities: InputDeviceCapabilities()Int8Array: Int8Array()Int16Array: Int16Array()Int32Array: Int32Array()IntersectionObserver: IntersectionObserver()IntersectionObserverEntry: IntersectionObserverEntry()Intl: ObjectJSON: JSONKeyboardEvent: KeyboardEvent()Location: Location()MIDIAccess: MIDIAccess()MIDIConnectionEvent: MIDIConnectionEvent()MIDIInput: MIDIInput()MIDIInputMap: MIDIInputMap()MIDIMessageEvent: MIDIMessageEvent()MIDIOutput: MIDIOutput()MIDIOutputMap: MIDIOutputMap()MIDIPort: MIDIPort()Map: Map()Math: MathMediaDevices: MediaDevices()MediaElementAudioSourceNode: MediaElementAudioSourceNode()MediaEncryptedEvent: MediaEncryptedEvent()MediaError: MediaError()MediaKeyMessageEvent: MediaKeyMessageEvent()MediaKeySession: MediaKeySession()MediaKeyStatusMap: MediaKeyStatusMap()MediaKeySystemAccess: MediaKeySystemAccess()MediaKeys: MediaKeys()MediaList: MediaList()MediaQueryList: MediaQueryList()MediaQueryListEvent: MediaQueryListEvent()MediaRecorder: MediaRecorder()MediaSource: MediaSource()MediaStreamAudioDestinationNode: MediaStreamAudioDestinationNode()MediaStreamAudioSourceNode: MediaStreamAudioSourceNode()MediaStreamEvent: MediaStreamEvent()MediaStreamTrack: MediaStreamTrack()MessageChannel: MessageChannel()MessageEvent: MessageEvent()MessagePort: MessagePort()MimeType: MimeType()MimeTypeArray: MimeTypeArray()MouseEvent: MouseEvent()MutationEvent: MutationEvent()MutationObserver: MutationObserver()MutationRecord: MutationRecord()NaN: NaNNamedNodeMap: NamedNodeMap()Navigator: Navigator()Node: Node()NodeFilter: NodeFilter()NodeIterator: NodeIterator()NodeList: NodeList()Notification: Notification()Number: Number()Object: Object()OfflineAudioCompletionEvent: OfflineAudioCompletionEvent()OfflineAudioContext: OfflineAudioContext()OffscreenCanvas: OffscreenCanvas()OffscreenCanvasRenderingContext2D: OffscreenCanvasRenderingContext2D()Option: HTMLOptionElement()OscillatorNode: OscillatorNode()PageTransitionEvent: PageTransitionEvent()PasswordCredential: PasswordCredential()Path2D: Path2D()Performance: Performance()PerformanceEntry: PerformanceEntry()PerformanceMark: PerformanceMark()PerformanceMeasure: PerformanceMeasure()PerformanceNavigation: PerformanceNavigation()PerformanceResourceTiming: PerformanceResourceTiming()PerformanceTiming: PerformanceTiming()PeriodicWave: PeriodicWave()PermissionStatus: PermissionStatus()Permissions: Permissions()Plugin: Plugin()PluginArray: PluginArray()PopStateEvent: PopStateEvent()Presentation: Presentation()PresentationAvailability: PresentationAvailability()PresentationConnection: PresentationConnection()PresentationConnectionAvailableEvent: PresentationConnectionAvailableEvent()PresentationConnectionCloseEvent: PresentationConnectionCloseEvent()PresentationRequest: PresentationRequest()ProcessingInstruction: ProcessingInstruction()ProgressEvent: ProgressEvent()Promise: Promise()PromiseRejectionEvent: PromiseRejectionEvent()Proxy: Proxy()PushManager: PushManager()PushSubscription: PushSubscription()RTCCertificate: RTCCertificate()RTCIceCandidate: RTCIceCandidate()RTCSessionDescription: RTCSessionDescription()RadioNodeList: RadioNodeList()Range: Range()RangeError: RangeError()ReadableByteStream: ReadableByteStream()ReadableStream: ReadableStream()ReferenceError: ReferenceError()Reflect: ObjectRegExp: RegExp()Request: Request()Response: Response()SVGAElement: SVGAElement()SVGAngle: SVGAngle()SVGAnimateElement: SVGAnimateElement()SVGAnimateMotionElement: SVGAnimateMotionElement()SVGAnimateTransformElement: SVGAnimateTransformElement()SVGAnimatedAngle: SVGAnimatedAngle()SVGAnimatedBoolean: SVGAnimatedBoolean()SVGAnimatedEnumeration: SVGAnimatedEnumeration()SVGAnimatedInteger: SVGAnimatedInteger()SVGAnimatedLength: SVGAnimatedLength()SVGAnimatedLengthList: SVGAnimatedLengthList()SVGAnimatedNumber: SVGAnimatedNumber()SVGAnimatedNumberList: SVGAnimatedNumberList()SVGAnimatedPreserveAspectRatio: SVGAnimatedPreserveAspectRatio()SVGAnimatedRect: SVGAnimatedRect()SVGAnimatedString: SVGAnimatedString()SVGAnimatedTransformList: SVGAnimatedTransformList()SVGAnimationElement: SVGAnimationElement()SVGCircleElement: SVGCircleElement()SVGClipPathElement: SVGClipPathElement()SVGComponentTransferFunctionElement: SVGComponentTransferFunctionElement()SVGCursorElement: SVGCursorElement()SVGDefsElement: SVGDefsElement()SVGDescElement: SVGDescElement()SVGDiscardElement: SVGDiscardElement()SVGElement: SVGElement()SVGEllipseElement: SVGEllipseElement()SVGFEBlendElement: SVGFEBlendElement()SVGFEColorMatrixElement: SVGFEColorMatrixElement()SVGFEComponentTransferElement: SVGFEComponentTransferElement()SVGFECompositeElement: SVGFECompositeElement()SVGFEConvolveMatrixElement: SVGFEConvolveMatrixElement()SVGFEDiffuseLightingElement: SVGFEDiffuseLightingElement()SVGFEDisplacementMapElement: SVGFEDisplacementMapElement()SVGFEDistantLightElement: SVGFEDistantLightElement()SVGFEDropShadowElement: SVGFEDropShadowElement()SVGFEFloodElement: SVGFEFloodElement()SVGFEFuncAElement: SVGFEFuncAElement()SVGFEFuncBElement: SVGFEFuncBElement()SVGFEFuncGElement: SVGFEFuncGElement()SVGFEFuncRElement: SVGFEFuncRElement()SVGFEGaussianBlurElement: SVGFEGaussianBlurElement()SVGFEImageElement: SVGFEImageElement()SVGFEMergeElement: SVGFEMergeElement()SVGFEMergeNodeElement: SVGFEMergeNodeElement()SVGFEMorphologyElement: SVGFEMorphologyElement()SVGFEOffsetElement: SVGFEOffsetElement()SVGFEPointLightElement: SVGFEPointLightElement()SVGFESpecularLightingElement: SVGFESpecularLightingElement()SVGFESpotLightElement: SVGFESpotLightElement()SVGFETileElement: SVGFETileElement()SVGFETurbulenceElement: SVGFETurbulenceElement()SVGFilterElement: SVGFilterElement()SVGForeignObjectElement: SVGForeignObjectElement()SVGGElement: SVGGElement()SVGGeometryElement: SVGGeometryElement()SVGGradientElement: SVGGradientElement()SVGGraphicsElement: SVGGraphicsElement()SVGImageElement: SVGImageElement()SVGLength: SVGLength()SVGLengthList: SVGLengthList()SVGLineElement: SVGLineElement()SVGLinearGradientElement: SVGLinearGradientElement()SVGMPathElement: SVGMPathElement()SVGMarkerElement: SVGMarkerElement()SVGMaskElement: SVGMaskElement()SVGMatrix: SVGMatrix()SVGMetadataElement: SVGMetadataElement()SVGNumber: SVGNumber()SVGNumberList: SVGNumberList()SVGPathElement: SVGPathElement()SVGPatternElement: SVGPatternElement()SVGPoint: SVGPoint()SVGPointList: SVGPointList()SVGPolygonElement: SVGPolygonElement()SVGPolylineElement: SVGPolylineElement()SVGPreserveAspectRatio: SVGPreserveAspectRatio()SVGRadialGradientElement: SVGRadialGradientElement()SVGRect: SVGRect()SVGRectElement: SVGRectElement()SVGSVGElement: SVGSVGElement()SVGScriptElement: SVGScriptElement()SVGSetElement: SVGSetElement()SVGStopElement: SVGStopElement()SVGStringList: SVGStringList()SVGStyleElement: SVGStyleElement()SVGSwitchElement: SVGSwitchElement()SVGSymbolElement: SVGSymbolElement()SVGTSpanElement: SVGTSpanElement()SVGTextContentElement: SVGTextContentElement()SVGTextElement: SVGTextElement()SVGTextPathElement: SVGTextPathElement()SVGTextPositioningElement: SVGTextPositioningElement()SVGTitleElement: SVGTitleElement()SVGTransform: SVGTransform()SVGTransformList: SVGTransformList()SVGUnitTypes: SVGUnitTypes()SVGUseElement: SVGUseElement()SVGViewElement: SVGViewElement()SVGViewSpec: SVGViewSpec()SVGZoomEvent: SVGZoomEvent()Screen: Screen()ScreenOrientation: ScreenOrientation()ScriptProcessorNode: ScriptProcessorNode()SecurityPolicyViolationEvent: SecurityPolicyViolationEvent()Selection: Selection()ServiceWorker: ServiceWorker()ServiceWorkerContainer: ServiceWorkerContainer()ServiceWorkerMessageEvent: ServiceWorkerMessageEvent()ServiceWorkerRegistration: ServiceWorkerRegistration()Set: Set()ShadowRoot: ShadowRoot()SharedWorker: SharedWorker()SourceBuffer: SourceBuffer()SourceBufferList: SourceBufferList()SpeechSynthesisEvent: SpeechSynthesisEvent()SpeechSynthesisUtterance: SpeechSynthesisUtterance()Storage: Storage()StorageEvent: StorageEvent()String: String()StyleSheet: StyleSheet()StyleSheetList: StyleSheetList()SubtleCrypto: SubtleCrypto()Symbol: Symbol()SyncManager: SyncManager()SyntaxError: SyntaxError()Text: Text()TextDecoder: TextDecoder()TextEncoder: TextEncoder()TextEvent: TextEvent()TextMetrics: TextMetrics()TextTrack: TextTrack()TextTrackCue: TextTrackCue()TextTrackCueList: TextTrackCueList()TextTrackList: TextTrackList()TimeRanges: TimeRanges()Touch: Touch()TouchEvent: TouchEvent()TouchList: TouchList()TrackEvent: TrackEvent()TransitionEvent: TransitionEvent()TreeWalker: TreeWalker()TypeError: TypeError()UIEvent: UIEvent()URIError: URIError()URL: URL()URLSearchParams: URLSearchParams()Uint8Array: Uint8Array()Uint8ClampedArray: Uint8ClampedArray()Uint16Array: Uint16Array()Uint32Array: Uint32Array()VTTCue: VTTCue()ValidityState: ValidityState()WaveShaperNode: WaveShaperNode()WeakMap: WeakMap()WeakSet: WeakSet()WebGLActiveInfo: WebGLActiveInfo()WebGLBuffer: WebGLBuffer()WebGLContextEvent: WebGLContextEvent()WebGLFramebuffer: WebGLFramebuffer()WebGLProgram: WebGLProgram()WebGLRenderbuffer: WebGLRenderbuffer()WebGLRenderingContext: WebGLRenderingContext()WebGLShader: WebGLShader()WebGLShaderPrecisionFormat: WebGLShaderPrecisionFormat()WebGLTexture: WebGLTexture()WebGLUniformLocation: WebGLUniformLocation()WebKitAnimationEvent: AnimationEvent()WebKitCSSMatrix: WebKitCSSMatrix()WebKitMutationObserver: MutationObserver()WebKitTransitionEvent: TransitionEvent()WebSocket: WebSocket()WebView: webview()WheelEvent: WheelEvent()Window: Window()Worker: Worker()XMLDocument: XMLDocument()XMLHttpRequest: XMLHttpRequest()XMLHttpRequestEventTarget: XMLHttpRequestEventTarget()XMLHttpRequestUpload: XMLHttpRequestUpload()XMLSerializer: XMLSerializer()XPathEvaluator: XPathEvaluator()XPathExpression: XPathExpression()XPathResult: XPathResult()XSLTProcessor: XSLTProcessor()alert: alert()applicationCache: ApplicationCacheatob: atob()blur: ()btoa: btoa()caches: CacheStoragecancelAnimationFrame: cancelAnimationFrame()cancelIdleCallback: cancelIdleCallback()captureEvents: captureEvents()chrome: ObjectclearInterval: clearInterval()clearTimeout: clearTimeout()clientInformation: Navigatorclose: ()closed: falseconfirm: confirm()console: ConsolecreateImageBitmap: createImageBitmap()crypto: Cryptodb: ObjectdecodeURI: decodeURI()decodeURIComponent: decodeURIComponent()defaultStatus: ""defaultstatus: ""devicePixelRatio: 1document: documentencodeURI: encodeURI()encodeURIComponent: encodeURIComponent()escape: escape()eval: eval()event: undefinedexternal: Objectfetch: fetch()find: find()focus: ()frameElement: nullframes: Windowga: (a)gaData: ObjectgaGlobal: Objectgaplugins: ObjectgetComputedStyle: getComputedStyle()getMatchedCSSRules: getMatchedCSSRules()getSelection: getSelection()gsAnalytics: ObjectgsSession: ObjectgsStorage: Objecthistory: HistoryindexedDB: IDBFactoryinnerHeight: 0innerWidth: 0isFinite: isFinite()isNaN: isNaN()isSecureContext: truelength: 0localStorage: Storagelocation: Locationlocationbar: BarPropmatchMedia: matchMedia()menubar: BarPropmoveBy: moveBy()moveTo: moveTo()name: ""navigator: NavigatoroffscreenBuffering: trueonabort: nullonanimationend: nullonanimationiteration: nullonanimationstart: nullonautocomplete: nullonautocompleteerror: nullonbeforeunload: nullonblur: nulloncancel: nulloncanplay: nulloncanplaythrough: nullonchange: nullonclick: nullonclose: nulloncontextmenu: nulloncuechange: nullondblclick: nullondevicemotion: nullondeviceorientation: nullondeviceorientationabsolute: nullondrag: nullondragend: nullondragenter: nullondragleave: nullondragover: nullondragstart: nullondrop: nullondurationchange: nullonemptied: nullonended: nullonerror: nullonfocus: nullonhashchange: nulloninput: nulloninvalid: nullonkeydown: nullonkeypress: nullonkeyup: nullonlanguagechange: nullonload: nullonloadeddata: nullonloadedmetadata: nullonloadstart: nullonmessage: nullonmousedown: nullonmouseenter: nullonmouseleave: nullonmousemove: nullonmouseout: nullonmouseover: nullonmouseup: nullonmousewheel: nullonoffline: nullononline: nullonpagehide: nullonpageshow: nullonpause: nullonplay: nullonplaying: nullonpopstate: nullonprogress: nullonratechange: nullonrejectionhandled: nullonreset: nullonresize: nullonscroll: nullonsearch: nullonseeked: nullonseeking: nullonselect: nullonshow: nullonstalled: nullonstorage: nullonsubmit: nullonsuspend: nullontimeupdate: nullontoggle: nullontransitionend: nullonunhandledrejection: nullonunload: nullonvolumechange: nullonwaiting: nullonwebkitanimationend: nullonwebkitanimationiteration: nullonwebkitanimationstart: nullonwebkittransitionend: nullonwheel: nullopen: open()arguments: nullcaller: nulllength: 2name: "open"__proto__: ()<function scope>openDatabase: openDatabase()opener: nullouterHeight: 0outerWidth: 0pageXOffset: 0pageYOffset: 0parent: WindowparseFloat: parseFloat()parseInt: parseInt()performance: Performancepersonalbar: BarProppostMessage: ()print: print()prompt: prompt()releaseEvents: releaseEvents()requestAnimationFrame: requestAnimationFrame()requestIdleCallback: requestIdleCallback()resizeBy: resizeBy()resizeTo: resizeTo()screen: ScreenscreenLeft: 0screenTop: 0screenX: 0screenY: 0scroll: scroll()scrollBy: scrollBy()scrollTo: scrollTo()scrollX: 0scrollY: 0scrollbars: BarPropself: WindowsessionStorage: StoragesetInterval: setInterval()setTimeout: setTimeout()speechSynthesis: SpeechSynthesisstatus: ""statusbar: BarPropstop: stop()styleMedia: StyleMediatgs: Objecttoolbar: BarProptop: Windowundefined: undefinedunescape: unescape()webkitAudioContext: AudioContext()webkitCancelAnimationFrame: webkitCancelAnimationFrame()webkitCancelRequestAnimationFrame: webkitCancelRequestAnimationFrame()webkitIDBCursor: IDBCursor()webkitIDBDatabase: IDBDatabase()webkitIDBFactory: IDBFactory()webkitIDBIndex: IDBIndex()webkitIDBKeyRange: IDBKeyRange()webkitIDBObjectStore: IDBObjectStore()webkitIDBRequest: IDBRequest()webkitIDBTransaction: IDBTransaction()webkitIndexedDB: IDBFactorywebkitMediaStream: MediaStream()webkitOfflineAudioContext: OfflineAudioContext()webkitRTCPeerConnection: RTCPeerConnection()webkitRequestAnimationFrame: webkitRequestAnimationFrame()webkitRequestFileSystem: webkitRequestFileSystem()webkitResolveLocalFileSystemURL: webkitResolveLocalFileSystemURL()webkitSpeechGrammar: SpeechGrammar()webkitSpeechGrammarList: SpeechGrammarList()webkitSpeechRecognition: SpeechRecognition()webkitSpeechRecognitionError: SpeechRecognitionError()webkitSpeechRecognitionEvent: SpeechRecognitionEvent()webkitStorageInfo: DeprecatedStorageInfowebkitURL: URL()window: Window__proto__: Window</code>
</details>

Also noticed the chrome menu bugs out with the alpha extension enabled: ![tgs alpha bug chrome menu](https://user-images.githubusercontent.com/480587/33426400-9da8f3d6-d58f-11e7-904e-f2464cb96d95.png)

I think it fixes itself after a browser restart, but toggling it results in this behavior when I click on the menu.

**Comment by deanoemcke** [comment]
ok. thanks a lot. 
it looks like some of the code in the new release is not supported by chrome v51. i'll see if i can work around this.

**Comment by deanoemcke** [comment]
I've bumped up the minimum required version of chrome to v55 :(

**Comment by DAOWAce** [comment]
No problem, got my Cent switch done so now I'm relatively up to date with Chrome updates and sites/extensions aren't broken anymore.

Just have to hope the developer doesn't give up on it or put in some drastic change caused by a major Chrome overhaul that Google does..

Why companies can't leave well enough alone is beyond me.  First Firefox, then Chrome.. ugh.
