### ISSUE TITLE
possible conflict with MacOS fast user switching

### ISSUE THREAD

**Issue by philmb** [deanoemcke/thegreatsuspender#615]
With the Great Suspender enabled (on Chrome Version 62.0.3202.62 (Official Build) (64-bit)), I had been having trouble with fast user switching between user accounts on MacOS Sierra (10.12.6 (16G29)). (I'm referring to MacOS accounts, not to Chrome/Google accounts.) I would be logged in as my work MacOS user, then try to switch over to my personal user, but as MacOS was switching, the screen would flash black and all users would be logged out as if the computer restarted. I wasn't expecting this to be related to TGS, but for another reason I disabled TGS in my work MacOS user account (but not my personal account) and this problem went away immediately and permanently. Coincidence? Perhaps. But there's a strong enough correlation that I wanted to mention it.

**Comment by liamjohnston** [comment]
Sheesh, I don't see how TGS could be responsible for logging your users out 😐
Can you do some more tests?? E.g. leave TGS off for a while longer and see if it happens again, and if not, re-enable it and see if it happens again?
I have an MBP and use fast user switching (both profiles use TGS) and have not seen this issue.

**Comment by philmb** [comment]
There may be other aspects involved - waking up from sleep, number of pages suspended, unplugging an external monitor, ... I'll see if I can get some more specific details for replicating the problem, but the correlation seems very strong that TGS is involved somehow.

**Comment by philmb** [comment]
So, I re-enabled TGS on both Mac User accounts, nearly two weeks ago, and the problem has returned. Again, there's probably other things going on in the mix, so I can't easily say how to recreate it, but the correlation remains. Sorry I can't be of more help, but maybe if someone else discovers this issue, you'll have a better idea where to start...

**Comment by philmb** [comment]
An update as I keep watching this: After I disabled TGS again, the problem cleared up, but recently the problem has cropped up again even though TGS in not enabled in either User account. So, I'm willing to let TGS off the hook, in spite of the correlations I reported above.
