### ISSUE TITLE
Not working today

### ISSUE THREAD

**Issue by dalelowry** [deanoemcke/thegreatsuspender#618]
When I start my computer in the morning, I reopen my previous chrome session from the previous day, which usually includes a number of tabs that have been suspended by the Great Suspender. None of them seem to be working today. They aren't suspended (the page progress icon shows that it's continually trying to load) but I can't get to the original page that was suspended, either. Thoughts?

**Comment by deanoemcke** [comment]
Are you able to paste a screenshot of one of these tabs?
What happens if you right-click on the tab favicon and choose 'Duplicate'?

**Comment by dalelowry** [comment]
Thanks. I ended up restarting my machine for the Mac Sierra security update and it started working again. I will take those steps if the issue repeats.
