### ISSUE TITLE
Allow local resources (file://) to be suspended

### ISSUE THREAD

**Issue by markifi** [deanoemcke/thegreatsuspender#62]
can local pdf files be suspended?

**Comment by michaelkolber** [comment]
@deanoemcke It's been a while since this issue was opened, has anything changed?

**Comment by deanoemcke** [comment]
I dont think that chrome extensions can run on local resources (ie: urls of the form file://...)

**Comment by michaelkolber** [comment]
@deanoemcke Please see [this SO answer](https://stackoverflow.com/questions/17155916/can-an-app-or-extension-open-files-on-system-with-permission-all-urls?noredirect=1&lq=1) where it seems as if extensions can run on local resources. In addition, I know that LastPass currently allows password filling for local resources. The only downside seems to be that the user must enable the option manually.

**Comment by deanoemcke** [comment]
@michaelkolber thanks for that.
so you're interested in local pdf files being suspendable?
i would like to do some testing to see just how useful this is (in terms of system resource reduction).

**Comment by michaelkolber** [comment]
As a student, when I suspend a 300-page textbook PDF on a Chromebook I immediately notice the difference in the entire system. I've been playing around with the code and found that file:// urls work fine with GS if you just add a few lines of code. Now I'm just working on a prompt for the user to enable access to file:// URLs if they have not already. I'll create a PR when I've finished.

**Comment by deanoemcke** [comment]
That's awesome. Thanks!
