### ISSUE TITLE
Are these screen areas created by The Great Suspender extension?

### ISSUE THREAD

**Issue by dominointernet** [deanoemcke/thegreatsuspender#620]
Hello,

I get these bizarre change of color in my suspended tabs.
Initially I thought my screen was failing (even though it's quite new) but I'm pretty sure it only happens in suspended tabs only.

Can anyone confirm me if they are related to the extension?
And if so, can I get rid of them? They are pretty anoying.

Screen capture here:
https://imgur.com/a/ayNZJ

Thanks for your help!

Jose

**Comment by deanoemcke** [comment]
Will paste it here directly:
![image](https://user-images.githubusercontent.com/1051763/32685841-750aba9a-c667-11e7-87cf-1809d092cba9.png)

**Comment by deanoemcke** [comment]
I don't think this is related to the extension. 
But then again, I have no idea what could cause something like this. 
Perhaps your graphics card? I'm really sorry, I have no idea.
