### ISSUE TITLE
How can use REGEX in whitelist?

### ISSUE THREAD

**Issue by Milor123** [deanoemcke/thegreatsuspender#625]
Hi whois, I need add a url to whitelist but i want use WILDCARDS or REGEX... How can i do it?

Thank you very much

**Comment by deanoemcke** [comment]
There is a tooltip ? icon in the options page which will give you examples on how to use the regex feature.
There is also more information here: https://github.com/deanoemcke/thegreatsuspender/issues/197

**Comment by Milor123** [comment]
Thank you very much.. i love you. !!!
