### ISSUE TITLE
[Alpha] Suspended icons sometimes not semi-transparent

### ISSUE THREAD

**Issue by fwextensions** [deanoemcke/thegreatsuspender#627]
This seems to always happen with pages where the content script doesn't load.  For me, that's on our Enterprise version of Google Docs.  Now that I can manually suspend them again in the alpha version, I don't see their icon get lightened when they're suspended.

However, it also happens with some other pages, and I'm not sure why.  This is a page hosted on github.io:

![image](https://user-images.githubusercontent.com/61631/33510461-13c7f85a-d6c1-11e7-8716-4af6fda48ffb.png)

I believe that was automatically suspended after an hour.  But when I just quit and restarted Chrome, it's now greyed out again:

![image](https://user-images.githubusercontent.com/61631/33510490-71bc02da-d6c1-11e7-84b0-70f7106855a9.png)

So it always happens with tabs where content scripts are blocked, but occasionally with normal tabs as well.

**Comment by fwextensions** [comment]
Here's another example where I had manually suspended the tab, and the icon was greyed out.  But then I restarted Chrome, and at some point (I'm not sure when, possibly at startup), the tab started showing the un-greyed out favicon:

![image](https://user-images.githubusercontent.com/61631/33511611-75d6ad82-d6d2-11e7-8581-7f91b00d2f09.png)

If I query that tab via `chrome.tabs.get()`, the `favIconUrl` is set to `"chrome://favicon/https://<page url>"` .

**Comment by fwextensions** [comment]
I just restarted Chrome and that site above that I had suspended is now unsuspended.  Its domain is on the whitelist, but I had manually suspended it.  Do suspended pages on whitelisted domains automatically get unsuspended on a restart now?  

Also, that suspended QuicKey page's favicon is now back to being the fully opaque version after the restart.

**Comment by fwextensions** [comment]
What I said in the first comment about pages where the content script didn't load not getting greyed out icons is no longer happening for me.  It was very consistent in one session, but after restarting recently, manually suspending one of those pages showed the correct suspended icon.  Not sure what's going on.

I'll open another issue on the suspended tabs getting unsuspended on restart.  That just happened for a bunch of suspended tabs, though not all.

**Comment by deanoemcke** [comment]
I did a major rewrite of the suspended tab page on Jan 4th 2018: https://github.com/deanoemcke/thegreatsuspender/commit/144fd5c49b1660507ff1453ae837b5c8a0962f87#diff-b45940944d233d9ccdd651384fc57fca

This should allow a semi-transparent icon even if the content script fails to load.
Let me know if you come across this issue in the future (as of v7.0.77)

**Comment by fwextensions** [comment]
Is there a v7.0.77 release on GitHub?  The last one I see under Releases is 7.0.alpha.72.  I assume there's a way of pulling that version, but I'm not git-savvy enough to do it.

**Comment by deanoemcke** [comment]
I have just tagged a new release (v7.0-alpha.85)
https://github.com/deanoemcke/thegreatsuspender/releases/tag/v7.0-alpha.85
