### ISSUE TITLE
[Alpha] Suspended tabs sometimes get unsuspended on restarting Chrome

### ISSUE THREAD

**Issue by fwextensions** [deanoemcke/thegreatsuspender#628]
I've got both the webstore extension (currently set to never suspend tabs) and the 7.0.72 alpha installed, which is set to suspend tabs after an hour.  I also had Session Buddy installed until I just disabled it.

I've noticed over the past several days that when restarting Chrome, tabs I thought had been suspended were in their normal unsuspended state.  I just restarted again a little while ago and definitely saw 4 or 5 tabs get unsuspended when the alpha TGS had previously had them suspended.  I don't see any pattern to which tabs get unsuspended.

**Comment by fwextensions** [comment]
This might (?) be more common when Chrome was force quit and then restarted.  I've been having issues with Chrome 62 on Win7 where its commit size would increase continuously after waking the laptop, so I've been having to force quit it more often.  I don't think I've seen any tabs suspended by the production extension unsuspend themselves.

**Comment by deanoemcke** [comment]
I'm pretty sure I know what was causing this, and it should now be fixed (v7.0.81).
I think that the extension was detecting that the suspended tab was unresponsive, so it was reloading it to be safe. Please let me know if you continue to experience this issue.
