### ISSUE TITLE
[Alpha] Repeated errors logged when content script is not available

### ISSUE THREAD

**Issue by fwextensions** [deanoemcke/thegreatsuspender#629]
I inspected the background page of the alpha build and noticed a few cases where there many repeated errors logged:

![image](https://user-images.githubusercontent.com/61631/33585343-9459c490-d918-11e7-8f78-3ec621dd41fc.png)

There were another couple of pages of those in the console.  I believe these were triggered when an Enterprise Gdoc that blocks the content script was loading and I clicked the TGS icon.  The menu showed the loading tab data spinner, and then showed the no tab data warning.  You'll see the errors were logged over 5 seconds. 

I haven't dug into it, but maybe the fact that a call was already made to the content script isn't getting recorded, and it keeps getting called again until a timeout happens?

**Comment by deanoemcke** [comment]
Yes. That is normal as it is trying to repeatedly contact the content script. These errors are not normally logged, however it seems you have debug=true set in your gsUtils.js file?
Which is good, if you want to help me with debugging :D 

On production these will be set to false and no errors will be logged.

**Comment by fwextensions** [comment]
I had downloaded the 7.0-alpha.72 zip and was using that.  Looks like debugging is enabled in that build.

**Comment by deanoemcke** [comment]
Ah yes. By production, I meant the chrome webstore.
I should probably ensure that debugging is also off for tagged releases in the repo too.
Thanks for the heads up.
