### ISSUE TITLE
[Alpha] Dark theme flashes window to light on unsuspend

### ISSUE THREAD

**Issue by ProditorMagnus** [deanoemcke/thegreatsuspender#632]
v7.0.72

Suspending does similar, but there the loading duration is much shorter, so does not feel to be problem then.

View when suspended: https://vgy.me/DBFrO6.png
Shortly after using unsuspend: https://vgy.me/P0MEwp.png

**Comment by deanoemcke** [comment]
Thanks for that. It has been fixed (v7.0.78)
https://github.com/deanoemcke/thegreatsuspender/commit/3c956e34cbcb2b672affd29956bf2efdcd88772f

**Comment by deanoemcke** [comment]
I've found a way to fix this for suspending also.
