### ISSUE TITLE
Tabs being unrecognizable by various versions. 

### ISSUE THREAD

**Issue by alidan** [deanoemcke/thegreatsuspender#635]
So, one of my issues, 400 youtube amongst other sites, is something that is fixable by going to the source branch, however in doing that not a single tab was recognized.

Now, this is what a suspended tabs address is

chrome-extension://klbibkeccnjlkjkiokjodocebajanakg/suspended.html#ttl=(12222)%20YouTube&uri=https://www.youtube.com/

Is there a way to implement something into the program, like a tab recovery command? 
I use an extension called tabs outliner in conjunction with the great suspender so I have quite a few tabs that would need to manually be scrubbed, but if there was a way to open them, then in TGS select recover all tabs, and have it remove all the garbage and load the tab, possibly re suspending it or letting there be an option to recover and let it load, that would be great.

**Comment by CollinChaffin** [comment]
I just posted in my open issue #646   a workaround for this which I meant to post here for you as well:

> P.S.  Also, as a workaround for those with saved session either via other 3rd party extensions or TGS where TGS new versions will not recognize the suspension via old versions (root cause being the Chrome extension ID# changing) is this:  The "unsuspend ALL tabs" code must be doing a regex or other search (I haven't read the code) but despite the extesion ID#'s changing between Github build etc........a single suspended page via diff version will NOT unsuspend via click so the trick is....go to any active tab (this is only PER WINDOW unfortunately so will have to be done for each WINDOW with mult tabs) and then click the TGS button and select the "unsuspend all tabs" and wholla it will then magically identify the old version's suspended open tabs and unsuspend them now allowing you to restore the original site's URL in the nav bar and take control of them with new TGS moving forward.

**Comment by deanoemcke** [comment]
The script posted by @fwextensions in this issue: https://github.com/deanoemcke/thegreatsuspender/issues/689 may also act as a workaround.
I'll close this issue as a duplicate of this other issue.
