### ISSUE TITLE
How to whitelist only part of a URL, not everything that contains that part?

### ISSUE THREAD

**Issue by voightkent** [deanoemcke/thegreatsuspender#636]
For example if a forum has "_boards/catalog/thread_" in its url and I put "_boards/catalog_" in the whitelist, I don't want "_boards/catalog/thread_" to be whitelisted as well?

I don't think this can currently be done but maybe this could be implemented in an update?

**Comment by deanoemcke** [comment]
The whitelist supports regular expressions. If you are familiar with them, then they should be able to achieve what you are after.

For example, you can use the $ character to specify the end of the url. So entering into the whitelist:
/github.com\/deanoemcke\/thegreatsuspender\/issues$/

will ONLY whitelist urls that have the word issues at the very end, like: ...thegreatsuspender/issues

Whereas:
/github.com\/deanoemcke\/thegreatsuspender\/issues/

will whitelist both: 
...thegreatsuspender/issues
and
...thegreatsuspender/issues/636

Note that you need to escape any / characters with a proceeding \ 
And the entire whitelist string needs to have the / character at the beginning and end.

**Comment by deanoemcke** [comment]
Link to original feature request: https://github.com/deanoemcke/thegreatsuspender/issues/197
