### ISSUE TITLE
[Enhancement] Unsuspend only tabs in current window.

### ISSUE THREAD

**Issue by awiebe** [deanoemcke/thegreatsuspender#637]
Sometimes I only want to unsuspend tabs in a certain window, not all of them.

**Comment by taniadaniela** [comment]
@awiebe there is that option, but is not available on the extension menu, you need to do right click on the suspended page, go to thegreatsuspender and there is the option for unsuspend all tabs in this window.
![screen shot 2018-02-01 at 12 39 23 pm](https://user-images.githubusercontent.com/5315791/35687243-f396b6fe-074c-11e8-8c34-2cd5bef9b8f9.jpg)

**Comment by deanoemcke** [comment]
Actually, the popup menu option 'Unsuspend all tabs' actually only unsuspends tabs in the current window (ie. it does exactly the same thing as the right-click menu option - it's just worded differently).

Conversely, if you actually do want to unsuspend all tabs in all windows, THEN you must use the right-click menu option, as this option does not appear in the popup menu.
