### ISSUE TITLE
Disable Tab Notifications when suspending tab

### ISSUE THREAD

**Issue by lynysys** [deanoemcke/thegreatsuspender#64]
When TGS suspends a tab - Ideally it shouldn't notify chrome of an event.
As it stands at the moment, when TGS suspends a tab, the suspended tab glows/pulsates to alert the user of this fact.

TGS should just do this in the background, the user has no need to know that a tab has been suspended until he comes back later to find it as such.

**Comment by xgdgsc** [comment]
This is still an issue for me. Especially I want to suspend pinned tabs and enable `Automatically unsuspend when tab gains focus`. The tab glowing with light is really annoying and sometimes kills performance on linux version of chrome. And I would have to click it to stop the animation, at the same time unsuspend the tab, which is not anything I want.
