### ISSUE TITLE
Blue notification dot on suspended pinned tabs

### ISSUE THREAD

**Issue by nbcraft** [deanoemcke/thegreatsuspender#641]
Hi, just started using this chrome extension and it's great.

One thing though: pinned tabs that get automatically suspended are showing a blue `notification` dot, when the one suspended manually don't, see below :
![tabs](https://user-images.githubusercontent.com/4719911/34709005-4916db58-f4ca-11e7-9c89-0a4810f46e7b.png)

Is this normal ? It kinda defeats the purpose because it catches my attention and I end up going in there, and re-suspending manually for it to go away.

Thanks.

**Comment by liamjohnston** [comment]
I am guessing you're on an old version of chrome. The blue dot feature was removed. 

This was all I could fine about it:
https://support.google.com/chrome/forum/AAAAP1KN0B05jUw-e8nCg0/?hl=en

**Comment by nbcraft** [comment]
@liamjohnston Sadly this guess is wrong:
```
Google Chrome is up to date
Version 63.0.3239.132 (Official Build) (64-bit)
```

Read all the posts in your link again, it is a feature currently active.

And this feature is very useful for Gmail, Linkedin, etc... But with the extension it gives me a false sense of notification.

**Comment by liamjohnston** [comment]
Oh, OK. My bad. 

I have never actually seen the blue dot, though I don't tend to pin tabs.

If my understanding of the dot is correct - that it appears when something(??) about the tab has changed - I'm don't think this extension would have the ability to not show it.

**Comment by nbcraft** [comment]
Yeah I see how that could be tricky, I think indeed that it is a change in the web page.
Oh well, I'll see if I can live with it. 😉
