### ISSUE TITLE
Restarting Chrome with suspended tabs

### ISSUE THREAD

**Issue by StrassenLaterne** [deanoemcke/thegreatsuspender#642]
I use to keep some tabs open which i frequently use or which i dont want to forget.
If i open Chrome and the active tab was suspended in the last session it shows the standard 'suspended tab' Page, but in the wrong color preset and i cant click to unsuspend. I have to refresh the page to be able to unsuspend that specific tab. All other tabs which are open and suspended work.
Would be great if there is a way, that you can fix that.

Greets and thanks for the awesome extension

**Comment by Firecul** [comment]
I have came across this bug before too, you can also unsuspended by
clicking the TGS icon and unsuspending from there instead if you want to
save the extra time.

**Comment by deanoemcke** [comment]
Unfortunately I cannot reproduce this.
Does this happen for you consistently?
What OS are you using, which version of chrome, and what version of the extension?
And are you talking about closing chrome down completely (with a suspended tab as the active tab).
And then opening chrome again later?

**Comment by StrassenLaterne** [comment]
Yeah it happens consistently. Windows 10, Chrome 64.0.3282.140 with Auto
Update on, TGS V6.30.
I usually have some open tabs waiting for me to finish the work with them
and they are usually all suspended, when i close Chrome. And if the active
tab at the relaunch is a suspended one, the error occures.
I'öll hope this could help you fixing it.
Thanks 4 the great extension.

Dean Oemcke <notifications@github.com> schrieb am Mi., 7. Feb. 2018 um
04:41 Uhr:

**Comment by totpet** [comment]
I also have this issue on two OS's with with TGS 6.30:

- Windows 10, chrome 64.0.3282.186 (Official Build) (64-bit)
- Xubuntu 17.10,  chromium 64.0.3282.167-0ubuntu0.17.10.1

My session has a lot of tabs open (4 windows, 157 tabs), most is which are suspended.
The original page title is missing from the 'tab suspended' page (both in the page and the tab title)

**Comment by fwextensions** [comment]
This sounds similar to bug #619 that I was seeing, and which seems to be fixed in the alpha versions.

**Comment by alexmipego** [comment]
I can confirm this bug, on OSX for over 1-2 years.
From my experience there 3 things that make this bug appear, first I've >10 windows some with 40-70 tabs, if I clean up to less tabs it usually goes away. Secondly, pinned tabs are almost ways bugged after you restart, thirdly the "active" tab for each window will always be bugged.
