### ISSUE TITLE
Updating version in Chrome webstore

### ISSUE THREAD

**Issue by orschiro** [deanoemcke/thegreatsuspender#643]
Dear @deanoemcke,

This extension is purely brilliant.

I am wondering if there is any reason that withholds updating the version in Chrome webstore?

The latest version is 6.30 from June 6, 2017, whereas the latest commit is from 6 days ago. 

Are you planning on a big new release coming?

**Comment by liamjohnston** [comment]
See https://github.com/deanoemcke/thegreatsuspender/issues/526 for an explanation.

**Comment by orschiro** [comment]
@liamjohnston that clarifies it sufficiently. Appreciated!
