### ISSUE TITLE
I love this app and want to help with themes

### ISSUE THREAD

**Issue by jdille** [deanoemcke/thegreatsuspender#644]
Hey there Suspension Labs,

I adore this app and use it all the time. I am a Visual Designer at Google ([linkedin](https://www.linkedin.com/in/jackdille/)) and I'd love to help you add a few more themes and polish tweaks if you'd be open to it. Let me know if this is something you'd be interested in.

Thanks,
Jack

**Comment by deanoemcke** [comment]
@jdille For sure Jack. Thanks for the offer. Get in touch with @liamjohnston. He's in charge of the styling for the project :)
Also, check out the latest version in the repo first (as opposed to that on the webstore). Things have changed a fair amount since then.
