### ISSUE TITLE
Google Image Search and Maps (and YouTube) issues

### ISSUE THREAD

**Issue by sflesch** [deanoemcke/thegreatsuspender#651]
I'm finding a number of people getting an error 400 while using TGS on YouTube. I also see a number of people complaining about Google Maps not having any images (which I also get every once in a while). Finally, I also get an error 400 when trying to do an image search. I did find a Google Product Forum post that mentioned the same issue for several people.
I suspect these may be related. Typically clearing the cache/cookies for Google clears up the issue.
I like TGS very much and probably won't remove it unless it gets really bad, but I'm sure we all would like this fixed.
Little more info on the picture search. You have to Right click an image and search, but dragging it into the Google search page works ok. The failed image search brings you to this page: https://www.google.com/searchbyimage/upload

**Comment by AlexWayfer** [comment]
Duplicate of #537

**Comment by allgameplaya** [comment]
Reddit seems to have picked up on it:
https://www.reddit.com/r/youtube/comments/6h59hh/400_thats_an_error_on_every_youtube_page/dlhqqwo/

It's a very annoying issue and it does happen at least once a week.

**Comment by sflesch** [comment]
Closing because of duplicate. Sorry about that. Thanks Alex.

**Comment by AlexWayfer** [comment]
No problems. 🙂

**Comment by sflesch** [comment]
I do have to thank @allgameplaya for pointing me to that thread. Now I know a faster way to delete the specific cookies without deleting all my Google cookies!
