### ISSUE TITLE
Screen Capturing Not Saving After Relaunch in Incognito 

### ISSUE THREAD

**Issue by volt55** [deanoemcke/thegreatsuspender#652]
(I have already commented the following on two other threads, I don't know if they will be seen by that many people however, so I decided to create a issue thread myself.)

 I have noticed that the screen capturing setting for TGS is automatically disabled for incognito mode windows whenever the browser is relaunched. Can you fix this? Did you know about this?

**Comment by deanoemcke** [comment]
Incognito mode uses a separate storage for it's own preferences and also throws away any changes made to these preferences after the incognito window is closed (as it should being incognito).
See this issue: #468

Note that there is a pending new feature to sync settings across chrome profiles. With this enabled, incognito mode will be able to sync it's settings with that of the normal window, which will resolve your issue.
See: #262

**Comment by volt55** [comment]
@deanoemcke Thank you. I want the requested feature #262 you mentioned to be implemented as well. So, mark me down as another person who wants that feature as well.

**Comment by Veazer** [comment]
> Note that there is a pending new feature to sync settings across chrome profiles. With this enabled, incognito mode will be able to sync it's settings with that of the normal window, which will resolve your issue.

Does this mean that the keyboard shortcut "Suspend all tabs in all windows" could potentially apply to incognito windows as well?
