### ISSUE TITLE
Why is all the text squished together in tab screenshots?

### ISSUE THREAD

**Issue by Vismund-Cygnus** [deanoemcke/thegreatsuspender#653]
When The Great Suspender captures a screenshot when suspending, it screws up all the text and seems to remove spaces between words. This happens a lot, on many websites.

Is there a reason for this? Doesn't that mean that TGS is actively reading all the text on every page instead of just taking a simple screenshot?

Example: https://i.imgur.com/1S1jjcL.png

**Comment by deanoemcke** [comment]
The screen capturing is done with an external js library called html2canvas. It is not perfect, but the best solution currently available for taking screenshots of a tab that is not currently active in the browser.
The current webstore version of the extension uses an older version of this library. The upcoming release has a more updated version. Here is an example of a screen capture of the same page on the newer version of html2canvas:

https://imgur.com/a/MTCgw

For more info on why I am using this library, see this thread: #503
