### ISSUE TITLE
Can "More tools -> Add to desktop..." pages that open in their own window be auto-suspended?

### ISSUE THREAD

**Issue by Wizek** [deanoemcke/thegreatsuspender#656]
I set the timer to 20 seconds, and they don't seem to be auto-suspended even when I minimize those windows to the taskbar.

Perhaps because the extension thinks that they are regular windows with a single tab open, that is always selected and visible? If so, maybe they could be specially handled as IIRC the chrome extension APIs do indicate if they are standalone windows with a boolean flag somewhere.

Also, I wonder if the detection could make sense to be done with blur events or the browser visibility api. That way no special handling is needed, and we would have accurate knowledge of visibility.

@deanoemcke, what do you think?

# Background

The whole reason why I am trying out this extension is because I have quite a few pinned desktop shortcuts, which are pinned to the taskbar. E.g. gmail. But gmail likes to eat 300-700 MB of ram. Bonkers. So I want to auto-unload it and auto-reload it when I focus it again.

**Comment by deanoemcke** [comment]
I suspect you are correct in your assumptions (i couldn't find the more tools -> add to desktop.. option on my chrome?).
This has been raised as an issue already in a slightly different context: https://github.com/deanoemcke/thegreatsuspender/issues/614

I don't think i'd go down the route of treating them differently to normal tabs, but including an option to allow active tabs to suspend is a possibility.

I'll close this as duplicate. Feel free to add your 2c to the other issue :)

**Comment by deanoemcke** [comment]
This has been implemented and will be available in the next release

**Comment by Wizek** [comment]
Great news, thanks!

**Comment by Wizek** [comment]
Btw, is there an estimate on when the version containing this feature may be released? E.g. roughly days/weeks/months? And/or can I follow an issue/milestone to be notified of updates of the release?

**Comment by deanoemcke** [comment]
I'm still optimistically hoping of the next month for the new release.
As for updates, if you follow the linked issue (#614) it will be given a tag of 'released' once the release is in the chrome webstore.

**Comment by Wizek** [comment]
Okay.
