### ISSUE TITLE
Display last capture Screenshot for quick visual cue

### ISSUE THREAD

**Issue by kapilrohit** [deanoemcke/thegreatsuspender#658]
Hi,

As of now when the Tab is suspended it shows the tab link and then the rest of screen is pretty much occupied by the message "Tab Suspended  Click to reload". 

Is it possible to save the screenshot before suspending the tab and use that as a background to display the message rather than a plain light blue background? This would help in quick visual identification of the tab.

**Comment by liamjohnston** [comment]
There's  screenshot capturing option in the settings. Disabled by default.
