### ISSUE TITLE
Report site that doesn't auto suspend

### ISSUE THREAD

**Issue by orschiro** [deanoemcke/thegreatsuspender#660]
Hey @deanoemcke,

Not sure how to best report a site that for some reasons doesn't automatically suspend (all other sites do).

http://www.gamestar.de/xenforo/threads/welche-musik-von-welchen-spielen-h%C3%B6rt-ihr-gerne-auch-einfach-mal-so.463266/

I made sure to not be on an input field but still this page is not auto suspending for me.

Does it work for anyone else?

Thanks!

**Comment by deanoemcke** [comment]
I'm sorry. I cannot reproduce this.
Just a few questions. 
- What version of the extension are you using?
- Do you have the screen capture option enabled? Does it work if you disable this?
- What happens if you click on the extension icon and click 'suspend this tab'?

**Comment by orschiro** [comment]
Thanks @deanoemcke!

No longer occurring with latest version from Master. :-)

![screenshot from 2018-03-14 17-53-06](https://user-images.githubusercontent.com/170947/37417437-9ce350a4-27b0-11e8-9ed7-751a2aa897d6.png)
