### ISSUE TITLE
crash on chromium 65.0.3325

### ISSUE THREAD

**Issue by xenogenesi** [deanoemcke/thegreatsuspender#666]
Hi,
I been using this extension for a while now on a Debian/Linux system (sid/unstable), it was working fine until chromium version 64.0.3282.119 (included), a recent upgrade to 65.0.3325 broke it, it just keep crashing.

Let me know if I can help in any way, and btw thanks for the extension.

**Comment by deanoemcke** [comment]
I'm not that familiar with debian sorry.
I tried installing debian stretch with gnome via virtualbox.
I installed chrome v65 and was able to add the extension and use it without issue.
Am I missing something in my test scenario?
Any ideas where to go from here?

**Comment by xenogenesi** [comment]
@deanoemcke thanks for checking, apparently that chromium build had problem with more extensions but had already been fixed (65.0.3325.146-4 installed now and is working)
