### ISSUE TITLE
Disable developer mode extensions pop up

### ISSUE THREAD

**Issue by tydude2641** [deanoemcke/thegreatsuspender#667]
Hello, I'm on windows 10 home version and the disable developer mode extensions on chrome keeps popping up trying to get me to disable TGS, I was on web store 6.3.0 but that version still has the issue error 400 with scroll pos, so I went to here and downloaded the latest 7.0.85 version through src install with developer mode, I am unable to remove the pop up as I do not have group policy editor method available to me, is there any way this could be fixed?

Edit: Not a necessarily big issue in any way, just I updated to fix error 400 and now I'm presented with a different, albeit less annoying issue.

**Comment by deanoemcke** [comment]
Sorry about that. There's no way to disable that warning unfortunately. The best you can do is keep and eye on the youtube issue thread and switch back once the release is live on the webstore.
