### ISSUE TITLE
"Only auto-suspend if running on battery" Option not Working

### ISSUE THREAD

**Issue by BigPrimeNumbers** [deanoemcke/thegreatsuspender#670]
### Specifications:
 * Extension version: Chrome Store v6.30
 * Browser & version: Chrome v65.0.3325.181 (Official Build) (64-bit)
 * Operating system & version: MacOS 10.13.3

Checking this option does not prevent tabs from being suspended when my laptop is plugged in (regardless of charging or being fully charged). Quitting and restarting Chrome does not help.

**Comment by dyaskur** [comment]
I have same problem, I just hope this will fix soon.

**Comment by deanoemcke** [comment]
Will assume this is fixed in the upcoming release v7.x
