### ISSUE TITLE
opened chrome mac and TGS sessions are all gone !

### ISSUE THREAD

**Issue by acetriper** [deanoemcke/thegreatsuspender#671]
Hi

I opened chrome mac and my tabs were all gone, (they were saved as well as a session)
I opened TGS sessions and everything is empty, no sessions there 

I believe this has happened once in the past, and reopening chrome / TGS and the sessions were reappeard,
This time they did not :(

What happened that might have cause a problem is that I was running out of space on my MBP, and I went to mail app and deleted all my internet accounts from there, maybe the lack of space when TGS was trying to save or something in relation to the that had caused the issue

Is there a place of backup on my mac that I can manually restore the sessions ?

Would really appreciate getting all my tabs back!
Thank you 

A Ben

### Specifications:
* Extension version:
TGS 6.30
 * Browser & version:
Chrome mac Version 65.0.3325.181 (Official Build) (64-bit)
 * Operating system & version:
Mac os Sierra 10.13.3

**Comment by deanoemcke** [comment]
Duplicate: #659
I believe I've been in contact with you about this over email. 
Sorry I wasn't able to be of much help :(
