### ISSUE TITLE
UX: The location of the whitelist link is confusing

### ISSUE THREAD

**Issue by mmartinez** [deanoemcke/thegreatsuspender#674]
The current location of the **"Add to whitelist"** link is too close to the title of the current tab. I believe it should be placed in the bottom right or left corner with a visible call to action in order to avoid confusion. 

What do you guys think? 

Thanks for considering the   suggestion!

**Comment by deanoemcke** [comment]
@nemanjaglumac thanks for the offer. we've actually had another person contributing and he's done some pretty cool stuff for the upcoming release: https://github.com/deanoemcke/thegreatsuspender/issues/644

your input would be welcome, if you want to check out the latest version of master.

**Comment by nemanjaglumac** [comment]
@deanoemcke I have installed it locally - it definitely looks more modern and polished. I like this new look a lot.

Two things: 
1. I don't see a SAVE button so I couldn't preview dark theme in developer mode. 
2. 768px is the last point when there is at least a little bit of horizontal margin left and after that the content isn't responsive anymore. 
However, if settings was meant to be accessed only on desktop computers, "responsiveness" actually isn't an issue, I guess :)

Overall, much much cleaner look. 
Nice job.

Best, 
N.

**Comment by liamjohnston** [comment]
@nemanjaglumac It's more 'responsive' than it used to be, but yeah - extensions don't work on mobile so it isn't really a concern :)
I miss the save button... we had one way back when. Maybe one day I'll convince Dean to put it back :) Mind you, the 'dark' theme only applies to the suspended tabs, not the settings or other pages.

**Comment by nemanjaglumac** [comment]
@liamjohnston my bad! :)
Thanks for the clarification about the dark theme.
