### ISSUE TITLE
HTML entities rendering in URL on suspended page

### ISSUE THREAD

**Issue by liamjohnston** [deanoemcke/thegreatsuspender#675]
On the suspended page, where the page's URL shows, it seems like (some?) HTML entities are being shown when they shouldn't. 

For example, my URL contains the parameter, "region". i.e. 
`...&cats=true&region=auckland`

This is rendered on the page as
`...&cats=true®ion=auckland`
because `&reg;` is the html entity for the '®' symbol.

Observed in the 'new-ui' branch, but I assume this to be happening on master.

Explanation here:
https://stackoverflow.com/questions/15532252/why-is-reg-being-rendered-as-without-the-bounding-semicolon

**Comment by deanoemcke** [comment]
A sample url would be nice ;)
But either way, is this still an issue on the latest version? I can't see any reference to the full url on the suspended tab page (except for the hyperlink when you hover the title).
Even the whitelist modal does not give any part of the url after the ?  symbol.
