### ISSUE TITLE
Importing a session deletes previously saved sessions

### ISSUE THREAD

**Issue by davidpat99** [deanoemcke/thegreatsuspender#679]
When I imported a session, the new imported session overwrote the previous imported saved session but not the saved sessions that were saved from the current session. 

Extension version: v7.0.85
Browser & version: Chrome 65.0.3325.181 (Official Build) (64-bit)
Operating system & version: Mac OSX 10.13.4 (17E199)

**Comment by deanoemcke** [comment]
Thanks for this. I can recreate it. Although, it only seems to do it when reimporting the same file? 
Not sure what's going on here but I'll take a look.

**Comment by deanoemcke** [comment]
@davidpat99 are you able to confirm that it only overwrites a session that was imported via exactly the same source file? Or are you actually losing sessions that contain different data?
