### ISSUE TITLE
Stopped working on MacOS High Sierra

### ISSUE THREAD

**Issue by sfaris** [deanoemcke/thegreatsuspender#680]
### Specifications:
 * Extension version: 6.3
 * Browser & version: Chrome 66.0.3359.117 (Official Build) (64-bit)
 * Operating system & version: MacOS High Sierra 10.13.4

Ever since I updated Chrome to version 66.0.3359.117 and my OS to MacOS High Sierra 10.13.4, The Great Suspender stopped working.  Anyone else seen this problem, or have a solution to offer?

I already tried rebooting the machine, re-starting Chrome, un-installing and reinstalling the extension (version 6.3) but with no success.

Thank you!

**Comment by sfaris-bw** [comment]
Hello - an update:

- Upgraded The Great Suspender Chrome Extension to v7.0.85
- Updated Chrome to Version 66.0.3359.139 (Official Build) (64-bit)

Same problem: none of the tabs are being suspended.  All tabs open and consuming CPU.

Is there a log file I can provide to help with debugging?

Following is an image of the options settings:

![image](https://user-images.githubusercontent.com/5339601/39898096-4837e93e-5483-11e8-90be-02089c43890c.png)

**Comment by draarong** [comment]
Hm, working for me (relatively new user, with newest everything on 2017 Macbook Pro)

**Comment by deanoemcke** [comment]
You can go to the url: chrome-extension://jmhiginckkdplecbbnnfcapnpofhmgbb/debug.html
That should show you the current status of each tab. Tabs with a status of 'normal' will be suspended. And the time-to-suspend will show you at what time that tab is due to be suspended.

Let me know if this helps. Also, at the top of that debug page, you can toggle debugInfo and debugErrors. This will cause logging to the background_page console. Perhaps the debugging page does not help, I can go through this with you.

**Comment by sfaris** [comment]
Hello, I tried your suggestion but got an error all the same.  A copy of the screen shot is attached.
![tgs error](https://user-images.githubusercontent.com/2423195/40456408-3dc48bba-5ebf-11e8-94da-0756e6ecd3eb.png)

**Comment by deanoemcke** [comment]
oh, I'm sorry. that's the wrong extension id (that's my local testing one).
you will need to substitute 'jmhiginckkdplecbbnnfcapnpofhmgbb' from that url i gave you with whatever the extension id is for you locally.
you can find this ID by going to chrome://extensions/ and searching for The Great Suspender

**Comment by sfaris** [comment]
Thank you, this worked.  The majority of tabs are indicated to be "suspended", there are a few "unknown" and a few "normal", "discarded", or "special".
