### ISSUE TITLE
Bitcoin donations don't work anymore?

### ISSUE THREAD

**Issue by Tritonio** [deanoemcke/thegreatsuspender#686]
I tried to donate a couple of bucks using bitcoin but coinbase says that bitcoin donations are permanently disabled and then takes me to the "Thank you" page.

**Comment by deanoemcke** [comment]
Yes. This stopped working when coinbase moved to the new coinbase merchant platform.
It will be re-enabled in the upcoming release.
In the meantime, if you really want to donate, here is a link to the new cypto donation page:
https://commerce.coinbase.com/charges/HRHXRR53

Thanks!
