### ISSUE TITLE
Installing latest version from master unsuspends all tabs, hammering the CPU

### ISSUE THREAD

**Issue by fwextensions** [deanoemcke/thegreatsuspender#687]
I've been running the webstore version, which was set to auto-suspend, along with the 7.0.72 alpha version, in which I had manually suspended some tabs.  About 340 tabs were open, probably ~250 were suspended.

This morning I cloned the repo and loaded the unpacked extension from the `/src` directory, without running the build steps in the readme (which I assume aren't necessary in the unpacked case). The install page for the new version opened and then Chrome and most of the OS became extremely unresponsive. 

It seems like the new version was unsuspending all the tabs that had been suspended by the webstore version.  This caused lots of memory thrashing and brought my machine to its knees.  Took about 10 minutes to get Proc Explorer open so I could kill Chrome.

![image](https://user-images.githubusercontent.com/61631/40743761-41382c28-6407-11e8-8049-9ca7ea2454cf.png)

I'm guessing the unsuspend all flow was part of the upgrade process, and installing the master version triggered that.  Maybe it's trying to unsuspend all the tabs before they get closed by an update?  If so, that's going to make the next webstore upgrade extremely painful.

More generally, I can't imagine a case where I'd want hundreds to be simultaneously unsuspended.  That "Unsuspend all tabs" menu item has always scared me.  :)  

Some suggested approaches to handling a mega-unsuspend:

1. If there are more than 20 (?) tabs suspended, an *unsuspend all* command should be confirmed by the user.
1. Unsuspend the tabs serially, instead of all at once. Unsuspend one, wait for the domcomplete event, unsuspend the next, etc.
1. Unsuspend the tab but then immediately call `chrome.tabs.discard()` on it. This will leave the tab pointing at the original page but won't load it, yet it will get automatically loaded by Chrome the next time it's activated. This should avoid huge memory usage.

2 is probably unnecessary if 3 works. I was able to get it mostly working in the console by doing:

	chrome.tabs.update(
		tabID, 
		{ url: unsuspendedURL }, 
		t => { 
			console.log(t); 
			setTimeout(
				() => chrome.tabs.discard(t.id, t => console.log("discard", t)), 250) 
		}
	)

Without the timeout, the first logged tab was showing the correctly updated unsuspended URL, but then the second showed the original suspended URL, as if nothing had changed. Adding the timeout made this more reliable, though not 100%. I'm guessing listening for a navigation or tab-updated event and then doing the discard would be more reliable.

### Specifications:
 * Extension version: latest from master branch
 * Browser & version: Chrome 66.0.3359.181 
 * Operating system & version: Win7

**Comment by deanoemcke** [comment]
Sorry about the late reply on this.
There was a brief period in time when I thought it would be a good idea to unsuspend all tabs before updating. I since realised this was a very BAD idea and removed the code.
AFAIK, the current beta release should not exhibit this behaviour.

**Comment by fwextensions** [comment]
If the unsuspend all was intentional, then the behavior I saw makes sense.  Glad that's been backed out. :)
