### ISSUE TITLE
In alpha versions, provide a way to switch suspended tabs from the webstore version to the alpha without unsuspending them

### ISSUE THREAD

**Issue by fwextensions** [deanoemcke/thegreatsuspender#689]
I'd been testing the .72 alpha version for awhile, but then stopped, as I didn't want it to suspend too many tabs that I'd then have to unsuspend to switch back to the webstore version when it was updated.  Later, I realized I could probably just rewrite the suspended URLs to use the alpha's extension ID, and then rewrite them again to switch them back to the webstore version.  

Before trying that, I installed the latest version from master, which is when I ran into the unsuspend all fiasco in #687.  After recovering from that, I went back to the .72 alpha, since I knew it behaved well, and tried rewriting the URLs of suspended tabs.  Turned out to be a little more complicated than I thought, as the `onbeforeunload` handler on the `suspended.html` page reloads the original page when the URL is changed, and I wanted to avoid dozens of suspended tabs from reloading.  I found that discarding the suspended tab before changing its URL avoided the reload.

Running this code in the background page of the alpha extension will switch all the suspended tabs from the release version to the alpha one:

```javascript
chrome.management.getSelf(self => {
	const fromID = "klbibkeccnjlkjkiokjodocebajanakg";
	const fromURLPattern = "chrome-extension://" + fromID + "/suspended.html*";
	const toID = self.id;

	chrome.tabs.query({ url: fromURLPattern }, tabs =>
		tabs.reduce((seq, tab) =>
			seq.then(() =>
				new Promise(resolve =>
					chrome.tabs.discard(tab.id, discardedTab =>
						chrome.tabs.update(chrome.runtime.lastError ? tab.id : discardedTab.id,
							{ url : tab.url.replace(fromID, toID) },
							() => {
								console.log("switched:", tab.title);
								resolve();
							}
						)
					)
				)
			), Promise.resolve()
		)
	);
});
```

When it's time to switch back to the release version, I can just reverse the IDs.  Or this could be used to move from one alpha version to another. 

There's probably a less brute-force way of doing this, and it only matters to people running development versions of the extension, but it might be nice to have a more official way of bulk-switching suspended tabs.

**Comment by deanoemcke** [comment]
tbh, i think that running some js code from the console is probably the best way to handle this use case.
the people wanting to do this are generally fairly tech-savvy, and having this as part of the official build would only cause confusion.
thoughts?

**Comment by fwextensions** [comment]
Definitely agree it doesn't belong in the GA extension, but I could imagine it showing up as an option in the Session Management section of Settings if the extension detects its ID isn't the webstore one (or it could check the `installType`).  Though it might not be worth the complication.  A link to a gist or something in the README could suffice to let people know it's possible and how to do it.

**Comment by alidan** [comment]
Ok got forwarded here due to a few of the issues I posted problems with
I never found the unsuspend all a viable option as there are a few websites I go to that would throw a fit if I unsuspended everything at once. 

I think this is a viable alternative, however doing anything with scripts goes over my head, anyone want to tell me what to do in a way that an idiot can do it?

just a side note, I think going forward there needs to be a recover option for TGS

chrome-extension://klbibkeccnjlkjkiokjodocebajanakg/suspended.html#ttl=Google&uri=https://www.google.com/?gws_rd=ssl

That should be google, Tgs should be able to see
chrome-extension://klbibkeccnjlkjkiokjodocebajanakg/suspended.html#ttl=Google&uri=
and recognize that its a tgs link

If I manually delete that string the page opens as normal so my thought would be in the icon or in the right click menu, a 'recover tab' option that would see the TGS string, remove it, and open it like normal would work, from here, I dont know if TGS needs to have the tab open, but you could get the string, remove the bit from the old one, and replace it with a new one, allowing the tab to remain suspended without forcing it open, as I said, I have websites that would hate being reopened only to be suspended again.

**Comment by fwextensions** [comment]
@alidan I assume you've installed a local copy of TGS from GitHub?  The following steps should automate what you suggested, changing the URL of the webstore version of TGS to a locally installed one.

1. Go to `chrome://extensions`.

2. Find the local version of The Great Suspender you installed.  The ID will *not* start with `klb` (which is the webstore version).

3. If it says [Background page]() next to  *Inspect views*, then click that link.  A devtools window should open.

4. Click the *Console* tab in the devtools window.

5. Copy and paste the following code into the console:

	```javascript
	function switchTabs(count) {
		chrome.management.getSelf(self => {
			const fromID = "klbibkeccnjlkjkiokjodocebajanakg";
			const fromURLPattern = "chrome-extension://" + fromID + "/suspended.html*";
			const toID = self.id;

			chrome.tabs.query({ url: fromURLPattern }, tabs => {
				tabs = tabs.slice(0, count || tabs.length);
				tabs.reduce((seq, tab) =>
					seq.then(() =>
						new Promise(resolve =>
							chrome.tabs.discard(tab.id, discardedTab =>
								chrome.tabs.update(chrome.runtime.lastError ? tab.id : discardedTab.id,
									{ url : tab.url.replace(fromID, toID) },
									() => {
										console.log("switched:", tab.title);
										resolve();
									}
								)
							)
						)
					), Promise.resolve()
				)
			});
		});
	}
	```
    
6. Type `switchTabs(1)` in the console and press <kbd>enter</kbd>.

7. The title of a suspended tab should print to the console.  Verify it's been switched to your local version of TGS.  It should have a URL like `chrome-extension://<your local copy's ID>/suspended.html#...`.

8. If that looks good, type `switchTabs()` and press <kbd>enter</kbd>.  Not passing any parameter will switch all the tabs.  Or you could do `switchTabs(20)` or whatever if you're more comfortable switching them in batches.  But it should be fine to do them all at once.

Let me know if that works for you.

**Comment by deanoemcke** [comment]
I've added a new debugging feature called 'tab claiming' which will allow you to revert any suspended tabs suspended by another version of the extension over to the current version of the extension (that is, the version running the debug page).

There is now also a handy link to the debug page in the about section of the extension options.

Duplicate of #748
