### ISSUE TITLE
Great Suspender's Ghost Is Blocking Pages

### ISSUE THREAD

**Issue by rperretta** [deanoemcke/thegreatsuspender#691]
Hi,

I removed Great Suspender but it's blocking random web pages having somehow insinuated itself in Chrome version 66.0.3359.181. I've verified that the file is no longer in the library/Appl... folder. It doesn't show up in the Chrome extensions page.

I get this in the address bar:

chrome-extension://klbibkeccnjlkjkiokjodocebajanakg/suspended.html#ttl=Kure%20%3A%20Strait%20(Ondo-no-seto)%20-%20Webcam%20Hopper&uri=http://www.webcamhopper.com/map/3976.html

And  this on the page:

klbibkeccnjlkjkiokjodocebajanakg is blocked
Requests to the server have been blocked by an extension.
Try disabling your extensions.
ERR_BLOCKED_BY_CLIENT

Any thoughts?

Thanks

Randy Perretta (GitHub ID: rperretta)
randy@perretta.net

### Specifications:
 * Extension version: Unknown - I removed it before this occurred.
 * Browser & version:See above
 * Operating system & version:Mac OS X 10.11.6

**Comment by fwextensions** [comment]
That `chrome-extension://...` URL is the page that replaces a tab when it's suspended by The Great Suspender.  I would've thought that tab would be closed when the extension is uninstalled, though.  

If you want to get back to the original page, copy everything after the `uri=` and paste that into the location bar.

**Comment by rperretta** [comment]
Hi,

I started the thread but have been out on the coast and away from the computer all week.

So I’m doing this from phone.  Hope I can help.

The upshot is that I removed the extension some time ago. Lately, I’ve had some pages blocked and Chrome reports the Great Suspender extension with the correct number as having been the one that blocked the URLs.

That’s about the most that I can say about it. 2008 MacBook Pro which I use for Solaris development (yes there are still people doing that) running El Capitan.

I’ll be back to the world next week. Let me know if I can help.

Randy

Sent from my iPhone

On Jun 15, 2018, at 5:22 PM, wildfire2020 <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm new here, and am reading before installing the app. Does anyone answer these questions coming in? I'd like to know there's somewhere to go should I run into problems after installing.

Please advise. Thank you.

**Comment by deanoemcke** [comment]
@rperretta the extension cannot affect your system once you have uninstalled it. you are somehow reopening old urls that were created while the extension was installed.

perhaps you have used another extension like session buddy to restore some tabs, and it has tried to restore tab that was suspended at the time (during the time you had the extension installed).

one solution is to reinstall the extension, then click 'unsuspend all' which will unsuspend all your tabs. then remove the extension again.

otherwise you can do as @fwextensions suggested.

**Comment by deanoemcke** [comment]
@wildfire2020 as you can see, there is some activity here, usually not by me, but by some other active github users.
if you're worried about installing the extension, my best advice is to install another extension called session buddy at the same time which will allow you to back up and restore your tabs sessions.
but as long as you ensure you unsuspend all your tabs before uninstalling the extension (should you wish to) you should be fine.

**Comment by Woofard** [comment]
Guess I'll find out how to re-open an old post here...   

Stale post, I know I know. However, interesting that I just witnessed this exact behavior after uninstalling "The Great Suspender" as well. Still happens even trying the page again, and no... not using the "Suspender's" blocking page address.  I cleared cache by the way, temp files, cookies and rebooted... yada yada..
