### ISSUE TITLE
just some questions

### ISSUE THREAD

**Issue by audi4444player** [deanoemcke/thegreatsuspender#693]
Are we going to see the store version updated at some point? and is what google's doing with the webstore only installations going to affect loading extentions directly from the computer?
Is the youtube scroll position 400 error bug fixed on the current store version?
How is the progress on making it so updates don't break everything? I know you wanted to implement that before updating the store version
Finally, a strange one, what am I using and where did I get it from , my version says 7.3.0 but I cant find a number that high anywhere, where has this come from?

I have memory issues and have forgotten how I put this on my machine, and often forget how everything works (like this website haha) so I have to re-learn, sorry if I sound completely stupid with any of these questions or if my information is completely wrong.
Thanks

**Comment by deanoemcke** [comment]
For the latest information on the date of the new release see this issue: 
https://github.com/deanoemcke/thegreatsuspender/issues/537

As for v7.3.0. I assume that must be a locally installed version? There was possibly a brief period where I may have mistakenly committed a bad version number. Perhaps your clone of the repo coincided with that? 

If you are using a locally installed version, I would suggest unsuspending (or saving) all your tabs, and then updating to the latest version from this repo.

If you are using the webstore version, sit tight. A new update is coming very shortly.
