### ISSUE TITLE
set timeout to 5mins per config

### ISSUE THREAD

**Issue by pc-dok** [deanoemcke/thegreatsuspender#694]
hi
is it possible, that when i add this extension over the Chrome ADMX GPO, that i can set a default value from 5mins to supsend the tabs, not as default 1hour?

**Comment by deanoemcke** [comment]
See this issue: https://github.com/deanoemcke/thegreatsuspender/issues/97

**Comment by allwizard** [comment]
Hi, I develop and implement custom tab suspenders, ping me hei.gb@outlook.com
