### ISSUE TITLE
Tabs Not Reloading

### ISSUE THREAD

**Issue by Merk7** [deanoemcke/thegreatsuspender#695]
I recently started using this and all was well. Now, I find 8 tabs for which "click to reload" does not work. (see screenshot attached). There is no URL available and the tabs are blank. Obviously, I have now lost these tabs, which means TGS is not working properly. Suggestions or explanation?

### Specifications:
 * Extension version: 6.30
 * Browser & version: Opera 53.0.2907.99
 * Operating system & version: Windows 10 Version 10.0.17134 Build 17134
![tgs](https://user-images.githubusercontent.com/6190251/41859819-a86a830e-7862-11e8-821a-9bbd643f4f5e.PNG)

**Comment by Merk7** [comment]
After upgrading to Opera 53.0.2907.106, the problem disappeared. Weird, since TGS previously worked in the prior version of Opera. I'm assuming it simply did not load properly for whatever reason and the browser reboot fixed the issue.  

Sorry to trouble you. Thanks for your hard work on this excellent concept.
![tgs](https://user-images.githubusercontent.com/6190251/41860995-ac436eb6-7865-11e8-981f-02fc8a09748d.PNG)

**Comment by deanoemcke** [comment]
Similar but probably different issue: https://github.com/deanoemcke/thegreatsuspender/issues/619
