### ISSUE TITLE
IDEA: Global Toggle for Suspension

### ISSUE THREAD

**Issue by osiixy** [deanoemcke/thegreatsuspender#698]
### IDEA
If I may suggest an idea
it could be a global toggle
for suspension in quick menu
which would make it possible
to pause every suspension
till further action.

**Comment by liamjohnston** [comment]
As a workaround, you can head to the settings page and change the automatically suspend' dropdown option to 'never'

**Comment by deanoemcke** [comment]
Duplicate of: https://github.com/deanoemcke/thegreatsuspender/issues/256
