### ISSUE TITLE
Form inputs clobbered on Coursera

### ISSUE THREAD

**Issue by mallove** [deanoemcke/thegreatsuspender#699]
Form inputs can get clobbered by [TheGreatSuspender](https://github.com/deanoemcke/thegreatsuspender) on [Coursera](https://www.coursera.org/learn/).

### Specifications:
 * Extension version: _v6.30_
 * Browser & version: _67.0.3396.99 (Official Build) (64-bit)_
 * Operating system & version: _Mac OS El Capitan 10.11.3 (15D21)_

**Comment by deanoemcke** [comment]
This is possible resolved with this PR: https://github.com/deanoemcke/thegreatsuspender/pull/623
Coming soon in the new release.
