### ISSUE TITLE
Add context menu for The Great Suspender.

### ISSUE THREAD

**Issue by Nemix77** [deanoemcke/thegreatsuspender#70]
Hi,

Would you be able to add an expanding context menu option for The Great Suspender with the main icon label and with all the suspend/reload functions?

I like to hide the button to keep my Chrome less cluttered but still would like to access on the fly suspend/reload functions via context menu if possible.

Thanks,

**Comment by justinsamsel** [comment]
I'm with Nemix on this. I am anti button. Having an optional context menu that allows you to right click on any page and suspend it would be the icing on the cake to this extension.

**Comment by deanoemcke** [comment]
thanks to @rvadlam1 for implementing this feature. the latest dev version now has an optional right-click context menu that replicates the popup menu.
