### ISSUE TITLE
Feature Request: Suspend all tabs when closing browser

### ISSUE THREAD

**Issue by vctrlt** [deanoemcke/thegreatsuspender#700]
I usually find myself manually suspending tabs before closing the browser so that the Chrome has a fast startup next time, trying to emulate Firefox behavior.

Would it be possible to implement an option which suspends all tabs when closing the browser?

Thank you.

**Comment by liamjohnston** [comment]
There's already the option to suspend all (or is it 'other'?) tabs - have you tried this? Still a manual process of course, but you don't need to do it on every tab.

**Comment by vctrlt** [comment]
Yes, that is what I do and what I mean by manual. I usually do "Suspend other tabs", then "Suspend this tab", then close the browser. Four extra clicks before closing the browser gets old pretty fast.

I think this feature as an extra option in the settings page would be very useful. Before finding out about this extension I would search for ways to replicate this Firefox behavior when it comes to reopening the browser and there were open threads about this functionality in StackExchange and maybe some Google forums (don't exactly rembember).

Thanks for your reply.

**Comment by fwextensions** [comment]
Depending on how many tabs you have open, I suspect TGS wouldn't have time to suspend them all before Chrome closes and kills the process.  Perhaps a shift-click on *Suspend other tabs* could be added that would suspend all (seems like too rare a use case to warrant its own menu item).  At least that would save two clicks.

Or you can *Suspend other tabs* and then use the keyboard shortcut to suspend the current one.  So two clicks and a keypress.

**Comment by deanoemcke** [comment]
@vctrlt From memory, I have tried this and it's as @fwextensions said, the tabs do not get suspended before chrome closes.
The upcoming release has a new keyboard shortcut called 'Force suspend all tabs in all windows' (also available via the right-click context menu).
This will reduce your actions down to 1 before closing (as it also suspends the currently active window).

**Comment by deanoemcke** [comment]
From this duplicate issue: #538 @H0R1Z0N suggests using the 'resuspend all' option on a previous session for the extensions session management. screen.

Also, here is a relevant chromium bug report on trying to detect chrome shutdown events: https://bugs.chromium.org/p/chromium/issues/detail?id=30885
