### ISSUE TITLE
Un-suspending radio.abc.net.au doesn't make audio play resume

### ISSUE THREAD

**Issue by orschiro** [deanoemcke/thegreatsuspender#702]
I am experiencing an issue on [1](http://radio.abc.net.au/stations/classic2/live?play=true). When I manually suspend and later un-suspend the page, the playback does not resume automatically. It gets stuck at a spinning wheel. Can someone reproduce this behaviour? I am using the latest commit version.

![image](https://user-images.githubusercontent.com/170947/42995268-b5ca3744-8c10-11e8-9348-8000fdbbf516.png)

**Comment by deanoemcke** [comment]
I'm sorry. I am unable to reproduce this.
Unsuspending that tab starts the audio playing again no problem.

**Comment by orschiro** [comment]
Dear @deanoemcke, 

I think the issue was somewhere else. 

I can't confirm it anymore either. 

Let's close it!
