### ISSUE TITLE
Hide extension context menu items

### ISSUE THREAD

**Issue by Alex-Sokolov** [deanoemcke/thegreatsuspender#708]
How to hide items in context menu?
Now, after uncheck option in setting & saving, there is item in context menu for links:

<img width="795" alt="2018-08-03 16 09 29" src="https://user-images.githubusercontent.com/4497128/43644616-1b283bae-9738-11e8-8dda-ce62dce70085.png">

### Specifications:
 * Extension version: 6.30
 * Browser & version: Chrome 69.0.3497.23, beta (64 bit)
 * Operating system & version: OS X 10.13.6

**Comment by deanoemcke** [comment]
That looks like a bug. Try checking and unchecking the 'context menu' extension option again to see if this fixes it.
There have also been some improvements to the functionality of the context menu in the upcoming release.

**Comment by Alex-Sokolov** [comment]
@deanoemcke trying without success

**Comment by deanoemcke** [comment]
ok :(
well i think the next step is to wait to see if the new release fixes the issue.

**Comment by Alex-Sokolov** [comment]
@deanoemcke when new release planned?
