### ISSUE TITLE
Add shortcut to suspend other tabs

### ISSUE THREAD

**Issue by UZR2000** [deanoemcke/thegreatsuspender#710]
Enjoying your extension for a long time. Just missing one thing. A shortcut for suspending other tabs. On my PC (Core 2 duo), it takes time to open TheGreatSuspender Menu in extension bar. Adding the said feature would be very helpful for people especially me... 
Thanks.

**Comment by liamjohnston** [comment]
Hi @UZR2000 
Is this what you're looking for?

![screen shot 2018-08-06 at 8 34 59 am](https://user-images.githubusercontent.com/1134713/43689801-b40592aa-9953-11e8-8b8d-869ed44f35e5.png)

It's available in the latest github version (not yet in the chrome web store). Instructions for using a dev extension are here: https://github.com/deanoemcke/thegreatsuspender#install-as-an-extension-from-source

You'l probably not want to have two versions of the extension running at the same time, so maybe also disable your current version of the extension while you're at it. BUT MAKE SURE YOU UN-SUSPEND YOUR TABS FIRST if you don't want to lost them.

**Comment by UZR2000** [comment]
Thank you sir! This is exactly what I am looking for.
