### ISSUE TITLE
"Click to Reload" broken in Chrome 68 on Windows 8.1

### ISSUE THREAD

**Issue by pruchkin2** [deanoemcke/thegreatsuspender#711]
"Click to Reload" broken in Chrome 68 on Windows 8.1

**Comment by deanoemcke** [comment]
@pruchkin2 can you please let me know the version of the extension you're using?
Is it happening on every single suspended page?
What happens after a chrome restart?

**Comment by pruchkin2** [comment]
v6.30
it just seems to happen after a Chrome relaunch for update or not relaunched recently

**Comment by deanoemcke** [comment]
Even though I cannot reproduce, I will assume that this issue will be made redundant by the upcoming release v7.x
