### ISSUE TITLE
Problem with Youtube after suspension

### ISSUE THREAD

**Issue by DPalmz** [deanoemcke/thegreatsuspender#713]
### Specifications:
 * Extension version: 7.0.85
 * Browser & version: Chrome Version 68.0.3440.84 (Official Build) (64-bit)
 * Operating system & version: Windows 10 Pro 64 bit build 17134
[https://gyazo.com/cc88030d12762de84c06c868bff88b29](url)

So for some reason, after I unsuspend a tab of youtube, it looks like that, theres no scroll bar, none of the buttons (other than pause/play) work, and if its in a playlist, it doesnt autoplay to the next one. Also once the problem is resolved, YT doesnt remember any of the length of the video played during this state.

Its fairly easy to fix it, so it's not a large bug, a simply page refresh will allow YT to load normally, but it is quite annoying at times, especially for videos with openings  that are irritating.

it is worth noting that this bug has been going on for at least month if not several, though it is only now I have gotten around to reporting it.

**Comment by deanoemcke** [comment]
I can't seem to replicate this. Can you please paste the following urls for me?
- The url of the youtube tab before you suspend it.
- The url of the suspended youtube tab.
- The url of the youtube tab AFTER you unsuspend it.

**Comment by DPalmz** [comment]
So it happens to me with almost every youtube video, but here's an example.


Update:
So I ran the experiment in incognito mode and noticed that the issue was not duplicated, so I went back and forced suspended and unsuspended a tab that I had open that just then was opened incorrectly. Turns out, whatever the problem is, it's with the auto-suspender.

**Comment by deanoemcke** [comment]
Will close this. But please add another comment if the issue arises again.

**Comment by DPalmz** [comment]
So whatever the problem is, it came back. Does seem to be happening much less frequently, however, so there's that.

**Comment by danpottshimself** [comment]
I had the same issue. Seemed like a caching issue. uninstalled the great suspender and cleared cache on browser and all works fine again.

**Comment by deanoemcke** [comment]
@danpottshimself That must be some internal chrome caching. Unsuspending a tab actually just calls `window.location.replace(<original-url>)` on the suspended tab.

So it's probable that it's a chrome / youtube issue. But the extension highlights the problem by causing the tab to reload from chrome cache more often than it would normally?

**Comment by danpottshimself** [comment]
FYI: The problem was with the chrome extension 'the great suspender'. I uninstalled and everything worked fine.
