### ISSUE TITLE
Suspend/unsuspend selected tabs not working in v7.0-beta.94

### ISSUE THREAD

**Issue by kankaristo** [deanoemcke/thegreatsuspender#715]
Suspend/unsuspend selected tabs is broken in v7.0-beta.94, clicking those buttons does nothing (and The Great Suspender's menu stays open).

It was working in an earlier alpha version, but I can't remember which version I used before.

BTW, the new "suspended.html" page looks great (although I liked the old icon a bit more). :smile:

### Specifications:
 * Extension version: v7.0-beta.94
 * Browser & version: Chrome 68.0.3440.106 (Official Build) (64-bit)
 * Operating system & version: Fedora 28 (Linux 4.17.14-202.fc28.x86_64)

**Comment by deanoemcke** [comment]
@kankaristo thanks a lot for catching this!
