### ISSUE TITLE
Block Welcome Site on start up

### ISSUE THREAD

**Issue by Benny1988** [deanoemcke/thegreatsuspender#716]
Is there a way to block or deactivate the welcome site on startup? We use this extension in our enviroment with many employees and that is really disturbing. 

Kind recards,
Benny

**Comment by Benny1988** [comment]
We use the extension in our terminal server enviroment. I installed it via group policy. The users get their remote desktop profile from a file server. Whenever the user logs in and chrome opens for the first time, the welcome window will appear. If they close and open it again, the Window will not appear - until the next logoff and login.

**Comment by deanoemcke** [comment]
Ah ok. I will refer you to this issue then (still unresolved): https://github.com/deanoemcke/thegreatsuspender/issues/97

Should this be implemented, you should be able to set a flag to let the extension know it is not the first time it is being installed.
