### ISSUE TITLE
screenshot / screen capture for pdf not working

### ISSUE THREAD

**Issue by umutisik** [deanoemcke/thegreatsuspender#718]
Currently for open PDFs, screen captures are showing as only a gray background. So the pdf page seen in the tab is not captured. 

### Specifications:
 * Extension version: 6.30
 * Browser & version: Chrome: 68.0.3440.106 (Official Build) (64-bit)
 * Operating system & version: MacOS 10.12.6

**Comment by deanoemcke** [comment]
Yes. Screen captures of pdfs is not currently supported. However, this feature is coming.
Please refer to this duplicate issue: https://github.com/deanoemcke/thegreatsuspender/issues/62
