### ISSUE TITLE
Excessive CPU usage with v7.0.104

### ISSUE THREAD

**Issue by stuartherbert** [deanoemcke/thegreatsuspender#722]
### Specifications:
 * Extension version:

v7.0.104, installed via the Chrome store

 * Browser & version:

Google Chrome v68.0.3440.106

 * Operating system & version:

Ubuntu Linux 18.04.

### The Problem

This new release of The Great Suspender is causing Chrome to use a lot more CPU than the previous release. `top` is showing that Chrome's CPU usage has shot up from 10% to over 50%, and Chrome's Task Manager is showing The Great Suspender as the biggest CPU user.

If I kill the Great Suspender (without touching anything else in Chrome), Chrome's CPU usage returns to around 10% in `top`. Shoots back up if I reload The Great Suspender.

I'm a laptop user who mostly works on battery power. The extra CPU usage is causing problems for other apps on the laptop, and the estimate is that it's knocked 45 minutes off the battery life. Desktop users probably won't notice the difference, but for me as a laptop user, this is a big problem.

Help :)

**Comment by deanoemcke** [comment]
@stuartherbert can you give a bit more info? specifically:
1. approximately how many tabs have you got open in your chrome?
2. are these tabs mostly suspended, mostly unsuspended, or a mix of both?
3. is this happening on chrome start only? what if you wait 5 minutes. does the cpu usage die down?

thanks for the feedback. i'm looking into this now.

**Comment by stuartherbert** [comment]
@deanoemcke thanks :)

1. 7 Chrome windows. About 120 tabs open in total. 
1. At any one time, no more than 10 tabs that are not suspended.
1. It happens on plugin load. CPU usage does not reduce over time at all. 

The plugin eventually crashed. I can't tell why from the information available to me. I can't tell if the crash was uptime-related (plugin had been running about 4 hours when it crashed) or due to an action (such as suspending a tab).

Very happy to grab any more information that you need.

**Comment by deanoemcke** [comment]
I have managed to recreate this 🎉 
I just hope that the issue on my end is due to the same thing as yours.

I'm working on a hotfix now.

**Comment by deanoemcke** [comment]
@stuartherbert the fix for this issue has been pushed to the webstore. unfortunately, do get to this version you may need to uninstall and reinstall the webstore version. either that, or wait another few days until this fix is rolled out to everyone (it's currently only targetting 5% of users, so the chances are pretty low that that will include you).

if you do uninstall/reinstall, just remember to unsuspend or backup all your tabs first!

**Comment by stuartherbert** [comment]
I've installed 7.0.109 from the Chrome Store. Thank you, it has fixed the issue I had.

For anyone else who has the problem with 7.0.104: I _had_ to uninstall/reinstall. Although I had an 'update' button showing, the update just hung.
