### ISSUE TITLE
Hotkey shortcuts forgotten during update

### ISSUE THREAD

**Issue by deanoemcke** [deanoemcke/thegreatsuspender#726]
After updating to the latest version (v7.0.104) some users (@AlexWayfer) are reporting that their keyboard shortcuts have been forgotten.

**Comment by AlexWayfer** [comment]
Yep. 

At another computer I have an old TGS version, and settings are:

![image](https://user-images.githubusercontent.com/6510020/44552339-aef07e00-a732-11e8-8811-a42fd8658492.png)

There is no `Ctrl+Shift+S`, but it works. :man_shrugging: 

And for the new version work-around (fix) is manual setting there the `Ctrl+Shift+S` (for me) for `Suspend active tab` action.

**Comment by jaekyeom** [comment]
I'm using version 7.0.85. And every time I restart Chrome, all of the shortcuts for thegreatsuspender are gone. Is this the same issue?
