### ISSUE TITLE
Dark mode should also change colour of options menu

### ISSUE THREAD

**Issue by deanoemcke** [deanoemcke/thegreatsuspender#727]
As suggested by @JonnyRedHed in: https://github.com/deanoemcke/thegreatsuspender/issues/701#issuecomment-415625882

Can the settings page also go dark when dark mode is set. Seems only logical.

Also, once dark mode is turned on could you also make the icon drop down menu dark please.

Am using with Opera (stable-latest) with its dark mode UI turned on.

**Comment by JonnyRedHed** [comment]
While we are here talking about the icon drop down menu.  This screen grab is from Opera (latest-stable) and your see the menu looks a little big with rather a lot of white space.  Apart from benefiting from being dark, when dark mode is on (in my opinion), the menu could do with a little work.  See that top text line appears to break onto another line with the 'Not Now' text.

Windows 7 x64,  is running at 125dpi.  But Opera is at 100%.

![seems a little big - copy](https://user-images.githubusercontent.com/7356491/44613204-5f7c8180-a808-11e8-89c4-44c3ed3af141.PNG)

**Comment by deanoemcke** [comment]
And while we're talking about text wrapping on the popup menu, here's the russian version (on OSX)

![image](https://user-images.githubusercontent.com/1051763/46713654-ca054780-cc25-11e8-853e-72455e5ec829.png)

**Comment by liamjohnston** [comment]
Not so bad 😊 could have a bigger line height I guess but probably not
worth the trouble.

**Comment by JonnyRedHed** [comment]
Go on, make the icon drop down menu dark for this upcoming release.   Using Opera with its dark mode on would be a lot easier on the eyes 3am when the bright drop down menu is clicked.

**Comment by deanoemcke** [comment]
Popup has been themed for night mode now (#790).
Will leave this issue open for the other screens (ie. options)

**Comment by JonnyRedHed** [comment]
Thanks.   So this will be out with 7.1 soon.

**Comment by JonnyRedHed** [comment]
Any update on this and the next main release.

**Comment by deanoemcke** [comment]
I've been swamped with moving to a new country. Giving it another regression test over the next week. Fingers crossed.

**Comment by JonnyRedHed** [comment]
Any update.

**Comment by deanoemcke** [comment]
Best to follow the milestone: https://github.com/deanoemcke/thegreatsuspender/milestone/1
I'll post any updates there. There's currently 3 open issues.

**Comment by JonnyRedHed** [comment]
The new dark mode is looking good. Thanks.
