### ISSUE TITLE
Improve clickable / non-clickable areas of the suspended page top-bar

### ISSUE THREAD

**Issue by fwextensions** [deanoemcke/thegreatsuspender#732]
Seeing the new suspended page in v109, the first thing I tried doing was drag select the URL to copy it.  But as soon as the mousedown happened, the page started reloading.  Not a big deal, but I would've expected to be able to copy the URL and/or title of the page by drag-selecting the text, which was possible in the old version.

**Comment by fwextensions** [comment]
Ah, you can drag select on the title if you start the drag at the very beginning of the text.  If you start it on either side of it, it'll trigger an unsuspend.  I think because the whole top bar was unclickable before, it was easier to select the title.  

The URL doesn't seem to drag selectable no matter where I start, but I agree that right-clicking is generally a better approach.  It's just that I saw both lines of text and thought it could be useful to select both to copy both.  Minor thing, though.

**Comment by deanoemcke** [comment]
Ah yes. That is unfortunate about starting your click outside of the text.
I think the main thing here is that using onmousedown is just a bit strange in general and i should probably look at changing it in future.

For the URL, yes, it's not drag selectable at all. As mentioned above, it's not something i thought to test as i always used right-click on the url portion.

**Comment by deanoemcke** [comment]
Related issue: https://github.com/deanoemcke/thegreatsuspender/issues/741
