### ISSUE TITLE
Session management in incognito mode missing

### ISSUE THREAD

**Issue by distancerunning** [deanoemcke/thegreatsuspender#736]
Don't know if this counts as an issue or a request but my version of great suspender just updated and as of now I can no longer find session management when incognito and as someone who browses almost exclusively incognito would love to have it back

### Specifications:
 * Extension version: v7.0.109
 * Browser & version: Chrome Version 68.0.3440.106 (Official Build) (64-bit)
 * Operating system & version: Windows 10

**Comment by deanoemcke** [comment]
This was removed intentionally as i don't feel like I should be showing this kind of information in incognito mode. People use that mode primarily for privacy, and i thought the extension should respect this. For those that are not aware of the session management features of the extension, they may be shocked to know that it is recording their incognito session history.

Can I recommend that you use a separate session management extension for this purpose? Perhaps session buddy or Tabs Backup & Restore.

**Comment by abishek28007** [comment]
this seems a bit odd, you might allow users to make such decisions. I feel dumb for being updated the extension
