### ISSUE TITLE
Option to force the update [enhancement]

### ISSUE THREAD

**Issue by SALITEL** [deanoemcke/thegreatsuspender#737]
### Feature request:
 * If you have several Chrome sessions on different computers, you only update in the first one, so you need an option in "Settings" to force the search for updates.

----------------------------------------------------------------------------------------------------

### Specifications:
 * Extension version: (update error on update to 7.0.108) - Actual 7.0.109
 * Browser & version: Chrome Last Version x64
 * Operating system & version: Windows 10 and Windows Server

**Comment by deanoemcke** [comment]
Do you mean that the extension only updates on one computer? Or only on one profile?
If you have multiple computers all logged into the same chrome profile, do they not all update to the same version?

As for forcing the update, if you go to `chrome://extensions/` you should see an 'update' button at the top which should force all extensions to update if there is a new version available.

**Comment by liamjohnston** [comment]
Note - I'm pretty sure the 'Update' button only appears if you have developer mode turned on.

**Comment by SALITEL** [comment]
@deanoemcke 
They all have the same profile. I think that Google communicates to other browsers that it is already updated and does not update.

Changing to developer mode and pressing update does nothing in the second installation of the same profile. That's the problem.

I had to uninstall it all and reinstall it again.

In the last version, before updating, I waited for the update message to appear in the two browsers. Then I have given to update on each without problems.

**Comment by SALITEL** [comment]
@liamjohnston 
Effectively, but it does not do anything in the second installation with the same profile.

I think Google marks the extension as "updated"

**Comment by SALITEL** [comment]
In another of my computers that has the Chrome browser with my profile has happened again.

It has version 6.30, I tell it to update in developer mode but it does not do anything.

I have executed:
chrome-extension: //klbibkeccnjlkjkiokjodocebajanakg/update.html

And it shows: "The Great Suspender has been updated" but it's still in version 6.30

**Comment by liamjohnston** [comment]
To be clear (as this may not have actually been mentioned anywhere): the new version is currently being rolled out gradually. Only about 10% of users currently. 

This is so we can catch any issues early before hitting all 1.4m with those issues.

The only way _currently_ to guarantee getting the new version is to remove and reinstall from the web store. 

As for why the same profile on different computers isn't getting the same version, I guess this might just be a limitation of Chrome's extension update functionality. The user targeting functionality does seem pretty basic.

For instance:
The new TGS is being rolled out gradually. When uploading a new version to the webstore, you can set a % of users to get a new version (e.g. 5%). 
But then when you want to release a hotfix or update, there's no way to target that same 5% of users.

My expectation _was_ that it would be based on Chrome profiles. But then again, you don't have to have a profile set up to use Chrome (and probably a massive portion of Chrome users don't).

**Comment by rebeccaralls** [comment]
Conversely - I have several profiles on the same computer - and only one of them has updated. I would like them all to get updated - the new interface is nicer! But I haven't figured out a way to make it happen.
