### ISSUE TITLE
Feature Request: Temporarily whitelist certain tabs

### ISSUE THREAD

**Issue by heavydoc** [deanoemcke/thegreatsuspender#744]
The feature request is for a way to temporarily disable auto-suspend on specific tabs, for the session (until browser closes or reboots).

When I do research, I open a bunch of web pages that I need temporarily, and there are certain tabs I TEMPORARILY don’t want to auto-suspend, BUT I also don’t want to white-list them either, because I don’t want to go through the trouble of un-white-listing them later.

There are different ways to implement the above. Some suggestions are:
1. For example, an implementation can be a settings-option, for if I select any of the text on the page (turn the text blue, with my mouse). (e.g. settings check-box text: “Never suspend tabs that have selected text”).
2. OR an alternative idea/implementation: an option in the Great Suspender drop-down menu: "Don't suspend this tab, for this session".

I think this option would be very handy for those of us doing research. Thanks for listening!

**Comment by liamjohnston** [comment]
The latest version(s) have this. See 'not now':
<img width="343" alt="screen shot 2018-08-29 at 8 06 49 am" src="https://user-images.githubusercontent.com/1134713/44747942-96cd9400-ab62-11e8-9761-1e3c37f860cb.png">

You can also set a keyboard shortcut for it (mine is command + shift + D)

**Comment by deanoemcke** [comment]
Closing this as it is already implemented (as @liamjohnston has demonstrated).
