### ISSUE TITLE
New tabs starting suspended

### ISSUE THREAD

**Issue by DrGaellon** [deanoemcke/thegreatsuspender#746]
* Extension version: v7.0.103
 * Browser & version: Chrome 68.0.3440.106 32-bit
 * Operating system & version: Windows 7 Enterprise SP1

Anytime I open a site in a new tab (either by right-click or by using Linkclump), it opens as a suspended tab.  If I open in the same tab, or by pasting the URL into the address bar, it works normally. I can't seem to find any way to make this behavior stop.

**Comment by fwextensions** [comment]
Maybe unchecking the *Instantly suspend when system memory gets very low* option would change that behavior?  Also, 7.0.109 is the latest version in the webstore, so you might try clicking *Update* in the Extensions page to force it to update (I think Developer mode has to be on to see the button).

**Comment by DrGaellon** [comment]
I don't believe so. I will test this when I get back to the office on Thursday. Thanks.

Randy
The content of this email is by me. The errors are by autocorrect.
