### ISSUE TITLE
Improved session management features

### ISSUE THREAD

**Issue by c933103** [deanoemcke/thegreatsuspender#749]
Hello, I was using some other session management tools, however because those other session management tools are unable to save and restore actual information within each tabs, like next/previous tab that I was browsing, where I scrolled down to in each tabs, half filled forms inside each tabs, placement/order of previously closed tabs when I hit Ctrl+Shift+T, I am looking for other extension that can do better tasks than those. Can this TheGreatSuspender extension help save and restore these informations about tabs?

**Comment by deanoemcke** [comment]
No sorry. There's a lot that you're asking for there. And I agree that some of those things would be great to have.

I think that these features belong in a different extension to The Great Suspender. This extension is limited to increasing browser performance, not providing a fully featured session management tool.

However, it does handle some of the things you've requested. Just not quite in the way you'd probably expect.

- Next/previous tab information for each tab: If you restore a session with the TGS session manager, it will not remember the tab history of each tab. Although I am working on another extension (Spaces) that will do this eventually.

- Current scroll position in each tab: TGS will remember the scroll position when it suspends a tab, and move back to that position when the tab is unsuspended. However, if you restore a session from the session manager, it will not remember scroll position when it reloads the tab.

- Half filled forms inside of tabs: TGS allows you to prevent tabs that have half-filled forms from suspending. But if you close the tab or manually suspend it, it will lose that information. I'm not aware of any extension that provides the ability to restore form information. I feel like it would be a pretty tricky thing to get right for all the different kinds of websites out there. And also a slight privacy risk.

- Position of tab within a window when you 'undo close' a tab: I'm not sure what you mean by this. The native chrome functionality works fine here. Are you suggesting that if you restore a session, it should also remember the closed tabs, and allow you to reopen them with Ctrl+Shift+T ? I can understand wanting to keep a record of closed tabs (once again, my other extension Spaces does this), but it doesn't make sense to me to be able to use Ctrl+Shift+T to reopen them, unless they were just closed in the current session (in which case chromes native functionality would work).

Hope that helps. Keen to hear your ideas as they are very similar to things I've thought about in the past and am trying to solve.

**Comment by c933103** [comment]
Humm I see.
As for "Position of tab within a window when you 'undo close' a tab", yes the native chrome functionality would work fine however the reason why I am looking at and use third party session recovery tool is because chrome's native functionality very frequently fails.
So that, if I close a tab by accident, and then Chrome crashed itself and fails to restore properly and then I have to use third party tools to restore the session, if I click Ctrl+Shift+T the previously closed tab would still come back, however that tab would not located at proper location (e.g. the 50th tab in the 3rd opened chrome window) as it was originally located at.

**Comment by neuhausneuhaus** [comment]
@deanoemcke I think that this and many future feature requests could be addressed by adding documentation on outside session management options (ideally with notes on their compatibility with greatsuspender)

**Comment by ossilator** [comment]
this should be closed (as a dupe?) at this point, no?
