### ISSUE TITLE
reposition "set keyboard shortcuts" button

### ISSUE THREAD

**Issue by NewUserHa** [deanoemcke/thegreatsuspender#754]
currently, the "set keyboard shortcuts" which is a hardly used button is at so middle and can cause misclick.
I misclicked it some times.

what do you feel about it?
what about put it 5% near the bottom edge?

**Comment by liamjohnston** [comment]
I'd rather not move or change it.

As a workaround, you can set a shortcut. This will stop it being a clickable link. You don't have to actually use the keyboard shortcut 😊

**Comment by NewUserHa** [comment]
I mean, the users may not want to set shortcuts for suspender because it already handles everything automatically.
but the position of the button is to close to the middle of a suspended page.
