### ISSUE TITLE
gsScrollPos cookies

### ISSUE THREAD

**Issue by hd-info** [deanoemcke/thegreatsuspender#755]
### Specifications:
 * Extension version:
 * Browser & version:
 * Operating system & version:

**Comment by hd-info** [comment]
Great suspender leaves a lot of gsScrollPos-<number> cookies. These cookies after a while affect google sites: maps, search, etc.. so some features on these sites does not work: map segments won't load on maps.google.com or Tools menu doesn't work on google.com.

**Comment by deanoemcke** [comment]
please refer to this issue: https://github.com/deanoemcke/thegreatsuspender/issues/537
