### ISSUE TITLE
Accept donation on Liberapay

### ISSUE THREAD

**Issue by MartinDelille** [deanoemcke/thegreatsuspender#764]
I'm working on this Patreon like donation system: https://liberapay.com

The code is fully opensource: https://github.com/liberapay/liberapay.com

Would you accept donation through this system?

I'll be happy to give you more information if needed!

**Comment by deanoemcke** [comment]
@MartinDelille Thanks for the info on your project. It looks great.
At this point I've only just implemented Patreon support and will see how it goes for a while before I commit to anything else.
Out of curiosity (and ignorance sorry) how do you differ from Patreon?

**Comment by MartinDelille** [comment]
@deanoemcke It is very similar. The difference is that there is no fee so when you give, more go to the creators. Liberapay is funded on Liberapay so everybody can give to the foundation like any other creator.
