### ISSUE TITLE
Chrome Extension Not Updating

### ISSUE THREAD

**Issue by wwwKris** [deanoemcke/thegreatsuspender#765]
The Chrome extension doesn't seem to be automatically updating to newer versions. I use multiple profiles in Chrome and one profile was stuck on v6, which I fixed by uninstalling and reinstalling the extension. Another profile is stuck on v7.0.104 when the latest version according to Web Store is 7.0.109.

Is there something I need to do to cause them to update?

### Specifications:
 * Extension version: 7.0.104 and v6
 * Browser & version: Chrome 69.0.3497.100 (Official Build) (64-bit)
 * Operating system & version: Windows 10 x64

**Comment by liamjohnston** [comment]
The gradual rollout is paused while some last fixes still being made/tested.
