### ISSUE TITLE
Help for something

### ISSUE THREAD

**Issue by teimon** [deanoemcke/thegreatsuspender#766]
## I have a suggestion for settings:
* When you reopen closed tabs, or open links on a new tab, it starts already interrupted (to avoid processing spend until clicked)
if it is possible to be valid also, when opening the browser (chrome) with the option marked "return from where stopped", only load the tab which was (only loaded)

----------------------------------------------------------------------------------------------------
**NT:** sorry for poor english T.T

**Comment by deanoemcke** [comment]
Please refer to these other issues:
For suspending tabs opened with 'open in new tab': https://github.com/deanoemcke/thegreatsuspender/issues/655
For suspending tabs on browser restart: https://github.com/deanoemcke/thegreatsuspender/issues/49

The best you can do right now to achieve what you want it to set the 'Automatically suspend tabs after' option to 20 seconds.
