### ISSUE TITLE
Opening multiple repeat of tabs

### ISSUE THREAD

**Issue by CertaSolutions** [deanoemcke/thegreatsuspender#768]
I have 5x tabs that open with Chrome. TGS opens 2 or sometimes 3 sets of these which is annoying...
Any fixes for this?

**Comment by deanoemcke** [comment]
Can you please provide a bit more information?
Firstly, what version of the extension are you using?
Secondly, can you please explain what you are doing when this happens?
That would be really useful in diagnosing your issue.

Some questions:
- WHEN does TGS open 2 or 3 sets of tabs? On chrome restart? Or when you try to restore a session from the TGS session manager?
- Does 5x tabs mean 50 something tabs? Or 5 windows of tabs?
- When you say 2 or 3 sets of them, do you mean the 50 something tabs get opened in 2 or 3 different identical windows?

**Comment by dashingassist** [comment]
I think that this is also what's happening to me. When I close my windows in Chrome at the end of the night when I reopen Chrome in the morning I get a double set of my startup tabs (that I have set in Google) as well as the tabs that were open when I closed the window and shut down Chrome (I use a Mac).

![screen shot 2018-10-04 at 12 46 17 pm](https://user-images.githubusercontent.com/43858098/46489504-8ba9fb80-c7d3-11e8-9fe0-e024198522d7.png)

**Comment by dashingassist** [comment]
Dean,
I notice the issue in v7.0.109. I use multiple Google profiles and use the
extension in all of them. I have been systematically upgrading them by
uninstalling v6.30. I've included screenshots of the general settings for both. 1. 
    No, I don't close each tab until there is one left. I never had to do that
    in the older version. When I'm finished for the day I close out the window
    regardless of what tabs are still open.
 2. 
    No, I don't usually turn off my iMac. Each night I close all programs and
    then the next day will start again. I do ensure that the programs, Chrome is
    completely closed when I leave the office.
 3. 
    I restart my computer once or so a week but it is really more so dictated by
    system updates.
 4. 
    Yes, I reopen Chrome each day. I do have multiple windows with multiple tabs
    because I use different profiles.
 5. 
    Yes, I see the startup tabs and whatever tabs that were open when I closed
    the window and quit Chrome.



LaToya M. Davidson-Perez  
Owner - BBA, MLIS & MEd,
Davidson Administrative Services  706.623.7835 706.383.7727 
latoya@dashingassistance.com Skype: latoyadavidsonperez  
www.dashingassistance.comSchedule a 15-Minute Meeting:  https://goo.gl/kKWr44  
Confidential: This communication and any attachment(s) may contain confidential
or privileged information and is intended solely for the address(es) or the
entity representing the recipient(s). If you have received this information in
error, you are hereby advised to destroy the document and any attachment(s),
make no copies of same and inform the sender immediately of the error. Any
unauthorized use or disclosure of this information is strictly prohibited.  





On Thu, Oct 4, 2018 2:25 PM, Dean Oemcke notifications@github.com  wrote:
@dashingassist  can you also tell me what version of the extension you are
using?

and to double check your exact process:

 1. you close each chrome window manually until there are no windows left.
 2. you turn off your computer.
 3. you turn your computer back on.
 4. you reopen chome.
 5. you see your startup tabs, as well as having (one?) extra window containing
    the tabs from the last window you closed the night before?

**Comment by dashingassist** [comment]
Indeed. It is odd. I hope that that is ironed out soon. Thanks for following
up.

LaToya M. Davidson-Perez  
Owner - BBA, MLIS & MEd,
Davidson Administrative Services  706.623.7835 706.383.7727 
latoya@dashingassistance.com Skype: latoyadavidsonperez  
www.dashingassistance.comSchedule a 15-Minute Meeting:  https://goo.gl/kKWr44  
Confidential: This communication and any attachment(s) may contain confidential
or privileged information and is intended solely for the address(es) or the
entity representing the recipient(s). If you have received this information in
error, you are hereby advised to destroy the document and any attachment(s),
make no copies of same and inform the sender immediately of the error. Any
unauthorized use or disclosure of this information is strictly prohibited.  





On Thu, Oct 4, 2018 7:22 PM, CertaSolutions notifications@github.com  wrote:
I haven’t quite figured out exactly why it does it as it seems to differ
slightly each time, but here’s an example. I closed all apps (incl Chrome) last
night, then shut my HP Elitebook down and took it home. Upon starting up I
opened my usual apps, then Chrome and it opened up all the tabs I had open
(before closing) last night plus my pinned tabs… 

Regards; 

[cid:image001.png@01D45CA6.08E5C730] 
[cid:image002.jpg@01D45CA6.08E5C730]<https://www.certasolutions.nz/specials>

**Comment by deanoemcke** [comment]
@CertaSolutions @dashingassist sorry about this guys.
i've worked out what is going on. session recovery is being triggered for you even though you have chrome set to 'open a set of specific pages'. 
my extension kindof assumes that everyone uses 'continue where i left off' :/

anyway, i have pushed a fix for this now (v7.0.127). it will be included in the webstore version soon.

**Comment by liamjohnston** [comment]
'Continue where i left off' is _not_ the default setting. So it's highly a lot (maybe most) TGS users don't have that setting on.

**Comment by CertaSolutions** [comment]
Cool thanks



Regards,
Matt Williamson
Certa Solutions
0800423782
(Sent from mobile, please excuse any brevity, typos and word auto-select)

-------- Original message --------

**Comment by dashingassist** [comment]
Thanks for the update. I look forward to v7.0.127. It appears that only
v7.0.109 is available presently.

LaToya M. Davidson-Perez  
Owner - BBA, MLIS & MEd,
Davidson Administrative Services  706.623.7835 706.383.7727 
latoya@dashingassistance.com Skype: latoyadavidsonperez  
www.dashingassistance.comSchedule a 15-Minute Meeting:  https://goo.gl/kKWr44  
Confidential: This communication and any attachment(s) may contain confidential
or privileged information and is intended solely for the address(es) or the
entity representing the recipient(s). If you have received this information in
error, you are hereby advised to destroy the document and any attachment(s),
make no copies of same and inform the sender immediately of the error. Any
unauthorized use or disclosure of this information is strictly prohibited.  





On Fri, Oct 5, 2018 11:02 PM, Dean Oemcke notifications@github.com  wrote:
@CertaSolutions  @dashingassist  sorry about this guys.
i've worked out what is going on. session recovery is being triggered for you
even though you have chrome set to 'open a set of specific pages'.
my extension kindof assumes that everyone uses 'continue where i left off' :/

anyway, i have pushed a fix for this now (v7.0.127). it will be included in the
webstore version soon.
