### ISSUE TITLE
Why does this extension need permission for https://*/*?

### ISSUE THREAD

**Issue by derSascha** [deanoemcke/thegreatsuspender#769]
Hi,

thanks for the great extension. After looking into the [manifest.json](https://github.com/deanoemcke/thegreatsuspender/blob/master/src/manifest.json#L11-L12
) i'm a little bit confused about this:

    "permissions": [
        "http://*/*",
        "https://*/*",

The extension suspends tabs, why does it need _any_ internet access at all?

**Comment by deanoemcke** [comment]
Please refer to this issue: https://github.com/deanoemcke/thegreatsuspender/issues/213
tldr: it needs to run a content script on every active page.
