### ISSUE TITLE
Suspend This Tab Now - not responding. While "Suspend All Other Tabls" working

### ISSUE THREAD

**Issue by William6868** [deanoemcke/thegreatsuspender#770]
I had this great extension on my old laptop (and still do). Today I installed my new laptop and saw that "Suspend This Tab Now" - not responding. While "Suspend All Other Tabls" working on the same tabs.

Would love to give more info if needed.
Loved this extension!

Thanks for future help :-)

### Specifications:
 * Extension version: v7.0.109
 * Browser & version: Chrome Version 69.0.3497.100 (Official Build) (64-bit)
 * Operating system & version: Windows 10 pro. installed and updated today to latest version. Version	10.0.17134 Build 17134

**Comment by William6868** [comment]
close... In #735 I found an answer linking to #657 where someone wrote:
"People have suggested using https://github.com/tsayen/dom-to-image instead of html2canvas (as a solution to the above issue).
I will look into this as part of: #677 "

But I didn't understand how to use dom-to-image... any suggestions?
Thank you very much!

**Comment by William6868** [comment]
Thanks! Working well now :-)

**Comment by deanoemcke** [comment]
@William6868 hopefully within a week.
