### ISSUE TITLE
Centralize deploy settings

### ISSUE THREAD

**Issue by schitthab** [deanoemcke/thegreatsuspender#771]
Hi,

how is it possible to export/import the settings for administrative deployment. We want to set some default settings for many users. 
Where are the settings stored? 
Is it possible to set the settings via group policy as default or not changeable for users?

OS: Windows 10 / Windows Server 2016

Thx

**Comment by AtumVirt** [comment]
The settings are in local storage.  It is not possible currently but this issue sounds similar to this request

https://github.com/deanoemcke/thegreatsuspender/issues/97

**Comment by deanoemcke** [comment]
Thanks for replying to this @AtumVirt

**Comment by Enissay** [comment]
@AtumVirt It is a much have functionality. In the meantime, it would've been nice to share a way to do it manually for those who needs it really (get it from local storage and move it to the new system's LS)
