### ISSUE TITLE
Tabs no longer auto suspending.

### ISSUE THREAD

**Issue by chrcoluk** [deanoemcke/thegreatsuspender#773]
Chrome 69 64bit
Windows 8.1 64bit
Extension version v7.0.109

I have the option automatically suspend tabs after XX mins enabled, previously this used to work as expected, at some point it stopped working, I dont know exactly when it stopped, I think it may be around the time the UI style for the great suspender changed.  Now tabs either stay open forever or just eventually get discarded using chrome's horrible discard system.  The only way I can get tabs suspended now is by right clicking the tab and doing it manually.

I have tried disabling all the options that prevent auto suspension like excluding pinned tabs, forms etc. but it doesnt work still.

**Comment by deanoemcke** [comment]
Is it possible that chrome discarding is happening before your XX mins timeout?
There is also another option near the bottom called 'Instantly suspend when system memory gets very low '.
Is this checked? If so, then tabs should automatically suspend if they get discarded BEFORE the time to suspend completes.

**Comment by CollinChaffin** [comment]
Nope, I do not have that enabled and never have.  I have tried with and without the new other option of `Apply Chrome's built-in memory-saving when suspending` however it has no effect.  I'm opening a third issue now on yet another bug I've found on this latest commit you guys are doing great on this it must just be a bad string of luck on these.  Let me know what else I can try it would certainly be helpful to perhaps look at adding an additional (even hidden on the about page etc.) of a checkbox to enable debug logging to help really narrow these down quicker.

**Comment by deanoemcke** [comment]
There is actually a debug screen you can access. Open the extension settings screen and then change the URL from options.html -> debug.html
From here, you can enable info and/or error logging which will then be visible from the extension background page.

Are you still having the issue of tabs not suspending on the latest development version (v7.0.129)?
If so, can you try these steps for me:
1. Go to options and change 'Automatically suspend tabs after' to '20 seconds'. Also ensure that you have screen capturing disabled.
2. Create a new tab and navigate to 'www.google.com' (ensure it is not whitelisted).
3. Focus on a different tab in the same window and wait 20 seconds.
4. Check to see if the other 'www.google.com' tab suspends automatically.

Thanks.

**Comment by deanoemcke** [comment]
@CollinChaffin I've just re-seen this issue and realised it's probably the one you were referring to in issue #781 where you wrote:

> ...since as of last night all had finally been fixed to at least show favicons EXCEPT in the most important one - the automatic "wait 15 min" suspend which is STILL broken. I also shot a video of that over in issue 478 (several, actually) to back up what others had already reported.

I can't see any video depicting this issue over in 478 however. And I also notice I had already provided you with instructions for enabling logging here above. Perhaps you missed it ;)

I'll copy and paste my relevant comments from 781 here for clarity:

> You mentioned that you would report back with results but seeing as you haven't i assumed the issue was resolved. It's odd that you specifically mention 15 minute auto-suspend. I would have thought that it was equally as likely to occur with any time period. I use the 20sec timer when testing this stuff and haven't had any issues with the favicons on automatic suspend so far. Once again though, if you can replicate this, a recording of the log during the issue would be super useful, especially if you can identify the tab id that is causing issues, as all log entries report their tab id to help follow the process flow for each tab.

**Comment by CollinChaffin** [comment]
See #478 

![thumbs-up-sign_1f44d](https://user-images.githubusercontent.com/9301483/49098619-3506ee00-f267-11e8-9805-f69f742acc87.png)

**Comment by chrcoluk** [comment]
Sorry I didnt respond, tabs were not been discarded within the time I configured, I know when they discarded as there is a delay when clicking and the tab icon dims.

I eventually stopped using the great suspender, so have moved on from it, but since you added a debug feature, I may test it on a test machine to see if I can provide further info.
