### ISSUE TITLE
After Restarting PC and opening Chrome all the tabs unsuspend.

### ISSUE THREAD

**Issue by goldenmane** [deanoemcke/thegreatsuspender#774]
Hi. 

After I restart my PC and open chrome, every single tab that was suspended isn't causing 100's of tabs to open and ram usage going over 99% thus freezing PC for a while before i can click suspend on the extension. 

This happens only when restarting PC, not when restarting chrome itself. 

Chrome remember which tabs were open, but The Great Suspender doesn't seem to remember which tabs were suspended, which is pretty weird. 
However it does suspend some individual sites, but only a few of them and at random.

I can only suspect this might have something to do with Clear Pagefile on Shutdown i enabled a while ago for security reasons in Windows, that's why I have to ask, are some files for the extension kept in the page file or is it some kind of bug?

**Comment by goldenmane** [comment]
Also, I noticed that my version of TGS is 6.3 while the version in Chrome Store is 7.0.109? But when I click on update it says that it is already updated? Any reason why it won't update to the newer version?

**Comment by liamjohnston** [comment]
The rollout of "automatic updates" of the new version is rolling out gradually. You can keep waiting and you'll get it once it rolls out to 100% of people. Otherwise you can uninstall it completely and reinstall from the web store, BUT if you do that, make sure you unsuspend your tabs first and make a backup of your whitelist.

**Comment by deanoemcke** [comment]
@goldenmane not sure what's going on there sorry. but i would recommend updating (or waiting) for the new version. 
a lot has changed and there's not much point in investigating an issue like this on an older version.

**Comment by goldenmane** [comment]
I understand, I shall wait for the new version to update for me. Thanks.
