### ISSUE TITLE
GPU Process Staying Inflated

### ISSUE THREAD

**Issue by TheBashar** [deanoemcke/thegreatsuspender#78]
I was having a lot of pagefile thrashing and I found the GPU Process was consuming 1.5GB of RAM.  I ended the GPU Process and it restarted and consumed back up to 1.5GB.  The 2nd largest process (500MB of memory) was the Great Suspender.  I ended that process (the suspender crashed of course) and the GPU Process dropped down to 200MB.  I guess the GPU Process is holding on to rendered data for the suspended tabs.

**Comment by deanoemcke** [comment]
It is very likely that suspended tabs will add extra memory usage to the GPU process - however, this memory usage should be much smaller than the combined memory of the tabs before they were suspended. 
Are you using the screen capturing option? If so, this may be adding the the memory usage.

**Comment by TheBashar** [comment]
Hi, thanks for the response!  No, I was not using the screen capturing
option.  It's probably safe to close this issue out.  I think it got
dramatically better somewhere in the last year.  I just did a quick check
and the GPU process is using a reasonable 108MB even with 25 recently
suspended tabs.  I think Chrome probably fixed some overly greedy caching
algorithm.

Thanks again!

-- Steve
