### ISSUE TITLE
Tabs placed in reverse order as saved upon session restore

### ISSUE THREAD

**Issue by CollinChaffin** [deanoemcke/thegreatsuspender#780]
Latest commit bf02517 from today (Oct 8th) upon opening a saved session, tabs are in perfect order with one issue - they are perfectly reversed.  When you are used to a left to right workflow and they restore backwards it really makes things difficult.  They had been restoring totally out of order so this is definitely a step-up, but since the order is now finally correct....could it possibly be reversed? :wink:

It would be awesome to finally know that full window restores will be exactly in the state they were in when suspended/exited, including the order.  Thanks and keep up the great work just let me know if I can test anything to assist!

**Comment by deanoemcke** [comment]
This is an odd one. I've never seen this happen on any version (either reverse ordered OR randomly ordered).
However, looking at the code, it IS conceivably possible for it to happen.
I have pushed some optimistic changes to try to ensure that tab order is preserved upon session restore.
Let me know if you still have issues on v7.0.129

**Comment by CollinChaffin** [comment]
It does appear in today's commit 238bfa1 that when I save a session of many suspended tabs with TGS, then restore them (with SB), that it is again restoring in the original stored order so let's close this one for the time being.  Thanks!
