### ISSUE TITLE
Unsuspend on focus not working with 'you are not connected to the internet' message

### ISSUE THREAD

**Issue by kraymitchell** [deanoemcke/thegreatsuspender#783]
I get this error sometimes after coming back from the weekend. Quitting Chrome and restarting seems to fix it, but it's a bit of a pain remembering to refresh after clicking the tab if I can't restart at that time.

My computer gets shut down every night and started up fresh. This is not consistent, and I can't seem to forcefully reproduce this, it just happens. 

### Specifications:
 * Extension version: v7.0.109
 * Browser & version: Chrome 69.0.3497.100 (64bit)
 * Operating system & version: OS X 10.13.6

**Comment by deanoemcke** [comment]
I'm assuming you are actually connected to the internet when this happens?
And also assume you've got 'Automatically unsuspend tab when it is viewed' option checked.

I will look into this. It's possible it has something to do with you bringing your computer out of sleep mode.

**Comment by kraymitchell** [comment]
Hey Dean,

Absolutely as I'm using the internet in other tabs that are not asleep. I
also have it automatically unsuspend.

It's a MacBook Air, so little ram and Chrome is a hog, so this has been
VERY handy!

Regards,

Kray

*KRAY MITCHELL* · k@kraymitchell.com · 250.212.1566

**Comment by deanoemcke** [comment]
How often would you say it happens? It sounds very much like this chromium bug: https://bugs.chromium.org/p/chromium/issues/detail?id=678075

The extension relies on `navigator.onLine` to determine if there is internet connectivity. 
As a workaround it sounds like disconnecting and reconnecting your internet should fix it (as opposed to restarting chrome).
