### ISSUE TITLE
Can't install/load extension, manifest file is missing or unreadable

### ISSUE THREAD

**Issue by mauigirl** [deanoemcke/thegreatsuspender#788]
I uninstalled my old chromestore version and trying to install 7.0.109 manually from here. this is the message i receive the following message, have tried repeatedly. for now i will go back to the old chromestore version until we can figure out what this is about:

Failed to load extension
File
~/Downloads/great suspender 7
Error
Manifest file is missing or unreadable
Could not load manifest.

extension: 7.0.109
chrome 69.0.3497.100 (Official Build) (64-bit)
mac os  10.13.6

**Comment by mauigirl** [comment]
when i went back to chromestore, since i had uninstalled my old version it now presented me with current 7 version and i was able to install that just fine. don't know what the problem is with installing from source but good to know we can get current non-beta through the main stream.

**Comment by deanoemcke** [comment]
@mauigirl i think your issue is that you need to point it to the `src/` folder.
In your case it seems like that would be `~/Downloads/great suspender 7/src`

Glad that you resolved your issue anyway :)
