### ISSUE TITLE
Remap keys not working onn Firefox

### ISSUE THREAD

**Issue by pandaassassin987** [deanoemcke/thegreatsuspender#789]
As you can see [here](https://gyazo.com/e6d2f8843f8e7f0f0ea30c980615f89c), the remap keys features for TGS is not working in Firefox. This is a problem isolated to just Firefox, as it works in Chrome on the same computer. Everything else including the preset shortcuts still works.

Specifications:
 * Extension version: The Great Suspender v6.30
 * Browser & version: Firefox 62.0.3 (64-bit)
 * Operating system & version: Windows 10 Home (64-bit) v1803

**Comment by deanoemcke** [comment]
Firefox is most definitely not supported at this point. When I do implement for firefox I will ensure that these bugs are fixed.
To follow the firefox implementation please see this issue: #409
