### ISSUE TITLE
Dialog box requesting permission to 'translate' keeps appearing

### ISSUE THREAD

**Issue by mkz7** [deanoemcke/thegreatsuspender#792]
I keep seeing a dialog box asking if I want to "translate this page" when I return to certain suspended tabs. 

Seems to only happen with particular tabs, but none are in a foreign language.

Is this a known issue?

![image](https://user-images.githubusercontent.com/16544283/46957445-9aab6c00-d065-11e8-87ec-e55769debd0d.png)
----------------------------------------------------------------------------------------------------
TGS v. 7.0.109
BRAVE DEV . . . Version 0.55.2 Chromium: 70.0.3528.4 (Official Build) dev (64-bit)
MAC OS 'High Sierra' (v. 10.13.5)

**Comment by liamjohnston** [comment]
Happens to me too sometimes on latest/recent dev versions.

**Comment by deanoemcke** [comment]
That's super odd. No idea why that might be happening.
I'll try to replicate at my end and report back.

**Comment by liamjohnston** [comment]
This PR resolves it:
https://github.com/deanoemcke/thegreatsuspender/pull/799
