### ISSUE TITLE
Session management shows the correct windows and tab # but won't restore them.

### ISSUE THREAD

**Issue by thefixer80** [deanoemcke/thegreatsuspender#797]
Hey team.

I closed my main chrome window - with 49 suspended tabs - and expected to recover it as usual. But I found another window opened with a single tab. Closed it too.

After this mess, when I try to recover the main one I just get the message attached.

Every time I click on it, just open 2 chrome windows with 3 tabs.

Help?

Chrome Version 69.0.3497.100 (Official Build) (64-bit)
MacOs Mojave 10.14

![screenshot 2018-10-21 at 3 50 47 pm](https://user-images.githubusercontent.com/43627535/47272150-a2807a00-d557-11e8-97a6-08483a8a697c.png)

**Comment by deanoemcke** [comment]
This is odd. In your screenshot it looks like the tabs being displayed belong to the session below (2 windows, 6 tabs)?
What happens if you click on the 'export' link next to the session with 1 window, 49 tabs?

**Comment by thefixer80** [comment]
Already tried that too...

[session.txt](https://github.com/deanoemcke/thegreatsuspender/files/2502061/session.txt)

**Comment by deanoemcke** [comment]
Ok. Well the data should be there somewhere. Try running the code below in the console of the extension background page.
To do this, navigate to `chrome://extensions` and then click on the link for `background_page` in the box for The Great Suspender. It looks like this:
![image](https://user-images.githubusercontent.com/1051763/47307543-46703100-d5fd-11e8-9f94-3db1342174d5.png)

You may need to click on 'details' to see the link for the background page.

This should pop up a new window. At the bottom of this window should be a place to enter text. Copy and paste the following code and then press enter to run it:

```
gsUtils.fetchCurrentSessions().then(o => {
 for (const s of o) {
  console.log('session: ' + s.date);
  for (const w of s.windows) {
    for (const t of w.tabs) {
      const url = t.url.indexOf('suspended.html') < 0 ? t.url : gsUtils.getSuspendedUrl(t.url);
      console.log(url);
    }
    console.log('\n');
  }
 }
})
```

This should print out the urls for all your current sessions.

**Comment by thefixer80** [comment]
@deanoemcke fabulous! Thanks!

**Comment by thefixer80** [comment]
Hey guys. It happened again.
I realized this: The crash occurs when there are two windows opened and I close the one with the tabs suspended.
I ran the code above and got the links for the suspended tabs.

**Comment by deanoemcke** [comment]
You might want to try updating to the latest version on the extension.
To do this, you'll need to uninstall and then reinstall the extension from the chrome webstore.
IMPORTANT! If you do this you will lose all open suspended tabs and all session history to be sure to unsuspend or backup all tabs and session histories first.
