### ISSUE TITLE
Add way to make current page temporarily exempt from automatic suspend

### ISSUE THREAD

**Issue by truth1ness** [deanoemcke/thegreatsuspender#80]
For pages where I'm typing something and need to switch between tabs it'd be great if I could select "Temporarily exempt from automatic suspend" from the icon menu to make that tab not suspend until that particular page is left.

**Comment by deanoemcke** [comment]
This has been implemented in the latest (gitHub) version of the extension. You can now 'pause' the suspension of any tab from the popup menu.
This feature will be available on the chrome webstore shortly.
