### ISSUE TITLE
Stop donation requests coming back

### ISSUE THREAD

**Issue by Bertoldino** [deanoemcke/thegreatsuspender#802]
I am very much annoyed by the fact that, after making a donation, the donation request keeps coming back again and again. There should be a means to stop it once payment is made.

**Comment by deanoemcke** [comment]
Hi. Firstly thanks a lot for donating.
Can I ask how you made the donation? If via PayPal, then you should have been redirected to a thankyou page, and the donation popups should be removed automatically.
If it was via a cryptocurrency then unfortunately this does not happen automatically.

You can turn off the donation popups by going into the extension options page, and clicking on the 'about' section in the left-hand sidebar.
From there, click the 'Already donated?' link and this will let the extension know that you have donated.

I hope this helps, and please let me know if you did donate via paypal, but the donation removal process failed for you.

**Comment by Bertoldino** [comment]
Hello, in fact I have made my payment on October 18 via PayPal. I can provide the transaction reference number if needed. And I was not redirected to your page. Anyway, I am glad to know that there is a means to stop the payment request. I will follow your instructions and let you know if that does not work either. Thank you.
 
P.S. This problem happens with Wikipedia also.
 
R.Dangelo
 
 
 
 
> Message du 26/10/18 20:20
> De : "Dean Oemcke" 
> A : "deanoemcke/thegreatsuspender" 
> Copie à : "Bertoldino" , "Author" 
> Objet : Re: [deanoemcke/thegreatsuspender] Stop donation requests coming back (#802)
> 
>
> Hi. Firstly thanks a lot for donating.
> Can I ask how you made the donation? If via PayPal, then you should have been redirected to a thankyou page, and the donation popups should be removed automatically.
> If it was via a cryptocurrency then unfortunately this does not happen automatically.
> You can turn off the donation popups by going into the extension options page, and clicking on the 'about' section in the left-hand sidebar.
> From there, click the 'Already donated?' link and this will let the extension know that you have donated.
> I hope this helps, and please let me know if you did donate via paypal, but the donation removal process failed for you.
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/deanoemcke/thegreatsuspender","title":"deanoemcke/thegreatsuspender","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/deanoemcke/thegreatsuspender"}},"updates":{"snippets":[{"icon":"PERSON","message":"@deanoemcke in #802: Hi. Firstly thanks a lot for donating.\r\nCan I ask how you made the donation? If via PayPal, then you should have been redirected to a thankyou page, and the donation popups should be removed automatically.\r\nIf it was via a cryptocurrency then unfortunately this does not happen automatically.\r\n\r\nYou can turn off the donation popups by going into the extension options page, and clicking on the 'about' section in the left-hand sidebar.\r\nFrom there, click the 'Already donated?' link and this will let the extension know that you have donated.\r\n\r\nI hope this helps, and please let me know if you did donate via paypal, but the donation removal process failed for you."}],"action":{"name":"View Issue","url":"https://github.com/deanoemcke/thegreatsuspender/issues/802#issuecomment-433499338"}}}[ { "@context": "http://schema.org", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "https://github.com/deanoemcke/thegreatsuspender/issues/802#issuecomment-433499338", "url": "https://github.com/deanoemcke/thegreatsuspender/issues/802#issuecomment-433499338", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "https://github.com" } }, { "@type": "MessageCard", "@context": "http://schema.org/extensions", "hideOriginalBody": "false", "originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB", "title": "Re: [deanoemcke/thegreatsuspender] Stop donation requests coming back (#802)", "sections": [ { "text": "", "activityTitle": "**Dean Oemcke**", "activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png", "activitySubtitle": "@deanoemcke", "facts": [ ] } ], "potentialAction": [ { "name": "Add a comment", "@type": "ActionCard", "inputs": [ { "isMultiLine": true, "@type": "java-script", "id": "IssueComment", "isRequired": false } ], "actions": [ { "name": "Comment", "@type": "HttpPOST", "target": "https://api.github.com", "body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"deanoemcke/thegreatsuspender\",\n\"issueId\": 802,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}" } ] }, { "name": "Close issue", "@type": "HttpPOST", "target": "https://api.github.com", "body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"deanoemcke/thegreatsuspender\",\n\"issueId\": 802\n}" }, { "targets": [ { "os": "default", "uri": "https://github.com/deanoemcke/thegreatsuspender/issues/802#issuecomment-433499338" } ], "@type": "OpenUri", "name": "View on GitHub" }, { "name": "Unsubscribe", "@type": "HttpPOST", "target": "https://api.github.com", "body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 401066721\n}" } ], "themeColor": "26292E" } ]

**Comment by Bertoldino** [comment]
Hi Dean, further to my previous message, be advised that, after a few days, the icon has reappeared. Is there a way to get rid of it permanently, since payment has been made ? I have re-executed the procedure you indicated in your message, but after some time the icon comes back. It's surely annoying. Thank you for your assistance on this issue.
 
Regards,
 
R.Dangelo
 
 
> Message du 26/10/18 20:20
> De : "Dean Oemcke" 
> A : "deanoemcke/thegreatsuspender" 
> Copie à : "Bertoldino" , "Author" 
> Objet : Re: [deanoemcke/thegreatsuspender] Stop donation requests coming back (#802)
> 
>
> Hi. Firstly thanks a lot for donating.
> Can I ask how you made the donation? If via PayPal, then you should have been redirected to a thankyou page, and the donation popups should be removed automatically.
> If it was via a cryptocurrency then unfortunately this does not happen automatically.
> You can turn off the donation popups by going into the extension options page, and clicking on the 'about' section in the left-hand sidebar.
> From there, click the 'Already donated?' link and this will let the extension know that you have donated.
> I hope this helps, and please let me know if you did donate via paypal, but the donation removal process failed for you.
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/deanoemcke/thegreatsuspender","title":"deanoemcke/thegreatsuspender","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/deanoemcke/thegreatsuspender"}},"updates":{"snippets":[{"icon":"PERSON","message":"@deanoemcke in #802: Hi. Firstly thanks a lot for donating.\r\nCan I ask how you made the donation? If via PayPal, then you should have been redirected to a thankyou page, and the donation popups should be removed automatically.\r\nIf it was via a cryptocurrency then unfortunately this does not happen automatically.\r\n\r\nYou can turn off the donation popups by going into the extension options page, and clicking on the 'about' section in the left-hand sidebar.\r\nFrom there, click the 'Already donated?' link and this will let the extension know that you have donated.\r\n\r\nI hope this helps, and please let me know if you did donate via paypal, but the donation removal process failed for you."}],"action":{"name":"View Issue","url":"https://github.com/deanoemcke/thegreatsuspender/issues/802#issuecomment-433499338"}}}[ { "@context": "http://schema.org", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "https://github.com/deanoemcke/thegreatsuspender/issues/802#issuecomment-433499338", "url": "https://github.com/deanoemcke/thegreatsuspender/issues/802#issuecomment-433499338", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "https://github.com" } }, { "@type": "MessageCard", "@context": "http://schema.org/extensions", "hideOriginalBody": "false", "originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB", "title": "Re: [deanoemcke/thegreatsuspender] Stop donation requests coming back (#802)", "sections": [ { "text": "", "activityTitle": "**Dean Oemcke**", "activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png", "activitySubtitle": "@deanoemcke", "facts": [ ] } ], "potentialAction": [ { "name": "Add a comment", "@type": "ActionCard", "inputs": [ { "isMultiLine": true, "@type": "java-script", "id": "IssueComment", "isRequired": false } ], "actions": [ { "name": "Comment", "@type": "HttpPOST", "target": "https://api.github.com", "body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"deanoemcke/thegreatsuspender\",\n\"issueId\": 802,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}" } ] }, { "name": "Close issue", "@type": "HttpPOST", "target": "https://api.github.com", "body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"deanoemcke/thegreatsuspender\",\n\"issueId\": 802\n}" }, { "targets": [ { "os": "default", "uri": "https://github.com/deanoemcke/thegreatsuspender/issues/802#issuecomment-433499338" } ], "@type": "OpenUri", "name": "View on GitHub" }, { "name": "Unsubscribe", "@type": "HttpPOST", "target": "https://api.github.com", "body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 401066721\n}" } ], "themeColor": "26292E" } ]

**Comment by Bertoldino** [comment]
Thank you for your response. I am glad you could fix this annoying problem. I would like to install v.7.0.141 but I cannot find it : Chrome Web Store offers 7.0.109 ; Download.cnet sends me to a new site indicating an error ; your site offers v.7.0-beta.128. Kindly advise where can I download it from. And thanks again for your action. I am sure it will benefit many more users.
 
 
 
 
 
 
 
> Message du 02/11/18 04:28
> De : "Dean Oemcke" 
> A : "deanoemcke/thegreatsuspender" 
> Copie à : "Bertoldino" , "Mention" 
> Objet : Re: [deanoemcke/thegreatsuspender] Stop donation requests coming back (#802)
> 
>
> @Bertoldino I have done some more investigation and it does indeed appear to be an issue with the new chrome sync behaviour.
> I have fixed this issue in the latest dev version (v7.0.141).
> I have also defined some new behaviour whereby if any instance of the extension (on any chrome profile) successfully makes a donation, it will cause all instances to appear as donated and this will be non-reversible, short of uninstalling the extension.
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/deanoemcke/thegreatsuspender","title":"deanoemcke/thegreatsuspender","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/deanoemcke/thegreatsuspender"}},"updates":{"snippets":[{"icon":"PERSON","message":"@deanoemcke in #802: @Bertoldino I have done some more investigation and it does indeed appear to be an issue with the new chrome sync behaviour.\r\nI have fixed this issue in the latest dev version (v7.0.141).\r\nI have also defined some new behaviour whereby if any instance of the extension (on any chrome profile) successfully makes a donation, it will cause all instances to appear as donated and this will be non-reversible, short of uninstalling the extension."}],"action":{"name":"View Issue","url":"https://github.com/deanoemcke/thegreatsuspender/issues/802#issuecomment-435260145"}}}[ { "@context": "http://schema.org", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "https://github.com/deanoemcke/thegreatsuspender/issues/802#issuecomment-435260145", "url": "https://github.com/deanoemcke/thegreatsuspender/issues/802#issuecomment-435260145", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "https://github.com" } }, { "@type": "MessageCard", "@context": "http://schema.org/extensions", "hideOriginalBody": "false", "originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB", "title": "Re: [deanoemcke/thegreatsuspender] Stop donation requests coming back (#802)", "sections": [ { "text": "", "activityTitle": "**Dean Oemcke**", "activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png", "activitySubtitle": "@deanoemcke", "facts": [ ] } ], "potentialAction": [ { "name": "Add a comment", "@type": "ActionCard", "inputs": [ { "isMultiLine": true, "@type": "java-script", "id": "IssueComment", "isRequired": false } ], "actions": [ { "name": "Comment", "@type": "HttpPOST", "target": "https://api.github.com", "body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"deanoemcke/thegreatsuspender\",\n\"issueId\": 802,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}" } ] }, { "name": "Close issue", "@type": "HttpPOST", "target": "https://api.github.com", "body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"deanoemcke/thegreatsuspender\",\n\"issueId\": 802\n}" }, { "targets": [ { "os": "default", "uri": "https://github.com/deanoemcke/thegreatsuspender/issues/802#issuecomment-435260145" } ], "@type": "OpenUri", "name": "View on GitHub" }, { "name": "Unsubscribe", "@type": "HttpPOST", "target": "https://api.github.com", "body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 401066721\n}" } ], "themeColor": "26292E" } ]

**Comment by deanoemcke** [comment]
It is still in development sorry but will be available on the chrome webstore shortly.

**Comment by Bertoldino** [comment]
Thank you ! I'll keep an eye on it. Have a great evening.
 
R.Dangelo
 
 
 
 
> Message du 14/11/18 02:19
> De : "Dean Oemcke" 
> A : "deanoemcke/thegreatsuspender" 
> Copie à : "Bertoldino" , "Mention" 
> Objet : Re: [deanoemcke/thegreatsuspender] Stop donation requests coming back (#802)
> 
>
> It is still in development sorry but will be available on the chrome webstore shortly.
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/deanoemcke/thegreatsuspender","title":"deanoemcke/thegreatsuspender","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/deanoemcke/thegreatsuspender"}},"updates":{"snippets":[{"icon":"PERSON","message":"@deanoemcke in #802: It is still in development sorry but will be available on the chrome webstore shortly."}],"action":{"name":"View Issue","url":"https://github.com/deanoemcke/thegreatsuspender/issues/802#issuecomment-438501402"}}}[ { "@context": "http://schema.org", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "https://github.com/deanoemcke/thegreatsuspender/issues/802#issuecomment-438501402", "url": "https://github.com/deanoemcke/thegreatsuspender/issues/802#issuecomment-438501402", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "https://github.com" } }, { "@type": "MessageCard", "@context": "http://schema.org/extensions", "hideOriginalBody": "false", "originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB", "title": "Re: [deanoemcke/thegreatsuspender] Stop donation requests coming back (#802)", "sections": [ { "text": "", "activityTitle": "**Dean Oemcke**", "activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png", "activitySubtitle": "@deanoemcke", "facts": [ ] } ], "potentialAction": [ { "name": "Add a comment", "@type": "ActionCard", "inputs": [ { "isMultiLine": true, "@type": "java-script", "id": "IssueComment", "isRequired": false } ], "actions": [ { "name": "Comment", "@type": "HttpPOST", "target": "https://api.github.com", "body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"deanoemcke/thegreatsuspender\",\n\"issueId\": 802,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}" } ] }, { "name": "Close issue", "@type": "HttpPOST", "target": "https://api.github.com", "body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"deanoemcke/thegreatsuspender\",\n\"issueId\": 802\n}" }, { "targets": [ { "os": "default", "uri": "https://github.com/deanoemcke/thegreatsuspender/issues/802#issuecomment-438501402" } ], "@type": "OpenUri", "name": "View on GitHub" }, { "name": "Unsubscribe", "@type": "HttpPOST", "target": "https://api.github.com", "body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 401066721\n}" } ], "themeColor": "26292E" } ]

**Comment by robguthm** [comment]
I'm also having this issue. I joined as a Patreon recurring supporter.
