### ISSUE TITLE
Suspended tabs deleted when removing extension

### ISSUE THREAD

**Issue by castaway** [deanoemcke/thegreatsuspender#804]
### Specifications:
 * Extension version: 6.50 (was trying to update)
 * Browser & version: Vivaldi 2.0.1309.42 (Stable channel) (64-bit)
 * Operating system & version: Linux Gentoo (current)

I was actually wanting to update the extension, however the "Update" button (dev mode) seemed to do nothing at all.. so I thought "ok, I'll uninstall/reinstall it"..

When hitting "Remove" (in the chrome web store page) to uninstall, *all* tabs that were suspended at that point vanished... that was not what I was expecting.. luckily I had backed up my session (vivaldi has session backups built-in), a few days ago.. I installed the new version, and opened the old session, and things seem fine.

Is there a way to "on-remove-restore-tabs" .. or at least warn the user they will vanish, and be able to cancel?

**Comment by liamjohnston** [comment]
Yep, this is expected and unfortunately unavoidable. Suspended tabs 'belong' to the extension, so when the extension goes, so do the tabs.

There's no hook the extension can use when someone attempts to remove it. As you could imagine, this would probably get abused by some extension developers (think nag screens etc).

As for the update - the new version is still being rolled out to only a percentage of users, until it's been fully tested and battle-hardened and that percentage is increased to 100%. No amount of hitting refresh will get you the new version. The only way is to remove it and re-add it (which you did) :)

**Comment by castaway** [comment]
That's quite a shame.. I shall remember not to do that again ;|

nag screens that said "hey, can you rate me or otherwise hint why removing" etc actually seem like a sane idea to me.. ohwell.. 

Hmm, if I'd known/noticed it wasn't final yet I wouldnt have upgraded.. I assumed "in the store" - for all.. admittedly I didnt go looking for details.
