### ISSUE TITLE
Right-click ICON context menu functions missing since new update

### ISSUE THREAD

**Issue by S-U-M-1** [deanoemcke/thegreatsuspender#806]
The new extension menu is bad. It's slow to load, and the "suspend this tab now" option does not work sometimes. I don't know why the corresponding right-click menu on the extension icon was removed, which always worked instantly.

![image](https://user-images.githubusercontent.com/29358863/47759794-331e2f00-dca9-11e8-8efc-66f1a4eff2f7.png)

I'm aware of the many reports of the "suspend this tab now" bug, which I also suffer from. But that bug only affects the main icon menu, not the webpage context menu, proving there are serious issues with the main menu. There was no reason to remove the right-click icon menu, which was the fastest way to suspend a tab by far. The main menu and the webpage context menu take more clicks and more time to suspend a tab.

Please reinstate the suspend functions on the right-click icon context menu. Thank you.

### Specifications:
* v7.0.109
* Chrome 69.0.3497.100
* Windows 7 64-bit

**Comment by deanoemcke** [comment]
Thanks for the feedback.

Can I get you to clarify a few things for me?

- Is there a chance that you're in incognito mode? The right-click context menu does not work in incognito mode. 

- Does it still happen after a chrome restart?

- What is the difference between the 'right-click icon menu' which you say has been removed, and the 'webpage context menu'? 

- The right-click menu should still be there. For me it looks like this:
![image](https://user-images.githubusercontent.com/1051763/47835548-d2f7bd80-dd7a-11e8-903f-78373c93a796.png)

Is that what you are expecting to see?
It should be noted that in the latest chrome (v70) it appears that the separators don't seem to display, so i'm currently working around this by adding disabled horizontal rules.

**Comment by S-U-M-1** [comment]
Somehow I never got notified of this response. However, I'll still answer.

- No, I was not in incognito mode.

- Yes, it happens regardless of restarts.

- The right-click icon menu is what you see when you right-click on The Great Suspender icon next to the Chrome address bar.
The webpage context menu is what you see when you right-click on a webpage – it is what you have in your screenshot.

- I can assure you that there used to be a duplication of some or all of the functions of the webpage context menu in the right-click icon menu, including and especially the functions to suspend or pause a tab. I used them frequently. These were removed from the menu in your large update which changed the appearance of the suspension page (I don't know the version number), and now the icon's right-click menu shows some default Chrome options, missing the former extension options.
I'm unable to show a screenshot as it is difficult to downgrade Chrome or run a separate instance of it, but just picture the menu I showed in my screenshot having the functions "Suspend/unsuspend tab" and "Pause tab suspension" in the red box I drew. That's what used to be there. Maybe these were there by accident, which your response seems to suggest. This would be perplexing to me, as I am aware developers are able to add functions to this menu, as shown here:

![image](https://user-images.githubusercontent.com/29358863/53841522-ed45e000-3f94-11e9-9a5c-c899573cf8db.png)

Either way, I invite you to consider adding these functions back to that context menu, and if not, then to please fix the main extension icon menu so that the "suspend tab" function works again, because currently it is not working at all, as someone who really appreciates and depends on the functionality of this extension. Thank you.

**Comment by deanoemcke** [comment]
@S-U-M-1 Can you please let me know the version of the extension, the chrome browser, and the OS you are using? 
Thanks.

**Comment by S-U-M-1** [comment]
@deanoemcke

- The Great Suspender: 7.0.109
- Chrome: 72.0.3626.121 (update pending)
- OS: Windows 7 64-bit
