### ISSUE TITLE
Session management and Suspend this tab do not work

### ISSUE THREAD

**Issue by Jollfye** [deanoemcke/thegreatsuspender#807]
Chrome dev got updated and first I noticed that when I try to suspend current tab by clicking corresponding option in the right click menu or in the extension menu (doesn't matter), tab not being suspended immediately, nothing happens, then for example I go to another tab, and after some time (more than a minute, but less than in "Automatically suspend tabs after" option, 5 mins) tab gets finally suspended, but (again) not immediately like before. I went to settings to see what's happening and when I clicked on sessions it just wasn't there and didn't work (see screeny). I tried to restart chrome/windows, no effect, issue persists.

![scr](https://user-images.githubusercontent.com/6180818/47786675-f2183000-dd25-11e8-85dc-006c47aaa88d.png)

Also I noticed one annoying thing all the way since extension was updated to the store latest 109 version. For example when windows gets restarted, lets say, for updates, or just restarted with chrome open, it kind of saves open windows to restore (open) them on the next start after login, soo when chrome gets "restarted" in this situation all suspended tabs getting doubled in the same window! Doubled not like after each tab appears it's doubled suspended copy but like a whole new set of the same tabs appearing right after original session (like current session gets doubled in one window). I have to close that chrome window and open a new empty one, then go to TGS settings and resuspend my latest session from session management to another new window. Interesting thing, when windows restarts now, with TGS session management "broken", chrome does not open itself at windows start with session doubled, which is good, but when I open chrome with a shortcut, tabs' icons not getting loaded, I have to go through all the tabs to get their icons loaded, same was with the old version of TGS, before 109. No need to go through all the tabs was a great improvement I liked a lot, hope it can be fixed.

OK, I think that's all I noticed so far. What a Great extension if only not those little pesky bugs ;3

### Specifications:
 * Extension version: 7.0.109
 * Browser & version: Google Chrome 72.0.3595.2 (Official Build) dev (64-bit)
 * Operating system & version: Windows 10 1809 17763.55

**Comment by Jollfye** [comment]
Alright, I decided to try (coz the issue with not immediately working "suspend this tab" option was too annoying) n installed latest available TGS extension version from releases here (7.0.131). Aand everything seems to be good, no bugs or lags. "Suspend this tab" works immediately as it should. Session management works, saves, imports sessions correctly. + With windows restart there's no more chrome being restored, it just sits in tray as it supposed to until I open it myself with a shortcut. + When chrome starts it gradually goes through all the tabs by itself loading theirs icons, Great. + Enabled this "Chrome's built-in memory-saving" option, not like I see a difference yet, but I guess yeah it's better to use built-in functionality, it just works. Thanks for this aamazing memory(life)saving extension!

**Comment by deanoemcke** [comment]
@Jollfye Thanks for getting back to me. I was going to suggest updating as a lot has changed since v7.0.109. 
Actually, a lot has changed since v7.0.131 as well. I've rewritten a lot of the code that deals with the session restore and tab suspension. Would you mind updating again to test out the latest code?

I've tried to replicate your latest issue (the re-suspending after losing focus bug) but can't do so on my current dev version.

**Comment by Jollfye** [comment]
@deanoemcke Ok, where can I get it (url)?

**Comment by Jollfye** [comment]
@deanoemcke Ok, updated to the latest 140, checked "losing focus" bug, it's no more, now everything looks n works just fine, no more issues yet, thanks.

**Comment by SnIPeRSnIPeR** [comment]
Where is the update on Chrome Web Store? :)
