### ISSUE TITLE
New Feature Request: Pause Suspension

### ISSUE THREAD

**Issue by Timmy123456789** [deanoemcke/thegreatsuspender#811]
I have just started using this add in, however sometimes when i am having a research session i become irritated when tabs become suspended when i am using multiple tabs and wish to switch between them (i understand this is the purpose of the extension). 

What im looking for is a disable button to stop the extension running. e.g. a 'Pause Suspension' option without needing to go into the settings.

I could increase the suspension timer to never or longer, but is not exactly a disable option.

**Comment by liamjohnston** [comment]
This exists. See "not now" option below. You can also set a keyboard shortcut for it if you wish :)

![screen shot 2018-11-07 at 8 22 13 am](https://user-images.githubusercontent.com/1134713/48088210-41022000-e266-11e8-857a-635ebd52d888.png)

**Comment by deanoemcke** [comment]
Actually, I think @Timmy123456789 is asking for a way to easily disable the entire extension, no just a single tab. 
This has already been requested here: https://github.com/deanoemcke/thegreatsuspender/issues/256
Will leave this closed as a duplicate.
