### ISSUE TITLE
Chrome updated, TGS stopped working

### ISSUE THREAD

**Issue by Jollfye** [deanoemcke/thegreatsuspender#822]
Chrome just updated to the latest dev 72.0.3626.7 version from previous 72.0.3622.0 and TGS stopped working (also latest). When Chrome full started (CPU/Disk load gone) after the update only one tab was loaded correctly, the first one (see screeny1), or the last one selected before Chrome exit (before update). All other tabs were like this YouTube, blank (scr1, again). Clicking on/reloading them does nothing, same blank, favicon also not loads, always TGS extension icon.

![scr1](https://user-images.githubusercontent.com/6180818/49564391-d0215700-f93c-11e8-8bf6-79c04103478c.png)

Opened new tab google.com (at the end), then tried to suspend it, didn't work. Not from extension menu, not from right click menu (which actually was gone).

Settings look like this now (nothing was changed before/after Chrome update)

![scr2](https://user-images.githubusercontent.com/6180818/49564603-8edd7700-f93d-11e8-9096-0651f27ef1bf.png)

Talking about gone right click menu, see scr3. Tho menu appears if uncheck -> check again 'Add TGS to right click menu' option. Aand it still doesn't work after appearance (tried with new tab as above, 'Suspend this tab' option doesn't work, does nothing).

![scr3](https://user-images.githubusercontent.com/6180818/49564685-d7953000-f93d-11e8-9813-74b948afaa3d.png)

Session management also doesn't work, shows no tabs in records, scr4.

![scr4](https://user-images.githubusercontent.com/6180818/49564969-fb0caa80-f93e-11e8-9a4d-7aac63fd5f12.png)

And versions screenshots here:

![scr5](https://user-images.githubusercontent.com/6180818/49565030-2b544900-f93f-11e8-98ef-6085214f3c8f.png)

![scr6](https://user-images.githubusercontent.com/6180818/49565038-31e2c080-f93f-11e8-9cda-37b2afb0380e.png)

Full Chrome restart doesn't help. Only one previously (before exit) selected tab gets loaded. Suspension doesn't work. All as above. Also tried old 147 TGS version with new Chrome dev, all the same, broken.

 * Extension version: v7.0.152
 * Browser name & version: Google Chrome 72.0.3626.7 (Official Build) dev (64-bit)
 * Operating system & version: Windows 10 1809 17763.134

**Comment by Jollfye** [comment]
Using latest Chrome stable 71.0.3578.80 (Official Build) (64-bit) version portable (from here: https://portableapps.com/apps/internet/google-chrome-portable-64 ) and 152 TGS all seems to be fine, at least tabs getting loaded, favicons ok, no blank, right click menu in place and suspension works from there and from extension menu. Except Session management, it doesn't work, it looks the same as from scr4 above, no tabs even for current session. Also these errors appear at Chrome portable start:

![scr1](https://user-images.githubusercontent.com/6180818/49569429-5cd41100-f94d-11e8-990e-4c7b33473504.png)

![scr2](https://user-images.githubusercontent.com/6180818/49569441-63628880-f94d-11e8-8312-1249ce782d65.png)

And this one (appears when I open Session management and click '+' to open any session, current also):

![scr3](https://user-images.githubusercontent.com/6180818/49569627-e2f05780-f94d-11e8-94ff-08b027b63a4a.png)

**Comment by Jollfye** [comment]
Full restarted several times. Errors right after Chrome stable portable start:

![scr5](https://user-images.githubusercontent.com/6180818/49570463-192ed680-f950-11e8-893d-21cdf2dffa06.png)

![scr6](https://user-images.githubusercontent.com/6180818/49570475-1df38a80-f950-11e8-8af0-33233513372c.png)

Also with every restart I'm getting bombarded with this security message (scr below), I guess it's coz errors above.

![scr4](https://user-images.githubusercontent.com/6180818/49570560-69a63400-f950-11e8-8485-c7009588e4d4.png)

**Comment by Jollfye** [comment]
This error I see right when I start my usual updated Chrome dev 72.0.3626.7:

![scr1](https://user-images.githubusercontent.com/6180818/49573352-361ad800-f957-11e8-9315-76ca0b3c79cd.png)

And this one appears later when I try to suspend some new tab from extension menu (coz right click one is gone as described):

![scr2](https://user-images.githubusercontent.com/6180818/49573401-50ed4c80-f957-11e8-9a09-9062a213d9dd.png)

Also wanted to mention that I use the same (Users\<User>\AppData\Local\Google\Chrome\User Data\Default) Chrome profile folder for my dev 72.0.3626.7 and stable 71.0.3578.80 portable Chrome versions, for installed dev it's default folder and for portable I just start it using GoogleChromePortable64\App\Chrome-bin\chrome.exe (not GoogleChromePortable64\GoogleChromePortable.exe) so it uses the same folder. And it seems that the same profile works fine with Chrome stable (with some errors + not working Session management) and TGS all breaks with dev.

**Comment by Jollfye** [comment]
Updated TGS to latest 153 version. When started Chrome dev, it's all the same, TGS doesn't work, even usual after update TGS 'updated' page didn't appear. But when started stable portable Chrome version all was fine, even 'updated' appeared, tho errors and security message didn't go anywhere.

**Comment by CollinChaffin** [comment]
The above errors are the same I have been seeing and reported several commits ago in #823 without any acknowledgement from @deanoemcke as of yet after 9 days and continued activity so I have no idea of status.  Even latest Chrome DEV 73.0.3639.1 running TGS latest commit c07ac99 produces this upon even initialization, and throws it again upon any suspend operation which all fail - so TGS has zero functionality ATM:

```
Uncaught (in promise) TypeError: Cannot read property 'queueTabAsPromise' of undefined
    at queueTabForSuspensionAsPromise (gsTabSuspendManager.js:49)
    at Object.queueTabForSuspension (gsTabSuspendManager.js:35)
    at activeTab (background.js:427)
    at background.js:176
```

**Comment by CollinChaffin** [comment]
FYI, I know it's an issue with the refactoring because simply rolling back to beta.128-68 Commit-g4e4d20e (prior to the recent major refactoring) of TGS instantly reverts TGS to a working state (suspend operations) on every version of Chrome I have tested to latest Canary - with the only exception being the session management seems blank but I believe that to be a case of lack of backwards compatibility of rolling back and having updated session data.  Either way, there are no good options right now so I hope Dean is close to a solution.

**Comment by CollinChaffin** [comment]
Have a working fix - creating a PR now for it to hopefully get merged soon.

**Comment by Jollfye** [comment]
@CollinChaffin I would be glad to help and test your build but I think we still may need @deanoemcke's help as we don't know the project the way Dean does.

**Comment by CollinChaffin** [comment]
PR #827 created
