### ISSUE TITLE
Consider to change all the img to webp

### ISSUE THREAD

**Issue by AlphaWong** [deanoemcke/thegreatsuspender#824]
Dear Community,

As the project aims to serve the user under Google chrome. I would like to suggect to replace all the image from `png` to `webp` in order to reduce the size of the extension.

Can anyone give me some feedback about it?

It anything is ok then I would like to submit a pull request to webp extension.

Best,
Alpha

**Comment by liamjohnston** [comment]
Good call. This extension actually us used in other browsers too, though that's not common.perhaps if your PR also did some browser sniffing to fallback to png if it isn't chrome?

**Comment by AlphaWong** [comment]
I think the extension do serve blink engine only am I correct ?

**Comment by deanoemcke** [comment]
@AlphaWong just to be clear, what images are we talking about here? are you referring to the ones located at `/src/img/` ?
Is your concern solely with the package size of the extension? If so, I really don't see an extra few KBs really making any difference?

**Comment by AlphaWong** [comment]
> @AlphaWong just to be clear, what images are we talking about here? are you referring to the ones located at `/src/img/` ?
> Is your concern solely with the package size of the extension? If so, I really don't see an extra few KBs really making any difference?

Sure. I just wondering can it be compress. As after I compress `https://github.com/deanoemcke/thegreatsuspender/blob/master/src/img/suspendy-guy.png`. It seems can reduce 44% size of it.

# reference
![image](https://user-images.githubusercontent.com/5622516/50193699-a7ed1b80-0372-11e9-81be-66f868a04f05.png)

# tools
https://github.com/google/zopfli
