### ISSUE TITLE
Ability to comment out URL exceptions from the list

### ISSUE THREAD

**Issue by orschiro** [deanoemcke/thegreatsuspender#825]
Dear @deanoemcke,

What do you think of a feature to comment out entries from the URL exception list?

This would be useful if you want to maintain your list but disable exceptions for specific URLs. 

Below an example. 

Much appreciated. 

Yours

![image](https://user-images.githubusercontent.com/170947/49693803-6c39a100-fb7d-11e8-91aa-35597b5e0ec7.png)

**Comment by deanoemcke** [comment]
@orschiro 
hmmm.. why not just remove the space between the hash and url in your above example?
that will effectively create a whitelist entry that never matches.

let me know if you think that's a fair workaround. it's certainly less development work for me :D

**Comment by orschiro** [comment]
@deanoemcke love this hacky idea, appreciated! :-)

I think that will work. Let's save you some time.

Yours
