### ISSUE TITLE
Keyboard shortcuts constantly disappear

### ISSUE THREAD

**Issue by shoomow** [deanoemcke/thegreatsuspender#828]
* Extension version: 7.0.109
 * Browser name & version: Chrome 71.0.3578.98 (Official Build) (64-bit)
 * Operating system & version: Win 10

I have to periodically set the keyboard shortcuts all over again because they simple cease as if they were never set in the first place. So far as I can tell it is not triggerred by anything specific, like browser update or system update and happens more or less randomly.

**Comment by deanoemcke** [comment]
I'm not sure what could be causing this sorry. Short of the extension being uninstalled and reinstalled again.
All the keyboard shortcuts are set and managed by chrome. Perhaps the best place to look for an answer would be on the chrome forums?
