### ISSUE TITLE
Suspended Google Docs and Sheets icons show Slides favicon instead

### ISSUE THREAD

**Issue by fwextensions** [deanoemcke/thegreatsuspender#829]
After pulling v155 from master, I'm seeing a strange new bug where suspended Google Docs and Sheets documents show the Slides icon instead:

![image](https://user-images.githubusercontent.com/61631/50173829-66466d00-02ad-11e9-99d7-f5418da11faa.png)

It's a bit transparent, but the tooltip shows that it's a Google Doc tab.  Only 5 of the tabs in the screenshot are actually presentations.  The rest are documents and spreadsheets.  Only one open Google Sheets tab is suspended and showing the correct icon.  Not sure what's special about that tab. 

Did something change about how TGS is pulling favicons?  

 * Extension version: 7.0.155
 * Browser name & version: Chrome 71
 * Operating system & version: Windows 10

**Comment by fwextensions** [comment]
I just manually suspended a Google Doc and it showed the correct favicon.  I believe all the ones with the wrong icons were auto-suspended and recovered after I restarted the extension.  I haven't restarted Chrome since, so maybe it's in a weird state.  I haven't noticed any other incorrect favicons.

**Comment by fwextensions** [comment]
I've since restarted my machine and now the logos are incorrectly showing Doc icons instead of Sheets:

![image](https://user-images.githubusercontent.com/61631/50193584-0f13bd00-02ec-11e9-8e67-62a668a8bb6d.png)

Some of those tabs are spreadsheets and presentations but they all look like documents.  

Is the new favicon handling only looking at domains and using the same favicon if the domains are the same?  They're all `docs.google.com`, and differ only in the root of the path, so that approach won't work for Google Docs and likely other sites as well.

**Comment by deanoemcke** [comment]
@fwextensions yes, there is some domain level favicon caching which explains the issue. i've just pushed a fixed for this (v7.0.159).

**Comment by deanoemcke** [comment]
@zen2go is this a session that you've imported from a different browser? the white document page icon will show if chrome does not have a favicon for the tab url in it's cache. so alternatively, possibly you've cleared the cache of the browser?

i have tested with brave and it behaves normally for me.

**Comment by fwextensions** [comment]
@deanoemcke I pulled 159 and this looks fixed.  Before and after shots:

![image](https://user-images.githubusercontent.com/61631/50666729-e1c14300-0f6a-11e9-8011-7e015446a2d3.png)
