### ISSUE TITLE
Suspended "Recent Tabs" don't work on mobile devices 

### ISSUE THREAD

**Issue by CoolkcaH** [deanoemcke/thegreatsuspender#83]
If you try to open a suspended tab from a mobile device when going to tabs open in another device, since iOS doesn't support the extension it breaks the link.

Need to find a way to work around this...

**Comment by deanoemcke** [comment]
Related to issue #46.
I agree that this would be great to get working. Unfortunately I haven't been able to crack this problem yet :/
