### ISSUE TITLE
How to filter local addresses (192.168.*.*)?

### ISSUE THREAD

**Issue by ScottBeeson** [deanoemcke/thegreatsuspender#831]
I have some management utilities on my local network that I don't want to suspend.  How can I filter those?  Would ` /*192\.168\.*/` work?

**Comment by ScottBeeson** [comment]
Looks like the regex I posted does not work (I don't really know regex).  Any help would be appreciated.

**Comment by deanoemcke** [comment]
`192\.168\.\d{1,3}\.\d{1,3}` should do it :)
