### ISSUE TITLE
Suggest feature convert suspension tab to real url in bookmark.

### ISSUE THREAD

**Issue by supakwong** [deanoemcke/thegreatsuspender#833]
Thank you developer create this plugin, I want to suggest feature or need your help.

Current version is 6.30, Chrome browser on Windows 10.

We have very big bookmark more than 8k url, because I following much more topics on many website.

Everyday we have more than 60 tab is open on Google Chrome. Sometime we save all tab to bookmark by Chrome feature (Bookmark all tabs). Currently we have 500 suspender tabs in bookmark. may be duplicate url and increase everyday. That url in bookmark is in suspender tab format with "chrome-extension://". We can't check duplicate url and delete when url in suspender format.

I hope you have feature or suggestion me how to restore every suspender tab in bookmark to real url. 

![2018-12-23_073906](https://user-images.githubusercontent.com/3039178/50379786-dece7480-0685-11e9-9ba7-662bb68bda3a.png)

**Comment by deanoemcke** [comment]
Yeah, I know this is a pain. There's already an issue for this: https://github.com/deanoemcke/thegreatsuspender/issues/720
