### ISSUE TITLE
[Vivaldi] Not suspending unfocused tabs (timeout enabled)

### ISSUE THREAD

**Issue by byaka** [deanoemcke/thegreatsuspender#834]
* Extension version: v7.0.109
* Browser name & version: Vivaldi 2.2.1388.34 (Stable channel)
* Operating system & version: Ubuntu 16.04

Just nothing happening after timeout (10 mins). If i suspend them manually - all ok.

**Comment by VOVPro** [comment]
Confirm case of **byaka**
Not susspend automaticaly!
v7.0.109

**Comment by byaka** [comment]
@VOVPro u also using Vivaldi? Are u have changed some `chrome://flags`?

**Comment by VOVPro** [comment]
I accidentally turned off access to sites in the settings. It was "When you click on the extension."
If enabled on all sites - it works :)
Google Chrome Version 71.0.3578.98. Although it does not matter....

**Comment by deanoemcke** [comment]
@VOVPro are you saying this has been resolved for you? 
@byaka are you still having this issue?

**Comment by VOVPro** [comment]
Yes! Extention is work fine for me. Thanks!

**Comment by byaka** [comment]
@VOVPro, @deanoemcke  can u pls explain how to swith this setting?

**Comment by VOVPro** [comment]
@byaka I can not find this item now, although version v7.0.109

**Comment by Jollfye** [comment]
@byaka in Google Chrome Extensions TGS extension details there's 2 settings that probably should be turned on: site access - on all sites and allow access to file urls, I guess in Vivaldi should be these settings too as it's Chromium based browser, idk maybe this info could help u.. also u could try latest TGS dev build and check if ur issue still persists, I recently wrote an expanded answer how to [here](https://github.com/deanoemcke/thegreatsuspender/issues/839#issuecomment-458312906)
