### ISSUE TITLE
Feature request: Pause/resume auto-suspension for all tabs

### ISSUE THREAD

**Issue by kshitij-sminq** [deanoemcke/thegreatsuspender#835]
* Extension version: v6.30
 * Browser name & version: Chrome 70
 * Operating system & version: Ubuntu 18.04

Please provide a shortcut in the extension window to pause and resume auto-suspension for all open tabs. There can also be a timeout to resume auto-suspension.

**Comment by deanoemcke** [comment]
Thanks for the feedback. I also like this idea. There's already a feature request for it: https://github.com/deanoemcke/thegreatsuspender/issues/256
