### ISSUE TITLE
[clarification] difference between suspending a tab and setting a page to "about:blank"

### ISSUE THREAD

**Issue by operabeats** [deanoemcke/thegreatsuspender#837]
* Extension version: 7
 * Browser name & version: Chromium 71
 * Operating system & version: Manjaro LInux

Is there any difference between "suspending a tab" and setting a page to "about:blank" while suspending tabs manually (auto suspend is disabled)?

**Comment by liamjohnston** [comment]
Pretty sure the functionality would be severely limited if you used `about:blank`.

For instance, retaining the tab title, the favicon, screenshot (for people that use this option)... You'd save memory, but probably miss out on every other feature of the extension I'm guessing.

So yeah, big difference. @deanoemcke correct me if I'm wrong.

Chrome extensions _can_ access/control the `about:blank` page, but I'm not sure this extension should do this.

**Comment by deanoemcke** [comment]
As @liamjohnston said, there would be a few things missing if you simply used about:blank. But essentially, that's what this extension does. It just runs a little javascript on the suspend page as well, so that it can try to retain the extension favicon and title.
