### ISSUE TITLE
Option to refresh unsuspended tab after getting focus

### ISSUE THREAD

**Issue by raulfragoso** [deanoemcke/thegreatsuspender#85]
The title says it all :)

**Comment by deanoemcke** [comment]
Do you mean, an option to unsuspend a suspended tab after getting focus???
This has been implemented in the more recent versions (gitHub) of the extension. 
It will be made available on the chrome webstore shortly.

If you meant an option to refresh an unsuspended tab after getting focus (as stated in the issue title), then i'm not sure that's in scope of what this extension is trying to achieve.
