### ISSUE TITLE
Restoring window view does not have internationalised text

### ISSUE THREAD

**Issue by deanoemcke** [deanoemcke/thegreatsuspender#856]
As discovered in this PR: https://github.com/deanoemcke/thegreatsuspender/pull/848#issuecomment-254244836
The restoring-window.html view does not contain internationalisation for the text.

![image](https://user-images.githubusercontent.com/1051763/52381514-a15b6480-2ad6-11e9-8cfa-8ba0d28de0f2.png)

**Comment by deanoemcke** [comment]
There is a branch to fix this: https://github.com/deanoemcke/thegreatsuspender/tree/feature/internationalised-restore-view

**Comment by deanoemcke** [comment]
![image](https://user-images.githubusercontent.com/1051763/52387327-a7f5d600-2aee-11e9-90de-8638fd86b67d.png)

There is also some untranslated text in the session history view (above).
This has also be added to the branch.

**Comment by AlexWayfer** [comment]
> As discovered in this PR: [#848 (comment)](https://github.com/deanoemcke/thegreatsuspender/pull/848#issuecomment-254244836)

I think, the link is broken.

---

Excuse me, but we have suggestions for English text there, to make buttons (links) more clear:

> %session% [open and suspend] [open and load] [export] [delete]

It's a kind of hard to translate `resuspend` in Russian, for example, especially with meaning "open a window".

**Comment by deanoemcke** [comment]
@AlexWayfer I agree with changing the english text to 'open and suspend' and 'open and load'. You can make this change yourself if you want in this PR, and also use this as a basis for the russian translations.

**Comment by deanoemcke** [comment]
Merged with master: e122ff570228b142d11f054df7cf536e73a5e03f
