### ISSUE TITLE
Title "Suspended Tab" for suspended tab

### ISSUE THREAD

**Issue by Jollfye** [deanoemcke/thegreatsuspender#861]
Updated to the latest dev TGS extension version 7.0.167 and just noticed an issue. When I suspend any tab it gets "Suspended Tab" in its title instead of the actual page's one.

 * Extension version: 7.0.167
 * Browser name & version: 73.0.3683.20 (Official Build) dev (64-bit)
 * Operating system & version: Windows 10 1809 17763.292

**Comment by deanoemcke** [comment]
I have confirmed this and also fixed it (https://github.com/deanoemcke/thegreatsuspender/commit/ab14e1e4b8dc6d412bf2536e8a98e05723db7b7a)

:)
