### ISSUE TITLE
Hotkeys

### ISSUE THREAD

**Issue by MonsterNya** [deanoemcke/thegreatsuspender#862]
I would suggest to update this inscription
![image](https://user-images.githubusercontent.com/23438485/52654257-ac612b00-2f02-11e9-89a5-89b6e7b37c0a.png)
for example on "Ctrl + Shift + S", as it is written in the settings
or add some gloss to them and do something like this
![image](https://user-images.githubusercontent.com/23438485/52654839-f0a0fb00-2f03-11e9-8238-2022b3154116.png)
and yes, I understand how petty this change 😅

 * Extension version: 7.0.165
 * Browser name & version: 72.0.3626.96
 * Operating system & version: win10 x64 1703

**Comment by deanoemcke** [comment]
I agree that screenshot is not ideal. FWIW it looks much nicer on a mac :P

![image](https://user-images.githubusercontent.com/1051763/52671346-b2492180-2f7f-11e9-9e32-b80c19a458dd.png)

Here is your suggested alternative on OSX:

![image](https://user-images.githubusercontent.com/1051763/52671970-52ec1100-2f81-11e9-8def-e8b634a1846a.png)

![image](https://user-images.githubusercontent.com/1051763/52672337-6fd51400-2f82-11e9-8d35-57240c90ae6e.png)

Not sure about the second one, although perhaps with the css styling changes it could be more acceptable.

@liamjohnston What do you think?

**Comment by liamjohnston** [comment]
That spacing in your screenshot @MonsterNya is in deed weird and bad. 

Mine looks like this (I'm on a mac too):
![screen shot 2019-02-13 at 11 31 38 am](https://user-images.githubusercontent.com/1134713/52672524-f558c400-2f82-11e9-88db-b35f828a963a.png)
(i.e. it looks as it's supposed to)

Personally, I sort of feel like adding a `+` between each character would make it look a bit busy without any usability gain. I don't hate it with the `+`, but I don't think it's _quite_ as good.

Definitely need to get to the bottom of your spacing bug though! I gotta find a windows machine to test on...

**Comment by MonsterNya** [comment]
on mac definitely looks better. On windows, the arrow does not look like the classic arrow Shift. more reminds me "up" key.
I don't know why I have such a gap, but he was always there.

**Comment by ressikanflute** [comment]
Not sure if I've had the shift-arrow icon on the shift button on the previous several keyboards. First time I saw a suspended tab for TGS I had to think a bit about what it meant. Guess it's been a while.

Is it possible to put a rectangle or button around each of them for Windows? [ctrl][shift][s]

**Comment by deanoemcke** [comment]
I've discovered the cause of the bad spacing (css issue where we assumed that all shortcut combos were single characters - which is true on a mac).
I've made some changes to help with readability across both mac and windows.
Here's some screenshots (dark theme are on mac, light theme are on windows):

![image](https://user-images.githubusercontent.com/1051763/53137577-2458e080-35e8-11e9-8064-c97145add873.png)
![image](https://user-images.githubusercontent.com/1051763/53137597-35095680-35e8-11e9-8fe3-248e993dc170.png)
![image](https://user-images.githubusercontent.com/1051763/53137728-a517dc80-35e8-11e9-986a-c7946ff4a495.png)

**Comment by liamjohnston** [comment]
Oh man, it's so obvious now 🤦‍♂️ I guess I'd have figured that out pretty quickly if I'd inspected it on windows. 
Sp what's your fix, @deanoemcke? Remove pletter spacing and wrap each 'key' in a <span>s with left/right margins? Want a hand?

**Comment by deanoemcke** [comment]
@liamjohnston nah, i'm just going to use space characters and the special 'middle dot' (U+00B7) character as a separator.

Here's a demo:
![image](https://user-images.githubusercontent.com/1051763/53140165-bf55b880-35f0-11e9-912c-fe92c03b455c.png)
![image](https://user-images.githubusercontent.com/1051763/53140182-cb417a80-35f0-11e9-9d27-dc6e943bf7a7.png)

![image](https://user-images.githubusercontent.com/1051763/53140127-a1885380-35f0-11e9-965d-26e16e8b85c2.png)

I'm pretty happy with it. What you think?

**Comment by liamjohnston** [comment]
On first impression I don't _love_ the middle dot 😬 But maybe I could learn to. 

I have a (only slight) preference for spacing, e.g. `&nbsp;&nbsp;` (two spaces). Like-a this:

<img width="996" alt="screen shot 2019-02-21 at 4 02 05 pm" src="https://user-images.githubusercontent.com/1134713/53140611-2aec5580-35f2-11e9-91bd-c21df8000065.png">

But no biggie either way :)

**Comment by deanoemcke** [comment]
Hmmm. I found that the space version doesn't look so good without the   character.
ie:
![image](https://user-images.githubusercontent.com/1051763/53140796-bcf45e00-35f2-11e9-89d3-bd16ac66ff1c.png)


Here's an alternative with the dot (but no spacing):
![image](https://user-images.githubusercontent.com/1051763/53140721-8585b180-35f2-11e9-8d90-097461c59a60.png)
![image](https://user-images.githubusercontent.com/1051763/53140744-9cc49f00-35f2-11e9-8dc2-d3cef93ed07e.png)

**Comment by liamjohnston** [comment]
How about a single space, then a `word-spacing` on the parent, e.g. `word-spacing: 2px;`?

**Comment by liamjohnston** [comment]
FWIW I thought that first screenshot in your last comment looks fine 🤷‍♂️ But if you don't think so, go with spaced dots. No biggie from my perspective :)

**Comment by MonsterNya** [comment]
https://user-images.githubusercontent.com/1051763/53140744-9cc49f00-35f2-11e9-8dc2-d3cef93ed07e.png
looks nice. If you do not use "+", then "dot" is the best option.

**Comment by Jollfye** [comment]
I like how new dot version looks, using latest commit c245df543f615a018d1e2fb15d00a83fb84ee8fc

![scr1 png](https://user-images.githubusercontent.com/6180818/53157355-c376db80-35da-11e9-83d8-bdfb26919d20.jpg)

And I would suggest to make it look the same in settings, with dot also (and no need to touch font size here below):

![scr2](https://user-images.githubusercontent.com/6180818/53157478-06d14a00-35db-11e9-8eda-25dc02035dbf.jpg)

**Comment by liamjohnston** [comment]
OK, the dots have it

**Comment by deanoemcke** [comment]
![image](https://user-images.githubusercontent.com/1051763/53536525-a5c1ed00-3b6b-11e9-9677-63921314bcbe.png)
