### ISSUE TITLE
Preserve original icon

### ISSUE THREAD

**Issue by picolo74** [deanoemcke/thegreatsuspender#863]
Can you add an option to preserve the original icon because when i have a lot of tabs it is impossible to easily find a tab.

Thank you

**Comment by liamjohnston** [comment]
Which version are you on? This bug has been fixed recently on master.

**Comment by picolo74** [comment]
Hi,

i have the version last version i think ? : 7.0.109
I restart chrome this morning and all the icons are replaced.

**Comment by liamjohnston** [comment]
It sounds like you're using the webstore version. 

The latest version is v7.0.171. It includes heaps of performance improvements and bugfixes. It will be pushed to the webstore once @deanoemcke is happy it's stable. IN the meantime you can either live with the bug or switch to using a dev version (I'd suggest just waiting :))
