### ISSUE TITLE
scroll position

### ISSUE THREAD

**Issue by MonsterNya** [deanoemcke/thegreatsuspender#864]
after unsuspend tab - position on the page is lost (in version 165 everything was fine).

 * Extension version: 7.0.171
 * Browser name & version: 72.0.3626.96
 * Operating system & version: win10 x64 1703

**Comment by Jollfye** [comment]
7.0.171, I confirm that, even if position saved in suspended tab url "pos", it's lost when unsuspended.

**Comment by deanoemcke** [comment]
Thanks for this. Should be fixed in v7.0.172
