### ISSUE TITLE
Content Security Policy mostly missing

### ISSUE THREAD

**Issue by egonil** [deanoemcke/thegreatsuspender#870]
Please complete the following information when submitting a feature request or bug report.
 * Extension version: 7.0.109
 * Browser name & version: Chrome 72.0.3626.109
 * Operating system & version: Window 10

https://crxcavator.io/report/klbibkeccnjlkjkiokjodocebajanakg/7.0.109

Reports various various CSP security risks, apparently due to it being mostly missing.

**Comment by deanoemcke** [comment]
Just to add to this, i'd like to reference a related issue on the extension privacy policy: https://github.com/deanoemcke/thegreatsuspender/issues/786

The privacy policy itself can be found here: https://greatsuspender.github.io/privacy

**Comment by Jollfye** [comment]
@deanoemcke hmm I guess that privacy url could be added to TGS's settings about page somewhere.

**Comment by deanoemcke** [comment]
@egonil I have updated the content security policy to explicitly define rules for `child-src`, `connect-src`, `img-src`, and `default-src`
