### ISSUE TITLE
Feature request: suspend only if tab is CPU hungry

### ISSUE THREAD

**Issue by triwebb1** [deanoemcke/thegreatsuspender#873]
I have lots of low-cpu tabs open that do not need to be suspended.  Un-suspending these tabs often causes an unnecessary page refresh.  I'd like a feature which makes it so that only tabs that are consuming an average of >1% cpu are suspended, while all the low resource tabs are left alone.

**Comment by deanoemcke** [comment]
Thanks for the feedback. This has already been requested: https://github.com/deanoemcke/thegreatsuspender/issues/448

Unfortunately, there is no practical way of implementing this feature right now, although I would really like to see it happen too!
