### ISSUE TITLE
add 'copy link' option to suspended tab

### ISSUE THREAD

**Issue by Strangehill** [deanoemcke/thegreatsuspender#875]
* Extension version: 6.30
 * Browser name & version: Chrome 72.0.3626.109
 * Operating system & version: OSX 10.14.2 Beta

To clear up unused tabs I sometimes copy a bunch of the addresses on my suspended tabs to a note I'll refer to later.
Currently I have to either un-suspend the tabs in question before being able to directly copy from the address bar, or I can copy the address displayed on the suspended tab and wrangle with it before storing it.
Ideally I would see a 'copy link' option right by 'add www.abc.com' to whitelist, or when I click on the extension icon above.

**Comment by deanoemcke** [comment]
The latest version of the extension has actually changed this and it will be available in the chrome webstore shortly. Please see this screenshot for how you might now manage this:

![image](https://user-images.githubusercontent.com/1051763/53535527-094a1b80-3b68-11e9-914b-5e75d566709c.png)

**Comment by deanoemcke** [comment]
@Strangehill also, you may be interested in this feature request (not implemented yet): https://github.com/deanoemcke/thegreatsuspender/issues/281
