### ISSUE TITLE
[Vivaldi] Incorrect tab icon after restarting the browser

### ISSUE THREAD

**Issue by wdhwg001** [deanoemcke/thegreatsuspender#878]
* Extension version: v7.0.109
 * Browser name & version: Vivaldi 2.3.1440.57
 * Operating system & version: Windows 10 x64 1809

I noticed that after restarting the browser, the tabs will be recovered, but the icons for all suspended tabs are the extension's icon instead of the actual one. However, the new suspended tabs after restarting have the right icons.

![image](https://user-images.githubusercontent.com/8943519/53537483-342f7200-3b5e-11e9-8cf7-866f3b3df6ec.png)
(The left tab was suspended after restarting and the right tabs were suspended before the restarting)

Maybe it's an issue of Vivaldi?

**Comment by Jollfye** [comment]
Hmm I think these favicons issues were fixed long since v7.0.109, u may try latest dev build as unpacked extension n see if issues still persist then.

**Comment by deanoemcke** [comment]
@wdhwg001 sorry, this issue has been fixed but only in the current development version. it will hopefully be released soon!
