### ISSUE TITLE
Feature request: suspend only specified domains

### ISSUE THREAD

**Issue by triwebb1** [deanoemcke/thegreatsuspender#881]
There aren't too many sites that I find consuming much CPU in the background.  Because we can't configure this extension to only suspend high-CPU tabs, how about having a mode where no tabs are suspended except if they match a list domains?  This way I can have a normal browsing experience while only suspending the few resource hungry tabs that I like to keep open.

**Comment by deanoemcke** [comment]
Thanks for the feedback. The feature you're after is being called a blacklist. There is already a feature request for that: https://github.com/deanoemcke/thegreatsuspender/issues/145
