### ISSUE TITLE
Sudden loss of export functions

### ISSUE THREAD

**Issue by tonsimple** [deanoemcke/thegreatsuspender#885]
Please complete the following information when submitting a feature request or bug report.
 * Extension version:7.0.109
 * Browser name & version: Version 72.0.3626.96 (Developer Build) 

 * Operating system & version:  Debian 9.8 (64-bit)

Basically, I decided to export my session, just in case, and noticed that the generated file is just 2 kb (usually my sessions are much huger)

Investigation revealed that almost 2/3 tabs don't get exported

last "healthy" export is 2 month old.

How do I look for exporting-related errors? 

P.S.:
tried to uninstall the extension, reinstall it, then import last healthy backup.
No cigar, issue persists ....

**Comment by deanoemcke** [comment]
Sorry about this. This is a known issue: #853
It has been fixed in the latest development version and will be pushed to the webstore shortly.
