### ISSUE TITLE
All suspended tabs are gone after last update

### ISSUE THREAD

**Issue by Mile140** [deanoemcke/thegreatsuspender#893]
v7.1.0, Chrome 72.0.3626.121, Windows 7
Came back from vacation and this extension automatically updated.  All suspended tabs are gone (about 300 of them).  The session management page shows nothing in current, recent and saved sessions.  

Not happy at all !

**Comment by deanoemcke** [comment]
I'm really sorry to hear this. The extension should have restored all your tabs from your last session. There are a couple of others having this same issue. I'm trying to get to the bottom of it now: #526

Once again, I'm really sorry. I know how much of a pain this can be.
