### ISSUE TITLE
Automatic update caused loss of tabs

### ISSUE THREAD

**Issue by bdickhaus** [deanoemcke/thegreatsuspender#896]

**Comment by bdickhaus** [comment]
Automatic update to v 7.1.0 caused loss of two windows with over 100 tabs. Chrome 73.0.3683.75. Windows 10 version 1803 64 bit. 

I had six windows. Only one of six was successfully migrated with all tabs. Only three windows out of the six were backed up. I guess it was time to clean up anyway, but you obviously did not test the backup or the automatic upgrade very well. And doing it automatically with no warning? Are you the new Microsoft?

**Comment by liamjohnston** [comment]
The developer did test as thoroughly as was feasible. As explained elsewhere, there was no way to warn users of an update. The new version does include this functionality though.

**Comment by deanoemcke** [comment]
@bdickhaus I'm sorry that the update caused you issues. I can assure you it has been tested very thoroughly. But there is obviously some cases that I have not anticipated. I'd love to get to the bottom of what has caused the issue for you.

What do you see if you go to the extensions' options screen and then click on session management? Did it save a backup of the session before the update? This is the session it uses to recover your tabs after the update. Are you saying that this only contains 3 windows out of the 6? This is unusual. Most people that have this issue have no entries in their session history at all.

Perhaps the other 3 windows belonged to a different chrome profile? Maybe that also updated the extension, but completely failed? 

Any extra information you could provide would be very useful.
Thanks.
