### ISSUE TITLE
Major differences between 6.3 and 7.1 versions, not always nice ones :/

### ISSUE THREAD

**Issue by nmr50** [deanoemcke/thegreatsuspender#899]
* Extension version: 6.3 and 7.1 on two browsers
 * Browser name & version: SrWare Iron 72.0.3750.0 (Chrome based browser) and Vivaldi browser 2.3.1440.57 - also Chrome based.
 * Operating system & version: Win7x64

Hello dear coder(s).
I just noticed major version's update of this GREAT extension for Vivaldi that does not work _that_ nice as prev. version 6.3. What I am talking about:
1) The v6.3 gives ability to click on top pane of suspended tab - white one with page name - without unsuspending whole page, only unsuspend it when clicking on lower pane with words written "Tab suspended, Click to reload". The new v7.3 has almost ALL page area is clickable-to-unsuspend - only string with site name is unclickable-so-unsuspendable. **NOT nice**, yet annoying.

2) In v7.3 suspended pages are unsuspending themselves automatically when I switch tabs - sometimes switching goes OK, but often when I switch to suspended page - it starts to unsuspend like I clicked on it after I switched to it, **but I did not** !
**NOT nice** because version 6.3 has main rule - when page is suspended - the user MUST click on lower pane to unsuspend it, and no other actions/clicks will unsuspend the page **for sure**.

And the final question - I urgently desperate in downgrading v7.1 to v6.3 - can you/someone tell me, where I can get this 6.3 packed version to (re)install ?

BIG thanks in advance !
-t

**Comment by x8009** [comment]
only close I found is this at the moment after quick search. I hope it helps u
https://www.crx4chrome.com/crx/108790/

**Comment by nmr50** [comment]
**x8009** -- many thanks, I solved downgrade case by packing 6.3 extension in Iron browser, then deinstalled 7.1 in Vivaldi, and installed 6.3 instead.
I'll be happy to see the answer from author(s) about two questions I mentioned earlier - what was that ?

**Comment by kalpaj12** [comment]
Hi @nmr50!
I guess the below steps might help you with your issue.
1) Click on the extension icon and then click on `settings`
2) Scroll down to `Suspended tabs` section
3) Here, check the box next to `Automatically unsuspend tab when it is viewed`

**Comment by nmr50** [comment]
**kalpaj12** -- Thanks, that was the first option I've checked... No -- chaotical unsuspend happened all the time.

**Comment by kalpaj12** [comment]
*uncheck, sorry for the typo.
Oh, I haven't had issues though, maybe as a last troubleshoot step try re-installing the extension.(v7.1.0)
Else, uhhm, I'm iffy as to why this happens.

**Comment by deanoemcke** [comment]
@nmr50 For the first issue, this was a UI decision we made and still back. What is your use-case for needing to click on the main tab content without wanting the page to unsuspend?

The second issue sounds like a bug. That should definitely not happen. Are you able to provide a repeatable test case for this? Is it happening on both SrWare Iron and Vivaldi? Can you reproduce it on Google's chrome?

A video would be great if you can reproduce it.

**Comment by SnIPeRSnIPeR** [comment]
Chrome on my PC can't update this extension :(

**Comment by deanoemcke** [comment]
@SnIPeRSnIPeR the new release has not fully rolled out to everybody yet. It will happen soon :)
