### ISSUE TITLE
[question] optimal state of "Proactive Tab Freeze and Discard" chrome flag in "chrome://flags/" for 7.1 with "Apply Chrome's built-in memory-saving when suspending" enabled

### ISSUE THREAD

**Issue by RachelHendy** [deanoemcke/thegreatsuspender#901]
Please complete the following information when submitting a feature request or bug report.
 * Extension version: 7.1
 * Browser name & version: chromium 72.0.3626.96
 * Operating system & version: Debian 9

Okay, so I have 7.1 great suspender and it is working.

However, I have found that "Proactive Tab Freeze and Discard" interacts with it oddly, and having it set to "enabled freeze and discard" causes weird behavior (basically always un-supends on click no matter what options are set)

I have changed "Proactive Tab Freeze and Discard"  to "freeze only" and enabled "Apply Chrome's built-in memory-saving when suspending"

All seems work fine but I can't help but wonder if the "proactive freezing" might still cause problems and I would be better off just disabling the "Proactive Tab Freeze and Discard"  

So decided to ask dev opinion here

**Comment by deanoemcke** [comment]
I'm having trouble replicating your issue. I have enabled the chrome flags as you mentioned but don't see any odd behaviour. When I focus on a tab it doesn't automatically unsuspend.

What exactly do you mean by 'always un-suspends on click'? you mean, when you focus the tab? Where are you clicking?

**Comment by deanoemcke** [comment]
@RachelHendy Good news. I started experiencing this same problem and was able to get to the bottom of the issue. I will be pushing a fix for this shortly.

**Comment by deanoemcke** [comment]
The fix for this is now available on master (v7.1.3)
