### ISSUE TITLE
[Feature] Option to keep the original icon/thumbnail of suspended tabs

### ISSUE THREAD

**Issue by Zatchey** [deanoemcke/thegreatsuspender#902]
With lots of tabs open and suspended it becomes difficult to quickly find a specific tab you're looking for, and you have to sift through, mouse over, and wait for the delay until the name pops up on each one until you find it. With the original icon left behind instead of The Great Suspender face, it'll be a snap.

Great Suspender v7.0.109
Google Chrome Version 73.0.3683.86 (Official Build) (64-bit)
Mac OS 10.14.13

**Comment by deanoemcke** [comment]
This has been fixed in the latest release. It's currently rolling out to the webstore (v7.1.0)
This is also a duplicate issue: https://github.com/deanoemcke/thegreatsuspender/issues/719
