### ISSUE TITLE
please add option to kill instead of suspend

### ISSUE THREAD

**Issue by mailinglists35** [deanoemcke/thegreatsuspender#91]
I have had tgs installed from chrome store and I am not satisfied with it at all. 

Memory still remains allocated, reopening a tab is slow, and most important, reopening chrome from a closed shutdown is still retrieving pages from the internet as if tgs was not there.

I would like to have an option to simply kill all the tabs on startup/idle, please.

That way my session wouldn't depend on tgs when I disable tgs extension (for example if I want to report a chrome bug I must disable all extensions) AND would save much more ram (a dead process consumes... zero)

I would not care much about losing unsent form data - Lazarus extension does it's job excellent.

**Comment by mailinglists35** [comment]
thanks! :)
in the meantime I downloaded a non-cygwin bash.exe, awk.exe, pslist/pskill, and I terminate them all but the master process. kills extensions, too, but I reload them from notifications ;)

the difference is that kill 'em all keeps the processes alive and they add to the memory consumption.
is there any way kill em all can do this automatically at startup?
that's actually the use case I need: when I close chrome with lots of tabs, then I must go run around the house several times until all tabs are restored at next launch.

**Comment by mailinglists35** [comment]
ok, rechecked, kill'em all is teh shit!!! :)
the only problem the other six users and i see is that it replaces the url with chrome://kill.
when I kill with pskill/task manager, the url remains. 

do you know what could the difference between chrome://kill and chrome://crash? 

could you try to make the extension use crash instead of kill? maybe that way will it retain the url in omnibar?

**Comment by deanoemcke** [comment]
@mailinglists35 
unfortunately, the only way to kill or crash a tab programmatically is to change the url in the omnibar. 
when a tab crashes for real, the url may remain, but there is currently no way to force the tab to crash without updating the omnibar.

**Comment by mailinglists35** [comment]
@deanoemcke so this api is actually replacing the url with chrome://kill? I was under the impression you can actually terminate the windows process.

"terminate − chrome.processes.terminate(integer processId, function callback)"

https://developer.chrome.com/extensions/processes

**Comment by deanoemcke** [comment]
@mailinglists35 unfortunately that api is on the chrome dev channel only. so while you could use it, it would only work on chromes that are running the dev channel version. not really worth implementing imo until the api makes it into the stable release.

**Comment by mailinglists35** [comment]
do you think that with above dev api is it possible to achieve the same result, if one was to write a new extension? i'd try to do it myself, but my coding skills are limited to simple bash scripts :D

**Comment by deanoemcke** [comment]
Yes. It'd be fairly simple. I'd do it myself, but I don't have the time. Perhaps when it reaches stable I'll take a look at it.

**Comment by mailinglists35** [comment]
great, I think it will be worth the wait :)
