### ISSUE TITLE
Option to keep fav icon when suspended

### ISSUE THREAD

**Issue by atollis** [deanoemcke/thegreatsuspender#911]
Currently when a tab is suspended it shows the suspender icon but id like an option to retain the sites icon and if possible change the opacity or apply a color overlay to the icon.

**Comment by Jollfye** [comment]
hmm looks like u r using old TGS extension version, I would recommend u to update as I wrote bout possibly the same situation [here](https://github.com/deanoemcke/thegreatsuspender/issues/905#issuecomment-476802818).

**Comment by deanoemcke** [comment]
This has been fixed in the latest version.

**Comment by deanoemcke** [comment]
Duplicate of https://github.com/deanoemcke/thegreatsuspender/issues/719
