### ISSUE TITLE
screen capturing on disk

### ISSUE THREAD

**Issue by dmgr** [deanoemcke/thegreatsuspender#92]
Turning on screen capturing will increase the memory footprint of the suspended page (somewhat contrary to the primary goal of this extension).

But what about saving that image on the disk instead of keeping it into memory.

The second option is that maybe that image, kept in the memory will be move to swap, but it is out of the controll.

**Comment by deanoemcke** [comment]
If you want to display the image on the screen, then it will be in memory. Saving the image to disk will not change anything. And in fact, all the images ARE already saved to disk in that they are stored locally in an indexedDb database.
