### ISSUE TITLE
Add support for the new Microsoft Edge

### ISSUE THREAD

**Issue by edmael** [deanoemcke/thegreatsuspender#921]
The new Microsoft Edge is based on Google Chrome and the extension works just fine if installed via Chrome Web Store.

It could just be uploaded to the Microsoft Store without too much works in theory.

**Comment by fwextensions** [comment]
AFAIK, there is no official extension submission process yet for the Chromium version of Edge.  Microsoft has been saying it's coming soon for like 6 weeks.  I'm sure TGS will get submitted when the store is opened.

**Comment by fwextensions** [comment]
Looks like Microsoft recently posted info about publishing extensions for Edge Chromium: https://blogs.windows.com/msedgedev/2019/12/16/get-started-extensions-addons-microsoft-edge-chromium/
