### ISSUE TITLE
Feature request - suspension for whitelist

### ISSUE THREAD

**Issue by GNOMES** [deanoemcke/thegreatsuspender#923]
Please complete the following information when submitting a feature request or bug report.
 * Extension version: v7.0.109
 * Browser name & version: Google Chrome Version 75.0.375XXX (Official Build) dev (64-bit)
 * Operating system & version: Windows 10, Arch Linux

And please also do a search for your request/bug before create a new one thanks!
---------------------------------------------------------------------------------------------

Are there plans to add a timer based suspend for whitelisted pages?

Use case: I currently whitelist the pages I use for work so they never suspend on me throughout the day. These include work email, monitoring, work wiki, ticket management, and related pages in new tabs. There are some days that I don't use a specific page for work, but fancy it open for quick accesses. 

It would be great if you could configure a timeout for whitelisted pages based on inactivity separately from the timeout for non-whitelisted pages. 

I personally would set the timeout for my whitelisted pages to 8 or 9 hours (typical work day). This would allow my work related tabs to stay suspended during my day, but inactive if not used at all, or if I keep the same browser session after work/keep computer on all night.

**Comment by ossilator** [comment]
that would make it a greylist. the next guy then will ask for making it configurable separately from the whitelist. ^^
