### ISSUE TITLE
Add an option to disable the "Tab Suspended" yellow bar

### ISSUE THREAD

**Issue by GitHubGeek** [deanoemcke/thegreatsuspender#93]
Not sure if this has been brought up before. IMHO, if the user has enabled "Automatically unsuspend when tab gains focus", it is pointless to display the yellow
"Tab suspended: click to reload" bar / splash screen.

I believe there should be an option to turn off the yellow bar altogether.

BTW, my first day using this extension and I absolutely love it. Great work @deanoemcke !

**Comment by deanoemcke** [comment]
It's true that if you automatically unsuspend when a tab gains focus, then there is no need for the splash screen. However, wouldn't you only see this screen very briefly before the page begins to refresh? What would you rather see on a suspended tab instead?

**Comment by GitHubGeek** [comment]
As you've said the yellow banner appears for a brief moment / a flash before the tab redraws.

I think just a `<html></html>` would do :)
