### ISSUE TITLE
Allow color selection for suspended tabs

### ISSUE THREAD

**Issue by oreillygshane** [deanoemcke/thegreatsuspender#931]
Please complete the following information when submitting a feature request or bug report.
 * Extension version: v7.0.109
 * Browser name & version: Chrome Version 76.0.3781.0 (Official Build) canary (64-bit)
 * Operating system & version: macOS 10.14.4 (18E226)

It would be great to have an option to define a RBG/Hex code to set the background color on Suspended tabs.
Right now it's just light vs dark.

Thanks for all the hard work!!!

**Comment by raviriley** [comment]
I came here to say the same thing!

**Comment by CollinChaffin** [comment]
+1 and also throw in the option to make it a custom CSS text box option to accept a few CSS elements you could define, tab color being one and then also why not allow the canvas (background) color, and even a few page elements that you set also able to be customized via CSS!
