### ISSUE TITLE
How to deploy greatsuspender with the same settings for all users. 

### ISSUE THREAD

**Issue by tech2610** [deanoemcke/thegreatsuspender#933]
I have found previous issues, but I'm not sure the answers are satisfactory.

I have a terminal server where I will push the great suspender as a GPO.  However, is there a way to make it so that all users receive the same pre-confirmed settings for the extension? 

Thank you.

**Comment by allwizard** [comment]
Hi, I develop and implement custom tab suspenders for companies, ping me hei.gb@outlook.com

**Comment by Simkonge** [comment]
Did you ever figure this out?
