### ISSUE TITLE
I donated, but donation nag screen keeps re-appearing

### ISSUE THREAD

**Issue by squidbe** [deanoemcke/thegreatsuspender#935]
Thanks for this awesome extension! I'm referencing the behavior noted in this closed issue: https://github.com/deanoemcke/thegreatsuspender/issues/802

I donated via PayPal the same day I installed the extension. When the nag screen showed up after that, I searched here and found the issue referenced above. I've followed the procedure you described at least 4 times over the last few weeks, and the nag screen disappears for a few days, but it always comes back. I have not and do not make any changes to local/session storage or cookies.

 * Extension version: 7.0.109
 * Browser name & version: Chrome 74.0.3729.131
 * Operating system & version: Mac Sierra

Do you need any more info?

**Comment by robguthm** [comment]
I'm also having this issue. I joined as a Patreon recurring supporter. 
![image](https://user-images.githubusercontent.com/50523536/57744200-3f426a80-7696-11e9-9c58-5325b2468316.png)
