### ISSUE TITLE
Add option only syspend tabs with url

### ISSUE THREAD

**Issue by svefro** [deanoemcke/thegreatsuspender#937]
Please complete the following information when submitting a feature request or bug report.
 * Extension version: v7.0.109
 * Browser name & version: Chrome 73
 * Operating system & version: Windows 10

Please add option to only auto suspend tabs that are in a list.

mail.google.com, drive.google.com, onedrive.com

All other tabs should never be suspended

**Comment by ossilator** [comment]
i suppose you want a checkbox to switch the blacklist to a whitelist ...

**Comment by svefro** [comment]
Yes, that's perfect.
