### ISSUE TITLE
Option to unsuspend all tabs on startup

### ISSUE THREAD

**Issue by sebeksd** [deanoemcke/thegreatsuspender#940]
Feature request
 * Extension version: 7.0.109
 * Browser name & version: Chrome 74.0.3729.131
 * Operating system & version: Windows 10

Most of the time after chrome startup I quickly look on tab icons to see if I need to check something. Unfortunately TGS not always show the right icons on tabs. For me loading all pages at startup is not a problem, pages will suspend automatically after a while, releasing "unused" RAM. Moreover I do check "suspended" tabs especially at startup and not during the day so having them already loaded is a plus for me. I would like to use this function on my desktop and work (also desktop) PC but not on my Laptop.

**Comment by ossilator** [comment]
the missing favicons upon session restore are annoying indeed, but that should be fixable without unsuspending the page - after all, the favicon is forced to a desaturated version of the original one when suspending, and that's clearly done by the plugin (i conclude that from the flicker).

that doesn't address the use case of checking some pages upon session restore, but that one should be done selectively (via another whitelist).
