### ISSUE TITLE
feature request: suspend in silently in the background

### ISSUE THREAD

**Issue by jimlynch22** [deanoemcke/thegreatsuspender#947]
When a tab suspends upon reaching time inactivity time threshold,  1) the browser is brought into foreground/focus if is not currently in focus 2) the timed-out tab is brought into focus if the browser is active on another tab.  Suspender shouldn't do either of these... It seems to be a new behavior. 

Suspender Version: 7.0.109
Browser: Chrome Version 74.0.3729.169 (Official Build) (64-bit)
OS: Win 7 64bit

**Comment by jasonbuechler** [comment]
Apparently the focus-stealing bug is a known issue/regression. Unfortunately, it was a bug introduced as part of the fix to the "chrome stealing focus when tab suspends" issue: #865, according to author

**Comment by ossilator** [comment]
@jasonbuechler, i don't see how what you're saying makes any sense. @jimlynch22's is a pre-fix version. imo clearly a duplicate of #865, and should be closed.

**Comment by jimlynch22** [comment]
Right, I had to upgrade to the
 latest Suspender version, problem solved. Thanks!


On August 15, 2019 6:31:53 AM Oswald Buddenhagen <notifications@github.com> wrote:

@jasonbuechler<https://github.com/jasonbuechler>, i don't see how what you're saying makes any sense. @jimlynch22<https://github.com/jimlynch22>'s is a pre-fix version. imo clearly a duplicate of #865<https://github.com/deanoemcke/thegreatsuspender/issues/865>, and should be closed.
