### ISSUE TITLE
send a window to front when a tab suspending

### ISSUE THREAD

**Issue by kanglezeng** [deanoemcke/thegreatsuspender#951]
Please complete the following information when submitting a feature request or bug report.
 * Extension version: v7.0.109
 * Browser name & version: Chrome 75.0.3770.100
 * Operating system & version: Mac 10.14.5

when a tab suspending, and the chrome window on this tab always send to front, and it's always break.

**Comment by MLCozad** [comment]
I have had the same problem. You leave a window in the background, to look at something else. Then in the middle of a read, POP. Up comes that window, just to suspend something.
That is annoying. Especially when piecing together bits of information that are not nicely put in one place for free.
Suspend in the background.
Please.  Suspend in the background.

**Comment by DevCentre** [comment]
Suspend in the background.
Please. Suspend in the background.

**Comment by mseleng** [comment]
+1

**Comment by ossilator** [comment]
duplicate of #865, please close
