### ISSUE TITLE
Extension getting constantly corrupted

### ISSUE THREAD

**Issue by marnovo** [deanoemcke/thegreatsuspender#953]
* Extension version: 7.1.0
* Browser name & version: Chrome Version 76.0.3809.36 (Official Build) beta (64-bit)
* Operating system & version: macOS Mojave 10.14.5 (18F203)

I have been for the last weeks having the extension corrupted (thus disabled) very often. I have tried repairing, uninstalling and installing the extension back again, and the problem stays.

Effectively, I lost all sessions a few times and don't feel I can rely on the extension anymore—which apart from this is awesome, by the way. Could this be related to the Chrome suspend feature somehow?

What info can I provide to debug this? Thank you.

**Comment by marnovo** [comment]
P.s.: it also seems "Sync settings with your Chrome profile" maybe didn't work somehow, since I could not get the history after repairing.

**Comment by kliop00023** [comment]
manual run package seems good lol
