### ISSUE TITLE
Development halted?

### ISSUE THREAD

**Issue by CollinChaffin** [deanoemcke/thegreatsuspender#956]
Has development and addressing open issues been halted?  Master hasn't had a commit in quarter year now and if there was an announcement I missed it.  Just curious of the status.  TIA!

**Comment by kliop00023** [comment]
not really as the extension is good enough to not change codes :P

**Comment by CTimmerman** [comment]
It just got a new release supporting Chrome's built-in suspender, so this question would fit better at https://github.com/deanoemcke/thegreatdiscarder

**Comment by CollinChaffin** [comment]
Sorry would be nice then to notify long-time users of this extension if it is in fact being depreciated for that one.

**Comment by CollinChaffin** [comment]
@CTimmerman LOL that other "new" extension repo hasn't had a single commit in it's single branch (master) since 2017 so not sure where all that development is happening?
