### ISSUE TITLE
Support of multiple languages

### ISSUE THREAD

**Issue by AndreyURL** [deanoemcke/thegreatsuspender#96]
Hello. I'm surprised I did not find support for multiple languages ​​in such a useful program. If the program needs to support multiple languages ​​I can offer Russian translation. Is this  required?

**Comment by deanoemcke** [comment]
If I get more requests for this in the future then I may well add additional language support. I never anticipated it being popular enough that it might require other language support!
Thanks for the offer of providing translation. I'll get back to you if russian proves to be a popular language request.

**Comment by deanoemcke** [comment]
Support for Chinese is coming in the next release. If your offer for russian translation is still open then I would consider it, as the groundwork has been done now.

**Comment by SnIPeRSnIPeR** [comment]
I need russian too. Can help with this if you send me all texts in english :)
