### ISSUE TITLE
[Bug] Suspending should stop once charging cable plugged on

### ISSUE THREAD

**Issue by wdhwg001** [deanoemcke/thegreatsuspender#960]
Hello,

I've noticed that right now if there're many tabs wait to be suspend, the whole suspend process will not stop when the power cable is plugged on. Usually thinking, the suspending queue should check the power cable status when processing each tab.

**Comment by NetherGranite** [comment]
@wdhwg001 Have you enabled "Never suspend tabs when connected to power source" in your settings?

**Comment by wdhwg001** [comment]
@NetherGranite I have. But the suspending process of all 20+ tabs take a few seconds and once it starts, plugging the power cable cannot stop it.
