### ISSUE TITLE
Feature Request: Auto suspension option for freshly opened new tabs

### ISSUE THREAD

**Issue by detfusco** [deanoemcke/thegreatsuspender#961]
Please complete the following information when submitting a feature request or bug report.
 * Extension version: v7.1.0
 * Browser name & version: Google Chrome Version 75.0.3770.142 (Official Build) (64-bit)
 * Operating system & version: Windows 8.1

I'll be quoting from my Chrome web market review for your extension.

"Nice extension but it would be nice to have auto suspension option for freshly opened new tabs alongside the timer. 'cause I tend to queue the tabs i wanna watch or read while browsing. This method results in huge piles of tabs like 10-20 tabs in a sitting. Then I go one by one after finishing each tab. So I don't need all these tabs to be running  at the same time in the background from the get-go."

**Comment by Noah1995** [comment]
+1    I also like open the new tab backstage.
