### ISSUE TITLE
Suspended window pushes to front now, s/b be silent in background!

### ISSUE THREAD

**Issue by DGPickett** [deanoemcke/thegreatsuspender#968]
Please complete the following information when submitting a feature request or bug report.
 * Extension version:
 * Browser name & version:
 * Operating system & version:

And please also do a search for your request/bug before create a new one thanks!

**Comment by DGPickett** [comment]
My work was disrupted several times lately by windows pushing to the front when suspended.  Suspension timeout should be in the deep background!

**Comment by karbassi** [comment]
@deanoemcke This effects me as well.

Does this have to do anything with any updates in Chrome?

Extension version: **7.0.109**
Browser name & version: **Version 76.0.3809.87 (Official Build) beta (64-bit)**
Operating system & version: **macOS Mojave 10.14.5**

**Comment by joonaskokko** [comment]
Having the same issues after updating Chrome to 76.0.3809.87. Really annoying. Have to disable the extension for now :(

**Comment by joonaskokko** [comment]
Actually fixed the problem by removing the extension and installing it again. I had the same issue as in https://github.com/deanoemcke/thegreatsuspender/issues/865#issuecomment-510102476

**Comment by DGPickett** [comment]
I'm trying that, but note that all suspended tabs are closed!  You might want to momentarily unsuspend them all before tossing the extension/plug-in!


-----Original Message-----

**Comment by karbassi** [comment]
Per @joonaskokko's suggestion, uninstalling and reinstalling the extension, it fixes it.

**Comment by igitur** [comment]
@DGPickett Being a maintainer of a different, unrelated repo, I can tell you that by not fully completing the original issue template is not at all conducive to getting attention on this issue. NEVER skip the issue template.
