### ISSUE TITLE
Chrome window is brought to front on tab suspend

### ISSUE THREAD

**Issue by AlexanderDudek** [deanoemcke/thegreatsuspender#975]
* Extension version: v7.0.109
 * Browser name & version: Chrome Version 76.0.3809.100 (Official Build) (64-bit)
 * Operating system & version: Mac OS 10.14.5

When one or more tabs get suspended, the containing Chrome window will pop up to the front. It's not entirely clear to me if this happens every time. I will try to test more.

**Comment by heavydoc** [comment]
- Extension version: v7.0.104
- Browser name & version: Chrome Version 76.0.3809.100 (Official Build) (64-bit)
- Operating system & version: Windows 7 Home Prem 6.1.7601 64-bit
This started happening to me about a week ago. It was once-in-a-while at first, and now it's happening to me often (about 3 times an hour). I'll be typing in a text field (like this one), and then another chrome window will steal focus (sometimes I don't notice and continue typing in the wrong window). I have 640 tabs open across 6 Chrome windows (research project), so I don't think it it happens every time a tab is suspended (or else I would be seeing it even more often), although I'm not sure. Notes that may be important: I use 7+ Taskbar Tweaker (which allows me to change the order of grouped windows, so I can change the order of my 6 Chrome windows, which Win7 doesn't allow you to natively do). I also have 3 taskbar programs running that read the clipboard (Onenote, Pure Text, Yankee Clipper).

**Comment by ozzyaaron** [comment]
OS X (Mojave) & Chrome (76.0.3809.100 (Official Build) (64-bit)) giving me this issue too

**Comment by mtsweir** [comment]
Same issue happening for me:
- OS X (Mojave)
- v6.30
- Version 76.0.3809.100 (Official Build) (64-bit)

When a website tab suspends it takes focus on whatever I have open, so example when using Adobe apps for designing I get Chrome taking over as the active app. This is just started happening recently - quite frustrating.

**Comment by jeffreytigch** [comment]
Same here, with same specs as OP.

**Comment by DoseOfGose** [comment]
Same here
 * OS X (Mojave)
 * Chrome 76.0.3809.100 (Official Build) (64-bit)
 * TGS Extension v6.30

Appears to happen every time.  Can easily reproduce by setting suspend time to 20 seconds and switching apps.  The Chrome window that contains the suspended tab will take focus on my screen each time a tab is suspended.

**Comment by iamwhaler** [comment]
Same here. Same specs as above

**Comment by DoseOfGose** [comment]
Following comments in another related issue, I removed the extension from Chrome and re-added it.  The problem seems to be resolved!

It also updated my TGS version to v7.1.0

**Comment by jucaslames** [comment]
Same here, same as above. I'll try uninstalling/reinstalling. 

- TGS v7.0.109
- Chrome v76.0.3809.100 (Official Build) (64-bit)
- Mac OS Mojave 10.14.6

**Comment by adamlove86** [comment]
Just worked out it's thegreatsuspender extension causing this issue, after experiencing it for a number of weeks now.
Version 76.0.3809.100 (Official Build) (64-bit)
El Capitan 10.11.6

**Comment by mtsweir** [comment]
@adamlove86 have you tried reinstalling it? There is a new version but I wasn't aware there was until I went to reinstall it.

**Comment by SteveWooding** [comment]
Been having the same issue on Linux and Chromebook. Even went as far as reporting this issue to Google. Then I caught it happening at the same time a tab got suspended. Glad I found out what it is. Hope you fix it soon. In the meantime, I try the above methods or just switch off auto suspend all together.

**Comment by adamlove86** [comment]
Yep removed extension and then re-added. All fixed.

**Comment by olso** [comment]
Removed and added again. It turns out Chrome didn't update this extension for some reason. I had v6 until now.

**Comment by raykle** [comment]
> Removed and added again. It turns out Chrome didn't update this extension for some reason. I was running v6 until now!

Me too! I am still using v6.30, don't know why the chrome does not update it automatically.
I just check the plugin on the chrome extension shop and find the version has come to 7.1. 😱

**Comment by DevCentre** [comment]
Just upgraded to v7.1.0 and the problem is fixed !! Finally !! Thanks @deanoemcke
