### ISSUE TITLE
Silently modifying webpage URLs (e.g. Youtube) may not work well for everyone.

### ISSUE THREAD

**Issue by will-ca** [deanoemcke/thegreatsuspender#979]
Please complete the following information when submitting a feature request or bug report.
 * Extension version: 7.1.0
 * Browser name & version: Chromium 76
 * Operating system & version: Linux

I understand that this was a requested feature (#444, #342) that somebody had to take the time to code (#682), but I'd still like to offer my feedback as a user.

My scenario is that I had many Youtube tabs open to different music pages. When I load up Chrome, they're unloaded by default, and I click on them in order to load them and start playback one at a time throughout the day.

Due to experimentation with this extension involving first loading and then suspending them all, all those URLs have now been modified with timestamps. Thus, whenever I try to play a song or reload a tab, it starts from the middle of the video and I have to manually truncate the query string from the URL in order to permanently fix it. Since I had dozens of these tabs active, it's somewhat non-trivial to restore my browser to its previous state.

I know this scenario seems rather specific and unimportant. But I don't think that means that it's necessarily irrelevant, or too rare to merit consideration. Consider, for example, the case of an extremely long video with one or two specific areas of interest. If you're doing research using that video, it makes sense that you might use a timestamp in the URL to save the relevant moments. Then, if the tab gets suspended, you'd lose that timestamp and have to scrub through multiple hours of footage all over again.

It also interferes with bookmarks whenever anything modifies the query string of an URL.

In principle, I'm also against anything that transparently edits user content without an option to disable it (or at least a notice that it's there). And in terms of behaviour, you could argue that losing the video position is reasonably expected when suspending and resuming a tab, but having the URL change and having all future playback from that tab begin from the middle of the video is more likely to be unexpected behaviour.

This default also additionally caught me off guard because the rest of the extension gave the impression of placing a lot of control in the user's hands, and generally being very clearly defined and well-communicated in its behaviour (which was my primary reason for trying it over Chrome's built-in `discard` functionality).

Are there any other specially coded cases where suspending a tab will silently alter the tab's contents based off of the website?

I'm not advocating for features to be removed or anything, but it'd be nice to have a toggle switch somewhere in the settings for disabling such features, or at least a mention of it somewhere in the Chrome Web Store page or settings menu so it's not done completely silently.

**Comment by FinObFom** [comment]
Youtube saves video watch timestamp. So watching can be continued from a different device. 
When I unsuspend video after watching it on a different device, watch timestamp is lost.
+1 for the toggleable switch in settings.
