### ISSUE TITLE
Feature request: Language setting in the config

### ISSUE THREAD

**Issue by xPumaa** [deanoemcke/thegreatsuspender#986]
Unfortunately the language after the update is German, but I would rather have it in English again. It would be good if you could specify the language for the extension.
 * Extension version: v7.1.0
 * Browser name & version: Chrome Version 76.0.3809.100 (Official Build) (64-bit)
 * Operating system & version: Windows 10 Pro 1903 (Build 18362.295)

**Comment by alexdonskih** [comment]
The same is for me. I got russian localization after the recent update, but would like to keep an english version.

Extension version: v7.1.0
Browser name & version: Chrome Version 76.0.3809.100 (Official Build) (64-bit)
Operating system & version: MacOS Mojave 10.14.6
