### ISSUE TITLE
Suspended tabs closed after automatic upgrade

### ISSUE THREAD

**Issue by usmonster** [deanoemcke/thegreatsuspender#988]
Hi, and thanks for the extension. I just noticed a few minutes ago that the new version was applied to my browser, and all my suspended tabs were closed without warning as a result.

Maybe it's because I have lots of tabs open (400+ before the upgrade, 100+ after... please don't ask 😅), and perhaps there was some kind of silent memory-related crash during whatever post-install activities are launched, but I can only guess.

Luckily/smartly, I see the plugin seems to have auto-saved my session as "Automatic save point for v6.30" before the upgrade, so I can restore just the missing tabs & windows, but it remains a pain. Please just be aware that this might happen to more folks as the upgrade rolls out, so I'll leave it up to you to decide whether or not to pause the rollout to investigate and maybe fix this behavior.

Thanks again for your great work!

 * Extension version: v7.1.0
 * Browser name & version: Google Chrome Version 76.0.3809.100 (Official Build) (64-bit)
 * Operating system & version: macOS Mojave 10.14.6 (18G87)

**Comment by usmonster** [comment]
Please note, I do see #987 (filed ~10 minutes before this one) seems closely related, but the side-effects sound slightly different, e.g. irrecoverable session on theirs, but backup session appears on mine, different OS might also be relevant, etc. Still, if the root cause is the same, feel free to close one.

**Comment by usmonster** [comment]
Also just noticed #526, and I strongly recommend the same solution as was suggested in [@uecasm's comment](https://github.com/deanoemcke/thegreatsuspender/issues/526#issuecomment-307257489).

@deanoemcke, did you ever get a change to look into this? It seems it would close the number one issue for users of this plugin. I'd love to follow the issue for this feature if one exists. Thanks again!

**Comment by usmonster** [comment]
New development—when I attempt a "Restore and suspend" of the backup session, I see a message saying *klbibkeccnjlkjkiokjodocebajanakg is blocked*:
![image](https://user-images.githubusercontent.com/1373334/63639374-96db7380-c692-11e9-8f0f-f4e2525c7bbb.png)

Looking at the extensions page, I now see that the extension is, suddenly, possibly corrupted (it wasn't just before I attempted the restore):
![image](https://user-images.githubusercontent.com/1373334/63639363-7f03ef80-c692-11e9-8dbe-38a15e498390.png)

Never seen this before, but I will attempt a "repair" and update this comment.

**Comment by usmonster** [comment]
(Sorry for monologuing...)

So I clicked "Repair", and it seems Chrome just reinstalled the plugin. As opposed to current upgrade behavior, my previously-suspended tabs remained open and in the suspended state, and they now seem to work as expected—_however_, the plug-in's options page now seems to display no content:
![image](https://user-images.githubusercontent.com/1373334/63639485-d22a7200-c693-11e9-89a5-e9c0fd8c2363.png)

I'll just restart the browser and pray everything's back to "normal" after that. Will hopefully be able to report back. Wish me luck.

**Comment by usmonster** [comment]
Dear diary,

I just restarted my browser. What a mistake! Now, I don't even see the suspended tabs that I'd just restored from the backup session—I'm in the same boat as those in #526! 😭 I guess when I clicked "Repair" Chrome also completely cleared my plugin settings, including session history. What's worse, diary, is that, even though I had previously selected "Sync settings with your Chrome profile"—these settings were not restored.

Luckily, I'd expected something catastrophic like this to happen. This is not my first rodeo, diary. 😎 (🤠?) Before doing anything I'd exported the backup session, so now all I have to do is "Import session" from the backup text file, and everything should be fine... right?? We'll see! Until next episode... 🤞

**Comment by maxxyme** [comment]
I just encountered the same problem, lost almost ALL my suspended tabs from my ~10 windows.

Although I saved the "current session" to a text file as suggested by The Great Suspender just before it would upgrade, in fact it only save the current WINDOWS tabs...

Seriously WHAT A MESS.
I'm really disappointed because I couldn't rely on this single extension in the future.

**Comment by retrospec13** [comment]
This is exactly why forced updates should never happen.

The dev needs to never again force an update, there's a reason why all major developers don't do this.

**Comment by usmonster** [comment]
> Although I saved the "current session" to a text file as suggested by The Great Suspender just before it would upgrade, in fact it only save the current WINDOWS tabs...

I had noticed that behavior previously, even before the update. I never reported it, since I thought "I guess I haven't needed that feature in a while"—and thank goodness it worked for me this time. Sorry you weren't as lucky, but maybe [this method](https://tom-chapman.uk/2017/01/30/restoring-google-chrome-last-tabs-session/) can help?

**Comment by hamakei** [comment]
I lost all my tabs too, thanks to an update I didn't ask for. TGS "helpfully" says "you can recover lost tabs from the session management page", but going to the session management page....there is no previous session to restore. It's all gone.

So, thanks a lot!

**Comment by maxxyme** [comment]
> > Although I saved the "current session" to a text file as suggested by The Great Suspender just before it would upgrade, in fact it only save the current WINDOWS tabs...
> 
> I had noticed that behavior previously, even before the update. I never reported it, since I thought "I guess I haven't needed that feature in a while"—and thank goodness it worked for me this time. Sorry you weren't as lucky, but maybe [this method](https://tom-chapman.uk/2017/01/30/restoring-google-chrome-last-tabs-session/) can help?

Won't work unfortunately, because I had the wonderful idea to subsequently update Google Chrome too as it had a pending update. 🙄
Well after all this is also a good sign to me that keeping so much tabs open/suspended is a really really bad thing. I just noticed I can somehow find all my closed suspended tabs in the Chrome history because apparently they were all kind of re-opened at the sane time. 😅

**Comment by jvschiavo** [comment]
@usmonster I think the "This extension may have been corrupted" message could be something with Chrome. Specifically v76. I got the exact same message with another extension, Video Speed Controller (https://chrome.google.com/webstore/detail/video-speed-controller/nffaoalbilbmmfgbnbgppjihopabppdk).

I've just noticed it wasn't working and then I checked Chrome's extensions page and saw the corrupted message. It happened more than one time, but never happened before Chrome v76. I'm gonna check their github too to see if more people got the same problem.

**Comment by jvschiavo** [comment]
@usmonster Bingo. https://github.com/igrigorik/videospeed/issues/492

**Comment by usmonster** [comment]
Thanks, @jvschiavo! I Just starred the upstream bug as well, https://crbug.com/977805. It sounds like the fix isn't quite ready for primetime, but hopefully I'll at least be able to restore all my tabs at once in the next version of Chrome.

And just to clarify for folks who don't read every single comment: the main issue is still likely an ongoing problem with the extension. The secondary issue (attempting to restore all the tabs resulting in a corrupt plugin message) is likely a Chrome v76 issue that should be fixed by Google folks soon.

**Comment by SirJorb** [comment]
Had this happen to me too, the last automatic backup was a month ago D:

**Comment by RobertAb1** [comment]
https://github.com/deanoemcke/thegreatsuspender/issues/987
https://github.com/deanoemcke/thegreatsuspender/issues/990
https://github.com/deanoemcke/thegreatsuspender/issues/1000

**Comment by RobertAb1** [comment]
Problems seems to be present with the large number of suspended tabs (+200); I am using *Session Buddy*. 
*Apply Chrome's built-in memory-saving when suspending* is new option in *The Great Suspender v7.1* and problem exists both with this option marked and unmarked.

**Comment by liamjohnston** [comment]
For anyone experiencing issues importing sessions - there is a bug preventing this from working in the great suspender :( 
BUT you should be able to import a Great Suspender session directly into Session Buddy. Tested and working for me :)

**Comment by usmonster** [comment]
[As mentioned above](https://github.com/deanoemcke/thegreatsuspender/issues/988#issuecomment-524573198), this is a known recent problem in Chrome v76 that affects several extensions. It _should_ be fixed in an upcoming version of Chrome.

**Comment by usmonster** [comment]
Not to doubt your experience, but it may be a bit trickier than that. There are lots of versions of "Chrome v76", and the bug is only present after one of them. The extension upgrade could have coincided with a Chrome upgrade, which could explain the behavior you saw. Unfortunately, it's hard to prove either way, since "downgrading" to 7.0 requires installing the package manually without the Chrome Web Store, and that won't trigger the problem on any version of the plugin due to the nature of the Chrome bug.

**Comment by RobertAb1** [comment]
@deanoemcke
Any progress?

**Comment by usmonster** [comment]
Has anyone retested in Chrome 77? Is it fixed?

I've been successfully using a workaround (i.e. installed a local clone of the plugin to avoid the mechanism that triggers the crash), and I'm not brave enough/too lazy to try it myself. 😅

**Comment by 1024mb** [comment]
I have updated just now on Vivaldi and apparently it didn't delete any of the backed up sessions, I mean I have 2 sessions form July and 2 from August so I guess it didn't delete any sessions on my end. Although I have to say that I don't use this extension as a session manager so I don't know if I had any more sessions saved and TGS deleted all of them and just leave 4, so there is that. Can't say anything about closing suspended tabs and failing to restore them as I didn't have any before updating.
I guess you guys should start using more than just one extension to backup your sessions. I use 2, Tab Session Manager and Session Buddy and Tab Session Manager has an auto backup option that exports a json file to wherever you set. I always thought TGS was a little fragile regarding session management, I don't know why, never trust it to manage my sessions. I've been using this extension for years and never use it to backup anything.

Sorry for your loss guys, I've been there once and is a pain in the ass to try to recreate at least the last session.
