### ISSUE TITLE
Session Manager deleted "saved sessions" ; Need help :(

### ISSUE THREAD

**Issue by jonibahu** [deanoemcke/thegreatsuspender#993]
Hi
Im using google chrome and v7.1.0 of the suspender.

The extension updated today.
The session manager had some saved sessions in it.
The extension had a fatal error and i had to repair it.

After that the sessions were gone.

I can access previous version of  C:\Users\AppData\Local\Google\Chrome\User Data\Default\IndexedDB\chrome-extension_klbibkeccnjlkjkiokjodocebajanakg_0.indexeddb.blob
Aswell as
C:\Users\AppData\Local\Google\Chrome\User Data\Default\IndexedDB\chrome-extension_klbibkeccnjlkjkiokjodocebajanakg_0.indexeddb.leveldb

for some reason the extension wont read them tho.
My guess is that its because of the newer extension version.
If i restore the files from a point after the update it works.
If i restore the IndexedDB from before the update, it wont show anything.

Is it possible that the newer version (7.1.0) cannot read the information from older versions of the session manager???

Also is it correct that "Session manager information" should be saved in those files???
Or is it saved in another file or not at all on my PC (which would be odd, its gotta be saved somewhere right!?)

 C:\Users\AppData\Local\Google\Chrome\User Data\Default\IndexedDB\chrome-extension_klbibkeccnjlkjkiokjodocebajanakg_0.indexeddb.blob

Aswell as

C:\Users\AppData\Local\Google\Chrome\User Data\Default\IndexedDB\chrome-extension_klbibkeccnjlkjkiokjodocebajanakg_0.indexeddb.leveldb

I would really appriciate an answer.
Thank you very much and have a good day.

**Comment by sirius16** [comment]
I have this same problem too. I'm afraid to click "Repair" because past experience leads me to believe that my settings will be wiped

**Comment by jonibahu** [comment]
i uploaded my indexedDB, maybe someone can tell me if the data is still in there or not.

https://gofile.io/?c=5N3pJ7

**Comment by usmonster** [comment]
> I have this same problem too. I'm afraid to click "Repair" because past experience leads me to believe that my settings will be wiped

You are correct not to click it. The "safer" way is to go to the Chrome WebStore page and re-enable the extension from there. After that, you will probably want to "export" the last saved session to a text file, since it will likely crash again due to [a bug in the current version of Chrome](https://crbug.com/977805).

See #988 or #526 for more information.

**Comment by jonibahu** [comment]
question:
I copied IndexedDB into my chrome folder.
(and it did not bring back my saved sessions, so i went ahead and did some research whats wrong)


Everytime i copy an older version of IndexedDB , the files get deleted when i run chrome.
I tried saving new sessions, deleting the indexed DB and pasting it back in (with the new saved sessions), that works.

I am wondering why the older versions of IndexedDB get deleted.
Are those files corrupt or are they not compatible with the current version of the Great Suspender?


Thank you very much, would appriciate an answer.

**Comment by liamjohnston** [comment]
There is a bug with the import functionality unfortunately. However if your Great Suspender export file contains all you need, you can import it with Session Buddy. (As mentioned in https://github.com/deanoemcke/thegreatsuspender/issues/1002#issuecomment-525041161)
