### ISSUE TITLE
New memory-saving option busted in Vivaldi

### ISSUE THREAD

**Issue by somnomania** [deanoemcke/thegreatsuspender#994]
GS 7.1.0, Vivaldi 2.7.1628.30, Windows 8.1 (Build 9600)

The new feature "Apply Chrome's built-in memory-saving when suspending" is causing all tabs to unsuspend and load when I switch to them. It doesn't do it in Chrome, but I'm also using an older version of Chrome (version 69), and I'm not interested in going through the hassle of updating and then downgrading again just to see if GS does it there as well. It's not a huge problem for me, I just figured I should report it as a bug.

**Comment by ch3rub1n** [comment]
Thanks @somnomania  for reporting. I have the exact same issue and wanted to report it. Happy to see it's already here. 

When "Apply Chrome's built-in memory-saving when suspending" is enabled TABs get unsuspended when viewed even when "Automatically unsuspend tab when it is viewed"  is turned off.

GS v7.1.0
Vivaldi 2.8.1664.40 (Stable channel) (32-bit)
